[package]
name = "channelflow"
version = "3.3.4"
description = "VYRON Content Operating System"
authors = ["VYRON"]
edition = "2021"

[lib]
name = "channelflow_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-dialog = "=2.7.3"
tauri-plugin-opener = "=2.5.5"
tauri-plugin-process = "=2.3.1"
tauri-plugin-updater = "=2.11.0"
tauri-plugin-notification = "=2.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
sha2 = "0.10"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
urlencoding = "2"
trash = "5"
notify = "=7.0.0"

base64 = "0.22"
chacha20poly1305 = "0.10"
argon2 = "0.5"
rand_core = { version = "0.6", features = ["getrandom"] }
tokio = { version = "1", features = ["fs", "io-util", "time"] }



[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "3.7.0"
security-framework-sys = "2.17.0"
core-foundation = "0.10.1"
core-foundation-sys = "0.8.7"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.59.0", features = ["Win32_Foundation", "Win32_Security_Credentials", "Win32_Storage_FileSystem", "Win32_System_WindowsProgramming"] }
