import React,{useEffect,useState} from 'react';
import {api} from './api';
import {useApp} from './store';
import type {AutopilotMode,LicenseStatus} from './types';

type Tab='general'|'youtube'|'autopilot'|'endlume'|'updates'|'diagnostics';
type DiagRow={label:string;status:string;ok?:boolean;detail?:string};
function Toggle({label,text,value,onChange}:{label:string;text:string;value:boolean;onChange:(v:boolean)=>void}){return <button className="toggleRow" type="button" onClick={()=>onChange(!value)}><div><b>{label}</b><small>{text}</small></div><i className={value?'on':''}><em/></i></button>}

export function SettingsOS({license}:{license:LicenseStatus}){
 const s=useApp(x=>x.settings),patch=useApp(x=>x.patchSettings),logs=useApp(x=>x.logs),toast=useApp(x=>x.toast),setPage=useApp(x=>x.setPage);
 const [tab,setTab]=useState<Tab>('general'),[update,setUpdate]=useState<any>(),[progress,setProgress]=useState<number|null>(null),[stage,setStage]=useState(''),[diag,setDiag]=useState<DiagRow[]>([]),[checking,setChecking]=useState(false),[installedVersion,setInstalledVersion]=useState('');
 useEffect(()=>{void api.appVersion().then(setInstalledVersion).catch(()=>{})},[]);
 const mode:AutopilotMode=s.autopilotMode||'off';
 const setMode=(m:AutopilotMode)=>{if(m==='off')patch({autopilotMode:m,autopilotEnabled:false,autoUploadYoutube:false});else patch({autopilotMode:m,autopilotEnabled:true,autoUploadYoutube:false})};
 async function runDiagnostics(){setChecking(true);try{let ws=s.workspace;if(!ws){ws=await api.defaultWorkspace();patch({workspace:ws})}const core=await api.diagnostics(ws);setDiag([{label:'Local Core',status:core.ok?'Готово':'Требует внимания',ok:core.ok},{label:'Workspace',status:core.workspaceWritable?'Доступен для записи':'Проблема записи',ok:core.workspaceWritable},{label:'ENDLUME',status:s.endlumePath?'Путь настроен':'Не выбран',ok:Boolean(s.endlumePath)},{label:'Updater',status:'Tauri signed updater подключён',ok:true},{label:'YouTube',status:'Проверяется только во вкладке YouTube',detail:'Zero Quota Policy: настройки не вызывают YouTube Data API.'}])}catch(e){setDiag([{label:'Диагностика',status:'Ошибка',ok:false,detail:String(e)}])}finally{setChecking(false)}}
 async function checkForUpdate(){try{setUpdate(await api.checkUpdate())}catch(e){setUpdate({error:String(e)})}}
 async function installUpdate(){setProgress(0);setStage('Downloading');try{await update.install((p:number)=>{setProgress(p);if(p>=100)setStage('Verifying signature / Installing')})}catch(e){setProgress(null);setStage('Обновление не установлено. Текущая версия сохранена.');toast(String(e))}}
 const label=(t:Tab)=>t==='general'?'Общие':t==='youtube'?'YouTube':t==='autopilot'?'Автопилот':t==='endlume'?'ENDLUME':t==='updates'?'Обновления':'Диагностика';
 return <><div className="pageHeader"><div><small>SETTINGS</small><h1>Настройки</h1><p>Локальная конфигурация VYRON. Ни один переход сюда не расходует YouTube API quota.</p></div></div><div className="settingsTabs osTabs">{(['general','youtube','autopilot','endlume','updates','diagnostics'] as Tab[]).map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{label(t)}</button>)}</div>
 {tab==='general'&&<div className="settingsStack"><section className="settingsCard"><h3>Workspace</h3><p>Inbox, проекты, очередь, backup и локальное состояние VYRON.</p><div className="pathLine"><input readOnly value={s.workspace} placeholder="создаётся автоматически"/><button onClick={async()=>{const p=await api.chooseWorkspace();if(p)patch({workspace:p})}}>Выбрать</button><button onClick={()=>s.workspace&&api.openLocal(s.workspace)}>Открыть</button></div></section><section className="settingsCard"><h3>Интерфейс</h3><div className="toggleRows"><Toggle label="FPS monitor" text="Показывать текущий FPS интерфейса." value={s.fpsMonitor} onChange={v=>patch({fpsMonitor:v})}/><Toggle label="Уменьшить анимации" text="Уменьшить декоративные переходы." value={s.reduceMotion} onChange={v=>patch({reduceMotion:v})}/></div></section><section className="settingsCard"><h3>Лицензия</h3><p>{license.valid?'VYRON активирован':'Требуется активация'} • {license.type||'—'}</p></section><details className="settingsCard advancedPanel"><summary>Advanced</summary><div className="advancedInner"><label>OpenAI API — опционально<input type="password" value={s.openaiApiKey} onChange={e=>patch({openaiApiKey:e.target.value.trim()})}/></label><label>OpenAI model<input value={s.openaiModel} onChange={e=>patch({openaiModel:e.target.value.trim()})}/></label><label>YouTube category<input value={s.youtubeCategoryId} onChange={e=>patch({youtubeCategoryId:e.target.value.trim()||'10'})}/></label></div></details></div>}
 {tab==='youtube'&&<div className="settingsStack"><section className="settingsCard youtubeMovedCard"><small>ZERO QUOTA POLICY</small><h3>YouTube вынесен в отдельную рабочую зону</h3><p>OAuth, синхронизация, аналитика, конкуренты, metadata и загрузка выполняются только во вкладке YouTube и только после явного действия пользователя.</p><button className="primary" onClick={()=>setPage('youtube')}>Открыть YouTube</button></section></div>}
 {tab==='autopilot'&&<div className="settingsStack"><section className="settingsCard"><h3>Режим Autopilot</h3><div className="modeSwitch large"><button className={mode==='off'?'active':''} onClick={()=>setMode('off')}>OFF</button><button className={mode==='assisted'?'active':''} onClick={()=>setMode('assisted')}>ASSISTED</button><button className={mode==='full'?'active':''} onClick={()=>setMode('full')}>FULL LOCAL</button></div><p>{mode==='off'?'Автоматизация выключена.':'Autopilot обслуживает только локальный Production pipeline и ENDLUME. YouTube API всегда остаётся ручным.'}</p></section><details className="settingsCard advancedPanel"><summary>Advanced Autopilot</summary><div className="toggleRows"><Toggle label="Поддерживать план" text="Создавать недостающие VIDEO_XXX." value={s.autoCreatePlan} onChange={v=>patch({autoCreatePlan:v})}/><Toggle label="Распределять музыку" text="Inbox/Music → проекты." value={s.autoAssignMusic} onChange={v=>patch({autoAssignMusic:v})}/><Toggle label="Распределять изображения" text="1 изображение = 1 проект." value={s.autoAssignImages} onChange={v=>patch({autoAssignImages:v})}/><Toggle label="AI metadata" text="Только при подключённом OpenAI API." value={s.autoGenerateMetadata} onChange={v=>patch({autoGenerateMetadata:v})}/><Toggle label="ENDLUME queue" text="Создавать render marker." value={s.autoQueueRender} onChange={v=>patch({autoQueueRender:v})}/><Toggle label="Открывать ENDLUME" text="Открывать приложение при render задачах." value={s.autoOpenEndlume} onChange={v=>patch({autoOpenEndlume:v})}/></div><label>Интервал локального цикла, сек<input type="number" min="10" max="3600" value={s.autopilotIntervalSec} onChange={e=>patch({autopilotIntervalSec:Math.max(10,+e.target.value||30)})}/></label></details></div>}
 {tab==='endlume'&&<div className="settingsStack"><section className="settingsCard"><h3>ENDLUME Studio</h3><p>Готовые локальные проекты отправляются в RenderQueue без обращения к YouTube.</p><div className="pathLine"><input readOnly value={s.endlumePath} placeholder="ENDLUME Studio.app"/><button onClick={async()=>{const p=await api.chooseEndlume();if(p)patch({endlumePath:p})}}>Выбрать</button>{s.endlumePath&&<button onClick={()=>api.openEndlume(s.endlumePath)}>Открыть</button>}</div></section></div>}
 {tab==='updates'&&<section className="settingsCard"><h3>Update Center</h3><p>Текущая версия: {installedVersion||'—'}</p><Toggle label="Проверять автоматически" text="Проверка updater feed не использует YouTube API." value={s.autoCheckUpdates} onChange={v=>patch({autoCheckUpdates:v})}/><button className="settingsAction" onClick={checkForUpdate}>Проверить обновления</button>{update?.none&&<div className="successBox">Установлена актуальная версия {update.current||installedVersion||'—'}.</div>}{update?.version&&<div className="updateFound"><b>Доступна: {update.version}</b><p>{update.body}</p>{stage&&<strong>{stage}</strong>}{progress!==null&&<div className="progress"><i style={{width:`${progress}%`}}/><span>{progress.toFixed(0)}%</span></div>}<button className="primary" onClick={installUpdate}>Установить и перезапустить</button></div>}{update?.error&&<div className="errorBox">Обновление не установлено. Текущая версия сохранена.<details><summary>Technical detail</summary>{update.error}</details></div>}</section>}
 {tab==='diagnostics'&&<div className="settingsStack"><section className="settingsCard"><div className="panelHead"><div><h3>Локальная диагностика</h3><p>YouTube health/API checks намеренно исключены отсюда.</p></div><button className="primary" disabled={checking} onClick={runDiagnostics}>{checking?'Проверяю…':'Запустить проверку'}</button></div>{diag.length>0&&<div className="diagnosticGrid">{diag.map((x,i)=><div key={i} className={x.ok===false?'bad':x.ok?'good':''}><span><b>{x.label}</b><em>{x.status}</em></span>{x.detail&&<details><summary>Подробнее</summary><p>{x.detail}</p></details>}</div>)}</div>}</section><section className="settingsCard"><h3>Последние события</h3><div className="logs">{logs.length?logs.slice(0,60).map((l,i)=><div key={i} className={l.level}><small>{new Date(l.at).toLocaleString('ru-RU')}</small><span>{l.message}</span></div>):<p>Событий пока нет.</p>}</div></section></div>}</>
}
