import React,{useEffect,useMemo,useState} from 'react';
import {api,type YoutubeUploadSession} from './api';
import {useApp} from './store';
import {readExistingCache} from './channelSchedule';
import {planYoutubeQuota} from './youtubeQuota';
import {mutateShortsState,nextPresetTitle,patchShort,readShortsState,recordShortUpload,shortStatusFromRecord,canStartShortUpload,shortsScheduleSlots,subscribeShortsState,titleConflict,type ShortRecord,type ShortsState} from './shortsCore';
import {todayKrasnoyarskDate} from './publisherSchedule';
import {sortChannelsAlphabetically} from './channelSort';

function useShorts(){const [s,setS]=useState<ShortsState>(()=>readShortsState());useEffect(()=>subscribeShortsState(()=>setS(readShortsState())),[]);return s}
const splitLines=(s:string)=>s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
const tagsText=(x:string[])=>x.join(', ');
const parseTags=(x:string)=>x.split(/[,\n]/).map(t=>t.trim()).filter(Boolean).slice(0,30);
export function ShortsMetadata(){
 const channels=useApp(s=>s.channels),settings=useApp(s=>s.settings),toast=useApp(s=>s.toast);const state=useShorts();const [channelId,setChannelId]=useState(channels[0]?.id||''),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[startDate,setStartDate]=useState(()=>todayKrasnoyarskDate()),[times,setTimes]=useState('10:00\n15:00\n20:00'),[perDay,setPerDay]=useState(3),[sessions,setSessions]=useState<YoutubeUploadSession[]>([]),[presetTitles,setPresetTitles]=useState(''),[presetDescription,setPresetDescription]=useState(''),[presetTags,setPresetTags]=useState('');const channel=channels.find(c=>c.id===channelId),profileId=channel?.youtubeProfileId||'';const rows=useMemo(()=>state.records.filter(r=>r.sourceChannelId===channelId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),[state.records,channelId]);const chosen=rows.filter(r=>selected.includes(r.id));const preset=state.presets[channelId];
 useEffect(()=>{setSelected([]);setPresetTitles((preset?.titleTemplates||[]).join('\n'));setPresetDescription(preset?.descriptionTemplate||'');setPresetTags(tagsText(preset?.tags||[]))},[channelId,preset?.descriptionTemplate,preset?.tags,preset?.titleTemplates]);
 useEffect(()=>{void api.youtubeUploadSessions().then(setSessions).catch(()=>{})},[state.records.filter(r=>r.status==='UPLOADING').length]);
 function setMeta(r:ShortRecord,p:Partial<ShortRecord>){const next={...r,...p};let ms:ShortRecord['metadataStatus']=next.title.trim()&&next.description.trim()&&next.tags.length?'READY':'EMPTY';if(next.title&&titleConflict(state.records,r.sourceChannelId,next.title,r.id))ms='CONFLICT';const locked=['PRIVATE','SCHEDULED','PUBLISHED','UPLOADING','ERROR','QUEUED','CREATING'].includes(r.status);patchShort(r.id,{...p,metadataStatus:ms,status:locked?r.status:'READY'})}
 function savePreset(){mutateShortsState(s=>({...s,presets:{...s.presets,[channelId]:{titleTemplates:splitLines(presetTitles),descriptionTemplate:presetDescription,tags:parseTags(presetTags)}}}));toast('Shorts metadata preset сохранён')}
 function applyPreset(){const titles=splitLines(presetTitles),tags=parseTags(presetTags);if(!presetDescription.trim()||!tags.length){toast('Shorts preset: заполните description и tags');return}let working=[...state.records],applied=0;for(const r of chosen){const title=nextPresetTitle(working,channelId,titles);if(!title){patchShort(r.id,{metadataStatus:'CONFLICT',error:'Нет свободной уникальной вариации Short title'});continue}const nr={...r,title,description:presetDescription,tags,metadataStatus:'READY' as const,status:(['QUEUED','CREATING'].includes(r.status)?r.status:'READY') as ShortRecord['status'],error:undefined};patchShort(r.id,nr);working=working.map(x=>x.id===r.id?nr:x);applied++}toast(`Preset применён: ${applied}`)}
 function assignSchedule(){const target=chosen.filter(r=>r.metadataStatus==='READY');if(!target.length){toast('Выберите Shorts с готовыми metadata');return}const selectedTimes=[...new Set(splitLines(times))];if(selectedTimes.length!==perDay){toast(`Укажите ровно ${perDay} уникальных времён публикации`);return}const existing=(readExistingCache(channelId)?.videos||[]).map(v=>v.publishAt).filter(Boolean) as string[];const own=state.records.filter(r=>r.sourceChannelId===channelId&&!selected.includes(r.id)).map(r=>r.publishAt).filter(Boolean) as string[];try{const slots=shortsScheduleSlots({startDate,times:selectedTimes,count:target.length,occupied:[...existing,...own]});target.forEach((r,i)=>patchShort(r.id,{publishAt:slots[i],privacyStatus:'private'}));toast(`Расписание локально назначено: ${slots.length} • YouTube API: 0`)}catch(e){toast(String(e))}}
 async function uploadPrivate(){if(!profileId){toast('Для этого канала YouTube ещё не подключён');return}const target=chosen.filter(canStartShortUpload);if(!target.length){toast('Нет выбранных Shorts с готовыми metadata');return}const fresh=readShortsState(),sessionJobs=new Set(sessions.map(s=>s.jobId));const uploadable=target.filter(r=>!fresh.records.find(x=>x.id===r.id)?.youtubeVideoId&&!sessionJobs.has(`short:${r.id}`));if(!uploadable.length){toast(target.some(r=>sessionJobs.has(`short:${r.id}`))?'Есть сохранённая resumable session — используйте ВОЗОБНОВИТЬ ЗАГРУЗКУ':'Все выбранные Shorts уже имеют youtubeVideoId — duplicate upload заблокирован');return}const plan=planYoutubeQuota([{method:'videos.insert',count:uploadable.length,label:'Shorts PRIVATE upload'}]);if(!plan.affordable){toast('Локальный quota preflight блокирует эту партию');return}setBusy(true);try{for(const r0 of uploadable){const r=readShortsState().records.find(x=>x.id===r0.id);if(!r||!canStartShortUpload(r))continue;try{await api.shortsValidateFile(r.outputPath,r.duration)}catch(e){patchShort(r.id,{status:'ERROR',uploadStatus:'ERROR',error:`Short validation перед upload: ${String(e)}`});continue}patchShort(r.id,{status:'UPLOADING',uploadStatus:'UPLOADING',error:undefined});const op=`short-upload:${r.id}:${Date.now()}`;try{const res=await api.youtubeUpload(profileId,`short:${r.id}`,r.outputPath,r.title,r.description,r.tags,undefined,settings.youtubeCategoryId,op);if(!res.videoId)throw new Error('YouTube upload завершился без videoId');mutateShortsState(s=>{const at=new Date().toISOString(),records=s.records.map(x=>x.id===r.id?{...x,youtubeVideoId:res.videoId,uploadedAt:at,status:'PRIVATE' as const,uploadStatus:'PRIVATE' as const,privacyStatus:'private' as const,error:undefined,updatedAt:at}:x);return recordShortUpload({...s,records},r.id,res.videoId!,at)});}catch(e){patchShort(r.id,{status:'ERROR',uploadStatus:'ERROR',error:String(e)});}}
 toast('PRIVATE Shorts upload завершён. youtubeVideoId сохранены локально.')}finally{setBusy(false);void api.youtubeUploadSessions().then(setSessions).catch(()=>{})}}
 async function resumeUpload(r:ShortRecord){const session=sessions.find(s=>s.jobId===`short:${r.id}`);if(!session){toast('Сохранённая resumable session не найдена');return}if(r.youtubeVideoId){toast('youtubeVideoId уже сохранён — повторная загрузка запрещена');return}setBusy(true);patchShort(r.id,{status:'UPLOADING',uploadStatus:'UPLOADING',error:undefined});try{const res=await api.youtubeResumeUpload(session.jobId);if(!res.videoId)throw new Error('Resume завершился без videoId');mutateShortsState(s=>{const at=new Date().toISOString(),records=s.records.map(x=>x.id===r.id?{...x,youtubeVideoId:res.videoId,uploadedAt:at,status:'PRIVATE' as const,uploadStatus:'PRIVATE' as const,privacyStatus:'private' as const,error:undefined,updatedAt:at}:x);return recordShortUpload({...s,records},r.id,res.videoId!,at)});toast('Short upload восстановлен без duplicate videos.insert')}catch(e){patchShort(r.id,{status:'ERROR',uploadStatus:'ERROR',error:String(e)});toast(String(e))}finally{setBusy(false)}}
 async function applyYoutubeSchedule(){if(!profileId){toast('YouTube не подключён');return}const target=chosen.filter(r=>r.youtubeVideoId&&r.publishAt);if(!target.length){toast('Нужны PRIVATE Shorts с youtubeVideoId и локальным publishAt');return}setBusy(true);try{for(const r of target){try{const result=await api.youtubeUpdateExisting(profileId,r.youtubeVideoId!,r.title,r.description,r.tags,r.publishAt,'private',`short-schedule:${r.id}:${Date.now()}`);if(result.scheduleAccepted===false||result.scheduleError)throw new Error(result.scheduleError||'YouTube не принял расписание');patchShort(r.id,{status:'SCHEDULED',publishStatus:'SCHEDULED',privacyStatus:'private',error:undefined})}catch(e){patchShort(r.id,{status:'ERROR',error:String(e)})}}toast('Расписание Shorts передано существующему YouTube scheduler pipeline')}finally{setBusy(false)}}
 async function syncStatuses(){if(!profileId){toast('YouTube не подключён');return}setBusy(true);try{const res=await api.youtubeListExisting(profileId,5000),map=new Map(res.videos.map(v=>[v.id,v]));for(const r of rows.filter(x=>x.youtubeVideoId)){const v=map.get(r.youtubeVideoId!);if(!v)continue;if(v.privacyStatus==='public')patchShort(r.id,{status:'PUBLISHED',publishStatus:'PUBLISHED',privacyStatus:'public',error:undefined});else if(v.privacyStatus==='private'&&v.publishAt)patchShort(r.id,{status:'SCHEDULED',publishStatus:'SCHEDULED',privacyStatus:'private',publishAt:v.publishAt,error:undefined});else patchShort(r.id,{status:'PRIVATE',uploadStatus:'PRIVATE',privacyStatus:(v.privacyStatus as ShortRecord['privacyStatus'])||'private',error:undefined})}toast('Статусы Shorts синхронизированы вручную')}catch(e){toast(String(e))}finally{setBusy(false)}}
 const counts=rows.reduce((a,r)=>(a[shortStatusFromRecord(r)]=(a[shortStatusFromRecord(r)]||0)+1,a),{} as Record<string,number>);
 return <div className="shortsMetadata">
  <div className="pageHeader"><div><small>METADATA • SHORTS</small><h1>Shorts Metadata</h1><p>Локальное редактирование metadata и расписания не обращается к YouTube. API вызывается только явными кнопками upload / schedule / sync.</p></div><div className="headerActions"><button disabled={busy||!profileId} onClick={()=>void syncStatuses()}>↻ СИНХРОНИЗИРОВАТЬ СТАТУСЫ</button></div></div>
  <section className="panel"><div className="panelHead"><div><small>CHANNEL</small><h3>Shorts Library</h3></div><span>{rows.length}</span></div><select value={channelId} onChange={e=>setChannelId(e.target.value)}>{sortChannelsAlphabetically(channels).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><div className="shortsKpis"><span><small>Ready</small><b>{counts.READY||0}</b></span><span><small>Metadata ready</small><b>{counts.METADATA_READY||0}</b></span><span><small>Private</small><b>{counts.PRIVATE||0}</b></span><span><small>Scheduled</small><b>{counts.SCHEDULED||0}</b></span><span><small>Published</small><b>{counts.PUBLISHED||0}</b></span><span><small>Errors</small><b>{counts.ERROR||0}</b></span></div></section>
  <section className="panel"><div className="panelHead"><div><small>SHORT PRESET</small><h3>Отдельно от Long VIDEO</h3></div><span>LOCAL</span></div><label>Title templates<textarea value={presetTitles} onChange={e=>setPresetTitles(e.target.value)} placeholder={'Rainy Night Ambience 🌧️ #shorts\nPeaceful Rain for Sleep #shorts'}/></label><label>Description<textarea value={presetDescription} onChange={e=>setPresetDescription(e.target.value)}/></label><label>Tags<input value={presetTags} onChange={e=>setPresetTags(e.target.value)}/></label><div className="publishActions"><button onClick={savePreset}>СОХРАНИТЬ PRESET</button><button className="primary" disabled={!chosen.length} onClick={applyPreset}>ПРИМЕНИТЬ К ВЫБРАННЫМ</button></div></section>
  <section className="panel"><div className="panelHead"><div><small>SCHEDULE • KRASNOYARSK</small><h3>Несколько Shorts в день</h3></div><span>{perDay}/ДЕНЬ</span></div><div className="shortCountPicker"><label>Shorts / день<input type="number" min="1" max="24" value={perDay} onChange={e=>setPerDay(Math.max(1,Math.min(24,+e.target.value||1)))}/></label><div className="presetRow">{[1,2,3,5].map(n=><button key={n} className={perDay===n?'active':''} onClick={()=>setPerDay(n)}>{n}</button>)}</div></div><div className="shortsSettings"><label>Старт<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>Времена<textarea value={times} onChange={e=>setTimes(e.target.value)} placeholder={'10:00\n15:00\n20:00'}/></label></div><div className="publishActions"><button disabled={!chosen.length} onClick={assignSchedule}>НАЗНАЧИТЬ ЛОКАЛЬНО • 0 API</button><button disabled={busy||!chosen.some(r=>r.youtubeVideoId&&r.publishAt)} onClick={()=>void applyYoutubeSchedule()}>ПРИМЕНИТЬ К PRIVATE НА YOUTUBE</button></div></section>
  <section className="panel"><div className="panelHead"><div><small>PRIVATE UPLOAD</small><h3>Существующий Upload Queue / OAuth</h3></div><span>{selected.length} SELECTED</span></div><div className="publishActions"><button onClick={()=>setSelected(rows.map(r=>r.id))}>ВЫБРАТЬ ВСЕ</button><button onClick={()=>setSelected([])}>СНЯТЬ</button><button className="primary" disabled={busy||!chosen.length} onClick={()=>void uploadPrivate()}>ЗАГРУЗИТЬ SHORTS PRIVATE</button></div><p className="quotaFinePrint">Повторный upload блокируется, если youtubeVideoId уже сохранён. Resumable session использует существующий youtube_resume_upload.</p></section>
  <section className="panel shortsMetaList">{rows.length?rows.map(r=><article key={r.id} className="shortMetaRow"><input type="checkbox" checked={selected.includes(r.id)} onChange={()=>setSelected(selected.includes(r.id)?selected.filter(x=>x!==r.id):[...selected,r.id])}/><div><small>{r.id} • {r.start.toFixed(1)}–{r.end.toFixed(1)}s • {shortStatusFromRecord(r)}</small><input value={r.title} placeholder="Short title" onChange={e=>setMeta(r,{title:e.target.value})}/><textarea value={r.description} placeholder="Description" onChange={e=>setMeta(r,{description:e.target.value})}/><input value={tagsText(r.tags)} placeholder="tags" onChange={e=>setMeta(r,{tags:parseTags(e.target.value)})}/><div className="shortMetaFoot"><span>{r.publishAt?new Date(r.publishAt).toLocaleString('ru-RU'):'Дата не назначена'}</span><span>{r.youtubeVideoId?`YouTube: ${r.youtubeVideoId}`:'LOCAL'}</span>{r.metadataStatus==='CONFLICT'&&<b className="jobError">TITLE CONFLICT</b>}</div>{r.error&&<small className="jobError">{r.error}</small>}{sessions.some(s=>s.jobId===`short:${r.id}`)&&!r.youtubeVideoId&&<button disabled={busy} onClick={()=>void resumeUpload(r)}>ВОЗОБНОВИТЬ ЗАГРУЗКУ</button>}</div></article>):<p>Shorts ещё не созданы.</p>}</section>
 </div>
}
