import React,{useEffect,useMemo,useRef,useState} from 'react';
import {api} from './api';
import {useApp} from './store';
import type {VideoJob} from './types';
import {mutateShortsState,patchShort,patchShortBatch,planSegments,readShortsState,recordUsedSegments,recoverInterruptedShorts,shortOutputPath,shortStatusFromRecord,subscribeShortsState,type ShortBatch,type ShortRecord,type ShortsState,type ShortSelectionMode,writeShortsState} from './shortsCore';

const statusRu:Record<string,string>={CREATING:'СОЗДАЁТСЯ',READY:'ГОТОВ',METADATA_READY:'METADATA READY',QUEUED:'В ОЧЕРЕДИ',UPLOADING:'ЗАГРУЗКА',PRIVATE:'PRIVATE',SCHEDULED:'SCHEDULED',PUBLISHED:'PUBLISHED',ERROR:'ОШИБКА'};
function useShorts(){const [s,setS]=useState<ShortsState>(()=>readShortsState());useEffect(()=>subscribeShortsState(()=>setS(readShortsState())),[]);return s}
function id(prefix:string){return `${prefix}_${typeof crypto!=='undefined'&&'randomUUID'in crypto?crypto.randomUUID():`${Date.now()}_${Math.random().toString(36).slice(2)}`}`}
export function ShortsFactory({channelId,selectedJobIds=[],initialSourceId}:{channelId:string;selectedJobIds?:string[];initialSourceId?:string}){
 const jobs=useApp(s=>s.jobs),channels=useApp(s=>s.channels),toast=useApp(s=>s.toast);const state=useShorts();const [count,setCount]=useState(20),[avg,setAvg]=useState(30),[min,setMin]=useState(30),[max,setMax]=useState(30),[mode,setMode]=useState<ShortSelectionMode>('uniform'),[busy,setBusy]=useState(false),[planning,setPlanning]=useState('');const worker=useRef(false);const channel=channels.find(c=>c.id===channelId);const ready=useMemo(()=>jobs.filter(j=>j.channelId===channelId&&j.status==='READY_UPLOAD'&&Boolean(j.finalPath)),[jobs,channelId]);const selected=ready.filter(j=>selectedJobIds.includes(j.id));const rows=state.records.filter(r=>r.sourceChannelId===channelId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const batches=state.batches.filter(b=>b.channelId===channelId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
 useEffect(()=>{const s=readShortsState();const r=recoverInterruptedShorts(s);if(JSON.stringify(s)!==JSON.stringify(r))writeShortsState(r)},[]);
 async function createFrom(list:VideoJob[]){if(!list.length){toast('Нет готовых MP4 для Shorts');return}setBusy(true);const batchId=id('shortbatch'),now=new Date().toISOString();setPlanning(`Проверяю ${list.length} исходников…`);const created:ShortRecord[]=[];try{for(let index=0;index<list.length;index++){const j=list[index];if(!j.finalPath)continue;setPlanning(`FFprobe ${index+1}/${list.length}: VIDEO_${String(j.number).padStart(3,'0')}`);const probe=await api.shortsProbeSource(j.finalPath);const used=recordUsedSegments([...state.records,...created],j.finalPath);const segments=planSegments({count,sourceDuration:probe.duration,averageDuration:avg,minDuration:min,maxDuration:max,mode,used});for(const seg of segments){const sid=id('short');created.push({id:sid,batchId,sourceProjectId:j.id,sourceVideoId:j.id,sourcePath:j.finalPath,sourceChannelId:j.channelId,start:seg.start,end:seg.end,duration:seg.duration,outputPath:shortOutputPath(j.finalPath,sid),createdAt:now,updatedAt:now,status:'QUEUED',metadataStatus:'EMPTY',uploadStatus:'LOCAL',publishStatus:'UNSCHEDULED',title:'',description:'',tags:[],privacyStatus:'private',attempts:0})}}
 const batch:ShortBatch={id:batchId,channelId,sourceProjectIds:list.map(x=>x.id),requestedPerVideo:count,createdAt:now,updatedAt:now,paused:false,status:'QUEUED'};mutateShortsState(s=>({...s,records:[...s.records,...created],batches:[...s.batches,batch]}));toast(`Shorts поставлены в очередь: ${created.length}`)}catch(e){toast(`Shorts Factory: ${String(e)}`)}finally{setPlanning('');setBusy(false)}}
 useEffect(()=>{if(worker.current)return;const next=state.records.find(r=>r.status==='QUEUED'&&!state.batches.find(b=>b.id===r.batchId)?.paused);if(!next)return;worker.current=true;void(async()=>{patchShort(next.id,{status:'CREATING',error:undefined,attempts:next.attempts+1});patchShortBatch(next.batchId,{status:'RUNNING'});try{const result=await api.shortsRenderSegment(next.sourcePath,next.outputPath,next.start,next.duration);patchShort(next.id,{status:next.metadataStatus==='READY'?'METADATA_READY':'READY',outputPath:result.outputPath,duration:result.duration,error:undefined});}catch(e){patchShort(next.id,{status:'ERROR',error:String(e)});}finally{const fresh=readShortsState(),batch=fresh.batches.find(b=>b.id===next.batchId);if(batch){const br=fresh.records.filter(r=>r.batchId===batch.id);const pending=br.some(r=>r.status==='QUEUED'||r.status==='CREATING');const ok=br.some(r=>r.status!=='ERROR');worker.current=false;patchShortBatch(batch.id,{status:pending?(batch.paused?'PAUSED':'QUEUED'):(ok?'DONE':'ERROR')})}else{worker.current=false}}})()},[state.records.map(r=>`${r.id}:${r.status}`).join('|'),state.batches.map(b=>`${b.id}:${b.paused}`).join('|')]);
 function pause(id:string,v:boolean){patchShortBatch(id,{paused:v,status:v?'PAUSED':'QUEUED'})}
 function retry(r:ShortRecord){patchShort(r.id,{status:'QUEUED',error:undefined})}
 const counts=useMemo(()=>{const x:Record<string,number>={};for(const r of rows)x[shortStatusFromRecord(r)]=(x[shortStatusFromRecord(r)]||0)+1;return x},[rows]);
 const suggested=initialSourceId?ready.find(x=>x.id===initialSourceId):undefined;
 return <div className="shortsFactory">
  <section className="panel"><div className="panelHead"><div><small>SHORTS FACTORY • LOCAL • 0 YOUTUBE API</small><h2>{channel?.name||'Shorts'}</h2><p>Готовый horizontal MP4 → 1080×1920. Полный 16:9 кадр поверх размытого фона, исходный звук, без субтитров.</p></div><span>{rows.length} SHORTS</span></div>
   <div className="shortsKpis"><span><small>Готово</small><b>{counts.READY||0}</b></span><span><small>Metadata</small><b>{counts.METADATA_READY||0}</b></span><span><small>Scheduled</small><b>{counts.SCHEDULED||0}</b></span><span><small>Uploaded</small><b>{(counts.PRIVATE||0)+(counts.SCHEDULED||0)+(counts.PUBLISHED||0)}</b></span><span><small>Published</small><b>{counts.PUBLISHED||0}</b></span><span><small>Errors</small><b>{counts.ERROR||0}</b></span></div>
  </section>
  <section className="panel"><div className="panelHead"><div><small>SETTINGS</small><h3>Нарезка</h3></div><span>~{avg}s</span></div><div className="shortCountPicker"><label>Количество / VIDEO<input type="number" min="1" max="500" value={count} onChange={e=>setCount(Math.max(1,Math.min(500,+e.target.value||1)))}/></label><div className="presetRow">{[1,5,10,20,30,50].map(n=><button key={n} className={count===n?'active':''} onClick={()=>setCount(n)}>{n}</button>)}</div></div><div className="shortsSettings"><label>Средняя длительность<input type="number" min="5" max="60" value={avg} onChange={e=>{const v=Math.max(5,Math.min(60,+e.target.value||30));if(min===max&&min===avg){setMin(v);setMax(v)}setAvg(v)}}/></label><label>Мин, сек<input type="number" min="5" max="60" value={min} onChange={e=>setMin(Math.max(5,Math.min(60,+e.target.value||30)))}/></label><label>Макс, сек<input type="number" min="5" max="60" value={max} onChange={e=>setMax(Math.max(5,Math.min(60,+e.target.value||30)))}/></label><label>Фрагменты<select value={mode} onChange={e=>setMode(e.target.value as ShortSelectionMode)}><option value="uniform">РАВНОМЕРНО</option><option value="random">СЛУЧАЙНО</option></select></label></div>{planning&&<div className="cacheNotice"><b>ПОДГОТОВКА</b><span>{planning}</span></div>}
   <div className="publishActions"><button className="primary" disabled={busy||!selected.length} onClick={()=>void createFrom(selected)}>СОЗДАТЬ SHORTS ИЗ ВЫБРАННЫХ VIDEO ({selected.length})</button><button disabled={busy||!ready.length} onClick={()=>void createFrom(ready)}>СОЗДАТЬ SHORTS ИЗ ВСЕХ ГОТОВЫХ VIDEO ({ready.length})</button></div>
  </section>
  <section className="panel"><div className="panelHead"><div><small>READY MP4</small><h3>Исходные VIDEO</h3></div><span>{ready.length}</span></div>{ready.length?<div className="shortsSources">{ready.map(j=><div key={j.id} className={suggested?.id===j.id?'shortSource suggested':'shortSource'}><span><b>VIDEO_{String(j.number).padStart(3,'0')}</b><small>{j.finalPath}</small></span><button className="primary small" disabled={busy} onClick={()=>void createFrom([j])}>СОЗДАТЬ SHORTS</button></div>)}</div>:<p>Нет READY_UPLOAD MP4 для этого канала.</p>}</section>
  <section className="panel"><div className="panelHead"><div><small>BATCH QUEUE</small><h3>Прогресс / Pause / Resume</h3></div><span>{batches.length}</span></div>{batches.map(b=>{const br=state.records.filter(r=>r.batchId===b.id),done=br.filter(r=>!['QUEUED','CREATING'].includes(r.status)).length,errors=br.filter(r=>r.status==='ERROR').length;return <div className="shortBatch" key={b.id}><span><b>{done} / {br.length}</b><small>{b.status}{errors?` • errors ${errors}`:''} • PAUSE после текущего render</small>{b.sourceProjectIds.map(pid=>{const sr=br.filter(r=>r.sourceProjectId===pid),sd=sr.filter(r=>!['QUEUED','CREATING'].includes(r.status)).length,se=sr.filter(r=>r.status==='ERROR').length,active=sr.find(r=>r.status==='CREATING');return <small key={pid}>{pid}: {sd}/{sr.length}{active?' • rendering':''}{se?` • errors ${se}`:''}</small>})}</span><div><button onClick={()=>pause(b.id,!b.paused)}>{b.paused?'RESUME':'PAUSE'}</button></div></div>})}</section>
  <section className="panel"><div className="panelHead"><div><small>SHORTS LIBRARY</small><h3>Локальные файлы</h3></div><span>{rows.length}</span></div>{rows.map(r=><div className="shortRow" key={r.id}><span><b>{r.id.slice(0,18)}</b><small>{r.start.toFixed(1)} → {r.end.toFixed(1)} • {r.duration.toFixed(1)}s</small><small>{r.outputPath}</small></span><em>{statusRu[shortStatusFromRecord(r)]||r.status}</em>{r.error&&<small className="jobError">{r.error}</small>}{r.status==='ERROR'&&<button onClick={()=>retry(r)}>RETRY</button>}</div>)}</section>
 </div>
}
