import {describe,it,expect} from 'vitest';
import {emptyShortsState,planSegments,rangesOverlap,recoverInterruptedShorts,shortOutputPath,shortsScheduleSlots,titleConflict,recordShortUpload,recordShortUploadAttempt,shortUploadsToday,normalizeShortsState,recordUsedSegments,shortStatusFromRecord,canStartShortUpload} from './shortsCore';
const seq=(xs:number[])=>{let i=0;return()=>xs[i++%xs.length]};
describe('Shorts Factory core',()=>{
 it('plans 20 unique non-overlapping uniform segments across two hours',()=>{const rows=planSegments({count:20,sourceDuration:7200,averageDuration:30,minDuration:30,maxDuration:30,mode:'uniform',rng:()=>0});expect(rows).toHaveLength(20);for(let i=0;i<rows.length;i++){expect(rows[i].duration).toBe(30);for(let j=i+1;j<rows.length;j++)expect(rangesOverlap(rows[i],rows[j])).toBe(false)}});
 it('random mode avoids persisted used range',()=>{const used=[{start:0,end:30,duration:30}],rows=planSegments({count:5,sourceDuration:600,averageDuration:30,minDuration:28,maxDuration:32,mode:'random',used,rng:seq([0,0,.1,.2,.3,.4,.5,.6,.7,.8,.9])});expect(rows).toHaveLength(5);expect(rows.every(r=>!rangesOverlap(r,used[0]))).toBe(true)});
 it('recovers CREATING after restart without resetting completed records',()=>{const s=emptyShortsState();s.records=[{id:'a',batchId:'b',sourceProjectId:'p',sourceVideoId:'p',sourcePath:'/a.mp4',sourceChannelId:'c',start:1,end:31,duration:30,outputPath:'/s.mp4',createdAt:'x',updatedAt:'x',status:'CREATING',metadataStatus:'EMPTY',uploadStatus:'LOCAL',publishStatus:'UNSCHEDULED',title:'',description:'',tags:[],privacyStatus:'private',attempts:1},{id:'z',batchId:'b',sourceProjectId:'p',sourceVideoId:'p',sourcePath:'/a.mp4',sourceChannelId:'c',start:50,end:80,duration:30,outputPath:'/z.mp4',createdAt:'x',updatedAt:'x',status:'READY',metadataStatus:'EMPTY',uploadStatus:'LOCAL',publishStatus:'UNSCHEDULED',title:'',description:'',tags:[],privacyStatus:'private',attempts:1}];const r=recoverInterruptedShorts(s);expect(r.records[0].status).toBe('QUEUED');expect(r.records[1].status).toBe('READY')});
 it('keeps channel/source output separation and Long sibling layout',()=>{expect(shortOutputPath('/Render/NEON/Long/video_001.mp4','short_001')).toBe('/Render/NEON/Shorts/video_001/short_001.mp4')});
 it('creates multiple daily Krasnoyarsk slots without duplicate times',()=>{const x=shortsScheduleSlots({startDate:'2026-09-10',times:['10:00','15:00','20:00'],count:6});expect(x).toHaveLength(6);expect(new Set(x).size).toBe(6);expect(x[0]).toContain('2026-09-10T03:00:00.000Z');expect(x[3]).toContain('2026-09-11T03:00:00.000Z')});
 it('detects duplicate confirmed titles',()=>{const s:any=[{id:'1',sourceChannelId:'c',title:'Rain #shorts',metadataStatus:'READY'}];expect(titleConflict(s,'c',' rain #SHORTS ','2')).toBe(true)});
 it('maps 5 source videos x 10 segments to 50 distinct source/output records',()=>{const all:any[]=[];for(let v=1;v<=5;v++){const path=`/Render/CH/Long/video_${String(v).padStart(3,'0')}.mp4`;const segs=planSegments({count:10,sourceDuration:7200,averageDuration:30,minDuration:30,maxDuration:30,mode:'uniform',rng:()=>.5});segs.forEach((seg,i)=>all.push({sourceProjectId:`p${v}`,sourceVideoId:`p${v}`,sourcePath:path,sourceChannelId:'ch',outputPath:shortOutputPath(path,`s${v}_${i}`),...seg}))}expect(all).toHaveLength(50);expect(new Set(all.map(x=>x.outputPath)).size).toBe(50);for(let v=1;v<=5;v++)expect(all.filter(x=>x.sourceProjectId===`p${v}`)).toHaveLength(10)});
 it('persists Shorts metadata fields and scheduling state through normalization',()=>{const s:any=emptyShortsState();s.records=[{id:'s',batchId:'b',sourceProjectId:'p',sourceVideoId:'p',sourcePath:'/a.mp4',sourceChannelId:'c',start:1,end:31,duration:30,outputPath:'/s.mp4',createdAt:'x',updatedAt:'x',status:'READY',metadataStatus:'READY',uploadStatus:'LOCAL',publishStatus:'UNSCHEDULED',title:'Title #shorts',description:'Desc',tags:['a','b'],publishAt:'2026-09-10T03:00:00.000Z',privacyStatus:'private',attempts:0}];const n=normalizeShortsState(JSON.parse(JSON.stringify(s)));expect(n.records[0].title).toBe('Title #shorts');expect(n.records[0].description).toBe('Desc');expect(n.records[0].tags).toEqual(['a','b']);expect(n.records[0].publishAt).toBe('2026-09-10T03:00:00.000Z');expect(n.records[0].privacyStatus).toBe('private')});
 it('keeps failed allocated ranges reserved so a new batch cannot reuse them',()=>{const r:any={sourcePath:'/a.mp4',start:100,end:130,duration:30,status:'ERROR'};expect(recordUsedSegments([r],'/a.mp4')).toEqual([{start:100,end:130,duration:30}])});
 it('reports queued creation as QUEUED instead of fake READY',()=>{const r:any={status:'QUEUED',metadataStatus:'EMPTY',uploadStatus:'LOCAL',publishStatus:'UNSCHEDULED'};expect(shortStatusFromRecord(r)).toBe('QUEUED')});
 it('blocks duplicate upload when youtubeVideoId is already persisted',()=>{const base:any={status:'READY',metadataStatus:'READY',uploadStatus:'LOCAL'};expect(canStartShortUpload({...base,youtubeVideoId:'yt1'})).toBe(false);expect(canStartShortUpload({...base,youtubeVideoId:undefined})).toBe(true);expect(canStartShortUpload({...base,status:'CREATING'})).toBe(false)});
 it('uses requested average as the center of a duration range',()=>{const x=planSegments({count:1,sourceDuration:600,averageDuration:30,minDuration:28,maxDuration:32,mode:'uniform',rng:()=>.5});expect(x[0].duration).toBe(30)});
 it('records actual videos.insert attempt once and attaches response id',()=>{let s=emptyShortsState();s=recordShortUploadAttempt(s,'s1','short-upload:s1:1','2026-09-06T12:00:00Z');s=recordShortUploadAttempt(s,'s1','short-upload:s1:1','2026-09-06T12:00:01Z');s=recordShortUpload(s,'s1','y1','2026-09-06T12:01:00Z');expect(s.shortUploadEvents).toHaveLength(1);expect(s.shortUploadEvents[0].youtubeVideoId).toBe('y1');expect(shortUploadsToday(s,new Date('2026-09-06T15:00:00Z'))).toBe(1)})
});
