import React,{useMemo,useState} from 'react';
import {useApp} from './store';
import {formatNumber} from './core';
import type {AnalyticsPoint,ChannelAnalytics} from './types';

type Period='7'|'28'|'90';
const money=(v?:number)=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
const num=(v?:number,d=0)=>v==null?'—':v.toLocaleString('ru-RU',{maximumFractionDigits:d});
const dur=(sec?:number)=>sec==null?'—':`${Math.floor(sec/60)}:${String(Math.round(sec)%60).padStart(2,'0')}`;
function slice(a:ChannelAnalytics|undefined,days:number){if(!a?.daily?.length)return[];return a.daily.slice(-days)}
function sum(rows:AnalyticsPoint[],key:'views'|'watchMinutes'|'estimatedRevenue'){return rows.reduce((n,x)=>n+Number(x[key]||0),0)}
function Line({rows}:{rows:AnalyticsPoint[]}){const vals=rows.map(x=>x.views),max=Math.max(1,...vals);const pts=vals.map((v,i)=>`${rows.length<2?0:i/(rows.length-1)*100},${38-v/max*34}`).join(' ');return <svg className="analyticsSpark revenueLine" viewBox="0 0 100 40" preserveAspectRatio="none"><polyline points={pts}/></svg>}

export function AnalyticsPage(){
 const channels=useApp(s=>s.channels),setPage=useApp(s=>s.setPage);
 const [channelId,setChannelId]=useState(channels[0]?.id||''),[period,setPeriod]=useState<Period>('28');
 const c=channels.find(x=>x.id===channelId),a=c?.analytics,days=Number(period),rows=useMemo(()=>slice(a,days),[a,days]);
 const views=rows.length?sum(rows,'views'):a?.periodDays===days?a.views:undefined,watch=rows.length?sum(rows,'watchMinutes'):a?.periodDays===days?a.watchMinutes:undefined,revKnown=Boolean(rows.some(x=>x.estimatedRevenue!=null)||(a?.periodDays===days&&a?.estimatedRevenue!=null)),revenue=rows.length?sum(rows,'estimatedRevenue'):a?.periodDays===days?a.estimatedRevenue:undefined,rpm=revKnown&&views?Number(revenue||0)/views*1000:undefined;
 return <><div className="pageHeader"><div><small>ANALYTICS • LOCAL CACHE</small><h1>Аналитика</h1><p>Никаких запросов к YouTube на этом экране. Показаны только данные последней ручной синхронизации из YouTube workspace.</p></div><div className="headerActions"><button className="primary" onClick={()=>setPage('youtube')}>Обновить в YouTube</button></div></div><div className="cacheNotice"><b>Последняя синхронизация</b><span>{a?.updatedAt?new Date(a.updatedAt).toLocaleString('ru-RU'):'Нет данных'}</span></div><div className="analyticsToolbar"><select value={channelId} onChange={e=>setChannelId(e.target.value)}>{channels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="periodTabs analyticsPeriods">{(['7','28','90'] as Period[]).map(x=><button key={x} className={period===x?'active':''} onClick={()=>setPeriod(x)}>{x} дней</button>)}</div></div>{!a?<div className="empty"><b>Аналитика ещё не синхронизирована</b><p>Открой YouTube → Данные YouTube и нажми «Обновить аналитику».</p></div>:<><div className="channelMetricsGrid analyticsKpis"><span><small>Views</small><b>{views==null?'—':formatNumber(views)}</b></span><span><small>Watch Time</small><b>{watch==null?'—':`${num(watch/60,1)} ч`}</b></span><span><small>Revenue</small><b>{revKnown?money(revenue):'—'}</b></span><span><small>RPM</small><b>{rpm==null?'—':`$${rpm.toFixed(2)}`}</b></span><span><small>Avg View Duration</small><b>{a.periodDays===days?dur(a.averageViewDuration):'—'}</b></span><span><small>Avg %</small><b>{a.periodDays===days?`${num(a.averageViewPercentage,1)}%`:'—'}</b></span><span><small>Subscribers</small><b>{c?.stats?.subscribers!=null?formatNumber(c.stats.subscribers):'—'}</b></span><span><small>CTR</small><b>{a.impressionCtr==null?'—':`${num(a.impressionCtr,2)}%`}</b></span></div><section className="panel analyticsWide"><div className="panelHead"><div><small>CACHED DYNAMICS</small><h3>Просмотры</h3></div><span>{rows.length} точек</span></div>{rows.length?<><Line rows={rows}/><div className="chartFoot"><span>{rows[0]?.date}</span><span>{rows.at(-1)?.date}</span></div></>:<p>Для этого периода нет сохранённых daily points.</p>}</section><section className="panel"><div className="panelHead"><div><small>TOP VIDEOS • CACHE</small><h3>Сохранённые метрики видео</h3></div></div>{a.topVideos?.length?<div className="topVideoList rich">{a.topVideos.slice(0,10).map(v=><div key={v.id}>{v.thumbnail?<img src={v.thumbnail} loading="lazy"/>:<i/>}<span><strong>{v.title}</strong><small>{formatNumber(v.views)} views • {num(v.averageViewPercentage,1)}% • {money(v.estimatedRevenue)}</small></span></div>)}</div>:<p>Нет данных.</p>}</section></>}</>
}
