#!/usr/bin/env python3
from pathlib import Path
import subprocess,sys,tempfile

src=Path(__file__).with_name('apply_v106.py')
s=src.read_text(encoding='utf-8')

old_line='replacement="{filtered.length===0?<div className=\\"empty\\"><b>Нет задач в этом фильтре</b><p>Создай точное число проектов или включи поддержание буфера.</p><button className=\\"primary\\" onClick={()=>setPlanOpen(true)}>Создать проекты</button></div>:<><div className=\\"pmBulkBar\\"><span>Выбрано <b>{selectedJobIds.filter(id=>visibleJobIds.includes(id)).length}</b> / {visibleJobIds.length}</span><button onClick={()=>patchPrefs({selectedJobIds:[...new Set([...selectedJobIds,...visibleJobIds])]})}>Выбрать всё</button><button onClick={()=>patchPrefs({selectedJobIds:selectedJobIds.filter(id=>!visibleJobIds.includes(id))})}>Снять выделение</button><button className=\\"danger\\" disabled={!selectedJobIds.some(id=>visibleJobIds.includes(id))} onClick={()=>void deleteJobs(selectedJobIds.filter(id=>visibleJobIds.includes(id)),\'Удалить выбранные проекты?\')}>Удалить выбранные</button><button className=\\"danger\\" onClick={()=>void deleteJobs(visibleJobIds,\'Удалить все проекты в текущем списке?\')}>Удалить все</button></div><div className=\\"jobs virtualReady\\">"'
new_line='replacement="{filtered.length===0?<div className=\\"empty\\"><b>Нет задач в этом фильтре</b><p>Создай точное число проектов или включи поддержание буфера.</p><button className=\\"primary\\" onClick={()=>setPlanOpen(true)}>Создать проекты</button></div>:<div className=\\"jobs virtualReady\\"><div className=\\"pmBulkBar\\"><span>Выбрано <b>{selectedJobIds.filter(id=>visibleJobIds.includes(id)).length}</b> / {visibleJobIds.length}</span><button onClick={()=>patchPrefs({selectedJobIds:[...new Set([...selectedJobIds,...visibleJobIds])]})}>Выбрать всё</button><button onClick={()=>patchPrefs({selectedJobIds:selectedJobIds.filter(id=>!visibleJobIds.includes(id))})}>Снять выделение</button><button className=\\"danger\\" disabled={!selectedJobIds.some(id=>visibleJobIds.includes(id))} onClick={()=>void deleteJobs(selectedJobIds.filter(id=>visibleJobIds.includes(id)),\'Удалить выбранные проекты?\')}>Удалить выбранные</button><button className=\\"danger\\" onClick={()=>void deleteJobs(visibleJobIds,\'Удалить все проекты в текущем списке?\')}>Удалить все</button></div>"'
if old_line not in s:
    raise SystemExit('VYRON 1.0.6 runner: expected bulk replacement line missing')
s=s.replace(old_line,new_line,1)

remove='''# Existing expression ends with </div>}</>} — convert first matching queue close.\nneedle="</div>}</>}\\n   {tab===\'materials\'"\nmust(needle in s,\'ProductionOS queue close marker missing\')\ns=s.replace(needle,"</div></>}</>}\\n   {tab===\'materials\'",1)\n'''
if remove not in s:
    raise SystemExit('VYRON 1.0.6 runner: expected obsolete close-marker block missing')
s=s.replace(remove,'',1)

# Keep the storage schema literal type exact after object spread.
s=s.replace("{...prev,...p,version:2};emit(next)","{...prev,...p,version:2 as const};emit(next)")

# Avoid a mutable/immutable borrow overlap in Rust rotate_left generated by the overlay.
s=s.replace('picked.rotate_left((project_no+attempt+1)%picked.len());','let n=picked.len();picked.rotate_left((project_no+attempt+1)%n);')

with tempfile.NamedTemporaryFile('w',suffix='.py',delete=False,encoding='utf-8') as f:
    f.write(s);tmp=Path(f.name)
try:
    subprocess.check_call([sys.executable,str(tmp),*sys.argv[1:]])
finally:
    tmp.unlink(missing_ok=True)

# Acceptance: prove v2 UI state actually survives a write/read cycle in localStorage.
target=Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve()
(target/'src/productionPrefs.test.ts').write_text(r'''import {beforeEach,describe,expect,it} from 'vitest';
import {defaultChannelProductionPrefs,patchChannelProductionPrefs,patchProductionPrefs,readProductionPrefs} from './productionPrefs';

class MemoryStorage {
  private data=new Map<string,string>();
  get length(){return this.data.size}
  clear(){this.data.clear()}
  getItem(k:string){return this.data.has(k)?this.data.get(k)!:null}
  key(i:number){return [...this.data.keys()][i]??null}
  removeItem(k:string){this.data.delete(k)}
  setItem(k:string,v:string){this.data.set(k,String(v))}
}

beforeEach(()=>{
  Object.defineProperty(globalThis,'localStorage',{value:new MemoryStorage(),configurable:true});
  Object.defineProperty(globalThis,'window',{value:{dispatchEvent:()=>true,addEventListener:()=>{},removeEventListener:()=>{}},configurable:true});
  Object.defineProperty(globalThis,'CustomEvent',{value:class {detail:any;constructor(_t:string,init?:any){this.detail=init?.detail}},configurable:true});
});

describe('Production Manager v2 persistence',()=>{
  it('migrates current Production channel from v1 and persists tab/channel across reads',()=>{
    localStorage.setItem('vyron:production-workspace:v1',JSON.stringify({selectedChannelId:'neon'}));
    expect(readProductionPrefs().selectedChannelId).toBe('neon');
    patchProductionPrefs({selectedChannelId:'lost-highway',tab:'manager'});
    const reloaded=readProductionPrefs();
    expect(reloaded.selectedChannelId).toBe('lost-highway');
    expect(reloaded.tab).toBe('manager');
    expect(reloaded.version).toBe(2);
  });
  it('persists channel-specific builder settings and selected projects',()=>{
    expect(defaultChannelProductionPrefs().tracksPerProject).toBe(15);
    patchChannelProductionPrefs('neon',{projectCount:40,tracksPerProject:30,mode:'alphabetical',allowImageReuse:true,lastBatchId:'BATCH-14',selectedProjectIds:['001','003']});
    const p=readProductionPrefs().byChannel.neon;
    expect(p.projectCount).toBe(40);
    expect(p.tracksPerProject).toBe(30);
    expect(p.mode).toBe('alphabetical');
    expect(p.allowImageReuse).toBe(true);
    expect(p.lastBatchId).toBe('BATCH-14');
    expect(p.selectedProjectIds).toEqual(['001','003']);
  });
});
''',encoding='utf-8')
