#!/usr/bin/env python3
from pathlib import Path
import subprocess,sys,tempfile

src=Path(__file__).with_name('apply_v106.py')
s=src.read_text(encoding='utf-8')

old_line='replacement="{filtered.length===0?<div className=\\"empty\\"><b>Нет задач в этом фильтре</b><p>Создай точное число проектов или включи поддержание буфера.</p><button className=\\"primary\\" onClick={()=>setPlanOpen(true)}>Создать проекты</button></div>:<><div className=\\"pmBulkBar\\"><span>Выбрано <b>{selectedJobIds.filter(id=>visibleJobIds.includes(id)).length}</b> / {visibleJobIds.length}</span><button onClick={()=>patchPrefs({selectedJobIds:[...new Set([...selectedJobIds,...visibleJobIds])]})}>Выбрать всё</button><button onClick={()=>patchPrefs({selectedJobIds:selectedJobIds.filter(id=>!visibleJobIds.includes(id))})}>Снять выделение</button><button className=\\"danger\\" disabled={!selectedJobIds.some(id=>visibleJobIds.includes(id))} onClick={()=>void deleteJobs(selectedJobIds.filter(id=>visibleJobIds.includes(id)),\'Удалить выбранные проекты?\')}>Удалить выбранные</button><button className=\\"danger\\" onClick={()=>void deleteJobs(visibleJobIds,\'Удалить все проекты в текущем списке?\')}>Удалить все</button></div><div className=\\"jobs virtualReady\\">"'
new_line='replacement="{filtered.length===0?<div className=\\"empty\\"><b>Нет задач в этом фильтре</b><p>Создай точное число проектов или включи поддержание буфера.</p><button className=\\"primary\\" onClick={()=>setPlanOpen(true)}>Создать проекты</button></div>:<div className=\\"jobs virtualReady\\"><div className=\\"pmBulkBar\\"><span>Выбрано <b>{selectedJobIds.filter(id=>visibleJobIds.includes(id)).length}</b> / {visibleJobIds.length}</span><button onClick={()=>patchPrefs({selectedJobIds:[...new Set([...selectedJobIds,...visibleJobIds])]})}>Выбрать всё</button><button onClick={()=>patchPrefs({selectedJobIds:selectedJobIds.filter(id=>!visibleJobIds.includes(id))})}>Снять выделение</button><button className=\\"danger\\" disabled={!selectedJobIds.some(id=>visibleJobIds.includes(id))} onClick={()=>void deleteJobs(selectedJobIds.filter(id=>visibleJobIds.includes(id)),\'Удалить выбранные проекты?\')}>Удалить выбранные</button><button className=\\"danger\\" onClick={()=>void deleteJobs(visibleJobIds,\'Удалить все проекты в текущем списке?\')}>Удалить все</button></div>"'
if old_line not in s:
    raise SystemExit('VYRON 1.0.6 runner: expected bulk replacement line missing')
s=s.replace(old_line,new_line,1)

remove='''# Existing expression ends with </div>}</>} — convert first matching queue close.\nneedle="</div>}</>}\\n   {tab===\'materials\'"\nmust(needle in s,\'ProductionOS queue close marker missing\')\ns=s.replace(needle,"</div></>}</>}\\n   {tab===\'materials\'",1)\n'''
if remove not in s:
    raise SystemExit('VYRON 1.0.6 runner: expected obsolete close-marker block missing')
s=s.replace(remove,'',1)

# Avoid a mutable/immutable borrow overlap in Rust rotate_left generated by the overlay.
s=s.replace('picked.rotate_left((project_no+attempt+1)%picked.len());','let n=picked.len();picked.rotate_left((project_no+attempt+1)%n);')

with tempfile.NamedTemporaryFile('w',suffix='.py',delete=False,encoding='utf-8') as f:
    f.write(s);tmp=Path(f.name)
try:
    subprocess.check_call([sys.executable,str(tmp),*sys.argv[1:]])
finally:
    tmp.unlink(missing_ok=True)
