use chrono::{Duration as ChronoDuration,Utc};
use serde_json::{json,Value};
use tauri::AppHandle;
use crate::youtube;

fn value_f64(v:&Value)->f64{if let Some(n)=v.as_f64(){return n}if let Some(s)=v.as_str(){return s.parse::<f64>().unwrap_or(0.0)}0.0}
fn value_u64(v:&Value)->u64{value_f64(v).max(0.0) as u64}
fn thumb_url(sn:&Value)->Option<String>{for p in ["/thumbnails/maxres/url","/thumbnails/standard/url","/thumbnails/high/url","/thumbnails/medium/url","/thumbnails/default/url"]{if let Some(x)=sn.pointer(p).and_then(|x|x.as_str()){return Some(x.to_string())}}None}
fn api_error(v:&Value,fallback:&str)->String{v.pointer("/error/message").and_then(|x|x.as_str()).or_else(||v.get("error_description").and_then(|x|x.as_str())).unwrap_or(fallback).to_string()}
fn report_rows(v:&Value)->Vec<Vec<Value>>{v.get("rows").and_then(|x|x.as_array()).cloned().unwrap_or_default().into_iter().filter_map(|r|r.as_array().cloned()).collect()}

async fn analytics_report(token:&str,start:&str,end:&str,metrics:&str,dimensions:Option<&str>,sort:Option<&str>,max_results:Option<u32>)->Result<Value,String>{
 let mut params:Vec<(&str,String)>=vec![("ids","channel==MINE".into()),("startDate",start.into()),("endDate",end.into()),("metrics",metrics.into())];
 if let Some(d)=dimensions{params.push(("dimensions",d.into()))}if let Some(x)=sort{params.push(("sort",x.into()))}if let Some(m)=max_results{params.push(("maxResults",m.to_string()))}
 let r=reqwest::Client::new().get("https://youtubeanalytics.googleapis.com/v2/reports").bearer_auth(token).query(&params).send().await.map_err(|e|format!("YouTube Analytics network: {e}"))?;
 let st=r.status();let v:Value=r.json().await.map_err(|e|format!("YouTube Analytics JSON: {e}"))?;if !st.is_success(){return Err(api_error(&v,"YouTube Analytics API вернул ошибку"))}Ok(v)
}

#[tauri::command]
pub async fn youtube_channel_analytics(app:AppHandle,profile_id:String,days:Option<u32>)->Result<Value,String>{
 let (token,scopes)=youtube::access_token_and_scopes(&app,&profile_id).await?;
 if !scopes.iter().any(|s|s=="https://www.googleapis.com/auth/yt-analytics.readonly"||s=="https://www.googleapis.com/auth/yt-analytics-monetary.readonly"){return Err("Для аналитики переподключи YouTube OAuth после установки VYRON 0.6.0 — требуется YouTube Analytics readonly.".into())}
 let days=days.unwrap_or(28).clamp(1,365);let end=Utc::now().date_naive();let start=end-ChronoDuration::days(days.saturating_sub(1) as i64);let start_s=start.format("%Y-%m-%d").to_string();let end_s=end.format("%Y-%m-%d").to_string();
 let summary=analytics_report(&token,&start_s,&end_s,"views,estimatedMinutesWatched,averageViewDuration,averageViewPercentage,subscribersGained,subscribersLost,likes,comments,shares",None,None,None).await?;let sr=report_rows(&summary).into_iter().next().unwrap_or_default();let get=|i:usize|sr.get(i).map(value_f64).unwrap_or(0.0);
 let daily=analytics_report(&token,&start_s,&end_s,"views,estimatedMinutesWatched,subscribersGained,subscribersLost",Some("day"),Some("day"),Some(400)).await.unwrap_or_else(|_|json!({"rows":[]}));let daily_rows=report_rows(&daily).into_iter().map(|r|json!({"date":r.get(0).and_then(|x|x.as_str()).unwrap_or(""),"views":r.get(1).map(value_u64).unwrap_or(0),"watchMinutes":r.get(2).map(value_f64).unwrap_or(0.0),"subscribersGained":r.get(3).map(value_u64).unwrap_or(0),"subscribersLost":r.get(4).map(value_u64).unwrap_or(0)})).collect::<Vec<_>>();
 let top=analytics_report(&token,&start_s,&end_s,"views,estimatedMinutesWatched,averageViewDuration,averageViewPercentage,likes,comments,shares",Some("video"),Some("-views"),Some(10)).await.unwrap_or_else(|_|json!({"rows":[]}));let top_rows=report_rows(&top);let top_ids=top_rows.iter().filter_map(|r|r.get(0).and_then(|x|x.as_str())).collect::<Vec<_>>();let mut video_meta=std::collections::HashMap::<String,Value>::new();if !top_ids.is_empty(){let joined=top_ids.join(",");let r=reqwest::Client::new().get("https://www.googleapis.com/youtube/v3/videos").bearer_auth(&token).query(&[("part","snippet"),("id",joined.as_str())]).send().await.map_err(|e|format!("Top videos metadata: {e}"))?;let st=r.status();let v:Value=r.json().await.unwrap_or_else(|_|json!({}));if st.is_success(){for item in v.get("items").and_then(|x|x.as_array()).cloned().unwrap_or_default(){if let Some(id)=item.get("id").and_then(|x|x.as_str()){video_meta.insert(id.to_string(),item);}}}}
 let top_videos=top_rows.into_iter().map(|r|{let id=r.get(0).and_then(|x|x.as_str()).unwrap_or("").to_string();let sn=video_meta.get(&id).and_then(|x|x.get("snippet")).cloned().unwrap_or_else(||json!({}));json!({"id":id,"title":sn.get("title").and_then(|x|x.as_str()).unwrap_or("Видео"),"thumbnail":thumb_url(&sn),"views":r.get(1).map(value_u64).unwrap_or(0),"watchMinutes":r.get(2).map(value_f64).unwrap_or(0.0),"averageViewDuration":r.get(3).map(value_f64).unwrap_or(0.0),"averageViewPercentage":r.get(4).map(value_f64).unwrap_or(0.0),"likes":r.get(5).map(value_u64).unwrap_or(0),"comments":r.get(6).map(value_u64).unwrap_or(0),"shares":r.get(7).map(value_u64).unwrap_or(0)})}).collect::<Vec<_>>();
 let traffic=analytics_report(&token,&start_s,&end_s,"views,estimatedMinutesWatched",Some("insightTrafficSourceType"),Some("-views"),Some(12)).await.unwrap_or_else(|_|json!({"rows":[]}));let traffic_sources=report_rows(&traffic).into_iter().map(|r|json!({"key":r.get(0).and_then(|x|x.as_str()).unwrap_or("OTHER"),"views":r.get(1).map(value_u64).unwrap_or(0),"watchMinutes":r.get(2).map(value_f64).unwrap_or(0.0)})).collect::<Vec<_>>();
 let countries=analytics_report(&token,&start_s,&end_s,"views,estimatedMinutesWatched",Some("country"),Some("-views"),Some(12)).await.unwrap_or_else(|_|json!({"rows":[]}));let countries_rows=report_rows(&countries).into_iter().map(|r|json!({"key":r.get(0).and_then(|x|x.as_str()).unwrap_or("—"),"views":r.get(1).map(value_u64).unwrap_or(0),"watchMinutes":r.get(2).map(value_f64).unwrap_or(0.0)})).collect::<Vec<_>>();
 let cr=reqwest::Client::new().get("https://www.googleapis.com/youtube/v3/channels").bearer_auth(&token).query(&[("part","snippet,statistics"),("mine","true")]).send().await.map_err(|e|format!("YouTube channel stats: {e}"))?;let cv:Value=cr.json().await.unwrap_or_else(|_|json!({}));let ci=cv.get("items").and_then(|x|x.as_array()).and_then(|a|a.first()).cloned().unwrap_or_else(||json!({}));let stat=ci.get("statistics").cloned().unwrap_or_else(||json!({}));
 Ok(json!({"periodDays":days,"updatedAt":Utc::now().to_rfc3339(),"views":get(0) as u64,"watchMinutes":get(1),"averageViewDuration":get(2),"averageViewPercentage":get(3),"subscribersGained":get(4) as u64,"subscribersLost":get(5) as u64,"likes":get(6) as u64,"comments":get(7) as u64,"shares":get(8) as u64,"daily":daily_rows,"topVideos":top_videos,"trafficSources":traffic_sources,"countries":countries_rows,"publicStats":{"channelId":ci.get("id").and_then(|x|x.as_str()),"title":ci.pointer("/snippet/title").and_then(|x|x.as_str()),"thumbnail":ci.get("snippet").and_then(thumb_url),"subscribers":stat.get("subscriberCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()),"views":stat.get("viewCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()),"videos":stat.get("videoCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok())}}))
}

async fn resolve_channel_ref(token:&str,channel_ref:&str)->Result<String,String>{let raw=channel_ref.trim();if raw.starts_with("UC"){return Ok(raw.split(|c:char|c=='?'||c=='/'||c=='&').next().unwrap_or(raw).to_string())}if let Some(pos)=raw.find("/channel/"){let rest=&raw[pos+9..];let id=rest.split(|c:char|c=='/'||c=='?'||c=='&').next().unwrap_or("");if id.starts_with("UC"){return Ok(id.to_string())}}if let Some(pos)=raw.find("/@"){let rest=&raw[pos+2..];let handle=rest.split(|c:char|c=='/'||c=='?'||c=='&').next().unwrap_or("");if !handle.is_empty(){let r=reqwest::Client::new().get("https://www.googleapis.com/youtube/v3/channels").bearer_auth(token).query(&[("part","id"),("forHandle",handle)]).send().await.map_err(|e|format!("YouTube handle: {e}"))?;let v:Value=r.json().await.unwrap_or_else(|_|json!({}));if let Some(id)=v.pointer("/items/0/id").and_then(|x|x.as_str()){return Ok(id.to_string())}}}Err("Не удалось определить Channel ID. Используй URL /channel/UC… или ссылку @handle.".into())}

#[tauri::command]
pub async fn youtube_competitor_snapshot(app:AppHandle,profile_id:String,channel_ref:String)->Result<Value,String>{
 let (token,_)=youtube::access_token_and_scopes(&app,&profile_id).await?;let channel_id=resolve_channel_ref(&token,&channel_ref).await?;let client=reqwest::Client::new();let r=client.get("https://www.googleapis.com/youtube/v3/channels").bearer_auth(&token).query(&[("part","snippet,statistics,contentDetails"),("id",channel_id.as_str())]).send().await.map_err(|e|format!("Competitor channel: {e}"))?;let st=r.status();let v:Value=r.json().await.map_err(|e|e.to_string())?;if !st.is_success(){return Err(api_error(&v,"Не удалось получить конкурента"))}let item=v.get("items").and_then(|x|x.as_array()).and_then(|a|a.first()).ok_or_else(||"Канал конкурента не найден".to_string())?;let sn=item.get("snippet").cloned().unwrap_or_else(||json!({}));let stat=item.get("statistics").cloned().unwrap_or_else(||json!({}));let uploads=item.pointer("/contentDetails/relatedPlaylists/uploads").and_then(|x|x.as_str()).unwrap_or("");
 let mut ids=Vec::<String>::new();if !uploads.is_empty(){let pr=client.get("https://www.googleapis.com/youtube/v3/playlistItems").bearer_auth(&token).query(&[("part","contentDetails"),("playlistId",uploads),("maxResults","10")]).send().await.map_err(|e|format!("Competitor uploads: {e}"))?;let pv:Value=pr.json().await.unwrap_or_else(|_|json!({}));for x in pv.get("items").and_then(|x|x.as_array()).cloned().unwrap_or_default(){if let Some(id)=x.pointer("/contentDetails/videoId").and_then(|x|x.as_str()){ids.push(id.to_string())}}}
 let mut latest=Vec::<Value>::new();if !ids.is_empty(){let joined=ids.join(",");let vr=client.get("https://www.googleapis.com/youtube/v3/videos").bearer_auth(&token).query(&[("part","snippet,statistics"),("id",joined.as_str())]).send().await.map_err(|e|format!("Competitor videos: {e}"))?;let vv:Value=vr.json().await.unwrap_or_else(|_|json!({}));let mut map=std::collections::HashMap::<String,Value>::new();for it in vv.get("items").and_then(|x|x.as_array()).cloned().unwrap_or_default(){if let Some(id)=it.get("id").and_then(|x|x.as_str()){map.insert(id.to_string(),it);}}for id in ids.iter(){if let Some(it)=map.get(id){let s=it.get("snippet").cloned().unwrap_or_else(||json!({}));let st=it.get("statistics").cloned().unwrap_or_else(||json!({}));latest.push(json!({"id":id,"title":s.get("title").and_then(|x|x.as_str()).unwrap_or(""),"thumbnail":thumb_url(&s),"publishedAt":s.get("publishedAt").and_then(|x|x.as_str()),"views":st.get("viewCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()).unwrap_or(0),"likes":st.get("likeCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()).unwrap_or(0),"comments":st.get("commentCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()).unwrap_or(0)}));}}}
 let recent_avg=if latest.is_empty(){0}else{latest.iter().map(|x|x.get("views").and_then(|x|x.as_u64()).unwrap_or(0)).sum::<u64>()/latest.len() as u64};let subscribers=stat.get("subscriberCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()).unwrap_or(0);let views=stat.get("viewCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()).unwrap_or(0);let videos=stat.get("videoCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()).unwrap_or(0);
 Ok(json!({"channelId":channel_id,"name":sn.get("title").and_then(|x|x.as_str()).unwrap_or("YouTube"),"thumbnail":thumb_url(&sn),"subscribers":subscribers,"views":views,"videos":videos,"recentAverageViews":recent_avg,"lastVideoAt":latest.first().and_then(|x|x.get("publishedAt")).and_then(|x|x.as_str()),"latestVideos":latest,"updatedAt":Utc::now().to_rfc3339()}))
}
