import React,{useEffect,useRef,useState} from 'react';
import {api,type GoogleConfigStatus,type YoutubeProfileHealth} from './api';
import {useApp} from './store';
import type {YoutubeProfile} from './types';

const ago=(iso?:string)=>{if(!iso)return '—';const ms=Date.now()-new Date(iso).getTime();const m=Math.max(0,Math.round(ms/60000));return m<1?'только что':m<60?`${m} мин. назад`:m<1440?`${Math.round(m/60)} ч. назад`:`${Math.round(m/1440)} дн. назад`};

export function AccountsPage(){
 const channels=useApp(s=>s.channels),addChannel=useApp(s=>s.addChannel),updateChannel=useApp(s=>s.updateChannel),toast=useApp(s=>s.toast),settings=useApp(s=>s.settings),patchSettings=useApp(s=>s.patchSettings);
 const [profiles,setProfiles]=useState<YoutubeProfile[]>([]),[health,setHealth]=useState<Record<string,YoutubeProfileHealth>>({}),[config,setConfig]=useState<GoogleConfigStatus|null>(null),[busy,setBusy]=useState(false),[checking,setChecking]=useState(false);const file=useRef<HTMLInputElement>(null);
 async function refresh(){const [p,c]=await Promise.all([api.youtubeProfiles(),api.youtubeGoogleConfig()]);setProfiles(p);setConfig(c);return p}
 useEffect(()=>{void refresh().catch(e=>toast(String(e)))},[]);
 async function importCredentials(fl:FileList|null){const f=fl?.[0];if(!f)return;setBusy(true);try{const c=await api.youtubeImportGoogleConfig(await f.text(),settings.youtubeApiKey||'');setConfig(c);toast('Google Credentials сохранены глобально')}catch(e){toast(String(e))}finally{setBusy(false)}}
 function bindProfile(p:YoutubeProfile){if(!p.channelId)return;const c=channels.find(x=>x.youtubeChannelId===p.channelId);if(c){updateChannel(c.id,{youtubeProfileId:p.id,youtubeChannelId:p.channelId,name:p.channelTitle||c.name});return c}return addChannel({name:p.channelTitle||'YouTube канал',youtubeProfileId:p.id,youtubeChannelId:p.channelId})}
 async function connect(){setBusy(true);try{const p=await api.youtubeConnectGlobal();bindProfile(p);await refresh();toast(`Подключён ${p.channelTitle||p.channelId||'YouTube канал'}`)}catch(e){toast(String(e))}finally{setBusy(false)}}
 async function checkAll(){setChecking(true);const next:Record<string,YoutubeProfileHealth>={};for(const p of profiles){try{next[p.id]=await api.youtubeProfileHealth(p.id)}catch(e){next[p.id]={ok:false,status:'RECONNECT_REQUIRED',error:String(e)}}}setHealth(next);setChecking(false)}
 useEffect(()=>{if(profiles.length)void checkAll()},[profiles.length]);
 return <>
  <div className="pageHeader"><div><small>ACCOUNT CENTER</small><h1>Аккаунты YouTube</h1><p>Google Cloud настраивается один раз. Каждый следующий канал подключается только через Google OAuth и автоматически привязывается к VYRON.</p></div><div className="headerActions"><button disabled={checking||!profiles.length} onClick={checkAll}>{checking?'Проверяю…':'↻ Проверить'}</button><button className="primary" disabled={busy||!config?.configured} onClick={connect}>+ Добавить YouTube аккаунт</button></div></div>
  <input ref={file} hidden type="file" accept=".json,application/json" onChange={e=>{void importCredentials(e.target.files);e.currentTarget.value=''}}/>
  <section className="panel googleConfigCard"><div><small>GLOBAL GOOGLE CONFIG</small><h3>Одна конфигурация для всех каналов</h3><p>Импортируй JSON Desktop OAuth Client один раз. VYRON будет использовать его для всех Google-аккаунтов.</p></div><div className="configChecks"><span className={config?.configured?'good':''}>OAuth Client <b>{config?.configured?'✓':'—'}</b></span><span className={config?.projectId?'good':''}>Project <b>{config?.projectId||'—'}</b></span><span className={config?.hasSecret?'good':''}>Client Secret <b>{config?.hasSecret?'✓':'—'}</b></span><span className={settings.youtubeApiKey?'good':''}>Public API Key <b>{settings.youtubeApiKey?'✓':'опционально'}</b></span></div><div className="googleConfigActions"><button className="primary" disabled={busy} onClick={()=>file.current?.click()}>Импортировать credentials.json</button><label>Public API Key<input type="password" placeholder="AIza… (один для всех каналов)" value={settings.youtubeApiKey} onChange={e=>patchSettings({youtubeApiKey:e.target.value.trim()})}/></label></div></section>
  <section className="panel accountsPanel"><div className="panelHead"><div><small>YOUTUBE ACCOUNTS</small><h3>{profiles.length?`${profiles.length} подключено`:'Аккаунтов пока нет'}</h3></div></div>{!profiles.length?<div className="empty"><b>Подключи первый YouTube-аккаунт</b><p>После импорта credentials.json нажми «Добавить YouTube аккаунт», выбери нужный Gmail и разреши доступ.</p></div>:<div className="accountList">{profiles.map(p=>{const h=health[p.id];const bound=channels.find(c=>c.youtubeProfileId===p.id||c.youtubeChannelId===p.channelId);return <article className="accountRow" key={p.id}>{h?.thumbnail?<img src={h.thumbnail} loading="lazy"/>:<div className="accountAvatar">YT</div>}<div className="accountMain"><b>{h?.channelTitle||p.channelTitle||'YouTube канал'}</b><small>{p.channelId||'Channel ID ещё не определён'}</small><div className="accountBadges"><span className={h?.ok?'good':'warn'}>{h?.ok?'● OAuth healthy':h?'● Требуется внимание':'● Проверяется'}</span><span>{bound?`VYRON: ${bound.name}`:'Не привязан'}</span></div></div><div className="accountMeta"><small>Подключён</small><b>{ago(p.connectedAt)}</b><small>Token</small><b>{h?.status||'—'}</b></div><div className="accountActions">{!bound&&<button onClick={()=>{bindProfile(p);toast('Канал добавлен в VYRON')}}>Добавить канал</button>}<button className="danger mini" onClick={async()=>{await api.youtubeDisconnect(p.id);await refresh()}}>Отключить</button></div></article>})}</div>}</section>
 </>
}
