import React,{useMemo,useState} from 'react';
import {useApp} from './store';
import {formatNumber} from './core';
import {refreshChannelAnalytics} from './youtubeIntelligence';
import type {AnalyticsBreakdown,AnalyticsPoint,AnalyticsTopVideo,Channel,ChannelAnalytics} from './types';

type PeriodKey='today'|'yesterday'|'7'|'28'|'90'|'365'|'all';
type DetailTab='overview'|'content'|'audience'|'revenue'|'traffic'|'geography';
type ChartMetric='views'|'estimatedRevenue'|'watchMinutes'|'netSubscribers';
const periods:{key:PeriodKey;label:string;days:number;offset:number;all?:boolean}[]=[{key:'today',label:'Сегодня',days:1,offset:0},{key:'yesterday',label:'Вчера',days:1,offset:1},{key:'7',label:'7 дней',days:7,offset:0},{key:'28',label:'28 дней',days:28,offset:0},{key:'90',label:'90 дней',days:90,offset:0},{key:'365',label:'365 дней',days:365,offset:0},{key:'all',label:'Всё время',days:3650,offset:0,all:true}];
const n=(v:number|undefined,d=0)=>v==null?'—':v.toLocaleString('ru-RU',{maximumFractionDigits:d});
const money=(v?:number)=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
const dur=(sec?:number)=>{if(sec==null)return '—';const s=Math.max(0,Math.round(sec));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
const calcRpm=(a?:ChannelAnalytics)=>a?.estimatedRevenue==null||!a.views?undefined:a.estimatedRevenue/a.views*1000;
const metricValue=(p:AnalyticsPoint,m:ChartMetric)=>m==='views'?p.views:m==='estimatedRevenue'?Number(p.estimatedRevenue||0):m==='watchMinutes'?p.watchMinutes:(p.subscribersGained||0)-(p.subscribersLost||0);
function Line({rows,metric}:{rows:AnalyticsPoint[];metric:ChartMetric}){const vals=rows.map(x=>metricValue(x,metric));const min=Math.min(0,...vals),max=Math.max(1,...vals),span=Math.max(1,max-min);const pts=vals.map((v,i)=>`${rows.length<2?0:i/(rows.length-1)*100},${38-(v-min)/span*34}`).join(' ');return <svg className="analyticsSpark revenueLine" viewBox="0 0 100 40" preserveAspectRatio="none"><polyline points={pts}/></svg>}
function Bars({rows,value='views'}:{rows:AnalyticsBreakdown[];value?:'views'|'revenue'}){const total=rows.reduce((s,x)=>s+(value==='revenue'?Number(x.estimatedRevenue||0):x.views),0),max=Math.max(1,...rows.map(x=>value==='revenue'?Number(x.estimatedRevenue||0):x.views));return <div className="breakdownBars">{rows.slice(0,10).map(x=>{const v=value==='revenue'?Number(x.estimatedRevenue||0):x.views;return <div key={x.key}><span><b>{x.key}</b><small>{value==='revenue'?money(v):`${formatNumber(v)} просмотров`} • {total?`${(v/total*100).toFixed(1)}%`:'0%'}</small></span><i><em style={{width:`${v/max*100}%`}}/></i></div>})}</div>}
const reason=(v:AnalyticsTopVideo,avgViews:number,avgRet:number)=>{if(v.rpm!=null&&v.rpm>3)return 'High RPM';if(v.subscribersGained&&v.subscribersGained>=5)return 'Subscriber driver';if(v.views>avgViews*1.2&&v.averageViewPercentage<avgRet*.8)return 'High views + low retention';if(v.views<avgViews*.6&&v.averageViewPercentage>avgRet*1.2)return 'Low views + strong retention';return v.views>=avgViews?'Strong views':'Needs reach'};
const channelHealth=(c:Channel)=>{let h=100;if(!c.youtubeProfileId)h-=30;if(!c.analytics)h-=25;if(c.analytics&&!c.analytics.monetaryAuthorized)h-=5;return Math.max(0,h)};

export function AnalyticsPage(){
 const channels=useApp(s=>s.channels),update=useApp(s=>s.updateChannel),toast=useApp(s=>s.toast);const [channelId,setChannelId]=useState(channels.find(c=>c.youtubeProfileId)?.id||channels[0]?.id||''),[period,setPeriod]=useState<PeriodKey>('28'),[busy,setBusy]=useState(false),[tab,setTab]=useState<DetailTab>('overview'),[chartMetric,setChartMetric]=useState<ChartMetric>('views');const c=channels.find(x=>x.id===channelId);const a=c?.analytics;const p=periods.find(x=>x.key===period)!;
 async function refreshOne(ch:Channel){if(!ch.youtubeProfileId)return;const r=await refreshChannelAnalytics(ch.id,p.days,true,p.offset,Boolean(p.all));update(ch.id,{analytics:r});return r}
 async function refresh(){if(!c)return;setBusy(true);try{await refreshOne(c);toast(`Аналитика ${c.name} обновлена`)}catch(e){toast(String(e))}finally{setBusy(false)}}
 async function refreshAll(){setBusy(true);let ok=0;try{for(const ch of channels.filter(x=>x.youtubeProfileId)){try{await refreshOne(ch);ok++}catch(e){useApp.getState().log(`${ch.name}: ${String(e)}`,'warn')}}toast(`Аналитика: обновлено ${ok}/${channels.filter(x=>x.youtubeProfileId).length}`)}finally{setBusy(false)}}
 const all=channels.map(x=>x.analytics).filter((x):x is ChannelAnalytics=>Boolean(x&&x.periodDays===p.days&&Number(x.offsetDays||0)===p.offset));const allViews=all.reduce((s,x)=>s+x.views,0),allWatch=all.reduce((s,x)=>s+x.watchMinutes,0),allRevKnown=all.some(x=>x.estimatedRevenue!=null),allRev=all.reduce((s,x)=>s+Number(x.estimatedRevenue||0),0),allSubs=all.reduce((s,x)=>s+(x.subscribersGained-x.subscribersLost),0),allRpm=allRevKnown&&allViews?allRev/allViews*1000:undefined;
 const net=(a?.subscribersGained||0)-(a?.subscribersLost||0),rpm=calcRpm(a);const videos=a?.topVideos||[];const avgViews=videos.length?videos.reduce((s,x)=>s+x.views,0)/videos.length:0,avgRet=videos.length?videos.reduce((s,x)=>s+x.averageViewPercentage,0)/videos.length:0;const worst=[...videos].sort((x,y)=>x.views-y.views).slice(0,10);
 const insights=useMemo(()=>{if(!a)return[];const out:string[]=[];if(a.daily.length>=14){const q=a.daily.slice(-7).reduce((s,x)=>s+x.views,0),prev=a.daily.slice(-14,-7).reduce((s,x)=>s+x.views,0);if(prev)out.push(`Просмотры ${q>=prev?'выросли':'снизились'} на ${Math.abs((q-prev)/prev*100).toFixed(0)}% за последние 7 дней`)}if(net)out.push(`За выбранный период канал получил ${net>0?'+':''}${net} подписчиков net`);if(rpm!=null)out.push(`Фактический RPM периода: $${rpm.toFixed(2)}`);if(videos[0])out.push(`${videos[0].title} — лидер по просмотрам среди полученных video metrics`);return out},[a,net,rpm,videos]);
 return <>
  <div className="pageHeader"><div><small>YOUTUBE ANALYTICS</small><h1>Аналитика</h1><p>Только данные YouTube Analytics / Data API. Revenue и RPM появляются только при monetary permission.</p></div><div className="headerActions"><button disabled={busy} onClick={refreshAll}>{busy?'Обновляю…':'↻ Все каналы'}</button><button className="primary" disabled={busy||!c?.youtubeProfileId} onClick={refresh}>↻ Обновить сейчас</button></div></div>
  <div className="analyticsToolbar"><select value={channelId} onChange={e=>setChannelId(e.target.value)}>{channels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="periodTabs analyticsPeriods">{periods.map(x=><button key={x.key} className={period===x.key?'active':''} onClick={()=>setPeriod(x.key)}>{x.label}</button>)}</div></div>
  <section className="allChannelsSummary panel"><div className="panelHead"><div><small>ALL CHANNELS</small><h3>Сеть за выбранный период</h3></div></div><div className="overviewStrip"><span><small>Total Subscribers</small><b>{channels.some(x=>x.stats?.subscribers!=null)?formatNumber(channels.reduce((s,x)=>s+(x.stats?.subscribers||0),0)):'—'}</b></span><span><small>Total Views</small><b>{all.length?formatNumber(allViews):'—'}</b></span><span><small>Watch Time</small><b>{all.length?`${n(allWatch/60,1)} ч`:'—'}</b></span><span><small>Total Revenue</small><b>{allRevKnown?money(allRev):'—'}</b></span><span><small>Average RPM</small><b>{allRpm==null?'—':`$${allRpm.toFixed(2)}`}</b></span><span><small>Net Subs</small><b>{all.length?`${allSubs>=0?'+':''}${n(allSubs)}`:'—'}</b></span></div></section>
  <div className="analyticsChannelRows">{channels.map(x=><div className="analyticsChannelRow" key={x.id}><span><b>{x.name}</b><small>Health {channelHealth(x)} • {x.analytics?.updatedAt?new Date(x.analytics.updatedAt).toLocaleString('ru-RU'):'нет sync'}</small></span><em>{x.analytics?.periodDays===p.days?formatNumber(x.analytics.views):'—'} views</em><em>{x.analytics?.periodDays===p.days?money(x.analytics.estimatedRevenue):'—'}</em><button onClick={()=>setChannelId(x.id)}>Открыть</button></div>)}</div>
  {!c?.youtubeProfileId?<div className="errorBox">Сначала привяжи YouTube OAuth к этому каналу.</div>:!a?<div className="empty"><b>Аналитика ещё не загружена</b><p>Нажми «Обновить сейчас».</p></div>:<>
   <div className="analyticsDetailTabs">{(['overview','content','audience','revenue','traffic','geography'] as DetailTab[]).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x==='overview'?'OVERVIEW':x==='content'?'CONTENT':x==='audience'?'AUDIENCE':x==='revenue'?'REVENUE':x==='traffic'?'TRAFFIC':'GEOGRAPHY'}</button>)}</div>
   {tab==='overview'&&<><div className="channelMetricsGrid analyticsKpis"><span><small>Views</small><b>{formatNumber(a.views)}</b></span><span><small>Engaged Views</small><b>{a.engagedViews==null?'—':formatNumber(a.engagedViews)}</b></span><span><small>Watch Time</small><b>{n(a.watchMinutes/60,1)} ч</b></span><span><small>Avg View Duration</small><b>{dur(a.averageViewDuration)}</b></span><span><small>Average %</small><b>{n(a.averageViewPercentage,1)}%</b></span><span><small>Subs Gained</small><b>+{n(a.subscribersGained)}</b></span><span><small>Subs Lost</small><b>−{n(a.subscribersLost)}</b></span><span><small>Net Subs</small><b>{net>=0?'+':''}{n(net)}</b></span><span><small>Likes</small><b>{n(a.likes)}</b></span><span><small>Comments</small><b>{n(a.comments)}</b></span><span><small>Shares</small><b>{n(a.shares)}</b></span><span><small>Revenue</small><b>{money(a.estimatedRevenue)}</b></span><span><small>RPM</small><b>{rpm==null?'—':`$${rpm.toFixed(2)}`}</b></span><span><small>CPM</small><b>{a.cpm==null?'—':`$${a.cpm.toFixed(2)}`}</b></span><span><small>Playback CPM</small><b>{a.playbackBasedCpm==null?'—':`$${a.playbackBasedCpm.toFixed(2)}`}</b></span></div><section className="panel analyticsWide"><div className="panelHead"><div><small>DYNAMICS</small><h3>Один график — выбранная метрика</h3></div><select value={chartMetric} onChange={e=>setChartMetric(e.target.value as ChartMetric)}><option value="views">Views</option><option value="estimatedRevenue">Revenue</option><option value="watchMinutes">Watch Time</option><option value="netSubscribers">Subscribers</option></select></div><Line rows={a.daily} metric={chartMetric}/><div className="chartFoot"><span>{a.daily[0]?.date||'—'}</span><span>{a.daily.at(-1)?.date||'—'}</span></div></section><section className="panel insightsPanel"><div className="panelHead"><div><small>CHANNEL INSIGHTS</small><h3>Rule-based выводы</h3></div></div>{insights.length?insights.map((x,i)=><div className="insightRow" key={i}>{x}</div>):<p>Недостаточно истории для выводов.</p>}</section></>}
   {tab==='content'&&<><section className="panel"><div className="panelHead"><div><small>TOP 10</small><h3>Лучшие видео</h3></div></div><div className="topVideoList rich">{videos.map((v,i)=><div key={v.id}>{v.thumbnail?<img src={v.thumbnail} loading="lazy"/>:<i/>}<span><strong>{v.title}</strong><small>{formatNumber(v.views)} views • {n(v.averageViewPercentage,1)}% • {dur(v.averageViewDuration)} • +{n(v.subscribersGained)} subs • {money(v.estimatedRevenue)} • RPM {v.rpm==null?'—':`$${v.rpm.toFixed(2)}`}</small></span><em>{reason(v,avgViews,avgRet)}</em></div>)}</div></section><section className="panel"><div className="panelHead"><div><small>WORST 10</small><h3>Слабые видео из полученной выборки</h3></div></div><div className="topVideoList rich">{worst.map(v=><div key={v.id}>{v.thumbnail?<img src={v.thumbnail} loading="lazy"/>:<i/>}<span><strong>{v.title}</strong><small>{formatNumber(v.views)} views • {n(v.averageViewPercentage,1)}%</small></span><em>{reason(v,avgViews,avgRet)}</em></div>)}</div></section></>}
   {tab==='revenue'&&<section className="panel revenuePanel"><div className="panelHead"><div><small>MONETARY ANALYTICS</small><h3>{a.monetaryAuthorized?'Реальный доход':'Доход — нет разрешения'}</h3></div></div>{!a.monetaryAuthorized?<div className="errorBox">Требуется разрешение Revenue Analytics. Переподключи канал в Настройки → YouTube → Подключить доход.</div>:<div className="channelMetricsGrid"><span><small>Estimated Revenue</small><b>{money(a.estimatedRevenue)}</b></span><span><small>Estimated Ad Revenue</small><b>{money(a.estimatedAdRevenue)}</b></span><span><small>YouTube Premium Revenue</small><b>{money(a.estimatedRedPartnerRevenue)}</b></span><span><small>RPM</small><b>{rpm==null?'—':`$${rpm.toFixed(2)}`}</b></span><span><small>Monetized Playbacks</small><b>{n(a.monetizedPlaybacks)}</b></span><span><small>Ad Impressions</small><b>{n(a.adImpressions)}</b></span><span><small>CPM</small><b>{a.cpm==null?'—':`$${a.cpm.toFixed(2)}`}</b></span><span><small>Playback CPM</small><b>{a.playbackBasedCpm==null?'—':`$${a.playbackBasedCpm.toFixed(2)}`}</b></span></div>}</section>}
   {tab==='traffic'&&<section className="panel"><div className="panelHead"><div><small>TRAFFIC SOURCES</small><h3>Источники трафика</h3></div></div>{a.trafficSources.length?<Bars rows={a.trafficSources}/>:<p>Нет данных</p>}<div className="reachUnavailable"><b>Thumbnail Impressions / CTR</b><span>{a.impressions!=null&&a.impressionCtr!=null?`${n(a.impressions)} • ${n(a.impressionCtr,2)}%`:'Нет данных — VYRON не вычисляет CTR из views.'}</span></div></section>}
   {tab==='geography'&&<section className="panel"><div className="panelHead"><div><small>TOP COUNTRIES</small><h3>География</h3></div></div>{a.countries.length?<div className="geoTable">{a.countries.map(x=><div key={x.key}><b>{x.key}</b><span>{formatNumber(x.views)} views</span><span>{n(x.watchMinutes/60,1)} h</span><span>{money(x.estimatedRevenue)}</span><span>RPM {x.rpm==null?'—':`$${x.rpm.toFixed(2)}`}</span></div>)}</div>:<p>Нет данных</p>}</section>}
   {tab==='audience'&&<section className="panel"><div className="panelHead"><div><small>AUDIENCE</small><h3>Аудитория</h3></div></div>{a.audience?.length?<Bars rows={a.audience}/>:<div className="empty"><b>Нет данных</b><p>Возраст, пол, returning/new viewers, devices и OS показываются только когда соответствующий YouTube report реально доступен.</p></div>}</section>}
  </>}
 </>;
}
