import React,{useEffect,useState} from 'react';
import {api,type CompetitorCandidate} from './api';
import {formatNumber} from './core';
import {useApp} from './store';
import {refreshCompetitor} from './youtubeIntelligence';
import type {Competitor} from './types';

const miniDate=(x?:string)=>x?new Date(x).toLocaleDateString('ru-RU',{day:'2-digit',month:'short',year:'2-digit'}):'—';
const velocity=(c:Competitor,key:'views'|'subscribers')=>{const h=c.history||[];if(h.length<2)return undefined;const a=h[h.length-2],b=h[h.length-1],days=Math.max(1,(new Date(b.at).getTime()-new Date(a.at).getTime())/86400000);return (Number(b[key]||0)-Number(a[key]||0))/days};
const uploadFrequency=(c:Competitor)=>{const dates=(c.latestVideos||[]).map(v=>Date.parse(v.publishedAt||'')).filter(Number.isFinite).sort((a,b)=>b-a);if(dates.length<2)return '—';const gaps=dates.slice(0,-1).map((d,i)=>(d-dates[i+1])/86400000);const avg=gaps.reduce((s,x)=>s+x,0)/gaps.length;return avg<1?`${Math.max(1,Math.round(1/Math.max(.05,avg)))} / день`:`раз в ${avg.toFixed(avg<3?1:0)} дн.`};
const signed=(v?:number)=>v==null?'—':`${v>0?'+':''}${Math.round(v).toLocaleString('ru-RU')}/д`;

export function CompetitorsPage(){
 const channels=useApp(s=>s.channels),competitors=useApp(s=>s.competitors),add=useApp(s=>s.addCompetitor),remove=useApp(s=>s.removeCompetitor),toast=useApp(s=>s.toast),settings=useApp(s=>s.settings);const [channelId,setChannelId]=useState(channels[0]?.id||''),[url,setUrl]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState<string>(''),[discovering,setDiscovering]=useState(false),[candidates,setCandidates]=useState<CompetitorCandidate[]>([]);const list=competitors.filter(c=>!channelId||c.channelId===channelId),own=channels.find(c=>c.id===channelId);
 async function refresh(c:Competitor){setBusy(c.id);try{await refreshCompetitor(c.id,true);toast(`${c.name}: обновлено`)}catch(e){toast(String(e))}finally{setBusy('')}}
 async function refreshAll(){for(const c of list)await refresh(c)}
 async function discover(autoAdd=true){if(!own?.youtubeProfileId){toast('Сначала подключи YouTube OAuth к своему каналу');return}setDiscovering(true);try{const found=await api.youtubeDiscoverCompetitors(own.youtubeProfileId,12);setCandidates(found);let added=0;if(autoAdd){const existing=new Set(competitors.filter(c=>c.channelId===channelId).map(c=>c.youtubeChannelId).filter(Boolean));for(const x of found.slice(0,10)){if(existing.has(x.channelId)||x.channelId===own.youtubeChannelId)continue;add({id:crypto.randomUUID(),channelId,name:x.name,url:x.url,youtubeChannelId:x.channelId,thumbnail:x.thumbnail,subscribers:x.subscribers,views:x.views,videos:x.videos,history:[],similarity:x.similarity,source:'auto'});existing.add(x.channelId);added++}toast(added?`Автопоиск: добавлено ${added} конкурентов`:'Автопоиск: новых конкурентов нет')}}catch(e){toast(String(e))}finally{setDiscovering(false)}}
 useEffect(()=>{if(!own?.youtubeProfileId||list.length)return;const k=`vyron:competitor-discovery:${own.id}`;const last=Number(localStorage.getItem(k)||0);if(Date.now()-last<24*3600_000)return;localStorage.setItem(k,String(Date.now()));void discover(true)},[channelId,own?.youtubeProfileId,list.length]);
 return <>
  <div className="pageHeader"><div><small>COMPETITOR RADAR</small><h1>Конкуренты</h1><p>Автопоиск по тематике собственного канала. Показываются только публичные YouTube-данные; private analytics конкурентов недоступна.</p></div><div className="headerActions"><select value={channelId} onChange={e=>setChannelId(e.target.value)}>{channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="primary" disabled={discovering||!own?.youtubeProfileId} onClick={()=>discover(true)}>{discovering?'Ищу…':'✦ Найти автоматически'}</button><button disabled={!list.length||!!busy} onClick={refreshAll}>↻ Обновить все</button></div></div>
  <section className="panel competitorDiscovery"><div><small>AUTO DISCOVERY • 24H CACHE</small><h3>Добавлять вручную не обязательно</h3><p>VYRON использует title, description и titles последних роликов собственного канала для поиска кандидатов через YouTube API.</p></div><span className="similarityBadge">PUBLIC DATA ONLY</span></section>
  {candidates.length>0&&<div className="publisherNotice"><b>Последний discovery: {candidates.length} кандидатов</b><p>{candidates.slice(0,6).map(x=>`${x.name} ${x.similarity}%`).join(' • ')}</p></div>}
  <details className="panel advancedPanel"><summary>Ручное добавление — Advanced</summary><div className="competitorAdd"><input placeholder="Название конкурента" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="YouTube /channel/UC… или /@handle" value={url} onChange={e=>setUrl(e.target.value)}/><button disabled={!channelId||!name||!url} onClick={()=>{add({id:crypto.randomUUID(),channelId,name,url,history:[],source:'manual'});setName('');setUrl('')}}>Добавить</button><small>{settings.youtubeIntelligenceAutoRefresh?`Обновление каждые ${settings.youtubeIntelligenceRefreshMin} мин.`:'Автообновление выключено'}</small></div></details>
  {!own?.youtubeProfileId&&<div className="errorBox">У выбранного собственного канала не привязан YouTube OAuth — discovery и snapshot недоступны.</div>}
  {list.length===0?<div className="empty"><b>Конкуренты ещё не найдены</b><p>Нажми «Найти автоматически».</p></div>:<div className="competitorOSList">{list.map(c=>{const vv=velocity(c,'views'),sv=velocity(c,'subscribers');return <article className="competitorOSCard" key={c.id}><header>{c.thumbnail?<img src={c.thumbnail} loading="lazy"/>:<i className="compAvatar">YT</i>}<span><b>{c.name}</b><small>{c.youtubeChannelId||c.url}</small>{c.similarity!=null&&<em className="similarityBadge">Similarity {c.similarity}%</em>}</span><button className="danger mini" onClick={()=>remove(c.id)}>×</button></header><div className="competitorMetrics"><span><small>Subscribers</small><b>{c.subscribers==null?'—':formatNumber(c.subscribers)}</b></span><span><small>Total Views</small><b>{c.views==null?'—':formatNumber(c.views)}</b></span><span><small>Video Count</small><b>{c.videos==null?'—':formatNumber(c.videos)}</b></span><span><small>Recent Avg Views</small><b>{c.recentAverageViews==null?'—':formatNumber(c.recentAverageViews)}</b></span><span><small>Subscriber velocity</small><b>{signed(sv)}</b></span><span><small>View velocity</small><b>{signed(vv)}</b></span><span><small>Last upload</small><b>{miniDate(c.lastVideoAt)}</b></span><span><small>Upload frequency</small><b>{uploadFrequency(c)}</b></span><span><small>Last sync</small><b>{c.updatedAt?new Date(c.updatedAt).toLocaleString('ru-RU'):'—'}</b></span></div>{c.latestVideos?.length?<div className="competitorVideos os">{c.latestVideos.slice(0,5).map(v=><button key={v.id} onClick={()=>api.openWeb(`https://youtube.com/watch?v=${v.id}`)}>{v.thumbnail?<img src={v.thumbnail} loading="lazy"/>:<i/>}<span><b>{v.title}</b><small>{formatNumber(v.views)} views • {miniDate(v.publishedAt)}</small></span></button>)}</div>:<div className="competitorPlaceholder">Ожидает первого публичного snapshot</div>}<footer><small>Revenue / RPM / CTR / retention конкурента не показываются: это private analytics.</small><div><button onClick={()=>api.openWeb(c.url)}>Открыть YouTube</button><button className="primary small" disabled={busy===c.id} onClick={()=>refresh(c)}>{busy===c.id?'…':'↻ Обновить'}</button></div></footer></article>})}</div>}
 </>;
}
