import React from 'react';
import {useApp} from './store';
import {bufferDays,formatNumber} from './core';
import type {AutopilotMode,Channel} from './types';

const money=(v?:number)=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
const rpm=(revenue?:number,views?:number)=>revenue==null||!views?'—':`$${(revenue/views*1000).toFixed(2)}`;
const health=(c:Channel,jobs:any[])=>{let n=100;const cj=jobs.filter(j=>j.channelId===c.id);if(!c.youtubeProfileId)n-=28;if(!c.analytics)n-=18;if(cj.some(j=>j.status==='ERROR'))n-=18;const b=bufferDays(c,jobs);if(b<7)n-=22;else if(b<14)n-=12;else if(b<30)n-=5;return Math.max(0,n)};

export function DashboardOS(){
 const channels=useApp(s=>s.channels),jobs=useApp(s=>s.jobs),settings=useApp(s=>s.settings),patch=useApp(s=>s.patchSettings),setPage=useApp(s=>s.setPage);
 const enabled=channels.filter(c=>c.enabled);const analytics=enabled.map(c=>c.analytics).filter(Boolean);const todayViews=analytics.reduce((n,a)=>n+(a?.daily?.at(-1)?.views||0),0);const views28=enabled.reduce((n,c)=>n+(c.analytics?.periodDays===28?c.analytics.views:0),0);const revenue28=enabled.reduce((n,c)=>n+(c.analytics?.periodDays===28&&c.analytics.estimatedRevenue!=null?c.analytics.estimatedRevenue:0),0);const revenueKnown=enabled.some(c=>c.analytics?.periodDays===28&&c.analytics.estimatedRevenue!=null);const subscribers=enabled.reduce((n,c)=>n+(c.stats?.subscribers||0),0);const scheduled=jobs.filter(j=>j.status==='SCHEDULED').length;const mode:AutopilotMode=settings.autopilotMode||'off';
 const setMode=(m:AutopilotMode)=>{if(m==='off')patch({autopilotMode:m,autopilotEnabled:false,autoUploadYoutube:false});else if(m==='assisted')patch({autopilotMode:m,autopilotEnabled:true,autoUploadYoutube:false});else patch({autopilotMode:m,autopilotEnabled:true,autoUploadYoutube:true})};
 const errors=jobs.filter(j=>j.status==='ERROR');const attention=[...(!enabled.some(c=>c.youtubeProfileId)?['YouTube OAuth не подключён']:[]),...(errors.length?[`${errors.length} ошибок производства/YouTube`]:[]),...(enabled.some(c=>!c.analytics)?['Не у всех каналов загружена аналитика']:[])];
 return <>
  <div className="controlHero"><div><small>VYRON CONTROL CENTER</small><h1>{attention.length?`${attention.length} действия требуют внимания`:'Всё хорошо'}</h1><p>{enabled.length} каналов • система показывает только подтверждённые данные и реальные исключения.</p></div>{attention.length>0&&<button className="primary" onClick={()=>setPage(errors.length?'production':'settings')}>Показать</button>}</div>
  <div className="overviewStrip"><span><small>КАНАЛЫ</small><b>{enabled.length}</b></span><span><small>VIEWS TODAY</small><b>{analytics.length?formatNumber(todayViews):'—'}</b></span><span><small>VIEWS 28D</small><b>{enabled.some(c=>c.analytics?.periodDays===28)?formatNumber(views28):'—'}</b></span><span><small>REVENUE 28D</small><b>{revenueKnown?money(revenue28):'—'}</b></span><span><small>SUBSCRIBERS</small><b>{enabled.some(c=>c.stats?.subscribers!=null)?formatNumber(subscribers):'—'}</b></span><span><small>SCHEDULED</small><b>{scheduled}</b></span></div>
  <section className="autopilotControl panel"><div><small>AUTOPILOT</small><h3>{mode==='off'?'OFF':mode==='assisted'?'ASSISTED':'FULL'}</h3><p>{mode==='off'?'Автоматизация не публикует контент. Sync и analytics продолжают работать.':mode==='assisted'?'VYRON готовит очередь, материалы, metadata и даты, но YouTube write требует подтверждения.':'Производственный pipeline и публикация работают автоматически по настроенным правилам.'}</p></div><div className="modeSwitch"><button className={mode==='off'?'active':''} onClick={()=>setMode('off')}>OFF</button><button className={mode==='assisted'?'active':''} onClick={()=>setMode('assisted')}>ASSISTED</button><button className={mode==='full'?'active':''} onClick={()=>setMode('full')}>FULL</button></div></section>
  <div className="todayStatus"><span><small>НУЖНЫ ИЗОБРАЖЕНИЯ</small><b>{jobs.filter(j=>j.status==='NEED_IMAGE').length}</b></span><span><small>НУЖНА МУЗЫКА</small><b>{jobs.filter(j=>j.status==='WAITING_MUSIC').length}</b></span><span><small>READY RENDER</small><b>{jobs.filter(j=>j.status==='READY_RENDER').length}</b></span><span><small>RENDERING</small><b>{jobs.filter(j=>j.status==='RENDERING').length}</b></span><span><small>READY UPLOAD</small><b>{jobs.filter(j=>j.status==='READY_UPLOAD').length}</b></span><span><small>UPLOADING</small><b>{jobs.filter(j=>j.status==='UPLOADING').length}</b></span><span><small>SCHEDULED</small><b>{scheduled}</b></span><span className={errors.length?'warn':''}><small>ERRORS</small><b>{errors.length}</b></span></div>
  {attention.length>0&&<section className="attentionPanel panel"><div className="panelHead"><div><small>NEEDS ATTENTION</small><h3>Только проблемы</h3></div></div>{attention.map((x,i)=><div className="attentionRow" key={i}><i>!</i><span>{x}</span></div>)}</section>}
  <section className="channelOSList dashboardChannels"><div className="sectionHead"><div><small>ALL CHANNELS</small><h2>Каналы</h2></div><button onClick={()=>setPage('channels')}>Открыть каналы</button></div>{enabled.map(c=>{const a=c.analytics,b=bufferDays(c,jobs),h=health(c,jobs);return <article className="channelOSCard" key={c.id}><header><div className="channelAvatarOS">{c.name.slice(0,2).toUpperCase()}</div><span><b>{c.name}</b><small>{c.youtubeChannelId||'YouTube Channel ID —'}</small></span><em className={h>=90?'good':h>=70?'warn':'bad'}>HEALTH {h}</em><em>Reserve {b} days</em></header><div className="channelOSKpis"><span><small>Views 28d</small><b>{a?.periodDays===28?formatNumber(a.views):'—'}</b></span><span><small>Revenue 28d</small><b>{a?.periodDays===28?money(a.estimatedRevenue):'—'}</b></span><span><small>RPM</small><b>{a?.periodDays===28?rpm(a.estimatedRevenue,a.views):'—'}</b></span><span><small>Subscribers</small><b>{c.stats?.subscribers!=null?formatNumber(c.stats.subscribers):'—'}</b></span></div></article>})}</section>
 </>;
}
