import React,{useEffect,useMemo,useRef,useState} from 'react';
import {convertFileSrc} from '@tauri-apps/api/core';
import {api,type ExistingVideoSyncResult} from './api';
import {useApp} from './store';
import type {YoutubeExistingVideo,YoutubeProfile} from './types';
import {parseMetadataFile,type ImportedMetadata} from './metadata';
import {buildExistingSchedule,orderedExistingVideos,overlayExistingMetadata} from './youtubeExisting';

const local=(iso?:string)=>{if(!iso)return '';const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const short=(s:string,n=145)=>s.length>n?s.slice(0,n).trim()+'…':s;
const sameTags=(a:string[]=[],b:string[]=[])=>JSON.stringify(a)===JSON.stringify(b);
const same=(a?:string,b?:string)=>(a||'')===(b||'');

type ThumbState='loading'|'ok'|'error';
function VideoThumb({video,onState}:{video:YoutubeExistingVideo;onState:(id:string,s:ThumbState)=>void}){
 const remotes=[video.thumbnail,`https://i.ytimg.com/vi/${video.id}/hqdefault.jpg`,`https://i.ytimg.com/vi/${video.id}/mqdefault.jpg`,`https://i.ytimg.com/vi/${video.id}/default.jpg`].filter(Boolean) as string[];
 const [src,setSrc]=useState(''),[fallback,setFallback]=useState(0),[retry,setRetry]=useState(0),[failed,setFailed]=useState(false);
 useEffect(()=>{let live=true;setSrc('');setFallback(0);setFailed(false);onState(video.id,'loading');api.youtubeCacheThumbnail(video.id,video.thumbnail).then(p=>{if(live){setSrc(convertFileSrc(p));onState(video.id,'ok')}}).catch(()=>{if(live)setSrc(remotes[0]||'')});return()=>{live=false}},[video.id,video.thumbnail,retry]);
 if(failed)return <button className="thumbRetry" onClick={e=>{e.stopPropagation();setRetry(x=>x+1)}}>↻ Повторить</button>;
 if(!src)return <span className="thumbSkeleton">YT</span>;
 return <img className="vyronThumb" src={src} loading="lazy" onLoad={()=>onState(video.id,'ok')} onError={()=>{const n=fallback+1;if(remotes[n]){setFallback(n);setSrc(remotes[n]);return}setFailed(true);onState(video.id,'error')}}/>;
}

export function ExistingVideos(){
 const channels=useApp(s=>s.channels),toast=useApp(s=>s.toast);
 const [profiles,setProfiles]=useState<YoutubeProfile[]>([]),[channelId,setChannelId]=useState(channels[0]?.id||''),[profileId,setProfileId]=useState(channels[0]?.youtubeProfileId||''),[videos,setVideos]=useState<YoutubeExistingVideo[]>([]),[baseline,setBaseline]=useState<Record<string,YoutubeExistingVideo>>({}),[lastUndo,setLastUndo]=useState<YoutubeExistingVideo[]>([]),[busy,setBusy]=useState(false),[limit,setLimit]=useState(100),[order,setOrder]=useState<'oldest'|'newest'>('oldest'),[start,setStart]=useState(()=>{const d=new Date();d.setDate(d.getDate()+1);d.setHours(18,0,0,0);return local(d.toISOString())}),[cadence,setCadence]=useState(2),[meta,setMeta]=useState<ImportedMetadata[]>([]),[expanded,setExpanded]=useState<Set<string>>(new Set()),[filter,setFilter]=useState<'all'|'private'|'public'>('all'),[sortMode,setSortMode]=useState<'dateAsc'|'dateDesc'|'youtubeOldest'|'youtubeNewest'|'privateFirst'>('dateAsc'),[syncInfo,setSyncInfo]=useState<ExistingVideoSyncResult|null>(null),[thumbs,setThumbs]=useState<Record<string,ThumbState>>({}),[confirm,setConfirm]=useState(false),[backupPath,setBackupPath]=useState('');
 const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{api.youtubeProfiles().then(setProfiles).catch(()=>{})},[]);
 useEffect(()=>{const c=channels.find(x=>x.id===channelId);if(c){setProfileId(c.youtubeProfileId||'');setCadence(c.cadenceDays||2)}},[channelId]);
 async function sync(){if(!profileId){toast('Сначала привяжи YouTube OAuth к каналу');return}setBusy(true);try{const r=await api.youtubeListExisting(profileId,limit);const next=(r.videos||[]).map((x:any)=>({...x,selected:x.privacyStatus==='private',applyState:'idle'}));setVideos(next);setBaseline(Object.fromEntries(next.map(v=>[v.id,{...v,tags:[...v.tags]}])));setLastUndo([]);setBackupPath('');setThumbs({});setSyncInfo(r);toast(`YouTube: получено ${r.received}/${Math.min(r.youtubeFound||r.received,r.requested||limit)} видео`)}catch(e){toast(String(e))}finally{setBusy(false)}}
 function schedule(){if(!start)return;setVideos(buildExistingSchedule(orderedExistingVideos(videos,order),new Date(start).toISOString(),cadence));}
 async function read(files:FileList|null){if(!files?.length)return;const rows:ImportedMetadata[]=[];for(const f of Array.from(files))rows.push(...parseMetadataFile(f.name,await f.text()));setMeta(rows);setVideos(v=>overlayExistingMetadata(orderedExistingVideos(v,order),rows));toast(`Метаданные: ${rows.length}`)}
 const selected=useMemo(()=>videos.filter(v=>v.selected),[videos]);
 const changes=useMemo(()=>selected.reduce((a,v)=>{const b=baseline[v.id];if(!b)return a;if(!same(v.title,b.title))a.title++;if(!same(v.description,b.description))a.description++;if(!sameTags(v.tags,b.tags))a.tags++;if(!same(v.publishAt,b.publishAt))a.date++;if(!same(v.privacyStatus,b.privacyStatus))a.privacy++;if(v.privacyStatus==='public')a.public++;return a},{title:0,description:0,tags:0,date:0,privacy:0,public:0}),[selected,baseline]);
 async function apply(){setConfirm(false);if(!selected.length||!profileId)return;const backup=selected.map(v=>baseline[v.id]).filter(Boolean).map(v=>({...v,tags:[...v.tags]}));setBusy(true);let ok=0;try{const saved=await api.youtubeBackupExisting(profileId,backup);setBackupPath(saved.path||'');for(const v of selected){setVideos(x=>x.map(z=>z.id===v.id?{...z,applyState:'saving',error:undefined}:z));try{const result=await api.youtubeUpdateExisting(profileId,v.id,v.title,v.description,v.tags,v.publishAt,v.privacyStatus);if(!result?.verified)throw new Error(`YouTube не подтвердил изменение ${v.id}`);ok++;setVideos(x=>x.map(z=>z.id===v.id?{...z,applyState:'done',verified:true}:z))}catch(e){setVideos(x=>x.map(z=>z.id===v.id?{...z,applyState:'error',verified:false,error:`${v.id}: ${String(e)}`}:z))}}if(ok){setLastUndo(backup);setBaseline(prev=>{const n={...prev};for(const v of selected.filter(x=>x.applyState!=='error'))n[v.id]={...v,tags:[...v.tags]};return n})}toast(ok===selected.length?`✓ ${ok} видео обновлено и подтверждено YouTube`:`YouTube подтвердил ${ok}/${selected.length}`)}catch(e){toast(`Backup/Update: ${String(e)}`)}finally{setBusy(false)}}
 async function undo(){if(!lastUndo.length||!profileId)return;setBusy(true);let ok=0;try{for(const v of lastUndo){try{const r=await api.youtubeUpdateExisting(profileId,v.id,v.title,v.description,v.tags,v.publishAt,v.privacyStatus);if(r?.verified)ok++}catch(e){toast(`Undo ${v.id}: ${String(e)}`)}}toast(`↶ YouTube подтвердил откат ${ok}/${lastUndo.length}`);if(ok===lastUndo.length)setLastUndo([]);await sync()}finally{setBusy(false)}}
 const displayDate=(v:YoutubeExistingVideo)=>v.publishAt||v.publishedAt||'';const timeOf=(v:YoutubeExistingVideo)=>{const t=Date.parse(displayDate(v));return Number.isFinite(t)?t:Number.POSITIVE_INFINITY};const youtubeTime=(v:YoutubeExistingVideo)=>{const t=Date.parse(v.publishedAt||v.publishAt||'');return Number.isFinite(t)?t:Number.POSITIVE_INFINITY};
 const shown=[...videos.filter(v=>filter==='all'||v.privacyStatus===filter)].sort((a,b)=>{if(sortMode==='dateAsc')return timeOf(a)-timeOf(b);if(sortMode==='dateDesc'){const ta=timeOf(a),tb=timeOf(b);if(!Number.isFinite(ta)&&!Number.isFinite(tb))return 0;if(!Number.isFinite(ta))return 1;if(!Number.isFinite(tb))return -1;return tb-ta}if(sortMode==='youtubeOldest')return youtubeTime(a)-youtubeTime(b);if(sortMode==='youtubeNewest'){const ta=youtubeTime(a),tb=youtubeTime(b);if(!Number.isFinite(ta)&&!Number.isFinite(tb))return 0;if(!Number.isFinite(ta))return 1;if(!Number.isFinite(tb))return -1;return tb-ta}const pa=a.privacyStatus==='private'?0:1,pb=b.privacyStatus==='private'?0:1;return pa-pb||timeOf(a)-timeOf(b)});
 const dateCounts=shown.reduce<Record<string,number>>((acc,v)=>{const k=displayDate(v);if(k)acc[k]=(acc[k]||0)+1;return acc},{});const toggle=(id:string)=>setExpanded(x=>{const n=new Set(x);n.has(id)?n.delete(id):n.add(id);return n});
 const thumbOk=Object.values(thumbs).filter(x=>x==='ok').length,thumbError=Object.values(thumbs).filter(x=>x==='error').length;
 const expected=syncInfo?Math.min(syncInfo.youtubeFound||syncInfo.received,syncInfo.requested||limit):0;const mismatch=Boolean(syncInfo?.complete&&syncInfo.received!==(syncInfo.youtubeFound||syncInfo.received));
 return <>
  <div className="pageHeader"><div><small>EXISTING VIDEOS MANAGER</small><h1>Загруженные</h1><p>Синхронизация идёт через uploads playlist с pagination. Изменение считается успешным только после повторного чтения YouTube.</p></div><div className="headerActions"><button disabled={busy} onClick={sync}>{busy?'Работаю…':'↻ Синхронизировать'}</button><button className="primary" disabled={busy||!selected.length} onClick={()=>setConfirm(true)}>ОТПРАВИТЬ В YOUTUBE • {selected.length}</button></div></div>
  {syncInfo&&<div className={`syncAudit ${mismatch?'warn':''}`}><span>YouTube найдено <b>{syncInfo.youtubeFound}</b></span><span>Получено VYRON <b>{syncInfo.received}</b></span><span>Private <b>{syncInfo.privateCount}</b></span><span>Public <b>{syncInfo.publicCount}</b></span><span>Scheduled <b>{syncInfo.scheduledCount}</b></span><span>Изображения <b>{thumbOk}/{videos.length}</b></span>{thumbError>0&&<span className="warn">{thumbError} ожидают retry</span>}{syncInfo.youtubeFound>limit&&<span>Лимит: {limit} из {syncInfo.youtubeFound}</span>}{mismatch&&<strong>⚠ Синхронизация неполная</strong>}</div>}
  {lastUndo.length>0&&<div className="undoBar"><span><b>✓ Последняя пачка подтверждена YouTube</b> • backup {lastUndo.length} видео{backupPath&&<small> • {backupPath}</small>}</span><button disabled={busy} onClick={undo}>↶ ОТМЕНИТЬ</button></div>}
  <input ref={file} hidden type="file" multiple accept=".json,.txt,.csv" onChange={e=>{void read(e.target.files);e.currentTarget.value=''}}/>
  <div className="existingToolbar"><label>Канал<select value={channelId} onChange={e=>setChannelId(e.target.value)}>{channels.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>OAuth<select value={profileId} onChange={e=>setProfileId(e.target.value)}><option value="">— не подключён —</option>{profiles.map(p=><option value={p.id} key={p.id}>{p.channelTitle||p.channelId||p.id}</option>)}</select></label><label>Видео<select value={limit} onChange={e=>setLimit(+e.target.value)}><option>30</option><option>50</option><option>100</option><option>200</option></select></label><label>Порядок<select value={order} onChange={e=>setOrder(e.target.value as any)}><option value="oldest">старые → новые</option><option value="newest">новые → старые</option></select></label><label>Сортировка<select value={sortMode} onChange={e=>setSortMode(e.target.value as any)}><option value="dateAsc">дата ↑</option><option value="dateDesc">дата ↓</option><option value="youtubeOldest">YouTube: старые → новые</option><option value="youtubeNewest">YouTube: новые → старые</option><option value="privateFirst">сначала Private</option></select></label><label>Первая дата<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Каждые N дней<input type="number" min="1" max="30" value={cadence} onChange={e=>setCadence(+e.target.value||1)}/></label><button onClick={schedule}>Расставить даты</button><button onClick={()=>file.current?.click()}>✦ Метаданные GPT</button></div>
  {videos.length>0&&<div className="existingQuick"><div className="periodTabs"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>ВСЕ {videos.length}</button><button className={filter==='private'?'active':''} onClick={()=>setFilter('private')}>PRIVATE {videos.filter(v=>v.privacyStatus==='private').length}</button><button className={filter==='public'?'active':''} onClick={()=>setFilter('public')}>PUBLIC {videos.filter(v=>v.privacyStatus==='public').length}</button></div><div><button onClick={()=>setVideos(x=>x.map(v=>({...v,selected:v.privacyStatus==='private'})))}>Выбрать Private</button><button onClick={()=>setVideos(x=>x.map(v=>({...v,selected:false})))}>Снять все</button></div></div>}
  {meta.length>0&&<div className="publisherNotice"><b>Metadata Inbox</b><p>Импортировано {meta.length} записей. Проверь соответствие роликов перед отправкой.</p></div>}
  {videos.length===0?<div className="empty"><b>Видео ещё не синхронизированы</b><p>Выбери канал и нажми «Синхронизировать».</p></div>:<div className="existingList compact">{shown.map((v,i)=>{const open=expanded.has(v.id);return <article className={`existingCard compact ${open?'open':''} ${v.applyState||''} ${dateCounts[displayDate(v)]>1?'dateConflictCard':''}`} key={v.id}><input className="existingCheck" type="checkbox" checked={v.selected} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,selected:e.target.checked}:z))}/><button className="existingPreview" onClick={()=>toggle(v.id)}><VideoThumb video={v} onState={(id,s)=>setThumbs(x=>x[id]===s?x:{...x,[id]:s})}/><em>{v.privacyStatus}</em></button><div className="existingSummary" onClick={()=>toggle(v.id)}><small>#{i+1} • {v.id}</small><b>{v.title}</b><p>{short(v.description||'Описание отсутствует')}</p><div className="tagChips">{v.tags.slice(0,5).map(t=><i key={t}>{t}</i>)}{v.tags.length>5&&<i>+{v.tags.length-5}</i>}</div></div><div className="existingSchedule"><input type="datetime-local" value={local(v.publishAt)} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,publishAt:e.target.value?new Date(e.target.value).toISOString():undefined}:z))}/>{dateCounts[displayDate(v)]>1&&<span className="dateConflict">⚠ Совпадает дата</span>}<b className={v.applyState==='error'?'bad':v.applyState==='done'?'ok':''}>{v.applyState==='done'?'✓ Подтверждено YouTube':v.applyState==='saving'?'Отправляю + проверяю…':v.applyState==='error'?'⚠ Не подтверждено':'К изменению'}</b><button className="expandBtn" onClick={()=>toggle(v.id)}>{open?'Свернуть':'Редактировать'}</button></div>{open&&<div className="existingEditor"><label>Название<input value={v.title} maxLength={100} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,title:e.target.value}:z))}/></label><label>Описание<textarea value={v.description} maxLength={5000} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,description:e.target.value}:z))}/></label><label>Теги<input value={v.tags.join(', ')} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,tags:e.target.value.split(',').map(a=>a.trim()).filter(Boolean)}:z))}/></label><label>Privacy<select value={v.privacyStatus} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,privacyStatus:e.target.value}:z))}><option value="private">PRIVATE</option><option value="unlisted">UNLISTED</option><option value="public">PUBLIC</option></select></label>{v.error&&<div className="errorBox">{v.error}</div>}</div>}</article>})}</div>}
  {confirm&&<div className="modalBackdrop" onMouseDown={()=>setConfirm(false)}><section className="confirmModal" onMouseDown={e=>e.stopPropagation()}><small>YOUTUBE WRITE CONFIRMATION</small><h2>Будет изменено {selected.length} видео</h2><div className="confirmCounts"><span>Название <b>{changes.title}</b></span><span>Описание <b>{changes.description}</b></span><span>Теги <b>{changes.tags}</b></span><span>Дата <b>{changes.date}</b></span><span>Privacy <b>{changes.privacy}</b></span><span className={changes.public?'dangerText':''}>Public <b>{changes.public}</b></span></div><p>Перед записью VYRON сохранит локальный backup. После каждого videos.update будет выполнен videos.list и сравнение фактических данных YouTube.</p><footer><button onClick={()=>setConfirm(false)}>ОТМЕНА</button><button className="primary" disabled={busy} onClick={apply}>ОТПРАВИТЬ {selected.length} В YOUTUBE</button></footer></section></div>}
 </>;
}
