from pathlib import Path
import re
root=Path('.vyron-v051')

def sub(path,pattern,repl,count=1):
 p=root/path;s=p.read_text();s2,n=re.subn(pattern,repl,s,count=count,flags=re.S|re.M)
 if n!=count: raise SystemExit(f'{path}: expected {count}, got {n} for {pattern[:100]}')
 p.write_text(s2)

# OAuth: desktop reconnect asks for the complete permission set, including monetary analytics.
p=root/'src-tauri/src/youtube.rs';s=p.read_text()
old='let scope="https://www.googleapis.com/auth/youtube.force-ssl https://www.googleapis.com/auth/yt-analytics.readonly";'
new='let scope="https://www.googleapis.com/auth/youtube.force-ssl https://www.googleapis.com/auth/yt-analytics.readonly https://www.googleapis.com/auth/yt-analytics-monetary.readonly";'
if old not in s: raise SystemExit('oauth scope anchor missing')
s=s.replace(old,new,1).replace('for attempt in 0..2{match client.get(&url).send().await','for attempt in 0..3{match client.get(&url).send().await',1)
p.write_text(s)

# Profile list reports capabilities, never inferred in UI.
sub('src-tauri/src/youtube.rs',r'#\[tauri::command\]\npub fn youtube_oauth_profiles\(app:AppHandle\)->Result<Value,String>\{.*?\}\n\n#\[tauri::command\]\npub fn youtube_oauth_disconnect',r'''#[tauri::command]
pub fn youtube_oauth_profiles(app:AppHandle)->Result<Value,String>{
 let s=load_store(&app)?;
 Ok(json!(s.profiles.into_iter().map(|p|{
  let analytics=p.scopes.iter().any(|x|x=="https://www.googleapis.com/auth/yt-analytics.readonly"||x=="https://www.googleapis.com/auth/yt-analytics-monetary.readonly");
  let monetary=p.scopes.iter().any(|x|x=="https://www.googleapis.com/auth/yt-analytics-monetary.readonly");
  json!({"id":p.id,"channelId":p.channel_id,"channelTitle":p.channel_title,"connectedAt":p.connected_at,"clientIdMasked":if p.client_id.len()>12{format!("{}…{}",&p.client_id[..8],&p.client_id[p.client_id.len()-6..])}else{"configured".into()},"scopes":p.scopes,"analyticsAuthorized":analytics,"monetaryAuthorized":monetary})
 }).collect::<Vec<_>>()))
}

#[tauri::command]
pub fn youtube_oauth_disconnect''')

# Health includes permission state.
sub('src-tauri/src/youtube.rs',r'#\[tauri::command\]\npub async fn youtube_oauth_profile_health\(app:AppHandle,profile_id:String\)->Result<Value,String>\{.*?\}\n#\[tauri::command\]\npub async fn youtube_cache_thumbnail',r'''#[tauri::command]
pub async fn youtube_oauth_profile_health(app:AppHandle,profile_id:String)->Result<Value,String>{
 let (_token,p)=valid_access_token(&app,&profile_id).await?;let token=p.access_token.clone();
 let r=reqwest::Client::new().get("https://www.googleapis.com/youtube/v3/channels").bearer_auth(&token).query(&[("part","snippet"),("mine","true")]).send().await.map_err(|e|format!("YouTube health: {e}"))?;
 let st=r.status();let v:Value=r.json().await.unwrap_or_else(|_|json!({}));if !st.is_success(){return Err(youtube_error(&v,"YouTube OAuth health check failed"))}
 let item=v.get("items").and_then(|x|x.as_array()).and_then(|a|a.first()).cloned().unwrap_or_else(||json!({}));let sn=item.get("snippet").cloned().unwrap_or_else(||json!({}));let thumb=sn.pointer("/thumbnails/high/url").or_else(||sn.pointer("/thumbnails/medium/url")).or_else(||sn.pointer("/thumbnails/default/url")).and_then(|x|x.as_str());
 let analytics=p.scopes.iter().any(|x|x=="https://www.googleapis.com/auth/yt-analytics.readonly"||x=="https://www.googleapis.com/auth/yt-analytics-monetary.readonly");let monetary=p.scopes.iter().any(|x|x=="https://www.googleapis.com/auth/yt-analytics-monetary.readonly");
 Ok(json!({"ok":true,"status":"TOKEN_HEALTHY","channelId":item.get("id").and_then(|x|x.as_str()).or(p.channel_id.as_deref()),"channelTitle":sn.get("title").and_then(|x|x.as_str()).or(p.channel_title.as_deref()),"thumbnail":thumb,"expiresAt":p.expires_at,"analyticsAuthorized":analytics,"monetaryAuthorized":monetary}))
}
#[tauri::command]
pub async fn youtube_cache_thumbnail''')

# Existing videos: retain uploads playlist pagination, expose audit counters.
sub('src-tauri/src/youtube.rs',r'#\[tauri::command\]\npub async fn youtube_list_existing_videos\(.*?\n\}\n\n#\[tauri::command\]\npub async fn youtube_update_existing_video',r'''#[tauri::command]
pub async fn youtube_list_existing_videos(app:AppHandle,profile_id:String,max_results:Option<u32>)->Result<Value,String>{
 let (token,profile)=valid_access_token(&app,&profile_id).await?;let limit=max_results.unwrap_or(30).clamp(1,200) as usize;let client=reqwest::Client::new();
 let r=client.get("https://www.googleapis.com/youtube/v3/channels").bearer_auth(&token).query(&[("part","contentDetails"),("mine","true")]).send().await.map_err(|e|format!("YouTube channel: {e}"))?;let st=r.status();let cv:Value=r.json().await.map_err(|e|e.to_string())?;if !st.is_success(){return Err(youtube_error(&cv,"Не удалось получить канал YouTube"))}let uploads=cv.pointer("/items/0/contentDetails/relatedPlaylists/uploads").and_then(|x|x.as_str()).ok_or_else(||"YouTube не вернул playlist загрузок".to_string())?;
 let mut ids=Vec::<String>::new();let mut page:Option<String>=None;let mut youtube_found:usize=0;
 while ids.len()<limit{
  let mut q=client.get("https://www.googleapis.com/youtube/v3/playlistItems").bearer_auth(&token).query(&[("part","contentDetails"),("playlistId",uploads),("maxResults","50")]);if let Some(ref t)=page{q=q.query(&[("pageToken",t.as_str())]);}
  let r=q.send().await.map_err(|e|format!("YouTube uploads: {e}"))?;let st=r.status();let v:Value=r.json().await.map_err(|e|e.to_string())?;if !st.is_success(){return Err(youtube_error(&v,"Не удалось получить список загрузок"))}
  if youtube_found==0{youtube_found=v.pointer("/pageInfo/totalResults").and_then(|x|x.as_u64()).unwrap_or(0) as usize;}
  if let Some(items)=v.get("items").and_then(|x|x.as_array()){for item in items{if ids.len()>=limit{break}if let Some(id)=item.pointer("/contentDetails/videoId").and_then(|x|x.as_str()){ids.push(id.to_string())}}}
  page=v.get("nextPageToken").and_then(|x|x.as_str()).map(str::to_string);if page.is_none(){break}
 }
 if youtube_found==0{youtube_found=ids.len()}
 let mut by_id=std::collections::HashMap::<String,Value>::new();for chunk in ids.chunks(50){let joined=chunk.join(",");let r=client.get("https://www.googleapis.com/youtube/v3/videos").bearer_auth(&token).query(&[("part","snippet,status,contentDetails,statistics"),("id",joined.as_str())]).send().await.map_err(|e|format!("YouTube videos: {e}"))?;let st=r.status();let v:Value=r.json().await.map_err(|e|e.to_string())?;if !st.is_success(){return Err(youtube_error(&v,"Не удалось получить данные видео"))}for item in v.get("items").and_then(|x|x.as_array()).cloned().unwrap_or_default(){if let Some(id)=item.get("id").and_then(|x|x.as_str()){by_id.insert(id.to_string(),item);}}}
 let mut out=Vec::new();for (position,id) in ids.iter().enumerate(){if let Some(item)=by_id.get(id){let sn=item.get("snippet").cloned().unwrap_or_else(||json!({}));let st=item.get("status").cloned().unwrap_or_else(||json!({}));out.push(json!({"id":id,"channelId":sn.get("channelId").and_then(|x|x.as_str()),"position":position,"title":sn.get("title").and_then(|x|x.as_str()).unwrap_or(""),"description":sn.get("description").and_then(|x|x.as_str()).unwrap_or(""),"tags":sn.get("tags").cloned().unwrap_or_else(||json!([])),"categoryId":sn.get("categoryId").and_then(|x|x.as_str()).unwrap_or("10"),"publishedAt":sn.get("publishedAt").and_then(|x|x.as_str()),"privacyStatus":st.get("privacyStatus").and_then(|x|x.as_str()).unwrap_or("unknown"),"publishAt":st.get("publishAt").and_then(|x|x.as_str()),"thumbnail":sn.pointer("/thumbnails/maxres/url").or_else(||sn.pointer("/thumbnails/standard/url")).or_else(||sn.pointer("/thumbnails/high/url")).or_else(||sn.pointer("/thumbnails/medium/url")).or_else(||sn.pointer("/thumbnails/default/url")).and_then(|x|x.as_str()),"duration":item.pointer("/contentDetails/duration").and_then(|x|x.as_str()),"views":item.pointer("/statistics/viewCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()),"likes":item.pointer("/statistics/likeCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()),"comments":item.pointer("/statistics/commentCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()),"selected":st.get("privacyStatus").and_then(|x|x.as_str())==Some("private")}));}}
 let private_count=out.iter().filter(|x|x.get("privacyStatus").and_then(|v|v.as_str())==Some("private")).count();let public_count=out.iter().filter(|x|x.get("privacyStatus").and_then(|v|v.as_str())==Some("public")).count();let scheduled_count=out.iter().filter(|x|x.get("publishAt").and_then(|v|v.as_str()).is_some()).count();let expected=std::cmp::min(youtube_found,limit);let complete=out.len()==expected;
 Ok(json!({"channelId":profile.channel_id,"channelTitle":profile.channel_title,"youtubeFound":youtube_found,"received":out.len(),"requested":limit,"privateCount":private_count,"publicCount":public_count,"scheduledCount":scheduled_count,"complete":complete,"videos":out}))
}

#[tauri::command]
pub async fn youtube_backup_existing_videos(app:AppHandle,profile_id:String,videos:Value)->Result<Value,String>{
 let (token,profile)=valid_access_token(&app,&profile_id).await?;let channel_id=profile.channel_id.clone().ok_or_else(||"OAuth профиль не содержит Channel ID".to_string())?;let arr=videos.as_array().ok_or_else(||"Backup: videos должен быть массивом".to_string())?;if arr.is_empty(){return Err("Backup: список видео пуст".into())}
 let ids=arr.iter().map(|x|x.get("id").and_then(|v|v.as_str()).map(str::to_string).ok_or_else(||"Backup: video ID отсутствует".to_string())).collect::<Result<Vec<_>,_>>()?;let client=reqwest::Client::new();
 for chunk in ids.chunks(50){let joined=chunk.join(",");let r=client.get("https://www.googleapis.com/youtube/v3/videos").bearer_auth(&token).query(&[("part","snippet"),("id",joined.as_str())]).send().await.map_err(|e|format!("Backup ownership check: {e}"))?;let st=r.status();let v:Value=r.json().await.unwrap_or_else(|_|json!({}));if !st.is_success(){return Err(youtube_error(&v,"Backup: не удалось проверить владельца видео"))}for item in v.get("items").and_then(|x|x.as_array()).cloned().unwrap_or_default(){let actual=item.pointer("/snippet/channelId").and_then(|x|x.as_str()).unwrap_or("");if actual!=channel_id{return Err(format!("BLOCK: video {} принадлежит другому channelId",item.get("id").and_then(|x|x.as_str()).unwrap_or("?")))}}}
 let safe=channel_id.chars().filter(|c|c.is_ascii_alphanumeric()||*c=='_'||*c=='-').collect::<String>();let dir=app.path().app_data_dir().map_err(|e|e.to_string())?.join("Backup").join("Youtube").join(safe);fs::create_dir_all(&dir).map_err(|e|format!("Backup dir: {e}"))?;let path=dir.join(format!("{}.json",Utc::now().format("%Y%m%d-%H%M%S-%3f")));
 let clean=arr.iter().map(|v|json!({"videoId":v.get("id"),"title":v.get("title"),"description":v.get("description"),"tags":v.get("tags"),"publishAt":v.get("publishAt"),"privacy":v.get("privacyStatus")})).collect::<Vec<_>>();let payload=json!({"channelId":channel_id,"createdAt":Utc::now().to_rfc3339(),"videos":clean});fs::write(&path,serde_json::to_vec_pretty(&payload).map_err(|e|e.to_string())?).map_err(|e|format!("Backup write: {e}"))?;#[cfg(unix)]{use std::os::unix::fs::PermissionsExt;let _=fs::set_permissions(&path,fs::Permissions::from_mode(0o600));}
 Ok(json!({"path":path.to_string_lossy(),"count":arr.len()}))
}

fn same_publish_time(a:Option<&str>,b:Option<&str>)->bool{match (a,b){(None,None)=>true,(Some(x),Some(y))=>chrono::DateTime::parse_from_rfc3339(x).ok().map(|d|d.timestamp())==chrono::DateTime::parse_from_rfc3339(y).ok().map(|d|d.timestamp()),_=>false}}

#[tauri::command]
pub async fn youtube_update_existing_video(app:AppHandle,profile_id:String,video_id:String,title:String,description:String,tags:Vec<String>,publish_at:Option<String>,privacy_status:Option<String>)->Result<Value,String>{
 let (token,profile)=valid_access_token(&app,&profile_id).await?;if !profile.scopes.iter().any(|s|s=="https://www.googleapis.com/auth/youtube.force-ssl"||s=="https://www.googleapis.com/auth/youtube"){return Err("YouTube профиль подключён со старыми правами. Переподключи канал.".into())}
 let client=reqwest::Client::new();let r=client.get("https://www.googleapis.com/youtube/v3/videos").bearer_auth(&token).query(&[("part","snippet,status"),("id",video_id.as_str())]).send().await.map_err(|e|format!("YouTube video read: {e}"))?;let st=r.status();let v:Value=r.json().await.map_err(|e|e.to_string())?;if !st.is_success(){return Err(youtube_error(&v,"Не удалось перечитать видео"))}let item=v.get("items").and_then(|x|x.as_array()).and_then(|a|a.first()).ok_or_else(||"Видео не найдено".to_string())?;let sn=item.get("snippet").cloned().unwrap_or_else(||json!({}));let old_status=item.get("status").cloned().unwrap_or_else(||json!({}));if profile.channel_id.as_deref()!=sn.get("channelId").and_then(|x|x.as_str()){return Err(format!("BLOCK {}: video.channelId не совпадает с oauthProfile.channelId",video_id))}
 let wanted_title=title.trim().chars().take(100).collect::<String>();let wanted_desc=description.chars().take(5000).collect::<String>();let wanted_tags=tags.into_iter().take(30).collect::<Vec<_>>();let category=sn.get("categoryId").and_then(|x|x.as_str()).unwrap_or("10");let old_privacy=old_status.get("privacyStatus").and_then(|x|x.as_str()).unwrap_or("private");let target_privacy=privacy_status.as_deref().filter(|x|matches!(*x,"private"|"public"|"unlisted")).unwrap_or(old_privacy).to_string();
 if publish_at.as_ref().is_some_and(|x|!x.trim().is_empty())&&target_privacy!="private"{return Err("Scheduled publishAt требует privacyStatus=private".into())}
 let mut body=json!({"id":video_id,"snippet":{"title":wanted_title,"description":wanted_desc,"tags":wanted_tags,"categoryId":category}});let mut parts="snippet".to_string();if publish_at.as_ref().is_some_and(|x|!x.trim().is_empty())||privacy_status.is_some(){let mut ns=json!({"privacyStatus":target_privacy});if let Some(p)=publish_at.as_ref().filter(|x|!x.trim().is_empty()){ns["publishAt"]=json!(p);}for k in ["embeddable","license","publicStatsViewable","selfDeclaredMadeForKids","containsSyntheticMedia"]{if let Some(x)=old_status.get(k){ns[k]=x.clone();}}body["status"]=ns;parts="snippet,status".into();}
 let u=client.put("https://www.googleapis.com/youtube/v3/videos").bearer_auth(&token).query(&[("part",parts.as_str())]).json(&body).send().await.map_err(|e|format!("YouTube update: {e}"))?;let ust=u.status();let uv:Value=u.json().await.unwrap_or_else(|_|json!({}));if !ust.is_success(){return Err(youtube_error(&uv,"YouTube не принял изменения"))}
 let check=client.get("https://www.googleapis.com/youtube/v3/videos").bearer_auth(&token).query(&[("part","snippet,status"),("id",video_id.as_str())]).send().await.map_err(|e|format!("YouTube verify: {e}"))?;let cst=check.status();let cv:Value=check.json().await.unwrap_or_else(|_|json!({}));if !cst.is_success(){return Err(youtube_error(&cv,"YouTube verify не выполнен"))}let got=cv.get("items").and_then(|x|x.as_array()).and_then(|a|a.first()).ok_or_else(||format!("Verify {}: видео не найдено",video_id))?;let gsn=got.get("snippet").cloned().unwrap_or_else(||json!({}));let gst=got.get("status").cloned().unwrap_or_else(||json!({}));let actual_tags=gsn.get("tags").and_then(|x|x.as_array()).cloned().unwrap_or_default().into_iter().filter_map(|x|x.as_str().map(str::to_string)).collect::<Vec<_>>();let wanted_tags=body.pointer("/snippet/tags").and_then(|x|x.as_array()).cloned().unwrap_or_default().into_iter().filter_map(|x|x.as_str().map(str::to_string)).collect::<Vec<_>>();let mut diff=Vec::<String>::new();if gsn.get("title").and_then(|x|x.as_str())!=body.pointer("/snippet/title").and_then(|x|x.as_str()){diff.push("title".into())}if gsn.get("description").and_then(|x|x.as_str())!=body.pointer("/snippet/description").and_then(|x|x.as_str()){diff.push("description".into())}if actual_tags!=wanted_tags{diff.push("tags".into())}if let Some(w)=publish_at.as_deref().filter(|x|!x.trim().is_empty()){if !same_publish_time(Some(w),gst.get("publishAt").and_then(|x|x.as_str())){diff.push("publishAt".into())}}if privacy_status.is_some()||publish_at.as_ref().is_some_and(|x|!x.trim().is_empty()){if gst.get("privacyStatus").and_then(|x|x.as_str())!=body.pointer("/status/privacyStatus").and_then(|x|x.as_str()){diff.push("privacyStatus".into())}}
 if !diff.is_empty(){return Err(format!("YouTube не подтвердил {}: {}",video_id,diff.join(", ")))}Ok(json!({"id":video_id,"verified":true}))
}''')

# Register persistent backup command.
p=root/'src-tauri/src/lib.rs';s=p.read_text();old='youtube::youtube_upload_video,youtube::youtube_list_existing_videos,youtube::youtube_update_existing_video,';new='youtube::youtube_upload_video,youtube::youtube_list_existing_videos,youtube::youtube_backup_existing_videos,youtube::youtube_update_existing_video,'
if old not in s: raise SystemExit('lib youtube handler anchor missing')
p.write_text(s.replace(old,new,1))

# Full analytics command: real monetary metrics only with monetary scope; snapshots written to disk.
sub('src-tauri/src/youtube_intelligence.rs',r'#\[tauri::command\]\npub async fn youtube_channel_analytics\(.*?\n\}\n\nasync fn resolve_channel_ref',r'''#[tauri::command]
pub async fn youtube_channel_analytics(app:AppHandle,profile_id:String,days:Option<u32>,offset_days:Option<u32>,all_time:Option<bool>)->Result<Value,String>{
 let (token,scopes)=youtube::access_token_and_scopes(&app,&profile_id).await?;if !scopes.iter().any(|s|s=="https://www.googleapis.com/auth/yt-analytics.readonly"||s=="https://www.googleapis.com/auth/yt-analytics-monetary.readonly"){return Err("YouTube Analytics не разрешён. Переподключи YouTube OAuth.".into())}
 let client=reqwest::Client::new();let cr=client.get("https://www.googleapis.com/youtube/v3/channels").bearer_auth(&token).query(&[("part","snippet,statistics,contentDetails"),("mine","true")]).send().await.map_err(|e|format!("YouTube channel stats: {e}"))?;let cst=cr.status();let cv:Value=cr.json().await.unwrap_or_else(|_|json!({}));if !cst.is_success(){return Err(api_error(&cv,"YouTube Data API не вернул канал"))}let ci=cv.get("items").and_then(|x|x.as_array()).and_then(|a|a.first()).cloned().unwrap_or_else(||json!({}));let stat=ci.get("statistics").cloned().unwrap_or_else(||json!({}));let sn=ci.get("snippet").cloned().unwrap_or_else(||json!({}));let offset=offset_days.unwrap_or(0).min(7300);let end=Utc::now().date_naive()-ChronoDuration::days(offset as i64);let req_days=days.unwrap_or(28).clamp(1,7300);let published=sn.get("publishedAt").and_then(|x|x.as_str()).and_then(|x|x.get(..10)).and_then(|x|chrono::NaiveDate::parse_from_str(x,"%Y-%m-%d").ok());let start=if all_time.unwrap_or(false){published.unwrap_or(end-ChronoDuration::days(req_days.saturating_sub(1) as i64))}else{end-ChronoDuration::days(req_days.saturating_sub(1) as i64)};let actual_days=(end-start).num_days().max(0) as u32+1;let start_s=start.format("%Y-%m-%d").to_string();let end_s=end.format("%Y-%m-%d").to_string();
 let summary=analytics_report(&token,&start_s,&end_s,"views,estimatedMinutesWatched,averageViewDuration,averageViewPercentage,subscribersGained,subscribersLost,likes,comments,shares",None,None,None).await?;let sr=report_rows(&summary).into_iter().next().unwrap_or_default();let get=|i:usize|sr.get(i).map(value_f64).unwrap_or(0.0);
 let engaged=analytics_report(&token,&start_s,&end_s,"engagedViews",None,None,None).await.ok().and_then(|v|report_rows(&v).into_iter().next()).and_then(|r|r.first().map(value_u64));
 let monetary=scopes.iter().any(|s|s=="https://www.googleapis.com/auth/yt-analytics-monetary.readonly");let mut monetary_error:Option<String>=None;let money_report=if monetary{match analytics_report(&token,&start_s,&end_s,"estimatedRevenue,estimatedAdRevenue,estimatedRedPartnerRevenue,monetizedPlaybacks,adImpressions,cpm,playbackBasedCpm",None,None,None).await{Ok(v)=>v,Err(e)=>{monetary_error=Some(e);json!({"rows":[]})}}}else{json!({"rows":[]})};let mr=report_rows(&money_report).into_iter().next().unwrap_or_default();let mget=|i:usize|mr.get(i).map(value_f64);
 let money_daily=if monetary{analytics_report(&token,&start_s,&end_s,"estimatedRevenue",Some("day"),Some("day"),Some(400)).await.unwrap_or_else(|_|json!({"rows":[]}))}else{json!({"rows":[]})};let mut daily_revenue=std::collections::HashMap::<String,f64>::new();for r in report_rows(&money_daily){if let Some(d)=r.first().and_then(|x|x.as_str()){daily_revenue.insert(d.to_string(),r.get(1).map(value_f64).unwrap_or(0.0));}}
 let daily=analytics_report(&token,&start_s,&end_s,"views,estimatedMinutesWatched,subscribersGained,subscribersLost",Some("day"),Some("day"),Some(400)).await.unwrap_or_else(|_|json!({"rows":[]}));let daily_rows=report_rows(&daily).into_iter().map(|r|{let d=r.first().and_then(|x|x.as_str()).unwrap_or("").to_string();json!({"date":d,"views":r.get(1).map(value_u64).unwrap_or(0),"watchMinutes":r.get(2).map(value_f64).unwrap_or(0.0),"subscribersGained":r.get(3).map(value_u64).unwrap_or(0),"subscribersLost":r.get(4).map(value_u64).unwrap_or(0),"estimatedRevenue":daily_revenue.get(&d).copied()})}).collect::<Vec<_>>();
 let top=analytics_report(&token,&start_s,&end_s,"views,estimatedMinutesWatched,averageViewDuration,averageViewPercentage,likes,comments,shares,subscribersGained",Some("video"),Some("-views"),Some(10)).await.unwrap_or_else(|_|json!({"rows":[]}));let top_rows=report_rows(&top);let top_ids=top_rows.iter().filter_map(|r|r.first().and_then(|x|x.as_str())).collect::<Vec<_>>();let mut video_meta=std::collections::HashMap::<String,Value>::new();if !top_ids.is_empty(){let joined=top_ids.join(",");let r=client.get("https://www.googleapis.com/youtube/v3/videos").bearer_auth(&token).query(&[("part","snippet"),("id",joined.as_str())]).send().await.map_err(|e|format!("Top videos metadata: {e}"))?;let st=r.status();let v:Value=r.json().await.unwrap_or_else(|_|json!({}));if st.is_success(){for item in v.get("items").and_then(|x|x.as_array()).cloned().unwrap_or_default(){if let Some(id)=item.get("id").and_then(|x|x.as_str()){video_meta.insert(id.to_string(),item);}}}}
 let video_money=if monetary{analytics_report(&token,&start_s,&end_s,"views,estimatedRevenue",Some("video"),Some("-views"),Some(200)).await.unwrap_or_else(|_|json!({"rows":[]}))}else{json!({"rows":[]})};let mut video_rev=std::collections::HashMap::<String,f64>::new();for r in report_rows(&video_money){if let Some(id)=r.first().and_then(|x|x.as_str()){video_rev.insert(id.to_string(),r.get(2).map(value_f64).unwrap_or(0.0));}}
 let top_videos=top_rows.into_iter().map(|r|{let id=r.first().and_then(|x|x.as_str()).unwrap_or("").to_string();let meta=video_meta.get(&id).cloned().unwrap_or_else(||json!({}));let vsn=meta.get("snippet").cloned().unwrap_or_else(||json!({}));let views=r.get(1).map(value_u64).unwrap_or(0);let rev=video_rev.get(&id).copied();let rpm=if views>0{rev.map(|x|x/views as f64*1000.0)}else{None};json!({"id":id,"title":vsn.get("title").and_then(|x|x.as_str()).unwrap_or("Видео"),"publishedAt":vsn.get("publishedAt").and_then(|x|x.as_str()),"thumbnail":thumb_url(&vsn),"views":views,"watchMinutes":r.get(2).map(value_f64).unwrap_or(0.0),"averageViewDuration":r.get(3).map(value_f64).unwrap_or(0.0),"averageViewPercentage":r.get(4).map(value_f64).unwrap_or(0.0),"likes":r.get(5).map(value_u64).unwrap_or(0),"comments":r.get(6).map(value_u64).unwrap_or(0),"shares":r.get(7).map(value_u64).unwrap_or(0),"subscribersGained":r.get(8).map(value_u64).unwrap_or(0),"estimatedRevenue":rev,"rpm":rpm})}).collect::<Vec<_>>();
 let traffic=analytics_report(&token,&start_s,&end_s,"views,estimatedMinutesWatched",Some("insightTrafficSourceType"),Some("-views"),Some(12)).await.unwrap_or_else(|_|json!({"rows":[]}));let traffic_sources=report_rows(&traffic).into_iter().map(|r|json!({"key":r.first().and_then(|x|x.as_str()).unwrap_or("OTHER"),"views":r.get(1).map(value_u64).unwrap_or(0),"watchMinutes":r.get(2).map(value_f64).unwrap_or(0.0)})).collect::<Vec<_>>();
 let countries=analytics_report(&token,&start_s,&end_s,"views,estimatedMinutesWatched",Some("country"),Some("-views"),Some(12)).await.unwrap_or_else(|_|json!({"rows":[]}));let country_money=if monetary{analytics_report(&token,&start_s,&end_s,"views,estimatedRevenue",Some("country"),Some("-views"),Some(50)).await.unwrap_or_else(|_|json!({"rows":[]}))}else{json!({"rows":[]})};let mut crev=std::collections::HashMap::<String,f64>::new();for r in report_rows(&country_money){if let Some(k)=r.first().and_then(|x|x.as_str()){crev.insert(k.to_string(),r.get(2).map(value_f64).unwrap_or(0.0));}}let countries_rows=report_rows(&countries).into_iter().map(|r|{let key=r.first().and_then(|x|x.as_str()).unwrap_or("—").to_string();let views=r.get(1).map(value_u64).unwrap_or(0);let rev=crev.get(&key).copied();json!({"key":key,"views":views,"watchMinutes":r.get(2).map(value_f64).unwrap_or(0.0),"estimatedRevenue":rev,"rpm":if views>0{rev.map(|x|x/views as f64*1000.0)}else{None}})}).collect::<Vec<_>>();
 let total_videos=if let Some(uploads)=ci.pointer("/contentDetails/relatedPlaylists/uploads").and_then(|x|x.as_str()){let r=client.get("https://www.googleapis.com/youtube/v3/playlistItems").bearer_auth(&token).query(&[("part","id"),("playlistId",uploads),("maxResults","1")]).send().await.ok();if let Some(r)=r{let v:Value=r.json().await.unwrap_or_else(|_|json!({}));v.pointer("/pageInfo/totalResults").and_then(|x|x.as_u64())}else{None}}else{None};
 let payload=json!({"source":"youtube-analytics-v2","snapshotDate":end_s,"periodDays":actual_days,"offsetDays":offset,"allTime":all_time.unwrap_or(false),"updatedAt":Utc::now().to_rfc3339(),"views":get(0) as u64,"engagedViews":engaged,"watchMinutes":get(1),"averageViewDuration":get(2),"averageViewPercentage":get(3),"subscribersGained":get(4) as u64,"subscribersLost":get(5) as u64,"likes":get(6) as u64,"comments":get(7) as u64,"shares":get(8) as u64,"monetaryAuthorized":monetary,"estimatedRevenue":mget(0),"estimatedAdRevenue":mget(1),"estimatedRedPartnerRevenue":mget(2),"monetizedPlaybacks":mget(3),"adImpressions":mget(4),"cpm":mget(5),"playbackBasedCpm":mget(6),"monetaryError":monetary_error,"impressions":Value::Null,"impressionCtr":Value::Null,"daily":daily_rows,"topVideos":top_videos,"trafficSources":traffic_sources,"countries":countries_rows,"audience":[],"channelPublishedAt":sn.get("publishedAt").and_then(|x|x.as_str()),"channelCountry":sn.get("country").and_then(|x|x.as_str()),"channelLanguage":sn.get("defaultLanguage").and_then(|x|x.as_str()).or_else(||sn.get("defaultAudioLanguage").and_then(|x|x.as_str())),"channelThumbnail":thumb_url(&sn),"totalVideos":total_videos,"publicStats":{"channelId":ci.get("id").and_then(|x|x.as_str()),"title":sn.get("title").and_then(|x|x.as_str()),"thumbnail":thumb_url(&sn),"subscribers":stat.get("subscriberCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()),"views":stat.get("viewCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok()),"videos":stat.get("videoCount").and_then(|x|x.as_str()).and_then(|x|x.parse::<u64>().ok())}});
 if let Some(cid)=ci.get("id").and_then(|x|x.as_str()){if let Ok(base)=app.path().app_data_dir(){let dir=base.join("ChannelAnalytics").join(cid);if std::fs::create_dir_all(&dir).is_ok(){let path=dir.join(format!("{}.json",end_s));let tmp=path.with_extension("tmp");if let Ok(bytes)=serde_json::to_vec_pretty(&payload){if std::fs::write(&tmp,bytes).is_ok(){let _=std::fs::rename(tmp,path);}}}}}
 Ok(payload)
}

async fn resolve_channel_ref''')
print('VYRON 0.9.0 backend safety + monetary analytics patch applied')
