import React,{useEffect,useState} from 'react';
import {api} from './api';
import {runAutopilotCycle} from './autopilotRuntime';
import {createMissingJobs} from './autopilotCore';
import {useApp} from './store';
import type {JobStatus} from './types';

type Tab='queue'|'materials';
const statusLabel:Record<JobStatus,string>={NEED_IMAGE:'Нужна картинка',WAITING_MUSIC:'Ждёт музыку',READY_RENDER:'Готов к рендеру',RENDERING:'Рендерится',READY_UPLOAD:'Готов к YouTube',UPLOADING:'Загружается',SCHEDULED:'Запланирован',ERROR:'Ошибка'};

export function ProductionOS(){
 const channels=useApp(s=>s.channels),jobs=useApp(s=>s.jobs),setJobs=useApp(s=>s.setJobs),patchJob=useApp(s=>s.patchJob),settings=useApp(s=>s.settings),toast=useApp(s=>s.toast),setPage=useApp(s=>s.setPage);const [tab,setTab]=useState<Tab>('queue'),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[channelId,setChannelId]=useState(channels[0]?.id||''),[inbox,setInbox]=useState<any>();const filtered=jobs.filter(j=>filter==='all'||j.channelId===filter).sort((a,b)=>a.number-b.number);const c=channels.find(x=>x.id===channelId);
 useEffect(()=>{if(!channelId&&channels[0])setChannelId(channels[0].id)},[channels.length]);
 async function refreshAll(){setBusy(true);try{for(const j of useApp.getState().jobs){const ch=channels.find(x=>x.id===j.channelId);if(!ch||!j.folder||j.status==='SCHEDULED')continue;try{patchJob(j.id,await api.refreshJob(j.folder,ch.minTracks))}catch(e){patchJob(j.id,{status:'ERROR',error:String(e)})}}toast('Статусы обновлены')}finally{setBusy(false)}}
 async function createPlan(){if(!settings.workspace){const ws=await api.defaultWorkspace();useApp.getState().patchSettings({workspace:ws})}let added=0;let next=[...useApp.getState().jobs];for(const ch of channels.filter(x=>x.enabled)){const created=createMissingJobs(ch,next);next=[...next,...created];added+=created.length}setJobs(next);await runAutopilotCycle(true);toast(added?`Создано задач: ${added}`:'Дефицита нет')}
 async function ensure(){if(!c)return;const r=await api.ensureChannelInbox(settings.workspace,c.name);setInbox(r);return r}
 async function importImages(){if(!c)return;const files=await api.chooseImages();if(!files.length)return;const pending=jobs.filter(j=>j.channelId===c.id&&j.status==='NEED_IMAGE').sort((a,b)=>a.number-b.number);const nums=pending.slice(0,files.length).map(j=>j.number);const imported=await api.importImages(settings.workspace,c.id,c.name,files,c.minTracks,nums);for(const x of imported){const old=useApp.getState().jobs.find(j=>j.channelId===c.id&&j.number===x.number);if(old)useApp.getState().patchJob(old.id,x);else useApp.getState().addJobs([x])}toast(`${files.length} изображений распределено`)}
 return <>
  <div className="pageHeader"><div><small>PRODUCTION</small><h1>Производство</h1><p>Материалы, проекты, ENDLUME и готовые final.mp4 в одном разделе.</p></div><div className="headerActions"><button disabled={busy} onClick={refreshAll}>{busy?'Проверяю…':'↻ Обновить статусы'}</button><button className="primary" onClick={createPlan}>Заполнить план</button></div></div>
  <div className="youtubeTabs productionTabs"><button className={tab==='queue'?'active':''} onClick={()=>setTab('queue')}>Очередь</button><button className={tab==='materials'?'active':''} onClick={()=>setTab('materials')}>Материалы</button></div>
  {tab==='queue'&&<><div className="todayStatus productionStatus"><span><small>Need image</small><b>{jobs.filter(j=>j.status==='NEED_IMAGE').length}</b></span><span><small>Need music</small><b>{jobs.filter(j=>j.status==='WAITING_MUSIC').length}</b></span><span><small>Ready render</small><b>{jobs.filter(j=>j.status==='READY_RENDER').length}</b></span><span><small>Rendering</small><b>{jobs.filter(j=>j.status==='RENDERING').length}</b></span><span><small>Ready upload</small><b>{jobs.filter(j=>j.status==='READY_UPLOAD').length}</b></span><span><small>Errors</small><b>{jobs.filter(j=>j.status==='ERROR').length}</b></span></div><div className="filterBar"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все каналы</option>{channels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><span>{filtered.length} задач</span></div>{filtered.length===0?<div className="empty"><b>Очередь пустая</b><p>VYRON рассчитает нужное число видео по графику каналов.</p><button className="primary" onClick={createPlan}>Создать план</button></div>:<div className="jobs virtualReady">{filtered.map(j=>{const ch=channels.find(x=>x.id===j.channelId);return <article className="job" key={j.id}><div className={`jobStatus ${j.status.toLowerCase()}`}>{statusLabel[j.status]}</div><div className="jobMain"><small>{ch?.name||'Канал удалён'} • VIDEO_{String(j.number).padStart(3,'0')}</small><b>{j.title||'Метаданные ещё не созданы'}</b><span>{j.publishAt?`План: ${new Date(j.publishAt).toLocaleString('ru-RU')}`:'Дата не назначена'} • треков {j.tracksCount}/{j.minTracks}</span>{j.status==='UPLOADING'&&<div className="miniProgress"><i style={{width:`${j.uploadProgress||0}%`}}/></div>}{j.error&&<em className="jobError">{j.error}</em>}</div><div className="jobActions">{j.folder&&<button onClick={()=>api.reveal(j.folder)}>Папка</button>}{j.status==='WAITING_MUSIC'&&<button className="primary small" onClick={async()=>{const files=await api.chooseTracks();if(!files.length||!j.folder)return;try{const r=await api.addTracks(j.folder,files,ch?.minTracks||j.minTracks);patchJob(j.id,{tracksCount:r.tracksCount,status:r.status as JobStatus})}catch(e){patchJob(j.id,{status:'ERROR',error:String(e)})}}}>+ Музыка</button>}{j.status==='READY_RENDER'&&<button className="primary small" onClick={async()=>{try{await api.enqueueRender(settings.workspace,j.folder);patchJob(j.id,{renderQueuedAt:new Date().toISOString()});if(settings.endlumePath)await api.openEndlume(settings.endlumePath);toast('Проект отправлен в RenderQueue')}catch(e){toast(String(e))}}}>В ENDLUME</button>}{j.status==='READY_UPLOAD'&&<button className="primary small" onClick={()=>setPage('youtube')}>YouTube</button>}{j.status==='ERROR'&&<button onClick={async()=>{if(!j.folder)return;try{patchJob(j.id,{...(await api.refreshJob(j.folder,ch?.minTracks||j.minTracks)),error:undefined})}catch(e){patchJob(j.id,{error:String(e)})}}}>Повторить</button>}</div></article>})}</div>}</>}
  {tab==='materials'&&<><section className="panel materialToolbar"><select value={channelId} onChange={e=>{setChannelId(e.target.value);setInbox(undefined)}}><option value="">— канал —</option>{channels.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="primary" disabled={!c} onClick={importImages}>+ Импортировать изображения</button><button disabled={!c} onClick={async()=>{const r=await ensure();if(r)await api.openLocal(r.music)}}>Music Inbox</button><button disabled={!c} onClick={async()=>{const r=await ensure();if(r)await api.openLocal(r.images)}}>Image Inbox</button></section><div className="contentLayout compactContent"><section className="panel importPanel"><small>01</small><h3>Музыка</h3><p>Автопилот распределяет треки по очереди.</p><strong>{jobs.filter(j=>j.status==='WAITING_MUSIC').length}</strong><span>ждут музыку</span></section><section className="panel importPanel"><small>02</small><h3>Изображения</h3><p>1 изображение = 1 будущий проект.</p><strong>{jobs.filter(j=>j.status==='NEED_IMAGE').length}</strong><span>ждут изображение</span></section><section className="panel importPanel"><small>03</small><h3>ENDLUME</h3><p>Готовые проекты уходят в RenderQueue.</p><strong>{jobs.filter(j=>j.status==='READY_RENDER').length}</strong><span>готовы к рендеру</span></section></div>{inbox&&<div className="panel"><b>Inbox готов</b><p>{inbox.root}</p></div>}</>}
 </>;
}
