import React,{useEffect,useState} from 'react';
import {api,type GoogleConfigStatus,type YoutubeProfileHealth} from './api';
import {AccountsPage} from './AccountsPage';
import {useApp} from './store';
import type {AutopilotMode,LicenseStatus,YoutubeProfile} from './types';

type Tab='general'|'youtube'|'autopilot'|'endlume'|'updates'|'diagnostics';
function Toggle({label,text,value,onChange}:{label:string;text:string;value:boolean;onChange:(v:boolean)=>void}){return <button className="toggleRow" onClick={()=>onChange(!value)}><div><b>{label}</b><small>{text}</small></div><i className={value?'on':''}><em/></i></button>}

export function SettingsOS({license}:{license:LicenseStatus}){
 const s=useApp(x=>x.settings),patch=useApp(x=>x.patchSettings),logs=useApp(x=>x.logs),toast=useApp(x=>x.toast);const [tab,setTab]=useState<Tab>('general'),[profiles,setProfiles]=useState<YoutubeProfile[]>([]),[config,setConfig]=useState<GoogleConfigStatus|null>(null),[health,setHealth]=useState<Record<string,YoutubeProfileHealth>>({}),[update,setUpdate]=useState<any>(),[progress,setProgress]=useState<number|null>(null),[stage,setStage]=useState(''),[diag,setDiag]=useState<{label:string;status:string;ok?:boolean;detail?:string}[]>([]),[checking,setChecking]=useState(false);
 async function refreshYoutube(){const [p,c]=await Promise.all([api.youtubeProfiles(),api.youtubeGoogleConfig()]);setProfiles(p);setConfig(c);const h:Record<string,YoutubeProfileHealth>={};for(const x of p){try{h[x.id]=await api.youtubeProfileHealth(x.id)}catch(e){h[x.id]={ok:false,status:'RECONNECT_REQUIRED',error:String(e)}}}setHealth(h)}
 useEffect(()=>{void refreshYoutube().catch(()=>{})},[]);
 const mode:AutopilotMode=s.autopilotMode||'off';const setMode=(m:AutopilotMode)=>{if(m==='off')patch({autopilotMode:m,autopilotEnabled:false,autoUploadYoutube:false});else if(m==='assisted')patch({autopilotMode:m,autopilotEnabled:true,autoUploadYoutube:false});else patch({autopilotMode:m,autopilotEnabled:true,autoUploadYoutube:true})};
 async function reconnectRevenue(){setChecking(true);try{const p=await api.youtubeConnectGlobal();toast(`Revenue Analytics: переподключён ${p.channelTitle||p.channelId||'канал'}`);await refreshYoutube()}catch(e){toast(String(e))}finally{setChecking(false)}}
 async function runDiagnostics(){setChecking(true);try{let ws=s.workspace;if(!ws){ws=await api.defaultWorkspace();patch({workspace:ws})}const core=await api.diagnostics(ws);let p:YoutubeProfile[]=[],c:GoogleConfigStatus|null=null;try{[p,c]=await Promise.all([api.youtubeProfiles(),api.youtubeGoogleConfig()])}catch{}const hh:YoutubeProfileHealth[]=[];for(const x of p){try{hh.push(await api.youtubeProfileHealth(x.id))}catch(e){hh.push({ok:false,status:'RECONNECT_REQUIRED',error:String(e)})}}const monetary=p.length>0&&p.every(x=>x.monetaryAuthorized);setDiag([{label:'Google configuration',status:c?.configured?'Готово':'Не настроено',ok:Boolean(c?.configured)},{label:'OAuth',status:p.length?`${p.length} профилей`:'Нет профилей',ok:p.length>0,detail:hh.filter(x=>!x.ok).map(x=>x.error).filter(Boolean).join(' • ')},{label:'YouTube Data API',status:hh.some(x=>x.ok)?'Доступен':'Не подтверждён',ok:hh.some(x=>x.ok)},{label:'YouTube Analytics',status:p.some(x=>x.analyticsAuthorized)?'Разрешён':'Нет разрешения',ok:p.some(x=>x.analyticsAuthorized)},{label:'Revenue Analytics',status:monetary?'Разрешён':'Требуется monetary scope',ok:monetary},{label:'ENDLUME',status:s.endlumePath?'Путь настроен':'Не выбран',ok:Boolean(s.endlumePath)},{label:'Workspace',status:core.workspaceWritable?'Доступен для записи':'Проблема записи',ok:core.workspaceWritable},{label:'Thumbnail Cache',status:'Проверяется при загрузке изображений',detail:'Отдельный размер cache backend пока не сообщает'},{label:'Upload Queue',status:`${useApp.getState().jobs.filter(j=>['READY_UPLOAD','UPLOADING','ERROR'].includes(j.status)).length} активных/ошибочных`},{label:'Updater',status:'Tauri signed updater подключён',ok:true},{label:'Internet',status:hh.some(x=>x.ok)?'Google API отвечает':'Не подтверждён',ok:hh.some(x=>x.ok)},{label:'API Quota',status:'Нет данных',detail:'YouTube не возвращает остаток quota через Data API'}])}catch(e){setDiag([{label:'Диагностика',status:'Ошибка',ok:false,detail:String(e)}])}finally{setChecking(false)}}
 return <>
  <div className="pageHeader"><div><small>SETTINGS</small><h1>Настройки</h1><p>Основные настройки без технического шума. Advanced открывается только при необходимости.</p></div></div>
  <div className="settingsTabs osTabs">{(['general','youtube','autopilot','endlume','updates','diagnostics'] as Tab[]).map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t==='general'?'Общие':t==='youtube'?'YouTube':t==='autopilot'?'Автопилот':t==='endlume'?'ENDLUME':t==='updates'?'Обновления':'Диагностика'}</button>)}</div>
  {tab==='general'&&<div className="settingsStack"><section className="settingsCard"><h3>Workspace</h3><p>VYRON хранит Inbox, проекты, очередь и локальное состояние.</p><div className="pathLine"><input readOnly value={s.workspace} placeholder="создаётся автоматически"/><button onClick={async()=>{const p=await api.chooseWorkspace();if(p)patch({workspace:p})}}>Выбрать</button><button onClick={()=>s.workspace&&api.openLocal(s.workspace)}>Открыть</button></div></section><section className="settingsCard"><h3>Интерфейс</h3><div className="toggleRows"><Toggle label="FPS monitor" text="Показывать текущий FPS интерфейса." value={s.fpsMonitor} onChange={v=>patch({fpsMonitor:v})}/><Toggle label="Уменьшить анимации" text="Отключить декоративные переходы." value={s.reduceMotion} onChange={v=>patch({reduceMotion:v})}/></div></section><section className="settingsCard"><h3>Лицензия</h3><p>{license.valid?'VYRON активирован':'Требуется активация'} • {license.type||'—'}</p></section><details className="settingsCard advancedPanel"><summary>Advanced</summary><div className="advancedInner"><label>OpenAI API — опционально<input type="password" value={s.openaiApiKey} onChange={e=>patch({openaiApiKey:e.target.value.trim()})}/></label><label>OpenAI model<input value={s.openaiModel} onChange={e=>patch({openaiModel:e.target.value.trim()})}/></label><label>YouTube category<input value={s.youtubeCategoryId} onChange={e=>patch({youtubeCategoryId:e.target.value.trim()||'10'})}/></label></div></details></div>}
  {tab==='youtube'&&<div className="settingsStack"><section className="settingsCard youtubeStatusCard"><div className="panelHead"><div><small>GLOBAL GOOGLE CONFIG</small><h3>Состояние YouTube</h3></div><button disabled={checking} onClick={()=>refreshYoutube()}>{checking?'…':'↻ Проверить'}</button></div><div className="configChecks"><span className={config?.configured?'good':''}>Google Credentials <b>{config?.configured?'✓':'—'}</b></span><span className={profiles.some(x=>x.analyticsAuthorized)?'good':''}>YouTube Analytics <b>{profiles.some(x=>x.analyticsAuthorized)?'✓':'—'}</b></span><span className={profiles.length&&profiles.every(x=>x.monetaryAuthorized)?'good':''}>Revenue Analytics <b>{profiles.length&&profiles.every(x=>x.monetaryAuthorized)?'✓':'—'}</b></span></div>{profiles.some(x=>!x.monetaryAuthorized)&&<div className="revenuePermission"><div><b>Доход — нет разрешения</b><p>Desktop OAuth требует полноценного reconnect с monetary scope. Refresh token будет заменён только после успешного Google OAuth.</p></div><button className="primary" disabled={checking||!config?.configured} onClick={reconnectRevenue}>Подключить доход</button></div>}</section><AccountsPage/></div>}
  {tab==='autopilot'&&<div className="settingsStack"><section className="settingsCard"><h3>Режим Autopilot</h3><div className="modeSwitch large"><button className={mode==='off'?'active':''} onClick={()=>setMode('off')}>OFF</button><button className={mode==='assisted'?'active':''} onClick={()=>setMode('assisted')}>ASSISTED</button><button className={mode==='full'?'active':''} onClick={()=>setMode('full')}>FULL</button></div><p>{mode==='off'?'Только sync и analytics.':mode==='assisted'?'Очередь и подготовка автоматические; запись в YouTube подтверждается вручную.':'После настройки pipeline может идти до YouTube автоматически.'}</p></section><details className="settingsCard advancedPanel"><summary>Advanced Autopilot</summary><div className="toggleRows"><Toggle label="Поддерживать план" text="Создавать недостающие Video_XXX." value={s.autoCreatePlan} onChange={v=>patch({autoCreatePlan:v})}/><Toggle label="Распределять музыку" text="Inbox/Music → проекты." value={s.autoAssignMusic} onChange={v=>patch({autoAssignMusic:v})}/><Toggle label="Распределять изображения" text="1 изображение = 1 проект." value={s.autoAssignImages} onChange={v=>patch({autoAssignImages:v})}/><Toggle label="AI metadata" text="Только при подключённом API." value={s.autoGenerateMetadata} onChange={v=>patch({autoGenerateMetadata:v})}/><Toggle label="ENDLUME queue" text="Создавать render marker." value={s.autoQueueRender} onChange={v=>patch({autoQueueRender:v})}/><Toggle label="Открывать ENDLUME" text="Открывать приложение при render задачах." value={s.autoOpenEndlume} onChange={v=>patch({autoOpenEndlume:v})}/><Toggle label="YouTube autoupload" text="В FULL режиме загружать готовые видео." value={s.autoUploadYoutube} onChange={v=>patch({autoUploadYoutube:v})}/></div><label>Интервал цикла, сек<input type="number" min="10" max="3600" value={s.autopilotIntervalSec} onChange={e=>patch({autopilotIntervalSec:Math.max(10,+e.target.value||30)})}/></label></details></div>}
  {tab==='endlume'&&<div className="settingsStack"><section className="settingsCard"><h3>ENDLUME Studio</h3><p>Готовые проекты отправляются в RenderQueue без изменения project metadata.</p><div className="pathLine"><input readOnly value={s.endlumePath} placeholder="ENDLUME Studio.app"/><button onClick={async()=>{const p=await api.chooseEndlume();if(p)patch({endlumePath:p})}}>Выбрать</button>{s.endlumePath&&<button onClick={()=>api.openEndlume(s.endlumePath)}>Открыть</button>}</div></section></div>}
  {tab==='updates'&&<section className="settingsCard"><h3>Update Center</h3><p>Текущая версия: 0.9.0</p><Toggle label="Проверять автоматически" text="При запуске, через 30 секунд и далее каждые 6 часов." value={s.autoCheckUpdates} onChange={v=>patch({autoCheckUpdates:v})}/><button className="settingsAction" onClick={async()=>{try{setUpdate(await api.checkUpdate())}catch(e){setUpdate({error:String(e)})}}>Проверить обновления</button>{update?.none&&<div className="successBox">Установлена актуальная версия {update.current||'0.9.0'}.</div>}{update?.version&&<div className="updateFound"><b>Доступна: {update.version}</b><p>{update.body}</p>{stage&&<strong>{stage}</strong>}{progress!==null&&<div className="progress"><i style={{width:`${progress}%`}}/><span>{progress.toFixed(0)}%</span></div>}<button className="primary" onClick={async()=>{setProgress(0);setStage('Downloading');try{await update.install((p:number)=>{setProgress(p);if(p>=100)setStage('Verifying signature / Installing')})}catch(e){setProgress(null);setStage('Обновление не установлено. Текущая версия сохранена.');toast(String(e))}}}>Установить и перезапустить</button></div>}{update?.error&&<div className="errorBox">Обновление не установлено. Текущая версия сохранена.<details><summary>Technical detail</summary>{update.error}</details></div>}</section>}
  {tab==='diagnostics'&&<div className="settingsStack"><section className="settingsCard"><div className="panelHead"><div><h3>Диагностика</h3><p>Основной текст — человеческий; техническая ошибка раскрывается отдельно.</p></div><button className="primary" disabled={checking} onClick={runDiagnostics}>{checking?'Проверяю…':'Запустить проверку'}</button></div>{diag.length>0&&<div className="diagnosticGrid">{diag.map((x,i)=><div key={i} className={x.ok===false?'bad':x.ok?'good':''}><span><b>{x.label}</b><em>{x.status}</em></span>{x.detail&&<details><summary>Technical detail</summary><p>{x.detail}</p></details>}</div>)}</div>}</section><section className="settingsCard"><h3>Последние события</h3><div className="logs">{logs.length?logs.slice(0,60).map((l,i)=><div key={i} className={l.level}><small>{new Date(l.at).toLocaleString('ru-RU')}</small><span>{l.message}</span></div>):<p>Событий пока нет.</p>}</div></section></div>}
 </>;
}
