import React,{useEffect,useState} from 'react';
import {api,type YoutubeProfileHealth} from './api';
import {useApp} from './store';
import {bufferDays,formatNumber} from './core';
import {refreshChannelAnalytics} from './youtubeIntelligence';
import type {Channel,YoutubeProfile} from './types';

const num=(x?:number,d=0)=>x==null?'—':x.toLocaleString('ru-RU',{maximumFractionDigits:d});
const money=(x?:number)=>x==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(x);
const dur=(sec?:number)=>{if(sec==null)return '—';const s=Math.round(sec);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
const age=(iso?:string)=>{if(!iso)return '—';const d=new Date(iso),n=new Date();let months=(n.getFullYear()-d.getFullYear())*12+n.getMonth()-d.getMonth();if(n.getDate()<d.getDate())months--;months=Math.max(0,months);const y=Math.floor(months/12),m=months%12;return `${y?`${y} г. `:''}${m} мес.`.trim()};
const sumLast=(c:Channel,days:number,key:'views'|'estimatedRevenue')=>{const a=c.analytics;if(!a?.daily?.length)return undefined;const rows=a.daily.slice(-days);if(!rows.length)return undefined;const values=rows.map(x=>Number(x[key]||0));return values.reduce((s,x)=>s+x,0)};
const rpm=(rev?:number,views?:number)=>rev==null||!views?undefined:rev/views*1000;
const health=(c:Channel,jobs:any[],oauth?:YoutubeProfileHealth)=>{let n=100;if(!c.youtubeProfileId)n-=30;else if(oauth&&!oauth.ok)n-=25;if(!c.analytics)n-=18;if(jobs.some(j=>j.channelId===c.id&&j.status==='ERROR'))n-=18;const b=bufferDays(c,jobs);if(b<7)n-=22;else if(b<14)n-=12;else if(b<30)n-=5;return Math.max(0,n)};

export function ChannelsOS(){
 const channels=useApp(s=>s.channels),jobs=useApp(s=>s.jobs),addChannel=useApp(s=>s.addChannel),updateChannel=useApp(s=>s.updateChannel),removeChannel=useApp(s=>s.removeChannel),toast=useApp(s=>s.toast);
 const [profiles,setProfiles]=useState<YoutubeProfile[]>([]),[healthMap,setHealthMap]=useState<Record<string,YoutubeProfileHealth>>({}),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState<string>('');
 useEffect(()=>{api.youtubeProfiles().then(async p=>{setProfiles(p);const next:Record<string,YoutubeProfileHealth>={};for(const x of p){try{next[x.id]=await api.youtubeProfileHealth(x.id)}catch(e){next[x.id]={ok:false,status:'RECONNECT_REQUIRED',error:String(e)}}}setHealthMap(next)}).catch(()=>{})},[]);
 async function refresh(c:Channel){if(!c.youtubeProfileId){toast('Сначала подключи YouTube OAuth');return}setBusy(c.id);try{const a=await refreshChannelAnalytics(c.id,90,true);updateChannel(c.id,{analytics:a});toast(`${c.name}: данные обновлены`)}catch(e){toast(String(e))}finally{setBusy('')}}
 useEffect(()=>{const pending=channels.filter(c=>c.youtubeProfileId&&(!c.analytics||Date.now()-Date.parse(c.analytics.updatedAt||'')>Math.max(5,useApp.getState().settings.youtubeIntelligenceRefreshMin)*60_000));if(!pending.length)return;let live=true;void (async()=>{for(const c of pending){if(!live)break;try{const a=await refreshChannelAnalytics(c.id,90,false);useApp.getState().updateChannel(c.id,{analytics:a})}catch(e){useApp.getState().log(`${c.name}: ${String(e)}`,'warn')}}})();return()=>{live=false}},[channels.map(c=>`${c.id}:${c.youtubeProfileId||''}`).join('|')]);
 return <>
  <div className="pageHeader"><div><small>CHANNEL NETWORK</small><h1>Каналы</h1><p>Один канал — одна строка. Публичные данные берутся из YouTube Data API, приватные — только из авторизованной Analytics API.</p></div><div className="headerActions"><button className="primary" onClick={()=>{const c=addChannel({name:`Канал ${channels.length+1}`});setEditing(c.id)}}>+ Добавить канал</button></div></div>
  {channels.length===0?<div className="empty"><b>Каналов пока нет</b><p>Добавь первый канал или подключи YouTube в Настройки → YouTube.</p></div>:<div className="channelOSList">{channels.map(c=>{const a=c.analytics,o=c.youtubeProfileId?healthMap[c.youtubeProfileId]:undefined,b=bufferDays(c,jobs),h=health(c,jobs,o),v7=sumLast(c,7,'views'),v28=sumLast(c,28,'views'),v90=sumLast(c,90,'views'),r28=sumLast(c,28,'estimatedRevenue'),rp=rpm(r28,v28),scheduled=jobs.filter(j=>j.channelId===c.id&&j.status==='SCHEDULED').length;return <article className={`channelOSCard ${editing===c.id?'editing':''}`} key={c.id}>
   <header><div className="channelAvatarOS">{a?.channelThumbnail?<img src={a.channelThumbnail} loading="lazy"/>:c.name.slice(0,2).toUpperCase()}</div><span className="channelIdentity"><b>{c.name}</b><small>{c.youtubeChannelId||'Channel ID —'}</small><em className={o?.ok?'good':c.youtubeProfileId?'warn':'bad'}>{o?.ok?'Google / OAuth ✓':c.youtubeProfileId?'OAuth требует проверки':'YouTube не подключён'}</em></span><span className="channelAge"><small>Создан</small><b>{a?.channelPublishedAt?new Date(a.channelPublishedAt).toLocaleDateString('ru-RU'):'—'}</b><small>Возраст</small><b>{age(a?.channelPublishedAt)}</b></span><span className="channelHealth"><small>HEALTH</small><b>{h}</b><em>Reserve {b} days</em></span><button onClick={()=>setEditing(editing===c.id?null:c.id)}>✎</button></header>
   <div className="channelMetaLine"><span>Страна <b>{a?.channelCountry||c.country||'—'}</b></span><span>Язык <b>{a?.channelLanguage||c.language||'—'}</b></span><span>Public Videos <b>{c.stats?.videos!=null?formatNumber(c.stats.videos):'—'}</b></span><span>Scheduled <b>{scheduled}</b></span><span>Total Videos <b>{a?.totalVideos!=null?formatNumber(a.totalVideos):'—'}</b></span><span>Last Analytics Sync <b>{a?.updatedAt?new Date(a.updatedAt).toLocaleString('ru-RU'):'—'}</b></span></div>
   <div className="channelMetricsGrid"><span><small>Subscribers</small><b>{c.stats?.subscribers!=null?formatNumber(c.stats.subscribers):'—'}</b></span><span><small>Total Views</small><b>{c.stats?.views!=null?formatNumber(c.stats.views):'—'}</b></span><span><small>Views today</small><b>{a?.daily?.length?formatNumber(a.daily.at(-1)?.views):'—'}</b></span><span><small>Views 7d</small><b>{v7!=null?formatNumber(v7):'—'}</b></span><span><small>Views 28d</small><b>{v28!=null?formatNumber(v28):'—'}</b></span><span><small>Views 90d</small><b>{v90!=null?formatNumber(v90):'—'}</b></span><span><small>Watch time</small><b>{a?`${num(a.watchMinutes/60,1)} ч`:'—'}</b></span><span><small>Avg duration</small><b>{dur(a?.averageViewDuration)}</b></span><span><small>Avg %</small><b>{a?.averageViewPercentage!=null?`${num(a.averageViewPercentage,1)}%`:'—'}</b></span><span><small>Subs gained</small><b>{a?`+${num(a.subscribersGained)}`:'—'}</b></span><span><small>Subs lost</small><b>{a?`−${num(a.subscribersLost)}`:'—'}</b></span><span><small>Likes</small><b>{a?num(a.likes):'—'}</b></span><span><small>Comments</small><b>{a?num(a.comments):'—'}</b></span><span><small>Shares</small><b>{a?num(a.shares):'—'}</b></span><span><small>Revenue 28d</small><b>{money(r28)}</b></span><span><small>RPM 28d</small><b>{rp==null?'—':`$${rp.toFixed(2)}`}</b></span></div>
   <div className="channelActions"><button disabled={busy===c.id||!c.youtubeProfileId} onClick={()=>refresh(c)}>{busy===c.id?'Обновляю…':'↻ Обновить 90 дней'}</button><button onClick={()=>setEditing(editing===c.id?null:c.id)}>{editing===c.id?'Закрыть настройки':'Настроить канал'}</button></div>
   {editing===c.id&&<div className="editGrid channelEdit"><label>Название<input value={c.name} onChange={e=>updateChannel(c.id,{name:e.target.value})}/></label><label>Жанр<input value={c.genre} onChange={e=>updateChannel(c.id,{genre:e.target.value})}/></label><label>Язык<input value={c.language} onChange={e=>updateChannel(c.id,{language:e.target.value})}/></label><label>Страна<input value={c.country} onChange={e=>updateChannel(c.id,{country:e.target.value})}/></label><label>Раз в N дней<input type="number" min="1" max="30" value={c.cadenceDays} onChange={e=>updateChannel(c.id,{cadenceDays:+e.target.value||1})}/></label><label>Запас, дней<input type="number" min="7" max="365" value={c.targetBufferDays} onChange={e=>updateChannel(c.id,{targetBufferDays:+e.target.value||60})}/></label><label>YouTube OAuth<select value={c.youtubeProfileId||''} onChange={e=>{const p=profiles.find(x=>x.id===e.target.value);updateChannel(c.id,{youtubeProfileId:e.target.value||undefined,youtubeChannelId:p?.channelId})}}><option value="">— не привязан —</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.channelTitle||p.channelId||p.id}</option>)}</select></label><label>Время публикации<input type="time" value={`${String(c.publishHour).padStart(2,'0')}:${String(c.publishMinute).padStart(2,'0')}`} onChange={e=>{const [hh,mm]=e.target.value.split(':').map(Number);updateChannel(c.id,{publishHour:hh,publishMinute:mm})}}/></label><label className="wide">Формулы названий<textarea value={c.seo.titlePatterns.join('\n')} onChange={e=>updateChannel(c.id,{seo:{...c.seo,titlePatterns:e.target.value.split('\n').filter(Boolean)}})}/></label><label className="wide">Шаблон описания<textarea value={c.seo.descriptionTemplate} onChange={e=>updateChannel(c.id,{seo:{...c.seo,descriptionTemplate:e.target.value}})}/></label><label className="wide">Теги<input value={c.seo.tags.join(', ')} onChange={e=>updateChannel(c.id,{seo:{...c.seo,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)}})}/></label><div className="editActions"><button className="danger" onClick={()=>{if(confirm(`Удалить ${c.name}? Файлы на диске останутся.`)){removeChannel(c.id);setEditing(null)}}}>Удалить из VYRON</button><button className="primary" onClick={()=>setEditing(null)}>Готово</button></div></div>}
  </article>})}</div>}
 </>;
}
