import React,{useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {formatNumber} from './core';
import {useApp} from './store';
import {discoverCompetitorsForChannel,refreshCompetitor} from './youtubeIntelligence';
import type {Competitor,CompetitorSnapshot} from './types';

const miniDate=(x?:string)=>x?new Date(x).toLocaleDateString('ru-RU',{day:'2-digit',month:'short',year:'2-digit'}):'—';
const velocity=(c:Competitor,key:'views'|'subscribers')=>{const h=c.history||[];if(h.length<2)return undefined;const a=h[h.length-2],b=h[h.length-1],days=Math.max(.01,(new Date(b.at).getTime()-new Date(a.at).getTime())/86400000);return (Number(b[key]||0)-Number(a[key]||0))/days};
const periodGrowth=(c:Competitor,days:number,key:'views'|'subscribers')=>{const h=c.history||[];if(h.length<2)return undefined;const last=h[h.length-1],target=Date.parse(last.at)-days*86400000;let base:CompetitorSnapshot|undefined;for(const x of h){if(Date.parse(x.at)<=target)base=x;else break}if(!base)base=h[0];return Number(last[key]||0)-Number(base[key]||0)};
const uploadFrequency=(c:Competitor)=>{const dates=(c.latestVideos||[]).map(v=>Date.parse(v.publishedAt||'')).filter(Number.isFinite).sort((a,b)=>b-a);if(dates.length<2)return '—';const gaps=dates.slice(0,-1).map((d,i)=>(d-dates[i+1])/86400000);const avg=gaps.reduce((s,x)=>s+x,0)/gaps.length;return avg<1?`${Math.max(1,Math.round(1/Math.max(.05,avg)))} / день`:`раз в ${avg.toFixed(avg<3?1:0)} дн.`};
const signed=(v?:number,suffix='/д')=>v==null?'—':`${v>0?'+':''}${Math.round(v).toLocaleString('ru-RU')}${suffix}`;
const money=(v:number)=>`$${Math.max(0,v).toLocaleString('en-US',{maximumFractionDigits:0})}`;
const median=(xs:number[])=>{const a=[...xs].sort((x,y)=>x-y);return a.length?a[Math.floor(a.length/2)]:0};

export function CompetitorsPage(){
 const channels=useApp(s=>s.channels),competitors=useApp(s=>s.competitors),add=useApp(s=>s.addCompetitor),remove=useApp(s=>s.removeCompetitor),toast=useApp(s=>s.toast),settings=useApp(s=>s.settings);const [channelId,setChannelId]=useState(channels[0]?.id||''),[url,setUrl]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState<string>(''),[discovering,setDiscovering]=useState(false);const list=competitors.filter(c=>!channelId||c.channelId===channelId),own=channels.find(c=>c.id===channelId);
 async function refresh(c:Competitor){setBusy(c.id);try{await refreshCompetitor(c.id,true);toast(`${c.name}: snapshot обновлён`)}catch(e){toast(String(e))}finally{setBusy('')}}
 async function refreshAll(){setBusy('all');let ok=0;try{for(const c of list){try{await refreshCompetitor(c.id,true);ok++}catch(e){useApp.getState().log(`${c.name}: ${String(e)}`,'warn')}}toast(`Конкуренты: обновлено ${ok}/${list.length}`)}finally{setBusy('')}}
 async function discover(){if(!own?.youtubeProfileId){toast('Сначала подключи YouTube OAuth к своему каналу');return}setDiscovering(true);try{const added=await discoverCompetitorsForChannel(own.id,true);toast(added?`Найдено новых конкурентов: ${added}`:'Новых конкурентов не найдено; существующий пул сохранён')}catch(e){toast(String(e))}finally{setDiscovering(false)}}
 useEffect(()=>{if(!own?.youtubeProfileId)return;void discoverCompetitorsForChannel(own.id,false).catch(()=>{})},[channelId,own?.youtubeProfileId]);
 const ownViews=own?.analytics?.periodDays===28?own.analytics.views:0;const comp28=list.map(c=>periodGrowth(c,28,'views')).filter((x):x is number=>x!=null&&x>=0);const med=median(comp28);const gap=Math.max(0,med-ownViews);const leaders=useMemo(()=>[...list].sort((a,b)=>(velocity(b,'views')||0)-(velocity(a,'views')||0)).slice(0,3),[list]);
 return <>
  <div className="pageHeader"><div><small>COMPETITOR RADAR</small><h1>Конкуренты</h1><p>Живые публичные snapshots, история роста и понятная цель. Чужие private Analytics недоступны, поэтому доход всегда помечается как расчётная оценка.</p></div><div className="headerActions"><select value={channelId} onChange={e=>setChannelId(e.target.value)}>{channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="primary compactAction" disabled={discovering||!own?.youtubeProfileId} onClick={discover}>{discovering?'Ищу…':'✦ Обновить пул'}</button><button disabled={!list.length||!!busy} onClick={refreshAll}>↻ Snapshots</button></div></div>
  <section className="competitorMotivation panel"><div><small>ТВОЯ ПОЗИЦИЯ • 28 ДНЕЙ</small><h3>{own?.name||'Канал'}</h3><strong>{ownViews?formatNumber(ownViews):'—'} views</strong></div><div><small>МЕДИАНА КОНКУРЕНТОВ</small><strong>{med?formatNumber(med):'—'}</strong><span>{gap?`До медианы: +${formatNumber(gap)} views`:'Ты не ниже медианы по доступной истории'}</span></div><div><small>РАСЧЁТ ДОХОДА ПРИ МЕДИАНЕ</small><strong>{med?`${money(med/1000*settings.competitorRpmLow)}–${money(med/1000*settings.competitorRpmHigh)}`:'—'}</strong><span>ОЦЕНКА • RPM ${settings.competitorRpmLow.toFixed(1)}–${settings.competitorRpmHigh.toFixed(1)}</span></div></section>
  <section className="panel competitorDiscovery"><div><small>AUTO DISCOVERY • DAILY + ROTATING SNAPSHOTS</small><h3>Пул до {settings.competitorPoolSize} каналов</h3><p>Discovery обновляется ежедневно. Фоновый scheduler ротирует старейшие snapshots, чтобы не сжигать YouTube quota одним огромным запросом.</p></div><span className="similarityBadge">PUBLIC DATA</span></section>
  {leaders.length>0&&<section className="panel competitorPulse"><div className="panelHead"><div><small>COMPETITOR PULSE</small><h3>Кто ускоряется сейчас</h3></div></div>{leaders.map(c=><div key={c.id}><b>{c.name}</b><span>{signed(velocity(c,'views'))} views • {signed(velocity(c,'subscribers'))} subs</span></div>)}</section>}
  <details className="panel advancedPanel"><summary>Добавить конкурента вручную</summary><div className="competitorAdd"><input placeholder="Название" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="YouTube /channel/UC… или /@handle" value={url} onChange={e=>setUrl(e.target.value)}/><button disabled={!channelId||!name||!url} onClick={()=>{add({id:crypto.randomUUID(),channelId,name,url,history:[],source:'manual'});setName('');setUrl('')}}>Добавить</button></div></details>
  {!own?.youtubeProfileId&&<div className="errorBox">У выбранного собственного канала не подключён OAuth.</div>}
  {list.length===0?<div className="empty"><b>Пул конкурентов пуст</b><p>Нажми «Обновить пул». Дальше VYRON будет поддерживать его автоматически.</p></div>:<div className="competitorOSList">{list.map(c=>{const vv=velocity(c,'views'),sv=velocity(c,'subscribers'),g7=periodGrowth(c,7,'views'),g28=periodGrowth(c,28,'views'),views28=g28??(vv!=null?Math.max(0,vv*28):undefined),low=views28==null?undefined:views28/1000*settings.competitorRpmLow,high=views28==null?undefined:views28/1000*settings.competitorRpmHigh;return <article className="competitorOSCard" key={c.id}><header>{c.thumbnail?<img src={c.thumbnail} loading="lazy"/>:<i className="compAvatar">YT</i>}<span><b>{c.name}</b><small>{c.youtubeChannelId||c.url}</small>{c.similarity!=null&&<em className="similarityBadge">Similarity {c.similarity}%</em>}</span><button className="danger mini" onClick={()=>remove(c.id)}>×</button></header><div className="competitorMetrics"><span><small>Subscribers</small><b>{c.subscribers==null?'—':formatNumber(c.subscribers)}</b></span><span><small>Total Views</small><b>{c.views==null?'—':formatNumber(c.views)}</b></span><span><small>Views / day</small><b>{signed(vv)}</b></span><span><small>Subs / day</small><b>{signed(sv)}</b></span><span><small>Growth 7d</small><b>{g7==null?'—':signed(g7,'')}</b></span><span><small>Growth 28d</small><b>{g28==null?'—':signed(g28,'')}</b></span><span><small>Recent Avg Views</small><b>{c.recentAverageViews==null?'—':formatNumber(c.recentAverageViews)}</b></span><span><small>Upload frequency</small><b>{uploadFrequency(c)}</b></span><span><small>Last upload</small><b>{miniDate(c.lastVideoAt)}</b></span><span className="estimateMetric"><small>Доход 28d • ОЦЕНКА</small><b>{low==null||high==null?'—':`${money(low)}–${money(high)}`}</b></span><span><small>Last snapshot</small><b>{c.updatedAt?new Date(c.updatedAt).toLocaleString('ru-RU'):'ожидает'}</b></span></div>{c.latestVideos?.length?<div className="competitorVideos os">{c.latestVideos.slice(0,5).map(v=><button key={v.id} onClick={()=>api.openWeb(`https://youtube.com/watch?v=${v.id}`)}>{v.thumbnail?<img src={v.thumbnail} loading="lazy"/>:<i/>}<span><b>{v.title}</b><small>{formatNumber(v.views)} views • {miniDate(v.publishedAt)}</small></span></button>)}</div>:<div className="competitorPlaceholder">Ожидает первого snapshot</div>}<footer><small>Доход — модельная оценка по публичным views и RPM диапазону; это не данные чужого YouTube Studio.</small><div><button onClick={()=>api.openWeb(c.url)}>YouTube</button><button className="primary small" disabled={busy===c.id||busy==='all'} onClick={()=>refresh(c)}>{busy===c.id?'…':'↻ Обновить'}</button></div></footer></article>})}</div>}
 </>
}
