import React from 'react';
import {useApp} from './store';
import {formatNumber} from './core';
import type {Competitor} from './types';

const money=(v?:number)=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
const velocity=(c:Competitor)=>{const h=c.history||[];if(h.length<2)return undefined;const a=h[h.length-2],b=h[h.length-1],days=Math.max(.01,(Date.parse(b.at)-Date.parse(a.at))/86400000);return (b.views-a.views)/days};
const rel=(iso?:string)=>{if(!iso)return '—';const m=Math.max(0,Math.round((Date.now()-Date.parse(iso))/60000));return m<60?`${m} мин назад`:m<1440?`${Math.round(m/60)} ч назад`:`${Math.round(m/1440)} дн назад`};

export function DashboardOS(){
 const channels=useApp(s=>s.channels),jobs=useApp(s=>s.jobs),competitors=useApp(s=>s.competitors),settings=useApp(s=>s.settings),setPage=useApp(s=>s.setPage),logs=useApp(s=>s.logs);const enabled=channels.filter(c=>c.enabled),errors=jobs.filter(j=>j.status==='ERROR'),needImage=jobs.filter(j=>j.status==='NEED_IMAGE'),needMusic=jobs.filter(j=>j.status==='WAITING_MUSIC');const analytics=enabled.map(c=>c.analytics).filter(Boolean);const todayViews=analytics.reduce((n,a)=>n+(a?.daily?.at(-1)?.views||0),0);const rev28=enabled.reduce((n,c)=>n+(c.analytics?.periodDays===28?Number(c.analytics.estimatedRevenue||0):0),0);const revenueKnown=enabled.some(c=>c.analytics?.periodDays===28&&c.analytics.estimatedRevenue!=null);const netSubs=enabled.reduce((n,c)=>n+(c.analytics?.periodDays===28?(c.analytics.subscribersGained-c.analytics.subscribersLost):0),0);const next=[...jobs].filter(j=>j.publishAt&&Date.parse(j.publishAt)>Date.now()).sort((a,b)=>Date.parse(a.publishAt!)-Date.parse(b.publishAt!)).slice(0,5);const issues=[...enabled.filter(c=>!c.youtubeProfileId).map(c=>({type:'OAuth',text:`${c.name}: YouTube не подключён`,page:'settings' as const})),...enabled.filter(c=>c.youtubeProfileId&&!c.analytics).map(c=>({type:'Analytics',text:`${c.name}: ждёт первую аналитику`,page:'analytics' as const})),...errors.slice(0,6).map(j=>({type:'Ошибка',text:`VIDEO_${String(j.number).padStart(3,'0')}: ${j.error||'ошибка производства'}`,page:'production' as const})),...(needImage.length?[{type:'Материалы',text:`${needImage.length} проектов ждут изображения`,page:'production' as const}]:[]),...(needMusic.length?[{type:'Материалы',text:`${needMusic.length} проектов ждут аудио`,page:'production' as const}]:[])].slice(0,10);const competitorPulse=[...competitors].map(c=>({c,v:velocity(c)})).filter(x=>x.v!=null).sort((a,b)=>(b.v||0)-(a.v||0)).slice(0,4);const systemOk=!errors.length&&enabled.every(c=>c.youtubeProfileId);
 return <>
  <div className="pageHeader morningHeader"><div><small>MORNING CONTROL CENTER</small><h1>{systemOk?'Система работает':'Есть действия, требующие внимания'}</h1><p>Один экран: каналы, публикации, производство, рост и конкуренты. Технический шум спрятан в Диагностике.</p></div><div className="headerActions"><button onClick={()=>setPage('production')}>Производство</button><button className="primary compactAction" onClick={()=>setPage('youtube')}>Открыть YouTube</button></div></div>
  <div className="morningMetrics"><span><small>VIEWS TODAY*</small><b>{analytics.length?formatNumber(todayViews):'—'}</b><em>*последняя доступная строка YouTube</em></span><span><small>REVENUE 28D</small><b>{revenueKnown?money(rev28):'—'}</b><em>{revenueKnown?'реальные monetary analytics':'нет monetary data'}</em></span><span><small>NET SUBS 28D</small><b>{analytics.length?`${netSubs>=0?'+':''}${formatNumber(netSubs)}`:'—'}</b><em>{enabled.length} каналов</em></span><span><small>NEXT PUBLISH</small><b>{next[0]?.publishAt?new Date(next[0].publishAt).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'}):'—'}</b><em>{next[0]?.publishAt?new Date(next[0].publishAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}):'нет в плане'}</em></span><span><small>AUTOPILOT</small><b>{settings.autopilotMode.toUpperCase()}</b><em>{settings.autopilotEnabled?'цикл активен':'ручной режим'}</em></span></div>
  <div className="morningGrid"><section className="panel morningAttention"><div className="panelHead"><div><small>ATTENTION INBOX</small><h3>{issues.length?`${issues.length} пунктов`:'Ничего срочного'}</h3></div></div>{issues.length?issues.map((x,i)=><button key={i} onClick={()=>setPage(x.page)}><i>!</i><span><small>{x.type}</small><b>{x.text}</b></span><em>→</em></button>):<div className="successBox">OAuth, очередь и основные проверки без критических ошибок.</div>}</section><section className="panel nextPublications"><div className="panelHead"><div><small>NEXT 5</small><h3>Ближайшие публикации</h3></div><button onClick={()=>setPage('youtube')}>Календарь</button></div>{next.length?next.map(j=>{const c=channels.find(x=>x.id===j.channelId);return <div key={j.id}><span><b>{c?.name||'Канал'} • VIDEO_{String(j.number).padStart(3,'0')}</b><small>{j.title||'без названия'}</small></span><em>{new Date(j.publishAt!).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</em></div>}):<p>Запланированных будущих публикаций нет.</p>}</section></div>
  <section className="panel channelPulse"><div className="panelHead"><div><small>CHANNEL PULSE</small><h3>Все каналы</h3></div><button onClick={()=>setPage('channels')}>Открыть каналы</button></div><div className="channelPulseRows">{enabled.map(c=>{const a=c.analytics,net=a?(a.subscribersGained-a.subscribersLost):undefined;return <button key={c.id} onClick={()=>setPage('analytics')}><span><b>{c.name}</b><small>{c.youtubeProfileId?'OAuth ✓':'OAuth —'} • sync {rel(a?.updatedAt)}</small></span><em><small>Views 28d</small><b>{a?.periodDays===28?formatNumber(a.views):'—'}</b></em><em><small>Revenue</small><b>{a?.periodDays===28?money(a.estimatedRevenue):'—'}</b></em><em><small>Net subs</small><b>{net==null?'—':`${net>=0?'+':''}${formatNumber(net)}`}</b></em></button>})}</div></section>
  <div className="morningGrid"><section className="panel competitorPulse"><div className="panelHead"><div><small>COMPETITOR PULSE</small><h3>Кто ускорился</h3></div><button onClick={()=>setPage('competitors')}>Radar</button></div>{competitorPulse.length?competitorPulse.map(({c,v})=><div key={c.id}><b>{c.name}</b><span>+{Math.max(0,Math.round(v||0)).toLocaleString('ru-RU')} views/д</span></div>):<p>Нужно минимум два snapshot конкурентов, чтобы увидеть скорость роста.</p>}</section><section className="panel autopilotActivity"><div className="panelHead"><div><small>AUTOPILOT ACTIVITY</small><h3>Последние действия</h3></div><button onClick={()=>setPage('settings')}>Настроить</button></div>{logs.length?logs.slice(0,6).map((l,i)=><div key={i}><small>{new Date(l.at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small><span>{l.message}</span></div>):<p>Автоматических действий пока нет.</p>}</section></div>
 </>
}
