import React,{useEffect,useMemo,useRef,useState} from 'react';
import * as mammoth from 'mammoth';
import {convertFileSrc} from '@tauri-apps/api/core';
import {api,type ExistingVideoSyncResult} from './api';
import {useApp} from './store';
import type {YoutubeExistingVideo} from './types';
import {countBuckets,existingBucket,latestPrivateIds,matchesExistingFilter,selectedVisibleIds,type ExistingFilter} from './youtubeWorkflow';
import {parseMetadataFile,validateSequentialMetadata,type ImportedMetadata} from './metadata';
import {buildExistingScheduleFromLocal,orderedExistingVideos,overlayExistingMetadata} from './youtubeExisting';
import {isYoutubeQuotaError,markYoutubeQuotaExceeded,youtubeQuotaMessage,youtubeQuotaState} from './youtubeQuota';
import {readExistingCache,writeExistingCache} from './channelSchedule';
import {sortChannelsAlphabetically} from './channelSort';

const local=(iso?:string)=>{if(!iso)return '';const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const short=(s:string,n=145)=>s.length>n?s.slice(0,n).trim()+'…':s;
const sameTags=(a:string[]=[],b:string[]=[])=>JSON.stringify(a)===JSON.stringify(b);
const same=(a?:string,b?:string)=>(a||'')===(b||'');


type ThumbState='loading'|'ok'|'error';
function VideoThumb({video,onState}:{video:YoutubeExistingVideo;onState:(id:string,s:ThumbState)=>void}){
 const remotes=[video.thumbnail,`https://i.ytimg.com/vi/${video.id}/hqdefault.jpg`,`https://i.ytimg.com/vi/${video.id}/mqdefault.jpg`,`https://i.ytimg.com/vi/${video.id}/default.jpg`].filter(Boolean) as string[];
 const [src,setSrc]=useState(''),[fallback,setFallback]=useState(0),[retry,setRetry]=useState(0),[failed,setFailed]=useState(false);
 useEffect(()=>{let live=true;setSrc('');setFallback(0);setFailed(false);onState(video.id,'loading');api.youtubeCacheThumbnail(video.id,video.thumbnail).then(p=>{if(live){setSrc(convertFileSrc(p));onState(video.id,'ok')}}).catch(()=>{if(live)setSrc(remotes[0]||'')});return()=>{live=false}},[video.id,video.thumbnail,retry]);
 if(failed)return <button className="thumbRetry" onClick={e=>{e.stopPropagation();setRetry(x=>x+1)}}>↻ Повторить</button>;
 if(!src)return <span className="thumbSkeleton">YT</span>;
 return <img className="vyronThumb" src={src} loading="lazy" onLoad={()=>onState(video.id,'ok')} onError={()=>{const n=fallback+1;if(remotes[n]){setFallback(n);setSrc(remotes[n]);return}setFailed(true);onState(video.id,'error')}}/>;
}

export function ExistingVideos(){
 const channels=useApp(s=>s.channels),toast=useApp(s=>s.toast);
 const [channelId,setChannelId]=useState(channels[0]?.id||''),[profileId,setProfileId]=useState(channels[0]?.youtubeProfileId||''),[videos,setVideos]=useState<YoutubeExistingVideo[]>([]),[baseline,setBaseline]=useState<Record<string,YoutubeExistingVideo>>({}),[lastUndo,setLastUndo]=useState<YoutubeExistingVideo[]>([]),[busy,setBusy]=useState(false),[limit,setLimit]=useState(1000),[order,setOrder]=useState<'oldest'|'newest'>('oldest'),[start,setStart]=useState(()=>{const d=new Date();d.setDate(d.getDate()+1);d.setHours(18,0,0,0);return local(d.toISOString())}),[cadence,setCadence]=useState(2),[meta,setMeta]=useState<ImportedMetadata[]>([]),[expanded,setExpanded]=useState<Set<string>>(new Set()),[filter,setFilter]=useState<ExistingFilter>('private'),[selectedOnly,setSelectedOnly]=useState(false),[sortMode,setSortMode]=useState<'dateAsc'|'dateDesc'|'youtubeOldest'|'youtubeNewest'|'privateFirst'>('dateAsc'),[syncInfo,setSyncInfo]=useState<ExistingVideoSyncResult|null>(null),[thumbs,setThumbs]=useState<Record<string,ThumbState>>({}),[confirm,setConfirm]=useState(false),[backupPath,setBackupPath]=useState('');
 const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{const c=channels.find(x=>x.id===channelId),cached=readExistingCache(channelId);setProfileId(c?.youtubeProfileId||'');if(c)setCadence(c.cadenceDays||2);setVideos(cached?.videos||[]);setBaseline(cached?.baseline||{});setLastUndo(cached?.lastUndo||[]);setSyncInfo(cached?.syncInfo||null);setThumbs({});setMeta([]);setSelectedOnly(false);},[channelId,channels.find(x=>x.id===channelId)?.youtubeProfileId]);

 useEffect(()=>{if(!channelId)return;const t=window.setTimeout(()=>writeExistingCache(channelId,{version:1,updatedAt:new Date().toISOString(),videos,baseline,lastUndo,syncInfo}),220);return()=>window.clearTimeout(t)},[channelId,videos,baseline,lastUndo,syncInfo]);
 async function sync(){if(!profileId){toast('Сначала привяжи YouTube OAuth к каналу');return}if(youtubeQuotaState().blocked){toast(youtubeQuotaMessage());return}setBusy(true);try{const selectedIds=new Set(videos.filter(v=>v.selected).map(v=>v.id));const r=await api.youtubeListExisting(profileId,limit);const next=(r.videos||[]).map((x:any)=>({...x,selected:selectedIds.has(x.id),applyState:'idle'}));setVideos(next);setBaseline(Object.fromEntries(next.map(v=>[v.id,{...v,tags:[...v.tags]}])));setLastUndo([]);setBackupPath('');setThumbs({});setSyncInfo(r);writeExistingCache(channelId,{version:1,updatedAt:new Date().toISOString(),videos:next,baseline:Object.fromEntries(next.map(v=>[v.id,{...v,tags:[...v.tags]}])),lastUndo:[],syncInfo:r});toast(`YouTube: получено ${r.received}/${Math.min(r.youtubeFound||r.received,r.requested||limit)} видео`)}catch(e){if(isYoutubeQuotaError(e)){markYoutubeQuotaExceeded(e);toast('⏸ YouTube quota: синхронизация поставлена на паузу')}else toast(String(e))}finally{setBusy(false)}}
 function schedule(){
  if(!start)return;
  const selectedNow=videos.filter(v=>v.selected);
  const targets=orderedExistingVideos(selectedNow.filter(v=>v.privacyStatus==='private'),order);
  if(!targets.length){toast('Для расписания выбери Private / Scheduled видео');return}
  if(targets.length!==selectedNow.length)toast(`Даты будут назначены только Private: ${targets.length} из ${selectedNow.length}`)
  const scheduled=buildExistingScheduleFromLocal(targets,start,cadence,meta);
  const byId=new Map(scheduled.map(v=>[v.id,v]));
  setVideos(prev=>prev.map(v=>byId.has(v.id)?{...v,publishAt:byId.get(v.id)!.publishAt}:v));
  const timed=meta.filter(x=>x.publishTime).length;
  toast(timed?`Даты расставлены: ${targets.length} • время взято из SEO pack`:`Даты расставлены: ${targets.length} видео`)
}
 async function read(files:FileList|null){
  if(!files?.length)return;
  const selectedNow=videos.filter(v=>v.selected);
  if(!selectedNow.length){toast('Сначала выбери видео для SEO pack');return}
  const rows:ImportedMetadata[]=[];
  let hasDocx=false;
  for(const f of Array.from(files)){
    const docx=f.name.toLowerCase().endsWith('.docx');
    hasDocx=hasDocx||docx;
    const text=docx?(await mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()})).value:await f.text();
    rows.push(...parseMetadataFile(f.name,text));
  }
  rows.sort((a,b)=>(a.number??Number.MAX_SAFE_INTEGER)-(b.number??Number.MAX_SAFE_INTEGER));
  if(hasDocx){
    const check=validateSequentialMetadata(rows,selectedNow.length);
    if(!check.ok){
      const details=[rows.length!==selectedNow.length?`в DOCX ${rows.length}, выбрано ${selectedNow.length}`:'',check.missing.length?`нет VIDEO ${check.missing.join(', ')}`:'',check.duplicates.length?`дубли VIDEO ${check.duplicates.join(', ')}`:''].filter(Boolean).join(' • ');
      toast(`SEO DOCX не применён: ${details}`);return
    }
    const incomplete=rows.filter(x=>!x.title||!x.description||!x.tags?.length);
    if(incomplete.length){toast(`SEO DOCX не применён: неполные блоки VIDEO ${incomplete.map(x=>x.number).join(', ')}`);return}
  }
  setMeta(rows);
  const firstTime=rows[0]?.publishTime;
  if(firstTime&&rows.every(x=>x.publishTime===firstTime))setStart(prev=>prev?`${prev.slice(0,10)}T${firstTime}`:prev);
  setVideos(prev=>{
    const targets=orderedExistingVideos(prev.filter(v=>v.selected),order);
    const overlaid=overlayExistingMetadata(targets,rows);
    const byId=new Map(overlaid.map(v=>[v.id,v]));
    return prev.map(v=>byId.has(v.id)?{...byId.get(v.id)!,selected:true}:v)
  });
  const zone=rows.find(x=>x.publishTime)?.publishTimezone;
  toast(hasDocx?`✓ SEO DOCX: ${rows.length}/${selectedNow.length} видео заполнено автоматически${firstTime?` • ${firstTime}${zone?` ${zone}`:''}`:''}`:`Метаданные применены: ${Math.min(rows.length,selectedNow.length)} из ${selectedNow.length}`)
}
 const selected=useMemo(()=>videos.filter(v=>v.selected),[videos]);
 const buckets=useMemo(()=>countBuckets(videos),[videos]);
 const selectNone=()=>setVideos(x=>x.map(v=>({...v,selected:false})));
 const selectLatestPrivate=(count:number)=>setVideos(x=>{const ids=latestPrivateIds(x,count);return x.map(v=>({...v,selected:ids.has(v.id)}))});
 const selectVisible=()=>setVideos(x=>{const ids=selectedVisibleIds(x,filter);return x.map(v=>({...v,selected:ids.has(v.id)}))});
 const toggleSelected=(id:string)=>setVideos(x=>x.map(v=>v.id===id?{...v,selected:!v.selected}:v));
 const changes=useMemo(()=>selected.reduce((a,v)=>{const b=baseline[v.id];if(!b)return a;if(!same(v.title,b.title))a.title++;if(!same(v.description,b.description))a.description++;if(!sameTags(v.tags,b.tags))a.tags++;if(!same(v.publishAt,b.publishAt))a.date++;if(!same(v.privacyStatus,b.privacyStatus))a.privacy++;if(v.privacyStatus==='public')a.public++;return a},{title:0,description:0,tags:0,date:0,privacy:0,public:0}),[selected,baseline]);
 async function apply(){setConfirm(false);if(!selected.length||!profileId)return;if(youtubeQuotaState().blocked){toast(youtubeQuotaMessage());return}const backup=selected.map(v=>baseline[v.id]).filter(Boolean).map(v=>({...v,tags:[...v.tags]}));setBusy(true);let ok=0;const verifiedIds=new Set<string>();try{const saved=await api.youtubeBackupExisting(profileId,backup);setBackupPath(saved.path||'');for(let i=0;i<selected.length;i++){const v=selected[i];setVideos(x=>x.map(z=>z.id===v.id?{...z,applyState:'saving',error:undefined}:z));try{const result=await api.youtubeUpdateExisting(profileId,v.id,v.title,v.description,v.tags,v.publishAt,v.privacyStatus);if(result?.metadataAccepted===false)throw new Error(`YouTube не принял metadata ${v.id}`);if(result.scheduleRequested&&result.scheduleAccepted===false){const err=result.scheduleError||'расписание не принято';if(isYoutubeQuotaError(err)){markYoutubeQuotaExceeded(err);const pendingIds=new Set(selected.slice(i).map(x=>x.id));setVideos(x=>x.map(z=>({...z,selected:pendingIds.has(z.id),applyState:z.id===v.id?'error':z.applyState,error:z.id===v.id?youtubeQuotaMessage():z.error})));toast(`⏸ Квота закончилась. Осталось ${pendingIds.size}; выбор сохранён.`);break}setVideos(x=>x.map(z=>z.id===v.id?{...z,applyState:'error',verified:false,error:`${v.id}: метаданные сохранены; расписание: ${err}`}:z));ok++;verifiedIds.add(v.id);continue}ok++;verifiedIds.add(v.id);setVideos(x=>x.map(z=>z.id===v.id?{...z,applyState:'done',verified:true,error:result.metadataVerifyPending||result.scheduleVerifyPending?'YouTube принял запись; контрольное чтение ещё догоняет':undefined}:z))}catch(e){if(isYoutubeQuotaError(e)){markYoutubeQuotaExceeded(e);const pendingIds=new Set(selected.slice(i).map(x=>x.id));setVideos(x=>x.map(z=>({...z,selected:pendingIds.has(z.id),applyState:z.id===v.id?'error':z.applyState,error:z.id===v.id?youtubeQuotaMessage():z.error})));toast(`⏸ Квота закончилась. Осталось ${pendingIds.size}; выбор сохранён.`);break}setVideos(x=>x.map(z=>z.id===v.id?{...z,applyState:'error',verified:false,error:`${v.id}: ${String(e)}`}:z))}}if(ok){setLastUndo(backup.filter(v=>verifiedIds.has(v.id)));setBaseline(prev=>{const n={...prev};for(const v of selected.filter(x=>verifiedIds.has(x.id)))n[v.id]={...v,tags:[...v.tags]};return n})}if(!youtubeQuotaState().blocked)toast(ok===selected.length?`✓ ${ok} видео приняты YouTube`:`YouTube принял ${ok}/${selected.length}`)}catch(e){if(isYoutubeQuotaError(e)){markYoutubeQuotaExceeded(e);toast('⏸ YouTube quota: пачка сохранена для продолжения')}else toast(`Backup/Update: ${String(e)}`)}finally{setBusy(false)}}
 async function undo(){if(!lastUndo.length||!profileId)return;setBusy(true);let ok=0;try{for(const v of lastUndo){try{const r=await api.youtubeUpdateExisting(profileId,v.id,v.title,v.description,v.tags,v.publishAt,v.privacyStatus);if(r?.verified)ok++}catch(e){toast(`Undo ${v.id}: ${String(e)}`)}}toast(`↶ YouTube подтвердил откат ${ok}/${lastUndo.length}`);if(ok===lastUndo.length)setLastUndo([]);await sync()}finally{setBusy(false)}}
 const displayDate=(v:YoutubeExistingVideo)=>v.publishAt||v.publishedAt||'';const timeOf=(v:YoutubeExistingVideo)=>{const t=Date.parse(displayDate(v));return Number.isFinite(t)?t:Number.POSITIVE_INFINITY};const youtubeTime=(v:YoutubeExistingVideo)=>{const t=Date.parse(v.publishedAt||v.publishAt||'');return Number.isFinite(t)?t:Number.POSITIVE_INFINITY};
 const shown=[...videos.filter(v=>matchesExistingFilter(v,filter)&&(!selectedOnly||v.selected))].sort((a,b)=>{if(sortMode==='dateAsc')return timeOf(a)-timeOf(b);if(sortMode==='dateDesc'){const ta=timeOf(a),tb=timeOf(b);if(!Number.isFinite(ta)&&!Number.isFinite(tb))return 0;if(!Number.isFinite(ta))return 1;if(!Number.isFinite(tb))return -1;return tb-ta}if(sortMode==='youtubeOldest')return youtubeTime(a)-youtubeTime(b);if(sortMode==='youtubeNewest'){const ta=youtubeTime(a),tb=youtubeTime(b);if(!Number.isFinite(ta)&&!Number.isFinite(tb))return 0;if(!Number.isFinite(ta))return 1;if(!Number.isFinite(tb))return -1;return tb-ta}return existingBucket(a).localeCompare(existingBucket(b))||timeOf(a)-timeOf(b)});
 const dateCounts=shown.reduce<Record<string,number>>((acc,v)=>{const k=v.publishAt||'';if(k)acc[k]=(acc[k]||0)+1;return acc},{});const toggle=(id:string)=>setExpanded(x=>{const n=new Set(x);n.has(id)?n.delete(id):n.add(id);return n});
 const thumbOk=Object.values(thumbs).filter(x=>x==='ok').length,thumbError=Object.values(thumbs).filter(x=>x==='error').length;
 const expected=syncInfo?Math.min(syncInfo.youtubeFound||syncInfo.received,syncInfo.requested||limit):0;const mismatch=Boolean(syncInfo&&(!syncInfo.complete||syncInfo.received!==expected));
 const selectedOrdered=orderedExistingVideos(selected,order);
 const mapping=meta.map((row,i)=>({row,video:selectedOrdered[i]}));
 return <>
  <div className="pageHeader"><div><small>EXISTING VIDEOS MANAGER</small><h1>Загруженные</h1><p>Синхронизация идёт через uploads playlist с pagination. Изменение считается успешным только после повторного чтения YouTube.</p></div><div className="headerActions"><button disabled={busy} onClick={sync}>{busy?'Работаю…':'↻ Синхронизировать'}</button><button className="primary" disabled={busy||!selected.length||mismatch} onClick={()=>setConfirm(true)}>ОТПРАВИТЬ В YOUTUBE • {selected.length}</button></div></div>
  {syncInfo&&<div className={`syncAudit ${mismatch?'warn':''}`}><span>YouTube найдено <b>{syncInfo.youtubeFound}</b></span><span>Получено VYRON <b>{syncInfo.received}</b></span><span>Private <b>{syncInfo.privateCount}</b></span><span>Scheduled <b>{syncInfo.scheduledCount}</b></span><span>Public <b>{syncInfo.publicCount}</b></span><span>Unlisted <b>{syncInfo.unlistedCount||0}</b></span><span>Изображения <b>{thumbOk}/{videos.length}</b></span>{thumbError>0&&<span className="warn">{thumbError} ожидают retry</span>}{syncInfo.youtubeFound>limit&&<span>Лимит: {limit} из {syncInfo.youtubeFound}</span>}{mismatch&&<strong>⚠ Синхронизация неполная</strong>}</div>}
  {lastUndo.length>0&&<div className="undoBar"><span><b>✓ Последняя пачка подтверждена YouTube</b> • backup {lastUndo.length} видео{backupPath&&<small> • {backupPath}</small>}</span><button disabled={busy} onClick={undo}>↶ ОТМЕНИТЬ</button></div>}
  <input ref={file} hidden type="file" multiple accept=".docx,.json,.txt,.csv" onChange={e=>{void read(e.target.files);e.currentTarget.value=''}}/>
  <div className="existingToolbar"><label>Канал<select value={channelId} onChange={e=>setChannelId(e.target.value)}>{sortChannelsAlphabetically(channels).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className={`profileAutoBadge ${profileId?'good':'warn'}`}><small>OAuth</small><b>{profileId?'✓ выбран автоматически':'не подключён'}</b></div><label>Видео<select value={limit} onChange={e=>setLimit(+e.target.value)}><option>30</option><option>50</option><option>100</option><option>200</option><option>500</option><option>1000</option><option>5000</option></select></label><label>SEO порядок<select value={order} onChange={e=>setOrder(e.target.value as any)}><option value="oldest">старые → новые</option><option value="newest">новые → старые</option></select></label><label>Сортировка<select value={sortMode} onChange={e=>setSortMode(e.target.value as any)}><option value="dateAsc">дата ↑</option><option value="dateDesc">дата ↓</option><option value="youtubeOldest">YouTube: старые → новые</option><option value="youtubeNewest">YouTube: новые → старые</option><option value="privateFirst">сначала Private</option></select></label><label>Первая дата<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Каждые N дней<input type="number" min="1" max="30" value={cadence} onChange={e=>setCadence(+e.target.value||1)}/></label><button disabled={!selected.length} onClick={schedule}>Расставить даты • {selected.length}</button><button disabled={!selected.length} onClick={()=>file.current?.click()}>⬆ Загрузить SEO DOCX • {selected.length}</button></div>
  {videos.length>0&&<div className="existingQuick stickyBatch"><div className="periodTabs"><button className={filter==='private'?'active':''} onClick={()=>setFilter('private')}>PRIVATE {buckets.private}</button><button className={filter==='scheduled'?'active':''} onClick={()=>setFilter('scheduled')}>SCHEDULED {buckets.scheduled}</button><button className={filter==='public'?'active':''} onClick={()=>setFilter('public')}>PUBLIC {buckets.public}</button><button className={filter==='unlisted'?'active':''} onClick={()=>setFilter('unlisted')}>UNLISTED {buckets.unlisted}</button><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>ВСЕ {videos.length}</button></div><div className="batchScopeActions"><span className="selectionCount">Выбрано <b>{selected.length}</b></span><button onClick={selectVisible}>Выбрать все здесь</button><button onClick={()=>selectLatestPrivate(30)}>Последние 30 Private</button><button onClick={()=>setSelectedOnly(x=>!x)}>{selectedOnly?'Показать все':'Только выбранные'}</button><button onClick={selectNone}>Снять всё</button></div></div>}
  {videos.length>0&&<div className="publisherNotice selectionNotice"><b>Область изменений: {selected.length?`${selected.length} выбранных видео`:'ничего не выбрано'}</b><p>Название, описание, теги, даты и отправка в YouTube применяются только к отмеченным роликам. Для всей приватной библиотеки используй «Все Private», для свежей партии — «Последние 30 Private».</p></div>}
  {meta.length>0&&<div className="publisherNotice seoMappingNotice"><b>SEO Pack • {meta.length} видео • сопоставление 1:1</b><p>Название, описание и теги подставлены только выбранным роликам. {meta.some(x=>x.publishTime)&&<>Время: <b>{meta[0]?.publishTime} {meta[0]?.publishTimezone||''}</b>.</>}</p><div className="seoMapRows">{mapping.slice(0,40).map((m,i)=><span key={i}><b>VIDEO {m.row.number||i+1}</b><em>→</em><small>{m.video?`${m.video.title} • ${m.video.id}`:'НЕ СОПОСТАВЛЕНО'}</small></span>)}</div></div>}
  {videos.length===0?<div className="empty"><b>Видео ещё не синхронизированы</b><p>Выбери канал и нажми «Синхронизировать».</p></div>:<div className="existingList compact">{shown.map((v,i)=>{const open=expanded.has(v.id);return <article className={`existingCard compact ${open?'open':''} ${v.selected?'selected':''} ${v.applyState||''} ${v.publishAt&&dateCounts[v.publishAt]>1?'dateConflictCard':''}`} key={v.id} onClick={e=>{if((e.target as HTMLElement).closest('button,input,select,textarea,label,a'))return;toggleSelected(v.id)}}><label className="existingCheckHit" onClick={e=>e.stopPropagation()}><input className="existingCheck" type="checkbox" checked={v.selected} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,selected:e.target.checked}:z))}/><i/></label><button className="existingPreview" onClick={e=>{e.stopPropagation();toggleSelected(v.id)}}><VideoThumb video={v} onState={(id,s)=>setThumbs(x=>x[id]===s?x:{...x,[id]:s})}/><em>{v.privacyStatus}</em></button><div className="existingSummary"><small>#{i+1} • {v.id}</small><b>{v.title}</b><p>{short(v.description||'Описание отсутствует')}</p><div className="tagChips">{v.tags.slice(0,5).map(t=><i key={t}>{t}</i>)}{v.tags.length>5&&<i>+{v.tags.length-5}</i>}</div></div><div className="existingSchedule"><input type="datetime-local" value={local(v.publishAt)} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,publishAt:e.target.value?new Date(e.target.value).toISOString():undefined}:z))}/>{v.publishAt&&dateCounts[v.publishAt]>1&&<span className="dateConflict">⚠ Совпадает дата публикации</span>}<b className={v.applyState==='error'?'bad':v.applyState==='done'?'ok':''}>{v.applyState==='done'?'✓ Подтверждено YouTube':v.applyState==='saving'?'Отправляю + проверяю…':v.applyState==='error'?'⚠ Не подтверждено':'К изменению'}</b><button className="expandBtn" onClick={()=>toggle(v.id)}>{open?'Свернуть':'Редактировать'}</button></div>{open&&<div className="existingEditor"><label>Название<input value={v.title} maxLength={100} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,title:e.target.value}:z))}/></label><label>Описание<textarea value={v.description} maxLength={5000} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,description:e.target.value}:z))}/></label><label>Теги<input value={v.tags.join(', ')} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,tags:e.target.value.split(',').map(a=>a.trim()).filter(Boolean)}:z))}/></label><label>Privacy<select value={v.privacyStatus} onChange={e=>setVideos(x=>x.map(z=>z.id===v.id?{...z,privacyStatus:e.target.value}:z))}><option value="private">PRIVATE</option><option value="unlisted">UNLISTED</option><option value="public">PUBLIC</option></select></label>{v.error&&<div className="errorBox">{v.error}</div>}</div>}</article>})}</div>}
  {confirm&&<div className="modalBackdrop" onMouseDown={()=>setConfirm(false)}><section className="confirmModal" onMouseDown={e=>e.stopPropagation()}><small>YOUTUBE WRITE CONFIRMATION</small><h2>Будет изменено {selected.length} видео</h2><div className="confirmCounts"><span>Название <b>{changes.title}</b></span><span>Описание <b>{changes.description}</b></span><span>Теги <b>{changes.tags}</b></span><span>Дата <b>{changes.date}</b></span><span>Privacy <b>{changes.privacy}</b></span><span className={changes.public?'dangerText':''}>Public <b>{changes.public}</b></span></div><p>Перед записью VYRON сохранит локальный backup. После каждого videos.update будет выполнен videos.list и сравнение фактических данных YouTube.</p><footer><button onClick={()=>setConfirm(false)}>ОТМЕНА</button><button className="primary" disabled={busy||mismatch} onClick={apply}>ОТПРАВИТЬ {selected.length} В YOUTUBE</button></footer></section></div>}
 </>;
}
