use serde_json::{json,Value};

fn output_text(v:&Value)->Option<String>{v.get("output")?.as_array()?.iter().flat_map(|x|x.get("content").and_then(|c|c.as_array()).into_iter().flatten()).find_map(|c|if c.get("type").and_then(|x|x.as_str())==Some("output_text"){c.get("text").and_then(|x|x.as_str()).map(str::to_string)}else{None})}
fn clean_json(s:&str)->String{let t=s.trim();if t.starts_with("```"){let mut lines=t.lines();let _=lines.next();let mut body=lines.collect::<Vec<_>>().join("\n");if body.trim_end().ends_with("```"){let n=body.trim_end().len()-3;body=body.trim_end()[..n].trim_end().to_string()}body}else{t.to_string()}}

#[tauri::command]
pub async fn ai_generate_metadata(api_key:String,model:String,channel_name:String,genre:String,language:String,country:String,number:u32,publish_at:Option<String>,previous_titles:Vec<String>,custom_prompt:String)->Result<Value,String>{
 if api_key.trim().is_empty(){return Err("OpenAI API key не указан".into())}
 let model=if model.trim().is_empty(){"gpt-5.6-luna"}else{model.trim()};
 let prompt=format!("Ты SEO-редактор музыкального YouTube-канала. Верни ТОЛЬКО JSON без markdown: {{\"title\":\"...\",\"description\":\"...\",\"tags\":[\"...\"]}}. Title максимум 100 символов. Description естественный, без выдуманных фактов. До 30 релевантных tags без #. Не повторяй прошлые заголовки. Канал: {channel_name}. Жанр: {genre}. Язык контента: {language}. Страна/рынок: {country}. Номер будущего ролика: {number}. Плановая дата: {}. Прошлые заголовки: {}. Дополнительные правила канала: {}",publish_at.unwrap_or_default(),previous_titles.into_iter().take(30).collect::<Vec<_>>().join(" | "),custom_prompt);
 let body=json!({"model":model,"input":prompt,"max_output_tokens":1200});
 let r=reqwest::Client::new().post("https://api.openai.com/v1/responses").bearer_auth(api_key.trim()).json(&body).send().await.map_err(|e|format!("OpenAI сеть: {e}"))?;let status=r.status();let v:Value=r.json().await.map_err(|e|format!("OpenAI ответ: {e}"))?;if !status.is_success(){return Err(v.pointer("/error/message").and_then(|x|x.as_str()).unwrap_or("OpenAI API вернул ошибку").to_string())}let text=output_text(&v).ok_or_else(||"OpenAI не вернул текст метаданных".to_string())?;let parsed:Value=serde_json::from_str(&clean_json(&text)).map_err(|_|format!("OpenAI вернул невалидный JSON: {}",text.chars().take(240).collect::<String>()))?;let title=parsed.get("title").and_then(|x|x.as_str()).unwrap_or("").trim();if title.is_empty(){return Err("OpenAI вернул пустое название".into())}let description=parsed.get("description").and_then(|x|x.as_str()).unwrap_or("");let tags=parsed.get("tags").and_then(|x|x.as_array()).map(|a|a.iter().filter_map(|x|x.as_str()).map(str::trim).filter(|x|!x.is_empty()).take(30).collect::<Vec<_>>()).unwrap_or_default();Ok(json!({"title":title.chars().take(100).collect::<String>(),"description":description.chars().take(4800).collect::<String>(),"tags":tags}))
}
