import React,{useEffect,useMemo,useRef,useState} from 'react';
import * as mammoth from 'mammoth';
import {api} from './api';
import {useApp} from './store';
import {parseMetadataFile,type ImportedMetadata} from './metadata';
import type {VideoJob} from './types';
import {sortChannelsAlphabetically} from './channelSort';
import {mapThumbnailsToJobs,metadataCoverage,mergePublishTime,baseName} from './publishCenterCore';
import {acquireChannelUploadLock,beginPublishAttempt,completePublishAttempt,failPublishAttempt,findSuccessfulUpload,interruptedPublishAttempts,isChannelUploadLocked,isYoutubeDailyUploadLimitError,releaseChannelUploadLock,safeDailyStatus} from './youtubePublishSafety';
import {isYoutubeQuotaError,planYoutubeQuota,releaseYoutubeQuotaReservation,reserveYoutubeQuota,subscribeYoutubeQuota,subscribeYoutubeQuotaClock,youtubeOperationActualCost,youtubeQuotaClockSnapshot,youtubeQuotaUsage} from './youtubeQuota';
import {notifyError,notifyInfo,notifySuccess,notifyWarning} from './notificationCenter';

const local=(iso?:string)=>{if(!iso)return '';const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const status=(j:VideoJob)=>j.status==='READY_UPLOAD'?'ГОТОВО':j.status==='UPLOADING'?'ЗАГРУЖАЕТСЯ':j.status==='SCHEDULED'?'YOUTUBE ✓':j.status==='ERROR'?'ОШИБКА':j.status;

export function PublisherOS(){
 const channels=useApp(s=>s.channels),jobs=useApp(s=>s.jobs),patchJob=useApp(s=>s.patchJob),updateChannel=useApp(s=>s.updateChannel),settings=useApp(s=>s.settings),log=useApp(s=>s.log);
 const orderedChannels=useMemo(()=>sortChannelsAlphabetically(channels.filter(c=>c.enabled)),[channels]);
 const [channelId,setChannelId]=useState(orderedChannels[0]?.id||''),[selectedIds,setSelectedIds]=useState<string[]>([]),[rows,setRows]=useState<ImportedMetadata[]>([]),[docx,setDocx]=useState(false),[thumbs,setThumbs]=useState<string[]>([]),[busy,setBusy]=useState(false),[allowMissingThumbs,setAllowMissingThumbs]=useState(false),[allowDuplicate,setAllowDuplicate]=useState(false),[fingerprints,setFingerprints]=useState<Record<string,{fingerprint:string;size:number}>>({}),[quotaRev,setQuotaRev]=useState(0),[clock,setClock]=useState(()=>youtubeQuotaClockSnapshot());
 const docInput=useRef<HTMLInputElement>(null);const channel=channels.find(c=>c.id===channelId),profileId=channel?.youtubeProfileId||'';
 const channelJobs=useMemo(()=>jobs.filter(j=>j.channelId===channelId&&Boolean(j.finalPath)&&['READY_UPLOAD','UPLOADING','SCHEDULED','ERROR'].includes(j.status)).sort((a,b)=>a.number-b.number),[jobs,channelId]);
 const selectable=channelJobs.filter(j=>j.status==='READY_UPLOAD'),selected=channelJobs.filter(j=>selectedIds.includes(j.id)).sort((a,b)=>a.number-b.number);
 const thumbMap=useMemo(()=>mapThumbnailsToJobs(selected,thumbs),[selected.map(j=>j.id).join('|'),thumbs.join('|')]);const thumbCount=selected.filter(j=>Boolean(thumbMap[j.id])).length,missingThumbs=Math.max(0,selected.length-thumbCount),coverage=metadataCoverage(rows,selected.length);
 const daily=safeDailyStatus(channelId,channel?.safeDailyUploadLimit);const safeAllowed=daily.remaining==null?selected.length:Math.min(selected.length,daily.remaining);const duplicates=selected.filter(j=>fingerprints[j.id]&&findSuccessfulUpload(channelId,fingerprints[j.id].fingerprint));
 const quotaPlan=useMemo(()=>planYoutubeQuota([{method:'videos.insert',count:selected.length,label:'Загрузка видео'},{method:'thumbnails.set',count:thumbCount,label:'Обложки'}]),[selected.length,thumbCount,quotaRev]);const quota=youtubeQuotaUsage();
 useEffect(()=>{const off=subscribeYoutubeQuota(()=>setQuotaRev(x=>x+1)),offClock=subscribeYoutubeQuotaClock(setClock);return()=>{off();offClock()}},[]);
 useEffect(()=>{setSelectedIds([]);setRows([]);setDocx(false);setThumbs([]);setFingerprints({});setAllowDuplicate(false);setAllowMissingThumbs(false)},[channelId]);
 useEffect(()=>{setSelectedIds(ids=>ids.filter(id=>selectable.some(j=>j.id===id)))},[selectable.map(x=>x.id).join('|')]);
 useEffect(()=>{let live=true;const targets=selected.filter(j=>j.finalPath&&!fingerprints[j.id]);if(!targets.length)return;Promise.all(targets.map(async j=>{try{return[j.id,await api.youtubeFileFingerprint(j.finalPath!)] as const}catch{return[j.id,null] as const}})).then(rows=>{if(!live)return;setFingerprints(prev=>{const next={...prev};for(const [id,x] of rows)if(x)next[id]={fingerprint:x.fingerprint,size:x.size};return next})});return()=>{live=false}},[selected.map(x=>`${x.id}:${x.finalPath}`).join('|')]);
 useEffect(()=>{const interrupted=interruptedPublishAttempts(channelId);if(interrupted.length)notifyWarning('Найдена прерванная загрузка',`${interrupted.length} незавершённых upload attempt. VYRON YT PEISOV не повторяет их автоматически — сначала проверьте канал.` ,{operationId:`publish-interrupted:${channelId}`})},[channelId]);
 async function readDoc(fl:FileList|null){if(!fl?.length)return;const out:ImportedMetadata[]=[];let strict=false;for(const f of Array.from(fl)){const isDocx=f.name.toLowerCase().endsWith('.docx');strict=strict||isDocx;const text=isDocx?(await mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()})).value:await f.text();out.push(...parseMetadataFile(f.name,text))}out.sort((a,b)=>(a.number??Number.MAX_SAFE_INTEGER)-(b.number??Number.MAX_SAFE_INTEGER));setRows(out);setDocx(strict);const c=metadataCoverage(out,selected.length);if(selected.length&&!c.ok)notifyWarning('Недостаточно метаданных',`Word: ${out.length} • выбрано видео: ${selected.length} • не хватает: ${c.missing}`);else notifySuccess('Word-файл принят',selected.length?`${out.length} записей • будет применено ${selected.length}${c.surplus?` • лишних ${c.surplus}`:''}`:`Распознано ${out.length}. Можно выбрать до ${out.length} видео.`)}
 function applyLocalMetadata(){if(!selected.length)return;if(rows.length<selected.length){notifyWarning('Недостаточно метаданных',`Word: ${rows.length} • видео: ${selected.length}`);return}selected.forEach((j,i)=>{const x=rows[i];const p:Partial<VideoJob>={metadataSource:'import',metadataLocked:true};if(x.title)p.title=x.title;if(x.description)p.description=x.description;if(x.tags?.length)p.tags=x.tags;const nextTime=x.publishAt||mergePublishTime(j.publishAt,x.publishTime);if(nextTime)p.publishAt=nextTime;patchJob(j.id,p);if(j.folder)void api.writeJobMetadata(j.folder,p.title||j.title,p.description||j.description,p.tags||j.tags,p.publishAt||j.publishAt,'import')});notifySuccess('Метаданные подготовлены',`${selected.length} видео получили title / description / tags / время локально. YouTube API: 0.`)}
 async function chooseThumbnails(){const x=await api.chooseImages();if(x.length){setThumbs(x);setAllowMissingThumbs(false);notifySuccess('Обложки загружены',`${x.length} изображений сопоставлены локально. YouTube API: 0.`)}}
 const missingMetadata=selected.filter(j=>!j.title.trim()).length,missingSchedule=selected.filter(j=>!j.publishAt).length,locked=isChannelUploadLocked(channelId),preflightBlocked=!selected.length||!profileId||!quotaPlan.affordable||(settings.youtubePublishSafeMode&&(missingMetadata>0||duplicates.length>0||locked))||(thumbs.length>0&&missingThumbs>0&&!allowMissingThumbs)||(daily.remaining!=null&&daily.remaining<=0);
 async function runBatch(requested?:number){
  if(!channel||!profileId)return;let batch=selected.slice(0,requested||selected.length);if(daily.remaining!=null)batch=batch.slice(0,daily.remaining);if(!batch.length){notifyWarning('Загрузка заблокирована','По вашему безопасному 24h лимиту сейчас нельзя загружать новые видео.');return}if(settings.youtubePublishSafeMode&&batch.some(j=>!j.title.trim())){notifyWarning('Pre-flight не пройден','У выбранных видео отсутствуют названия.');return}if(thumbs.length>0&&batch.some(j=>!thumbMap[j.id])&&!allowMissingThumbs){notifyWarning('Обложек меньше, чем видео','Подтвердите продолжение без обложек для оставшихся видео.');return}const dup=batch.filter(j=>fingerprints[j.id]&&findSuccessfulUpload(channelId,fingerprints[j.id].fingerprint));if(dup.length&&!allowDuplicate){notifyWarning('Найдены уже загруженные файлы',`${dup.length} видео имеют успешный fingerprint на этом канале. Повторная загрузка заблокирована.`);return}
  const token=acquireChannelUploadLock(channelId);if(!token){notifyWarning('Канал занят',`Для ${channel.name} уже выполняется загрузка.`);return}const operationId=`publish:${channelId}:${Date.now()}`;const plan=planYoutubeQuota([{method:'videos.insert',count:batch.length,label:'Загрузка видео'},{method:'thumbnails.set',count:batch.filter(j=>Boolean(thumbMap[j.id])).length,label:'Обложки'}]);if(!plan.affordable||!reserveYoutubeQuota(operationId,plan)){releaseChannelUploadLock(channelId,token);notifyWarning('Недостаточно quota','Операция не запущена.');return}
  setBusy(true);let completed=0,stopped=false;try{for(const j of batch){if(!j.finalPath)continue;const fp=fingerprints[j.id]||await api.youtubeFileFingerprint(j.finalPath);const attempt=beginPublishAttempt({channelId,jobId:j.id,filePath:j.finalPath,fingerprint:fp.fingerprint,fileSize:fp.size});patchJob(j.id,{status:'UPLOADING',uploadProgress:0,error:undefined,uploadFingerprint:fp.fingerprint});try{const uploaded=await api.youtubeUpload(profileId,j.id,j.finalPath,j.title,j.description,j.tags,j.publishAt,settings.youtubeCategoryId,operationId);if(!uploaded.videoId)throw new Error('YouTube не вернул video ID');completePublishAttempt(attempt.id,uploaded.videoId);updateChannel(channelId,{lastUploadAt:new Date().toISOString(),knownUploadLimitState:'ok',lastDailyLimitError:undefined});let thumbError='';const thumb=thumbMap[j.id];if(thumb){try{await api.youtubeSetThumbnail(profileId,uploaded.videoId,thumb,operationId);patchJob(j.id,{thumbnailPath:thumb})}catch(e){thumbError=String(e);notifyWarning('Видео загружено, но обложка не применена',`VIDEO_${String(j.number).padStart(3,'0')}: ${thumbError}`)}}patchJob(j.id,{status:'SCHEDULED',youtubeVideoId:uploaded.videoId,uploadProgress:100,uploadedAt:new Date().toISOString(),error:thumbError||undefined});completed++;log(`VIDEO_${String(j.number).padStart(3,'0')} загружено на YouTube${thumb?' • thumbnail':''}`)}catch(e){failPublishAttempt(attempt.id,e);if(isYoutubeDailyUploadLimitError(e)){updateChannel(channelId,{knownUploadLimitState:'limited',lastDailyLimitError:String(e),lastUploadAt:new Date().toISOString()});patchJob(j.id,{status:'ERROR',error:'YouTube остановил загрузки: достигнут лимит загрузок канала'});notifyWarning('YouTube остановил загрузки для этого канала',`Достигнут лимит загрузок. Успешно: ${completed}. Оставшаяся партия сохранена.`);stopped=true;break}if(isYoutubeQuotaError(e)){patchJob(j.id,{status:'ERROR',error:String(e)});notifyWarning('YouTube quota остановила batch','Оставшаяся партия сохранена.');stopped=true;break}patchJob(j.id,{status:'ERROR',error:String(e)});notifyError(`VIDEO_${String(j.number).padStart(3,'0')} не загружено`,String(e))}}
  }finally{const actual=youtubeOperationActualCost(operationId);releaseYoutubeQuotaReservation(operationId);releaseChannelUploadLock(channelId,token);setBusy(false);const left=Math.max(0,youtubeQuotaUsage().limit-youtubeQuotaUsage().used);if(completed)notifySuccess(requested===1?'Тестовое видео успешно обработано':'Публикация завершена',`${completed} видео загружено. Quota general: −${actual.buckets.general}. Video Uploads: ${actual.buckets.videoUploads}. Осталось general: ${left}.${stopped?' Batch остановлен безопасно.':''}`,{operationId:`publish-done:${operationId}`})}
 }
 const general=quotaPlan.buckets.general,uploadBucket=quotaPlan.buckets.videoUploads,plannedCalls=quotaPlan.operations.reduce((n,x)=>n+x.count,0);
 return <>
  <input ref={docInput} hidden type="file" multiple accept=".docx,.json,.txt,.csv,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>{void readDoc(e.target.files);e.currentTarget.value=''}}/>
  <div className="pageHeader publishMasterHeader"><div><small>VYRON YT PEISOV • YOUTUBE</small><h1>ПУБЛИКАЦИЯ НА YOUTUBE</h1><p>Готовые видео ENDLUME → metadata → thumbnails → zero-API preflight → подтверждённая загрузка.</p></div><div className="headerActions"><button disabled={!selected.length} onClick={()=>docInput.current?.click()}>Загрузить Word / DOCX</button><button disabled={!selected.length} onClick={chooseThumbnails}>Добавить обложки</button></div></div>
  <section className="panel publishChannelSelect"><label>Канал<select value={channelId} onChange={e=>setChannelId(e.target.value)}>{orderedChannels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className={`profileAutoBadge ${profileId?'good':'warn'}`}><small>OAuth</small><b>{profileId?'✓ привязан':'не подключён'}</b></div><label>Безопасный лимит загрузок / 24 часа<input type="number" min="1" placeholder="Не установлен" value={channel?.safeDailyUploadLimit||''} onChange={e=>updateChannel(channelId,{safeDailyUploadLimit:e.target.value?Math.max(1,+e.target.value||1):undefined})}/></label><div className="dailySafety"><small>Точный остаток YouTube не сообщает</small><b>Через VYRON за 24ч: {daily.used}</b><span>{daily.limit?`Ваш лимит: ${daily.limit} • можно сейчас: ${daily.remaining}`:'Безопасный лимит не установлен'}</span></div></section>

  <section className="panel publishVideoPicker"><div className="panelHead"><div><small>01 • VIDEO</small><h3>Готовые видео ENDLUME</h3><p>Выберите 1, 5, 30 или любое количество готовых MP4.</p></div><div className="batchScopeActions"><button onClick={()=>setSelectedIds(selectable.map(j=>j.id))}>Выбрать все</button><button onClick={()=>setSelectedIds([])}>Снять всё</button></div></div>{selectable.length===0?<div className="empty"><b>Нет готовых MP4 для этого канала</b><p>После завершения ENDLUME видео автоматически получает статус «Готов к YouTube».</p></div>:<div className="publishSelectRows">{selectable.map(j=><button key={j.id} className={selectedIds.includes(j.id)?'selected':''} onClick={()=>setSelectedIds(ids=>ids.includes(j.id)?ids.filter(x=>x!==j.id):[...ids,j.id])}><i>{selectedIds.includes(j.id)?'✓':''}</i><span><b>VIDEO_{String(j.number).padStart(3,'0')}</b><small>{baseName(j.finalPath||'')} • {j.title||'без названия'}</small></span><em>{j.publishAt?new Date(j.publishAt).toLocaleString('ru-RU'):'PRIVATE без даты'}</em></button>)}</div>}</section>

  {selected.length>0&&<div className="publishSetupGrid"><section className="panel"><div className="panelHead"><div><small>02 • METADATA</small><h3>Word / DOCX</h3></div><button onClick={()=>docInput.current?.click()}>Выбрать файл</button></div>{rows.length?<><div className={`coverageBox ${coverage.ok?'good':'bad'}`}><b>{rows.length} записей / {selected.length} видео</b><span>{coverage.ok?`Будет применено ${selected.length}${coverage.surplus?` • ${coverage.surplus} останутся неиспользованы`:''}`:`Не хватает ${coverage.missing}`}</span></div><button className="primary" disabled={!coverage.ok} onClick={applyLocalMetadata}>Применить локально</button></>:<p>Можно загрузить DOCX с количеством записей не меньше выбранных видео. Production Plan не участвует в проверке.</p>}</section><section className="panel"><div className="panelHead"><div><small>03 • THUMBNAILS</small><h3>Обложки</h3></div><button onClick={chooseThumbnails}>Выбрать изображения</button></div>{thumbs.length?<><div className={`coverageBox ${missingThumbs?'warn':'good'}`}><b>{thumbCount} / {selected.length} сопоставлено</b><span>{missingThumbs?`Без обложки: ${missingThumbs}`:'Все видео имеют обложку'}</span></div>{missingThumbs>0&&<button className={allowMissingThumbs?'active':''} onClick={()=>setAllowMissingThumbs(x=>!x)}>{allowMissingThumbs?'✓ Продолжить без недостающих':'Продолжить без обложек для '+missingThumbs}</button>}</>:<p>Обложки необязательны. Если добавляете — VYRON сначала сопоставляет номер файла с VIDEO_XXX, затем использует порядок.</p>}</section></div>}

  {selected.length>0&&<section className="panel publishMapping"><div className="panelHead"><div><small>04 • PREVIEW</small><h3>Что именно будет загружено</h3></div><span>{selected.length} видео</span></div><div className="publishMappingRows">{selected.slice(0,100).map((j,i)=>{const row=rows[i],dup=fingerprints[j.id]?findSuccessfulUpload(channelId,fingerprints[j.id].fingerprint):undefined;return <div key={j.id} className={dup?'duplicate':''}><span><b>VIDEO_{String(j.number).padStart(3,'0')}</b><small>{status(j)}</small></span><span><small>Название</small><b>{row?.title||j.title||'—'}</b></span><span><small>Расписание</small><b>{j.publishAt?new Date(j.publishAt).toLocaleString('ru-RU'):'PRIVATE'}</b></span><span><small>Обложка</small><b>{thumbMap[j.id]?baseName(thumbMap[j.id]):'—'}</b></span>{dup&&<em>Уже загружалось → {dup.videoId}</em>}</div>})}</div>{duplicates.length>0&&<div className="duplicateWarning"><b>⚠ {duplicates.length} файлов уже успешно загружались на этот канал</b><button className={allowDuplicate?'active':''} onClick={()=>setAllowDuplicate(x=>!x)}>{allowDuplicate?'✓ Повтор разрешён':'ВСЁ РАВНО ЗАГРУЗИТЬ'}</button></div>}</section>}

  {selected.length>0&&<section className={`panel youtubePreflight ${preflightBlocked?'blocked':'ready'}`}><div className="panelHead"><div><small>05 • ZERO-API PRE-FLIGHT</small><h3>{preflightBlocked?'Требует внимания':'ГОТОВО К ЗАГРУЗКЕ'}</h3><p>До кнопки ниже YouTube upload requests: 0.</p></div><span>{settings.youtubePublishSafeMode?'SAFE MODE ON':'SAFE MODE OFF'}</span></div><div className="preflightGrid"><span><small>Видео</small><b>{selected.length}</b></span><span><small>Metadata title</small><b>{selected.length-missingMetadata}/{selected.length}</b></span><span><small>Обложки</small><b>{thumbCount}/{selected.length}</b></span><span><small>Расписание</small><b>{selected.length-missingSchedule}/{selected.length}</b></span><span><small>API methods</small><b>{plannedCalls}</b></span><span><small>Дубликаты</small><b>{duplicates.length}</b></span></div><div className="quotaOperationCard"><div><small>YOUTUBE API — РАСЧЁТ ОПЕРАЦИИ</small><h3>До подтверждения quota не расходуется</h3></div><div className="quotaOperationNumbers"><span><small>Сейчас general</small><b>{general.available.toLocaleString('ru-RU')}</b></span><span><small>Эта операция потратит</small><b>−{general.required.toLocaleString('ru-RU')}</b></span><span><small>После операции останется</small><b>{general.remainingAfter.toLocaleString('ru-RU')}</b></span><span><small>Video Uploads</small><b>{uploadBucket.required} / {uploadBucket.available}</b></span><span><small>Сброс quota</small><b>{clock.localTime}</b></span><span><small>До сброса</small><b className="mono">{clock.countdown}</b></span></div><details><summary>Показать расчёт</summary>{quotaPlan.operations.map((x,i)=><p key={i}>{x.count} × {x.method} = {x.cost} {x.bucket==='general'?'units':x.bucket}</p>)}</details></div>{daily.remaining!=null&&selected.length>daily.remaining&&<div className="dailyLimitWarning"><b>⚠ Не загружать всю партию</b><span>Через VYRON за 24 часа: {daily.used} • ваш лимит: {daily.limit} • можно сейчас: {daily.remaining} • партия: {selected.length}</span></div>}{locked&&<div className="errorBox">Для этого канала уже выполняется batch upload.</div>}<div className="publishFinalActions"><button disabled={busy||preflightBlocked} onClick={()=>runBatch(1)}>ПРОВЕРИТЬ НА ОДНОМ</button>{daily.remaining!=null&&selected.length>daily.remaining?<button className="primary" disabled={busy||daily.remaining<=0||(!quotaPlan.affordable)} onClick={()=>runBatch(daily.remaining)}>ЗАГРУЗИТЬ ТОЛЬКО {daily.remaining}</button>:<button className="primary" disabled={busy||preflightBlocked} onClick={()=>runBatch()}>{busy?'ЗАГРУЖАЮ…':`ЗАГРУЗИТЬ ${selected.length} ВИДЕО НА YOUTUBE`}</button>}</div></section>}
 </>
}
