import React,{useEffect,useState} from 'react';
import {api} from './api';
import {useApp} from './store';
import type {AutopilotMode,LicenseStatus} from './types';
import {notifyError,notifyInfo,notifySuccess} from './notificationCenter';
import {VYRON_BUILD_DATE,VYRON_PRODUCT_NAME,VYRON_PRODUCT_SUBTITLE} from './buildInfo';

type Tab='general'|'youtube'|'endlume'|'updates'|'license'|'about'|'diagnostics';
type DiagRow={label:string;status:string;ok?:boolean;detail?:string};
function Toggle({label,text,value,onChange}:{label:string;text:string;value:boolean;onChange:(v:boolean)=>void}){return <button className="toggleRow" type="button" onClick={()=>onChange(!value)}><div><b>{label}</b><small>{text}</small></div><i className={value?'on':''}><em/></i></button>}
const licenseName=(license:LicenseStatus)=>license.type==='owner-lifetime'?'Бессрочная лицензия владельца':license.type==='monthly'?'Ежемесячная лицензия':license.type==='development'?'Development license':license.type||'Не определено';

export function SettingsOS({license}:{license:LicenseStatus}){
 const s=useApp(x=>x.settings),patch=useApp(x=>x.patchSettings),logs=useApp(x=>x.logs),setPage=useApp(x=>x.setPage);
 const [tab,setTab]=useState<Tab>('general'),[update,setUpdate]=useState<any>(),[progress,setProgress]=useState<number|null>(null),[stage,setStage]=useState(''),[diag,setDiag]=useState<DiagRow[]>([]),[checking,setChecking]=useState(false),[installedVersion,setInstalledVersion]=useState('');
 useEffect(()=>{void api.appVersion().then(setInstalledVersion).catch(()=>{})},[]);const mode:AutopilotMode=s.autopilotMode||'off';
 const setMode=(m:AutopilotMode)=>patch({autopilotMode:m,autopilotEnabled:m!=='off',autoUploadYoutube:false});
 async function runDiagnostics(){setChecking(true);try{let ws=s.workspace;if(!ws){ws=await api.defaultWorkspace();patch({workspace:ws})}const core=await api.diagnostics(ws);setDiag([{label:'Local Core',status:core.ok?'Готово':'Требует внимания',ok:core.ok},{label:'Workspace',status:core.workspaceWritable?'Доступен для записи':'Проблема записи',ok:core.workspaceWritable},{label:'ENDLUME',status:s.endlumePath?'Путь настроен':'Не выбран',ok:Boolean(s.endlumePath)},{label:'Лицензия',status:license.valid?licenseName(license):'Не активирована',ok:license.valid},{label:'Updater',status:'Signed updater подключён',ok:true},{label:'YouTube',status:'Проверяется только явным действием во вкладке YouTube',detail:'Диагностика не расходует YouTube Data API quota.'}])}catch(e){setDiag([{label:'Диагностика',status:'Ошибка',ok:false,detail:String(e)}])}finally{setChecking(false)}}
 async function checkForUpdate(){try{const next=await api.checkUpdate();setUpdate(next);if(next?.none)notifySuccess('VYRON YT PEISOV обновлён',`Установлена актуальная версия ${next.current||installedVersion||'—'}.`,{operationId:`update-latest:${next.current||installedVersion}`});else if(next?.version)notifyInfo(`Доступно обновление VYRON YT PEISOV ${next.version}`,'Можно установить и перезапустить приложение.',{operationId:`settings-update:${next.version}`})}catch(e){setUpdate({error:String(e)});notifyError('Не удалось проверить обновления',String(e))}}
 async function installUpdate(){setProgress(0);setStage('Загрузка');localStorage.setItem('vyron:update-installing-version',String(update.version||''));try{await update.install((p:number)=>{setProgress(p);if(p>=100)setStage('Проверка подписи и установка')})}catch(e){localStorage.removeItem('vyron:update-installing-version');setProgress(null);setStage('Обновление не установлено. Текущая версия сохранена.');notifyError('Не удалось установить обновление',String(e))}}
 const tabs:[Tab,string][]=[['general','Общие'],['youtube','YouTube'],['endlume','ENDLUME'],['updates','Обновления'],['license','Лицензия'],['about','О программе'],['diagnostics','Диагностика']];
 return <><div className="pageHeader settingsMasterHead"><div><small>VYRON YT PEISOV • SETTINGS</small><h1>Настройки</h1><p>Основные параметры, YouTube safety, ENDLUME, лицензия и обновления — без скрытых API-запросов.</p></div></div><div className="settingsTabs osTabs masterSettingsTabs">{tabs.map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='general'&&<div className="settingsStack"><section className="settingsCard"><small>STORAGE</small><h3>Workspace</h3><p>Локальные проекты, очередь, backup и состояние приложения.</p><div className="pathLine"><input readOnly value={s.workspace} placeholder="создаётся автоматически"/><button onClick={async()=>{const p=await api.chooseWorkspace();if(p)patch({workspace:p})}}>Выбрать</button><button disabled={!s.workspace} onClick={()=>s.workspace&&api.openLocal(s.workspace)}>Открыть</button></div></section><section className="settingsCard"><small>INTERFACE</small><h3>Интерфейс</h3><div className="toggleRows"><Toggle label="FPS monitor" text="Показывать текущий FPS интерфейса." value={s.fpsMonitor} onChange={v=>patch({fpsMonitor:v})}/><Toggle label="Уменьшить анимации" text="Уменьшить декоративные переходы." value={s.reduceMotion} onChange={v=>patch({reduceMotion:v})}/></div></section><section className="settingsCard"><small>LOCAL AUTOMATION</small><h3>Autopilot</h3><div className="modeSwitch large"><button className={mode==='off'?'active':''} onClick={()=>setMode('off')}>OFF</button><button className={mode==='assisted'?'active':''} onClick={()=>setMode('assisted')}>ASSISTED</button><button className={mode==='full'?'active':''} onClick={()=>setMode('full')}>FULL LOCAL</button></div><p>Autopilot работает только с локальным Production/ENDLUME. YouTube остаётся ручной зоной.</p><details className="advancedPanel"><summary>Расширенные параметры</summary><div className="toggleRows"><Toggle label="Поддерживать план" text="Создавать недостающие VIDEO_XXX." value={s.autoCreatePlan} onChange={v=>patch({autoCreatePlan:v})}/><Toggle label="Распределять музыку" text="Автоматически разносить треки." value={s.autoAssignMusic} onChange={v=>patch({autoAssignMusic:v})}/><Toggle label="Распределять изображения" text="Автоматически разносить изображения." value={s.autoAssignImages} onChange={v=>patch({autoAssignImages:v})}/><Toggle label="ENDLUME queue" text="Подготавливать локальную очередь рендера." value={s.autoQueueRender} onChange={v=>patch({autoQueueRender:v})}/></div></details></section></div>}
 {tab==='youtube'&&<div className="settingsStack"><section className="settingsCard publishSafetyCard"><small>YOUTUBE SAFETY</small><h3>Безопасная публикация</h3><Toggle label="Безопасный режим публикации" text="Блокировать batch при duplicate, missing metadata/schedule, недостатке quota или превышении пользовательского 24h лимита." value={s.youtubePublishSafeMode} onChange={v=>patch({youtubePublishSafeMode:v})}/><p>Точный остаток суточного лимита загрузок YouTube не сообщает. Свой безопасный лимит задаётся отдельно для каждого канала в «YouTube → Публикация».</p><button className="primary" onClick={()=>setPage('youtube')}>Открыть YouTube</button></section><details className="settingsCard advancedPanel"><summary>Advanced YouTube</summary><label>YouTube category<input value={s.youtubeCategoryId} onChange={e=>patch({youtubeCategoryId:e.target.value.trim()||'10'})}/></label><p>OAuth/синхронизация запускаются только из YouTube Center и не выполняются при открытии Settings.</p></details></div>}
 {tab==='endlume'&&<div className="settingsStack"><section className="settingsCard"><small>RENDER ENGINE</small><h3>ENDLUME Studio</h3><p>VYRON YT PEISOV передаёт выбранные проекты локально и отслеживает render status без YouTube API.</p><div className="pathLine"><input readOnly value={s.endlumePath} placeholder="ENDLUME Studio.app"/><button onClick={async()=>{const p=await api.chooseEndlume();if(p)patch({endlumePath:p})}}>Выбрать</button>{s.endlumePath&&<button onClick={()=>api.openEndlume(s.endlumePath)}>Открыть</button>}</div></section><section className="settingsCard"><h3>Целевой рендер</h3><div className="settingsInfoGrid"><span><small>Длительность</small><b>{s.endlumeTargetDurationMin} мин</b></span><span><small>Цель рендера</small><b>{s.endlumeTargetRenderSec} сек</b></span><span><small>Файл</small><b>{s.endlumeTargetFileMinMb}–{s.endlumeTargetFileMaxMb} MB</b></span></div></section></div>}
 {tab==='updates'&&<section className="settingsCard updateMasterCard"><small>UPDATE CENTER</small><h3>Обновления</h3><div className="settingsInfoGrid"><span><small>Текущая версия</small><b>{installedVersion||'—'}</b></span><span><small>Автопроверка</small><b>{s.autoCheckUpdates?'ON':'OFF'}</b></span></div><Toggle label="Проверять автоматически" text="Signed updater; YouTube API не используется." value={s.autoCheckUpdates} onChange={v=>patch({autoCheckUpdates:v})}/><button className="settingsAction" onClick={checkForUpdate}>Проверить обновления</button>{update?.none&&<div className="successBox">Установлена актуальная версия {update.current||installedVersion||'—'}.</div>}{update?.version&&<div className="updateFound"><b>Доступна: {update.version}</b><p>{update.body}</p>{stage&&<strong>{stage}</strong>}{progress!==null&&<div className="progress"><i style={{width:`${progress}%`}}/><span>{progress.toFixed(0)}%</span></div>}<button className="primary" onClick={installUpdate}>Установить и перезапустить</button></div>}{update?.error&&<div className="errorBox">Обновление не установлено. Текущая версия сохранена.<details><summary>Technical detail</summary>{update.error}</details></div>}</section>}
 {tab==='license'&&<section className={`settingsCard licenseMasterCard ${license.valid?'activeLicense':'inactiveLicense'}`}><small>LICENSE</small><div className="licenseHero"><i>{license.valid?'✓':'!'}</i><div><h2>{license.valid?'VYRON YT PEISOV активирована':'Требуется активация'}</h2><p>{licenseName(license)}</p></div></div><div className="settingsInfoGrid"><span><small>Статус</small><b>{license.valid?'Активна':'Не активна'}</b></span><span><small>Тип</small><b>{licenseName(license)}</b></span><span><small>Срок</small><b>{license.expiresAt?new Date(license.expiresAt).toLocaleDateString('ru-RU'):'Без срока окончания'}</b></span>{license.maskedKey&&<span><small>Ключ</small><b>{license.maskedKey}</b></span>}</div><p>Основные локальные функции работают без постоянного подключения к интернету. Интернет необходим для YouTube/OAuth, публикации, проверки лицензии и обновлений.</p></section>}
 {tab==='about'&&<section className="settingsCard aboutMasterCard"><div className="aboutBrand"><div className="brandMark">▶</div><div><h2>{VYRON_PRODUCT_NAME}</h2><p>{VYRON_PRODUCT_SUBTITLE}</p></div></div><div className="aboutVersion">{installedVersion||'—'}</div><div className="settingsInfoGrid aboutGrid"><span><small>Версия</small><b>{installedVersion||'—'}</b></span><span><small>Сборка</small><b>{VYRON_BUILD_DATE==='development'?'Development':VYRON_BUILD_DATE}</b></span><span><small>Платформа</small><b>macOS • Apple Silicon M1+</b></span><span><small>Core</small><b>Rust + YouTube Data API</b></span><span><small>UI</small><b>Tauri 2 + React</b></span><span><small>Создатель</small><b>Kirill Peisov</b></span><span><small>Email</small><b>peisov.business@gmail.com</b></span></div></section>}
 {tab==='diagnostics'&&<div className="settingsStack"><section className="settingsCard"><div className="panelHead"><div><small>LOCAL ONLY</small><h3>Диагностика</h3><p>YouTube health/API checks намеренно не запускаются.</p></div><button className="primary" disabled={checking} onClick={runDiagnostics}>{checking?'Проверяю…':'Запустить проверку'}</button></div>{diag.length>0&&<div className="diagnosticGrid">{diag.map((x,i)=><div key={i} className={x.ok===false?'bad':x.ok?'good':''}><span><b>{x.label}</b><em>{x.status}</em></span>{x.detail&&<details><summary>Подробнее</summary><p>{x.detail}</p></details>}</div>)}</div>}</section><section className="settingsCard"><h3>Последние события</h3><div className="logs">{logs.length?logs.slice(0,60).map((l,i)=><div key={i} className={l.level}><small>{new Date(l.at).toLocaleString('ru-RU')}</small><span>{l.message}</span></div>):<p>Событий пока нет.</p>}</div></section></div>}</>
}
