import React,{useEffect,useMemo,useRef,useState} from 'react';
import {api} from './api';
import {useApp} from './store';
import {parseMetadataFile,type ImportedMetadata} from './metadata';
import {orderedExistingVideos} from './youtubeExisting';
import type {VideoJob,YoutubeExistingVideo,YoutubeProfile} from './types';

type Target='future'|'youtube';
type Match={row:ImportedMetadata;job?:VideoJob;video?:YoutubeExistingVideo;index:number};
const short=(s?:string,n=90)=>!s?'—':s.length>n?s.slice(0,n).trim()+'…':s;
const metaCount=(r:ImportedMetadata)=>Number(Boolean(r.title))+Number(Boolean(r.description))+Number(Boolean(r.tags?.length))+Number(Boolean(r.publishAt));

export function MetadataPage(){
  const channels=useApp(s=>s.channels),jobs=useApp(s=>s.jobs),patchJob=useApp(s=>s.patchJob),toast=useApp(s=>s.toast);
  const [channelId,setChannelId]=useState(channels[0]?.id||''),[target,setTarget]=useState<Target>('future'),[rows,setRows]=useState<ImportedMetadata[]>([]),[paste,setPaste]=useState(''),[profiles,setProfiles]=useState<YoutubeProfile[]>([]),[profileId,setProfileId]=useState(''),[yt,setYt]=useState<YoutubeExistingVideo[]>([]),[busy,setBusy]=useState(false),[order,setOrder]=useState<'oldest'|'newest'>('oldest'),[limit,setLimit]=useState(50);const file=useRef<HTMLInputElement>(null);
  const channel=channels.find(c=>c.id===channelId);
  useEffect(()=>{api.youtubeProfiles().then(setProfiles).catch(()=>{})},[]);
  useEffect(()=>{setProfileId(channel?.youtubeProfileId||'')},[channelId,channel?.youtubeProfileId]);
  async function readFiles(fl:FileList|null){if(!fl?.length)return;const out:ImportedMetadata[]=[];for(const f of Array.from(fl))out.push(...parseMetadataFile(f.name,await f.text()));setRows(out);toast(`Метаданные: ${out.length} записей`)}
  function parsePaste(){const out=parseMetadataFile('GPT.txt',paste);setRows(out);toast(out.length?`GPT: распознано ${out.length} записей`:'Не удалось распознать метаданные')}
  async function loadYoutube(){if(!profileId){toast('Сначала привяжи YouTube OAuth к выбранному каналу');return}setBusy(true);try{const r=await api.youtubeListExisting(profileId,Math.max(1,Math.min(200,limit)));const videos=orderedExistingVideos((r.videos||[]).filter((v:YoutubeExistingVideo)=>v.privacyStatus==='private'),order);setYt(videos);toast(`YouTube: приватных/запланированных ${videos.length}`)}catch(e){toast(String(e))}finally{setBusy(false)}}
  const future=useMemo(()=>jobs.filter(j=>j.channelId===channelId&&j.status!=='SCHEDULED').sort((a,b)=>a.number-b.number),[jobs,channelId]);
  const matches=useMemo<Match[]>(()=>rows.map((row,index)=>{if(target==='future'){const pool=future;const job=row.number?pool.find(j=>j.number===row.number):pool[index];return{row,job,index}}const pool=yt;const video=row.number?pool[row.number-1]:pool[index];return{row,video,index}}),[rows,target,future,yt]);
  const matched=matches.filter(m=>target==='future'?m.job:m.video).length;
  async function applyFuture(){setBusy(true);let ok=0;try{for(const m of matches){const j=m.job,r=m.row;if(!j)continue;const p:Partial<VideoJob>={metadataSource:'import',metadataLocked:true};if(r.title)p.title=r.title;if(r.description)p.description=r.description;if(r.tags?.length)p.tags=r.tags;if(r.publishAt)p.publishAt=r.publishAt;patchJob(j.id,p);const after={...j,...p};if(j.folder)await api.writeJobMetadata(j.folder,after.title,after.description,after.tags,after.publishAt,'import');ok++}toast(`Будущие видео: применено ${ok}/${rows.length}`)}catch(e){toast(String(e))}finally{setBusy(false)}}
  async function applyYoutube(){if(!profileId)return;setBusy(true);let ok=0,err=0;try{for(const m of matches){const v=m.video,r=m.row;if(!v)continue;try{await api.youtubeUpdateExisting(profileId,v.id,r.title||v.title,r.description||v.description,r.tags?.length?r.tags:v.tags,r.publishAt||v.publishAt);ok++}catch{err++}}toast(`YouTube: обновлено ${ok}${err?` • ошибок ${err}`:''}`);if(ok)await loadYoutube()}finally{setBusy(false)}}
  async function apply(){if(!rows.length){toast('Сначала вставь или загрузи метаданные');return}if(target==='future')await applyFuture();else await applyYoutube()}
  return <>
    <div className="pageHeader"><div><small>METADATA HUB</small><h1>Метаданные</h1><p>Одна пачка из ChatGPT → 30–50 видео. Название, описание, теги и дата закрепляются за будущими проектами или уже запланированными роликами YouTube.</p></div><div className="headerActions"><button className="primary" disabled={busy||!rows.length||!matched} onClick={apply}>{busy?'ПРИМЕНЯЮ…':`ПРИМЕНИТЬ ${matched}`}</button></div></div>
    <input ref={file} hidden type="file" multiple accept=".json,.txt,.csv" onChange={e=>{void readFiles(e.target.files);e.currentTarget.value=''}}/>
    <div className="metadataHubGrid">
      <section className="panel metadataSourcePanel"><div className="panelHead"><div><small>01 • ИСТОЧНИК</small><h3>Вставь прямо из GPT</h3></div><button onClick={()=>file.current?.click()}>ЗАГРУЗИТЬ ФАЙЛ</button></div><textarea className="metadataPaste" value={paste} onChange={e=>setPaste(e.target.value)} placeholder={'VIDEO_001\nTITLE: ...\nDESCRIPTION: ...\nTAGS: tag1, tag2, tag3\nDATE: 2026-09-01T18:00:00+07:00\n---\nVIDEO_002\nTITLE: ...'}/><div className="metadataPasteActions"><button className="primary" disabled={!paste.trim()} onClick={parsePaste}>РАЗОБРАТЬ ТЕКСТ GPT</button><button onClick={()=>{setPaste('');setRows([])}}>ОЧИСТИТЬ</button><span>JSON / TXT / CSV тоже поддерживаются</span></div></section>
      <section className="panel metadataTargetPanel"><div className="panelHead"><div><small>02 • НАЗНАЧЕНИЕ</small><h3>Куда применить</h3></div></div><label>Канал<select value={channelId} onChange={e=>setChannelId(e.target.value)}>{channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="metadataTargetSwitch"><button className={target==='future'?'active':''} onClick={()=>setTarget('future')}><b>Будущие VYRON</b><small>до рендера и загрузки</small></button><button className={target==='youtube'?'active':''} onClick={()=>setTarget('youtube')}><b>Уже на YouTube</b><small>private / scheduled</small></button></div>{target==='future'?<div className="metadataTargetInfo"><strong>{future.length}</strong><span>будущих проектов найдено</span><small>Метаданные сохраняются в проекте и автоматически наследуются final.mp4.</small></div>:<><label>OAuth<select value={profileId} onChange={e=>setProfileId(e.target.value)}><option value="">— не подключён —</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.channelTitle||p.channelId||p.id}</option>)}</select></label><div className="metadataYoutubeLoad"><label>Видео<input type="number" min="1" max="200" value={limit} onChange={e=>setLimit(+e.target.value||50)}/></label><label>Порядок<select value={order} onChange={e=>setOrder(e.target.value as any)}><option value="oldest">старые → новые</option><option value="newest">новые → старые</option></select></label><button disabled={busy||!profileId} onClick={loadYoutube}>↻ ПОДТЯНУТЬ</button></div><div className="metadataTargetInfo"><strong>{yt.length}</strong><span>private/scheduled роликов</span><small>Public-видео намеренно не попадают в массовое применение.</small></div></>}</section>
    </div>
    <section className="panel metadataPreviewPanel"><div className="panelHead"><div><small>03 • ПРЕДПРОСМОТР</small><h3>{rows.length?`${rows.length} записей • сопоставлено ${matched}`:'Метаданные ещё не загружены'}</h3><p>Ничего не изменяется до нажатия «Применить».</p></div>{rows.length>0&&<div className="metadataStats"><span><b>{rows.filter(r=>r.title).length}</b> названий</span><span><b>{rows.filter(r=>r.description).length}</b> описаний</span><span><b>{rows.filter(r=>r.tags?.length).length}</b> тегов</span><span><b>{rows.filter(r=>r.publishAt).length}</b> дат</span></div>}</div>{rows.length===0?<div className="empty"><b>Вставь пачку из ChatGPT</b><p>Лучше использовать VIDEO_001, VIDEO_002… — тогда сопоставление будет однозначным.</p></div>:<div className="metadataPreviewList">{matches.slice(0,80).map((m,i)=>{const dest=target==='future'?m.job:m.video;return <div className={`metadataPreviewRow ${dest?'matched':'missing'}`} key={i}><span><b>{m.row.number?`VIDEO_${String(m.row.number).padStart(3,'0')}`:`СТРОКА ${i+1}`}</b><small>{dest?target==='future'?`→ VIDEO_${String(m.job!.number).padStart(3,'0')}`:`→ ${short(m.video!.title,42)}`:'→ НЕ НАЙДЕНО'}</small></span><strong>{m.row.title||'Название не задано'}</strong><em>{metaCount(m.row)}/4 поля</em></div>})}</div>}</section>
  </>
}
