import {describe,expect,it} from 'vitest';import {buildAuthRecoveryMapping,nextReconnectProfileId,reconnectQueue} from './authRecoveryCore';import type {Channel,YoutubeProfile} from './types';
const ch=(i:number,p?:string):Channel=>({id:`c${i}`,name:`Channel ${i}`,slug:`c${i}`,cadenceDays:4,targetBufferDays:60,publishHour:18,publishMinute:0,language:'EN',genre:'Music',country:'US',minTracks:10,targetDurationMin:120,enabled:true,youtubeProfileId:p,youtubeChannelId:p?`UC_${p}`:undefined,seo:{titlePatterns:[],descriptionTemplate:'',tags:[],banned:[]}});
const pr=(i:number,status:YoutubeProfile['credentialStatus']='RECONNECT_REQUIRED'):YoutubeProfile=>({id:`p${i}`,channelId:`UC_p${i}`,channelTitle:`YT ${i}`,credentialStatus:status,clientIdMasked:'client…masked'});
describe('auth recovery mapping',()=>{
 it('H multiple channels/profile mapping preserved',()=>{const channels=[ch(1,'p1'),ch(2,'p1'),ch(3,'p2')];const m=buildAuthRecoveryMapping(channels,[pr(1),pr(2)]);expect(m.profiles.find(x=>x.profile.id==='p1')?.channels.map(x=>x.channelId)).toEqual(['c1','c2']);expect(m.uniqueProfilesRequiringReconnect).toBe(2)});
 it('I 31 channel / 17 profile fixture preserved',()=>{const profiles=Array.from({length:17},(_,i)=>pr(i+1));const channels=Array.from({length:31},(_,i)=>i<17?ch(i+1,`p${i+1}`):ch(i+1));const m=buildAuthRecoveryMapping(channels,profiles);expect(m.channels).toHaveLength(31);expect(m.profiles).toHaveLength(17);expect(m.missingChannels).toHaveLength(14);expect(m.uniqueProfilesRequiringReconnect).toBe(17);expect(reconnectQueue(m)).toHaveLength(17)});
 it('detects stale and duplicate profiles without reconnecting them',()=>{const profiles=[pr(1),{...pr(2),channelId:'UC_p1'},pr(3)];const m=buildAuthRecoveryMapping([ch(1,'p1')],profiles);expect(m.staleProfiles.map(x=>x.profile.id)).toContain('p3');expect(m.duplicateProfiles.map(x=>x.profile.id)).toContain('p2');expect(m.uniqueProfilesRequiringReconnect).toBe(1)});
 it('J queue advances only after validated success',()=>{const m=buildAuthRecoveryMapping([ch(1,'p1'),ch(2,'p2')],[pr(1),pr(2)]);expect(nextReconnectProfileId(m,'p1',false)).toBe('p1');expect(nextReconnectProfileId(m,'p1',true)).toBe('p2')});
});
