import type {Channel,YoutubeProfile} from './types';
export type RecoveryAuthState='READY'|'RECONNECT REQUIRED'|'CONNECTING'|'VALIDATING'|'CONNECTED'|'WRONG CHANNEL'|'FAILED';
export type RecoveryChannelRow={channelId:string;channelName:string;youtubeChannelId?:string;profileUuid?:string;mapping:'EXPLICIT'|'CHANNEL_ID_FALLBACK'|'MISSING_PROFILE'|'NO_PROFILE'};
export type RecoveryProfileRow={profile:YoutubeProfile;channels:RecoveryChannelRow[];duplicateOf?:string;stale:boolean;mappingConflict:boolean;needsReconnect:boolean};
export type AuthRecoveryMapping={channels:RecoveryChannelRow[];profiles:RecoveryProfileRow[];missingChannels:RecoveryChannelRow[];staleProfiles:RecoveryProfileRow[];duplicateProfiles:RecoveryProfileRow[];uniqueProfilesRequiringReconnect:number};
export function buildAuthRecoveryMapping(channels:Channel[],profiles:YoutubeProfile[]):AuthRecoveryMapping{
 const byId=new Map(profiles.map(p=>[p.id,p]));const byChannel=new Map<string,YoutubeProfile[]>();for(const p of profiles){if(p.channelId){const a=byChannel.get(p.channelId)||[];a.push(p);byChannel.set(p.channelId,a)}}
 const rows:RecoveryChannelRow[]=channels.map(c=>{if(c.youtubeProfileId&&byId.has(c.youtubeProfileId))return {channelId:c.id,channelName:c.name,youtubeChannelId:c.youtubeChannelId,profileUuid:c.youtubeProfileId,mapping:'EXPLICIT'};if(c.youtubeProfileId&&!byId.has(c.youtubeProfileId))return {channelId:c.id,channelName:c.name,youtubeChannelId:c.youtubeChannelId,profileUuid:c.youtubeProfileId,mapping:'MISSING_PROFILE'};if(c.youtubeChannelId){const matches=byChannel.get(c.youtubeChannelId)||[];if(matches.length===1)return {channelId:c.id,channelName:c.name,youtubeChannelId:c.youtubeChannelId,profileUuid:matches[0].id,mapping:'CHANNEL_ID_FALLBACK'}}return {channelId:c.id,channelName:c.name,youtubeChannelId:c.youtubeChannelId,mapping:'NO_PROFILE'}});
 const explicitUse=new Map<string,number>();for(const r of rows)if(r.profileUuid)explicitUse.set(r.profileUuid,(explicitUse.get(r.profileUuid)||0)+1);
 const canonicalByChannel=new Map<string,string>();for(const p of profiles){if(!p.channelId)continue;const same=profiles.filter(x=>x.channelId===p.channelId);if(same.length<2)continue;const ranked=[...same].sort((a,b)=>(explicitUse.get(b.id)||0)-(explicitUse.get(a.id)||0)||a.id.localeCompare(b.id));canonicalByChannel.set(p.channelId,ranked[0].id)}
 const mapped=profiles.map(p=>{const ch=rows.filter(r=>r.profileUuid===p.id);const canonical=p.channelId?canonicalByChannel.get(p.channelId):undefined;const duplicateOf=canonical&&canonical!==p.id?canonical:undefined;const stale=ch.length===0;const mappingConflict=Boolean(p.channelId&&ch.some(c=>c.youtubeChannelId&&c.youtubeChannelId!==p.channelId));const needsReconnect=!stale&&!duplicateOf&&!mappingConflict&&p.credentialStatus!=='WORKING';return {profile:p,channels:ch,duplicateOf,stale,mappingConflict,needsReconnect}});
 return {channels:rows,profiles:mapped,missingChannels:rows.filter(r=>!r.profileUuid||r.mapping==='MISSING_PROFILE'),staleProfiles:mapped.filter(p=>p.stale),duplicateProfiles:mapped.filter(p=>Boolean(p.duplicateOf)),uniqueProfilesRequiringReconnect:mapped.filter(p=>p.needsReconnect).length};
}
export function recoveryDisplayState(p:RecoveryProfileRow,transient?:string):RecoveryAuthState{if(transient==='CONNECTING')return 'CONNECTING';if(transient==='VALIDATING'||transient==='SAVING')return 'VALIDATING';if(transient==='CONNECTED')return 'CONNECTED';if(transient==='WRONG_CHANNEL')return 'WRONG CHANNEL';if(transient==='FAILED')return 'FAILED';if(p.duplicateOf||p.mappingConflict)return 'FAILED';if(p.profile.credentialStatus==='WORKING')return 'CONNECTED';if(p.profile.credentialStatus==='RECONNECT_REQUIRED')return 'RECONNECT REQUIRED';return 'READY'}
export function reconnectQueue(mapping:AuthRecoveryMapping){return mapping.profiles.filter(p=>p.needsReconnect)}
export function nextReconnectProfileId(mapping:AuthRecoveryMapping,currentId:string,validatedSuccess:boolean){if(!validatedSuccess)return currentId;const q=reconnectQueue(mapping);const i=q.findIndex(x=>x.profile.id===currentId);return q[i+1]?.profile.id||q.find(x=>x.profile.id!==currentId)?.profile.id||''}
