import React,{useEffect,useMemo,useState} from 'react';
import {ModalPortal} from './ModalPortal';
import {useApp} from './store';
import {api,type OAuthCredentialStateProfile} from './api';
import {bufferDays,formatNumber} from './core';
import type {Channel,YoutubeProfile} from './types';
import {hasChannelNameConflict,isFutureChannel} from './channelIdentity';
import {saveActivePublishChannel} from './publishWorkspaceState';
import {activeErrorCount} from './activeErrors';
import {YOUTUBE_OAUTH_STATE_CHANGED_EVENT} from './youtubeOauthState';
import {OWNER_INVENTORY_EVENT,ownerInventoryForChannel} from './youtubeOwnerInventory';
import {safeDailyStatus} from './youtubePublishSafety';
import {ChannelAvatar} from './ChannelAvatar';
import {ChannelPassport} from './ChannelPassport';

type Filter='all'|'connected'|'disconnected'|'attention'|'queue'|'noqueue';
const OPEN_TAB_KEY='vyron:youtube-open-tab:v1';
const date=(iso?:string)=>iso?new Date(iso).toLocaleDateString('ru-RU'):'—';
const dateTime=(iso?:string)=>iso?new Date(iso).toLocaleString('ru-RU'):'—';
export function channelOauthStateLabel(state:string){return state==='READY'?'OAuth ✓':state==='RECOVERABLE_KEYCHAIN_BLOCKED'?'OAuth: восстановить доступ':state==='KEYCHAIN_BLOCKED'?'OAuth: доступ заблокирован':state==='RECONNECT_REQUIRED'||state==='MISSING'?'OAuth: требуется вход':state==='WRONG_CHANNEL'?'OAuth: выбран другой канал':'OAuth: не проверено'}

export function ChannelsOS(){
 const channels=useApp(s=>s.channels),jobs=useApp(s=>s.jobs),addChannel=useApp(s=>s.addChannel),updateChannel=useApp(s=>s.updateChannel),removeChannel=useApp(s=>s.removeChannel),setPage=useApp(s=>s.setPage),toast=useApp(s=>s.toast);
 const [editing,setEditing]=useState<string|null>(null),[passportId,setPassportId]=useState<string|null>(null),[creating,setCreating]=useState(false),[futureName,setFutureName]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState<Filter>('all'),[oauthStates,setOauthStates]=useState<Record<string,OAuthCredentialStateProfile>>({}),[profiles,setProfiles]=useState<YoutubeProfile[]>([]),[ownerRevision,setOwnerRevision]=useState(0);
 useEffect(()=>{let live=true;const load=()=>{void api.youtubeOauthCredentialStates().then(x=>{if(live)setOauthStates(Object.fromEntries(x.profiles.map(p=>[p.profileUuid,p]))) }).catch(()=>{});void api.youtubeProfiles().then(x=>{if(live)setProfiles(x)}).catch(()=>{})};load();window.addEventListener(YOUTUBE_OAUTH_STATE_CHANGED_EVENT,load);return()=>{live=false;window.removeEventListener(YOUTUBE_OAUTH_STATE_CHANGED_EVENT,load)}},[channels.map(c=>c.youtubeProfileId||'').join('|')]);
 useEffect(()=>{const bump=()=>setOwnerRevision(x=>x+1);window.addEventListener(OWNER_INVENTORY_EVENT,bump);window.addEventListener('vyron-channel-schedule-changed',bump);return()=>{window.removeEventListener(OWNER_INVENTORY_EVENT,bump);window.removeEventListener('vyron-channel-schedule-changed',bump)}},[]);
 const rows=useMemo(()=>channels.filter(c=>{const p=profiles.find(x=>x.id===c.youtubeProfileId),scheduled=jobs.filter(j=>j.channelId===c.id&&Boolean(j.publishAt)&&new Date(j.publishAt!).getTime()>Date.now()).length,connected=Boolean(c.youtubeProfileId),attention=activeErrorCount(jobs.filter(j=>j.channelId===c.id))>0||(!isFutureChannel(c)&&!connected)||!c.renderFolderPath||!c.projectsFolderPath;const q=query.trim().toLowerCase(),matches=!q||[c.name,c.stats?.handle,c.youtubeChannelId,p?.googleEmail].filter(Boolean).some(x=>String(x).toLowerCase().includes(q));if(!matches)return false;if(filter==='connected')return connected;if(filter==='disconnected')return !connected;if(filter==='attention')return attention;if(filter==='queue')return scheduled>0;if(filter==='noqueue')return scheduled===0;return true}),[channels,jobs,profiles,query,filter,ownerRevision]);
 function openYoutube(c:Channel,tab:'publish'|'schedule'|'accounts'){saveActivePublishChannel(c.id);try{localStorage.setItem(OPEN_TAB_KEY,tab)}catch{}setPage('youtube')}
 function createFuture(){const n=futureName.trim().replace(/\s+/g,' ');if(!n)return;if(hasChannelNameConflict(channels,n)){toast('Канал с таким названием уже есть в VYRON');return}const c=addChannel({name:n});setCreating(false);setFutureName('');setEditing(c.id);toast('Будущий канал '+n+' создан')}
 return <div className="channelsFleetPage"><div className="pageHeader"><div><small>CHANNEL FLEET</small><h1>Каналы</h1><p>Оперативное управление каналами. Google credentials и диагностика OAuth остаются в «Аккаунтах».</p></div><div className="headerActions"><button className="primary" onClick={()=>setCreating(true)}>+ Будущий канал</button></div></div>
  <div className="fleetToolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск: название, @handle, Channel ID, Google email"/><div className="filterChips">{([['all','Все'],['connected','Подключены'],['disconnected','Не подключены'],['attention','Требуют внимания'],['queue','Есть очередь'],['noqueue','Нет очереди']] as [Filter,string][]).map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div></div>
  {!rows.length?<div className="empty"><b>Каналы не найдены</b><p>Измените фильтр или добавьте будущий канал.</p></div>:<div className="channelFleetGrid">{rows.map(c=>{const p=profiles.find(x=>x.id===c.youtubeProfileId),state=c.youtubeProfileId?oauthStates[c.youtubeProfileId]?.credentialState||'NOT_CHECKED':'NOT_CHECKED',connected=Boolean(c.youtubeProfileId),scheduledJobs=jobs.filter(j=>j.channelId===c.id&&Boolean(j.publishAt)&&new Date(j.publishAt!).getTime()>Date.now()).sort((a,b)=>String(a.publishAt).localeCompare(String(b.publishAt))),owner=ownerInventoryForChannel(c.id),ownerPrefix=owner.available&&owner.complete?'':'≥',daily=safeDailyStatus(c.id,c.safeDailyUploadLimit),reserve=bufferDays(c,jobs),errors=activeErrorCount(jobs.filter(j=>j.channelId===c.id)),last=c.stats?.statisticsUpdatedAt||c.stats?.updatedAt||c.analytics?.updatedAt;return <article className={'channelFleetCard '+(editing===c.id?'editing':'')} key={c.id}><header><div className="fleetIdentity"><ChannelAvatar channel={c} size="lg"/><span><b>{c.name}</b><small>{c.stats?.handle||c.youtubeChannelId||'Локальный канал'}</small><em className={connected&&state==='READY'?'good':'warn'}>{connected?channelOauthStateLabel(state):isFutureChannel(c)?'Будущий канал':'YouTube не подключён'}</em></span></div><button className="icon compact" onClick={()=>setEditing(editing===c.id?null:c.id)}>✎</button></header>
    <div className="fleetMetrics"><span><small>Подписчики</small><b>{c.stats?.hiddenSubscriberCount?'—':c.stats?.subscriberCount??c.stats?.subscribers??'—'}</b></span><span><small>Всего просмотров</small><b>{c.stats?.viewCount!=null?formatNumber(c.stats.viewCount):c.stats?.views!=null?formatNumber(c.stats.views):'—'}</b></span><span><small>Owner-видео</small><b>{owner.available?ownerPrefix+formatNumber(owner.total):'—'}</b></span><span><small>Public</small><b>{owner.available?ownerPrefix+formatNumber(owner.public):'—'}</b></span><span><small>Private</small><b>{owner.available?ownerPrefix+formatNumber(owner.private):'—'}</b></span><span><small>YouTube Scheduled</small><b>{owner.available?ownerPrefix+formatNumber(owner.scheduled):'—'}</b></span><span><small>VYRON plan</small><b>{scheduledJobs.length}</b></span><span><small>Local запас</small><b>{reserve} дн.</b></span><span><small>Следующая YouTube публикация</small><b>{dateTime(owner.nextScheduledAt)}</b></span><span><small>Последнее обновление</small><b>{dateTime(owner.updatedAt||last)}</b></span></div>
    <div className="fleetFolderState"><span className={c.renderFolderPath?'ok':'warn'}>Render {c.renderFolderPath?'✓':'не выбран'}</span><span className={c.projectsFolderPath?'ok':'warn'}>Projects {c.projectsFolderPath?'✓':'не выбран'}</span><span className={daily.configured&&!daily.unlimited&&daily.remaining===0?'warn':'ok'}>VYRON upload limit {daily.unlimited?'без ограничения':daily.configured?daily.used+'/'+daily.limit:'не настроен'}</span>{errors>0&&<span className="warn">Ошибки {errors}</span>}{p?.googleEmail&&<span>{p.googleEmail}</span>}</div>
    <div className="channelActions fleetActions"><button className="primary" onClick={()=>setPassportId(c.id)}>Паспорт</button>{c.youtubeChannelId&&<button onClick={()=>void api.openWeb('https://www.youtube.com/channel/'+c.youtubeChannelId)}>YouTube</button>}<button onClick={()=>openYoutube(c,'publish')}>Публикация</button><button onClick={()=>{saveActivePublishChannel(c.id);setPage('analytics')}}>Аналитика</button><button onClick={()=>openYoutube(c,'schedule')}>Расписание</button><button onClick={()=>{if(c.projectsFolderPath)void api.reveal(c.projectsFolderPath);else if(c.renderFolderPath)void api.reveal(c.renderFolderPath);else setEditing(c.id)}}>Папки</button><button onClick={()=>setEditing(editing===c.id?null:c.id)}>Настроить</button></div>
    {editing===c.id&&<div className="editGrid channelEdit"><label>Название<input value={c.name} onChange={e=>updateChannel(c.id,{name:e.target.value})}/></label><label>Жанр<input value={c.genre} onChange={e=>updateChannel(c.id,{genre:e.target.value})}/></label><label>Язык<input value={c.language} onChange={e=>updateChannel(c.id,{language:e.target.value})}/></label><label>Страна<input value={c.country} onChange={e=>updateChannel(c.id,{country:e.target.value})}/></label><label>Раз в N дней<input type="number" min="1" max="30" value={c.cadenceDays} onChange={e=>updateChannel(c.id,{cadenceDays:+e.target.value||1})}/></label><label>Целевой запас<input type="number" min="1" max="365" value={c.targetBufferDays} onChange={e=>updateChannel(c.id,{targetBufferDays:+e.target.value||60})}/></label><label>Дневной лимит upload VYRON<select value={c.safeDailyUploadLimit==null?-1:c.safeDailyUploadLimit} onChange={e=>{const n=+e.target.value;updateChannel(c.id,{safeDailyUploadLimit:n<0?undefined:n})}}><option value="-1">не настроен</option><option value="0">без ограничения VYRON</option><option value="10">10</option><option value="20">20</option><option value="30">30</option></select></label><label className="wide">Render folder<input value={c.renderFolderPath||''} onChange={e=>updateChannel(c.id,{renderFolderPath:e.target.value||undefined})}/></label><label className="wide">Projects folder<input value={c.projectsFolderPath||''} onChange={e=>updateChannel(c.id,{projectsFolderPath:e.target.value||undefined})}/></label><div className="editActions"><button onClick={()=>openYoutube(c,'accounts')}>Управление Google в Аккаунтах</button><button className="danger" onClick={()=>{if(window.confirm('Удалить '+c.name+' из VYRON? Файлы на диске останутся.')){removeChannel(c.id);setEditing(null)}}}>Удалить</button><button className="primary" onClick={()=>setEditing(null)}>Готово</button></div></div>}
   </article>})}</div>}
  {passportId&&(()=>{const c=channels.find(x=>x.id===passportId);if(!c)return null;const p=profiles.find(x=>x.id===c.youtubeProfileId),state=c.youtubeProfileId?oauthStates[c.youtubeProfileId]?.credentialState:undefined;return <ChannelPassport channel={c} profile={p} oauthState={state} onClose={()=>setPassportId(null)}/>})()}
  {creating&&<ModalPortal onClose={()=>setCreating(false)}><section className="confirmModal" onMouseDown={e=>e.stopPropagation()}><small>БУДУЩИЙ КАНАЛ</small><h2>Добавить канал без YouTube</h2><p>Производство можно начать до подключения Google.</p><label>Название<input autoFocus value={futureName} onChange={e=>setFutureName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')createFuture()}}/></label><footer><button onClick={()=>setCreating(false)}>Отмена</button><button className="primary" disabled={!futureName.trim()} onClick={createFuture}>Создать</button></footer></section></ModalPortal>}
 </div>;
}
