import React,{useEffect,useMemo,useState} from 'react';
import {useApp} from './store';
import {bufferDays} from './core';
import {humanizeError} from './errorCenter';
import {isFutureChannel} from './channelIdentity';
import {buildReadyVideoInventory} from './readyVideoInventory';
import {subscribeUploadQueue,uploadQueueRuntimeFacts,uploadQueueSnapshot} from './uploadQueueRuntime';
import {formatDuration,formatUploadSpeed,subscribeUploadTelemetry,uploadTelemetrySnapshot} from './uploadTelemetry';
import {loadActivePublishChannel,subscribeActivePublishChannel} from './publishWorkspaceState';
import {CommandCenter} from './CommandCenter';
import {ScreenErrorBoundary} from './ScreenErrorBoundary';
import {activeJobErrors} from './activeErrors';
import {inventoryTotals,useLiveInventory} from './renderInventoryRuntime';
import {ownerInventoryTotals} from './youtubeOwnerInventory';

const fmt=(n:number)=>new Intl.NumberFormat('ru-RU').format(n);
const sameLocalDay=(iso:string|undefined,now:Date)=>{if(!iso)return false;const d=new Date(iso);return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()&&d.getDate()===now.getDate()};

export function DashboardOS(){const page=useApp(s=>s.page),setPage=useApp(s=>s.setPage);return <ScreenErrorBoundary page={page} onHome={()=>setPage('dashboard')}>{page==='autopilot'?<CommandCenter/>:<OperationsDashboard/>}</ScreenErrorBoundary>}

function OperationsDashboard(){
 const channels=useApp(s=>s.channels),jobs=useApp(s=>s.jobs),settings=useApp(s=>s.settings),uploadHistory=useApp(s=>s.uploadHistory),projectLifecycle=useApp(s=>s.projectLifecycle),fingerprintCache=useApp(s=>s.fingerprintCache),ownerYoutubeInventory=useApp(s=>s.ownerYoutubeInventory),setPage=useApp(s=>s.setPage),liveSnapshots=useLiveInventory(s=>s.snapshots);
 const [queue,setQueue]=useState(()=>uploadQueueSnapshot()),[telemetry,setTelemetry]=useState(()=>uploadTelemetrySnapshot()),[activeId,setActiveId]=useState(()=>loadActivePublishChannel());
 useEffect(()=>{const offQueue=subscribeUploadQueue(setQueue),offTelemetry=subscribeUploadTelemetry(setTelemetry),offActive=subscribeActivePublishChannel(setActiveId);return()=>{offQueue();offTelemetry();offActive()}},[]);
 const enabled=useMemo(()=>channels.filter(c=>c.enabled!==false),[channels]),uploadFacts=useMemo(()=>uploadQueueRuntimeFacts(),[queue]),inventory=useMemo(()=>buildReadyVideoInventory(enabled,jobs,uploadHistory,projectLifecycle,fingerprintCache,uploadFacts,new Date()),[enabled,jobs,uploadHistory,projectLifecycle,fingerprintCache,uploadFacts]),liveTotals=useMemo(()=>inventoryTotals(liveSnapshots,enabled),[liveSnapshots,enabled]),ownerTotals=useMemo(()=>ownerInventoryTotals(enabled,ownerYoutubeInventory),[enabled,ownerYoutubeInventory]);
 const active=enabled.find(c=>c.id===activeId)||enabled[0],activeInv=active?inventory.byChannel[active.id]:undefined,activeLive=active?liveSnapshots[active.id]:undefined,activeOwner=active?ownerYoutubeInventory[active.id]:undefined,activeQueued=active?queue.queued.filter(x=>x.spec.channelId===active.id).length:0,activeRunning=active?queue.running.filter(x=>x.spec.channelId===active.id).length:0;
 const scheduled=ownerTotals.scheduledCount,jobErrors=activeJobErrors(jobs),actionableErrors=jobErrors.length,readyEndlume=jobs.filter(j=>j.status==='READY_RENDER').length,rendering=jobs.filter(j=>j.status==='RENDERING').length;
 const subscriberRows=enabled.filter(c=>c.stats&&!c.stats.hiddenSubscriberCount&&c.stats.subscriberCount!=null),viewRows=enabled.filter(c=>c.stats&&Number.isFinite(c.stats.viewCount));
 const totalSubscribers=subscriberRows.length?subscriberRows.reduce((n,c)=>n+Number(c.stats!.subscriberCount||0),0):undefined;
 const totalViews=viewRows.length?viewRows.reduce((n,c)=>n+Number(c.stats!.viewCount||0),0):undefined;
 const progressRows=enabled.filter(c=>c.stats&&!c.stats.hiddenSubscriberCount&&c.stats.subscriberCount!=null).slice().sort((a,b)=>Number(b.stats?.subscriberCount||0)-Number(a.stats?.subscriberCount||0)).slice(0,5);
 const now=new Date(),completedToday=queue.recent.filter(x=>x.state==='SUCCEEDED'&&sameLocalDay(x.finishedAt,now)).length,failedToday=queue.recent.filter(x=>x.state==='FAILED'&&sameLocalDay(x.finishedAt,now)).length;
 const attention=useMemo(()=>{const rows:{key:string;label:string;text:string;page:'channels'|'production'|'inventory'|'youtube'|'settings'}[]=[];for(const c of enabled){const inv=liveSnapshots[c.id];if(inv&&inv.folderState==='ONLINE'&&inv.readyVideos===0)rows.push({key:'stock:'+c.id,label:c.name,text:'0 дней фактического запаса Render',page:'inventory'});if(!isFutureChannel(c)&&!c.youtubeProfileId)rows.push({key:'oauth:'+c.id,label:c.name,text:'требуется подключение YouTube OAuth',page:'youtube'});if(!isFutureChannel(c)&&settings.autoUploadYoutube&&!c.safeDailyUploadLimit)rows.push({key:'upload-limit:'+c.id,label:c.name,text:'для авто-YouTube не задан безопасный 24h-limit',page:'youtube'})}for(const j of jobErrors)rows.push({key:'job:'+j.id,label:'VIDEO_'+String(j.number).padStart(3,'0'),text:humanizeError(j.error,'generic').message,page:j.uploadInterruptedAt?'youtube':'production'});return rows.slice(0,5)},[enabled,liveSnapshots,jobErrors,settings.autoUploadYoutube]);
 const primaryUpload=telemetry.active[0],primaryJob=primaryUpload?jobs.find(j=>j.id===primaryUpload.jobId):undefined,primaryChannel=primaryUpload?channels.find(c=>c.id===primaryUpload.channelId):undefined;
 return <><div className="opsKpiGrid" data-testid="dashboard-kpis">
 <Kpi label="КАНАЛЫ" value={channels.length}/>
 <Kpi label="ПОДКЛЮЧЕНО" value={ownerTotals.connected}/>
 <Kpi label="ПОДПИСЧИКИ" value={totalSubscribers==null?'—':totalSubscribers}/>
 <Kpi label="ПРОСМОТРЫ" value={totalViews==null?'—':totalViews}/>
 <Kpi label="OWNER ВИДЕО" value={ownerTotals.refreshed?ownerTotals.ownerVisible:'—'}/>
 <Kpi label="ЛОКАЛЬНО ГОТОВО" value={liveTotals.ready}/>
 <Kpi label="В ОЧЕРЕДИ" value={queue.queued.length}/>
 <Kpi label="ЗАГРУЖАЕТСЯ" value={telemetry.active.length}/>
 <Kpi label="YOUTUBE SCHEDULED" value={ownerTotals.refreshed?scheduled:'—'}/>
 <Kpi label="ОШИБКИ" value={actionableErrors} warn={actionableErrors>0}/>
 </div><div className="opsDashboardGrid">
 <section className="opsCard"><div className="opsCardHead"><div><small>ТЕКУЩИЙ КАНАЛ</small><h2>{active?.name||'Канал не выбран'}</h2></div></div>{active?<div className="opsStats"><span><small>Локально готово</small><b>{activeLive?.readyVideos??activeInv?.free??0}</b></span><span><small>YouTube scheduled</small><b>{activeOwner?activeOwner.scheduledCount:'—'}</b></span><span><small>Private</small><b>{activeOwner?activeOwner.privateCount:'—'}</b></span><span><small>Owner видео</small><b>{activeOwner?activeOwner.total:'—'}</b></span><span><small>Запас локально</small><b>{activeLive?.runwayDays??activeInv?.stockDays??bufferDays(active,jobs)} дн.</b></span></div>:<p className="opsEmpty">Добавьте канал, чтобы видеть оперативное состояние.</p>}<footer><button onClick={()=>setPage('autopilot')}>Командный центр</button><button onClick={()=>setPage('channels')}>Открыть канал</button><button className="primary" onClick={()=>setPage('youtube')}>Открыть публикацию</button></footer></section>
 <section className="opsCard"><div className="opsCardHead"><div><small>ПРОИЗВОДСТВО</small><h2>Локальная очередь</h2></div></div><div className="opsStats production"><span><small>Проектов</small><b>{fmt(jobs.length)}</b></span><span><small>MP4 всего</small><b>{fmt(inventory.globalFinalVideoCount)}</b></span><span><small>Свободно для публикации</small><b>{fmt(liveTotals.ready)}</b></span><span><small>Рендерится</small><b>{fmt(rendering)}</b></span><span><small>Готово к ENDLUME</small><b>{fmt(readyEndlume)}</b></span></div><footer><button className="primary" onClick={()=>setPage('production')}>Открыть Production</button></footer></section>
 <section className="opsCard"><div className="opsCardHead"><div><small>YOUTUBE OWNER INVENTORY</small><h2>Реально на YouTube</h2></div><span>{ownerTotals.allComplete?'полный sync':'snapshot / обновление'}</span></div><div className="opsStats"><span><small>Всего owner-visible</small><b>{ownerTotals.refreshed?fmt(ownerTotals.ownerVisible):'—'}</b></span><span><small>Public</small><b>{ownerTotals.refreshed?fmt(ownerTotals.publicCount):'—'}</b></span><span><small>Private</small><b>{ownerTotals.refreshed?fmt(ownerTotals.privateCount):'—'}</b></span><span><small>Scheduled</small><b>{ownerTotals.refreshed?fmt(ownerTotals.scheduledCount):'—'}</b></span><span><small>Unlisted</small><b>{ownerTotals.refreshed?fmt(ownerTotals.unlistedCount):'—'}</b></span></div><footer><button className="primary" onClick={()=>setPage('youtube')}>Открыть YouTube</button></footer></section>
 <section className="opsCard"><div className="opsCardHead"><div><small>YOUTUBE</small><h2>Загрузка</h2></div></div><div className="opsStats"><span><small>В очереди</small><b>{queue.queued.length}</b></span><span><small>Активно</small><b>{telemetry.active.length}</b></span><span><small>Завершено сегодня</small><b>{completedToday}</b></span><span><small>Ошибок сегодня</small><b>{failedToday}</b></span></div>{primaryUpload?<div className="activeUploadLine"><div><small>{primaryChannel?.name||'Канал'} • {primaryJob?'VIDEO_'+String(primaryJob.number).padStart(3,'0'):'Видео'}</small><b>{primaryUpload.percent==null?'…':Math.round(primaryUpload.percent)+'%'}</b></div><div><span>{formatUploadSpeed(primaryUpload.speedBps)}</span><span>ETA {formatDuration(primaryUpload.etaSeconds)}</span></div><i><em style={{width:Math.max(0,Math.min(100,primaryUpload.percent||0))+'%'}}/></i></div>:<p className="opsEmpty">Активных загрузок нет</p>}<footer><button onClick={()=>setPage('youtube')}>Открыть Upload Center</button></footer></section>
 <section className="opsCard"><div className="opsCardHead"><div><small>ПРОГРЕСС К ЦЕЛИ</small><h2>Каналы по подписчикам</h2></div><span>ориентировочно</span></div><div className="opsAttentionRows">{progressRows.length?progressRows.map(ch=>{const subs=Number(ch.stats?.subscriberCount||0),pct=Math.max(0,Math.min(100,subs/1000*100));return <button key={ch.id} onClick={()=>setPage('channels')}><span><b>{ch.name}</b><small>{fmt(subs)} / 1 000 • осталось {fmt(Math.max(0,1000-subs))} • {pct.toFixed(1)}%</small></span><em>→</em></button>}):<p className="opsEmpty">Нет доступных данных о подписчиках.</p>}</div></section>
 <section className={'opsCard attention '+(attention.length?'warn':'good')}><div className="opsCardHead"><div><small>ТРЕБУЕТ ВНИМАНИЯ</small><h2>{attention.length?attention.length+' важных пунктов':'Всё в порядке'}</h2></div></div>{attention.length?<div className="opsAttentionRows">{attention.map(x=><button key={x.key} onClick={()=>setPage(x.page)}><span><b>{x.label}</b><small>{x.text}</small></span><em>→</em></button>)}</div>:<div className="opsAllGood">✓ Активных ошибок нет</div>}<footer><button onClick={()=>setPage(attention[0]?.page||'youtube')}>{attention.length?'Показать':'Открыть YouTube'}</button></footer></section>
 </div></>;
}
function Kpi({label,value,warn=false}:{label:string;value:number|string;warn?:boolean}){return <div className={'opsKpi '+(warn?'warn':'')}><small>{label}</small><strong>{typeof value==='number'?fmt(value):value}</strong></div>}
