export type ErrorContext='youtube'|'upload'|'metadata'|'thumbnail'|'oauth'|'analytics'|'competitors'|'endlume'|'storage'|'update'|'generic';
export type HumanError={code:string;title:string;message:string;detail:string;retryable:boolean;action?:'retry'|'reconnect'|'wait-reset'|'check-file'|'open-settings'|'resume-upload'};
const lower=(e:unknown)=>String(e??'').toLocaleLowerCase('ru-RU');
function youtubeRootMessage(detail:string){
 const jsonStart=detail.indexOf('{');if(jsonStart>=0){try{const v=JSON.parse(detail.slice(jsonStart));const m=v?.error?.message||v?.error_description;const r=v?.error?.errors?.[0]?.reason;if(m)return `${m}${r?` [${r}]`:''}`}catch{}}
 const quoted=detail.match(/"message"\s*:\s*"([^"]+)"/i)?.[1],reason=detail.match(/"reason"\s*:\s*"([^"]+)"/i)?.[1];if(quoted)return `${quoted}${reason?` [${reason}]`:''}`;
 return detail.replace(/^Error:\s*/i,'').slice(0,500)
}
export function humanizeError(error:unknown,context:ErrorContext='generic'):HumanError{
 const detail=String(error??'Неизвестная ошибка'),s=lower(error);
 if(s.includes('updater_signature_invalid'))return{code:'UPDATER_SIGNATURE_INVALID',title:'Подпись обновления не прошла проверку',message:'Установка заблокирована. Текущая версия VYRON сохранена.',detail,retryable:true,action:'retry'};
 if(s.includes('updater_manifest_fetch_failed'))return{code:'UPDATER_MANIFEST_FETCH_FAILED',title:'Не удалось проверить обновления',message:'Проверьте интернет и повторите позже. Работа VYRON не блокируется.',detail,retryable:true,action:'retry'};
 if(s.includes('updater_archive_download_failed'))return{code:'UPDATER_ARCHIVE_DOWNLOAD_FAILED',title:'Не удалось скачать обновление',message:'Текущая версия VYRON сохранена. Повторите загрузку после восстановления сети.',detail,retryable:true,action:'retry'};
 if(s.includes('updater_restart_failed'))return{code:'UPDATER_RESTART_FAILED',title:'Не удалось перезапустить VYRON',message:'Обновление установлено, но автоматический перезапуск не завершился. Закройте и откройте VYRON вручную.',detail,retryable:true,action:'retry'};
 if(s.includes('updater_install_failed'))return{code:'UPDATER_INSTALL_FAILED',title:'Обновление не установлено',message:'Текущая версия VYRON сохранена. Повторите установку позже.',detail,retryable:true,action:'retry'};
 if(s.includes('oauth_client_setup_required'))return{code:'OAUTH_CLIENT_SETUP_REQUIRED',title:'OAuth Client VYRON не настроен',message:'Настройте текущий Google OAuth Client один раз. После этого существующие каналы можно переподключать через нужный браузер без смены Profile UUID.',detail,retryable:true,action:'open-settings'};
 if(s.includes('oauth_client_secret_required')||s.includes('oauth_client_secret_reimport_required')||s.includes('client_secret is missing'))return{code:'OAUTH_CLIENT_SECRET_REQUIRED',title:'OAuth Client не настроен',message:'Для этого OAuth Client отсутствует client_secret. Настройте текущий Google OAuth Client один раз; не импортируйте credentials.json отдельно для каждого канала.',detail,retryable:true,action:'open-settings'};
 if(s.includes('legacy_reconnect_required')||s.includes('oauth_reconnect_required'))return{code:'OAUTH_RECONNECT_REQUIRED',title:'Требуется переподключить Google',message:'VYRON не будет запрашивать пароль macOS для старой записи Keychain. Переподключите Google один раз — UUID профиля и привязка канала сохранятся.',detail,retryable:true,action:'reconnect'};
 if(s.includes('keychain_auth_failed')||s.includes('osstatus=-25293')||s.includes('osstatus -25293')||s.includes('passphrase you entered is not correct'))return{code:'KEYCHAIN_AUTH_FAILED',title:'Защищённая запись Keychain недоступна без interaction',message:'VYRON заблокировал системный запрос пароля. Для YouTube-профиля используйте переподключение Google вместо ввода пароля macOS.',detail,retryable:true,action:'reconnect'};
 if(s.includes('keychain_user_canceled')||s.includes('osstatus=-128')||s.includes('osstatus -128'))return{code:'KEYCHAIN_CANCELED',title:'Keychain interaction отменён',message:'Обычная работа VYRON больше не должна открывать этот диалог. Для недоступного OAuth-профиля используйте переподключение Google.',detail,retryable:true,action:'reconnect'};
 if(s.includes('keychain_interaction_required')||s.includes('osstatus=-25308')||s.includes('osstatus -25308'))return{code:'KEYCHAIN_INTERACTION_BLOCKED',title:'Keychain требует interaction',message:'VYRON намеренно не показывает системный запрос пароля. Переподключите Google или повторно импортируйте credentials вместо разблокировки legacy-записи.',detail,retryable:true,action:'reconnect'};
 if(s.includes('keychain_autosave_paused'))return{code:'KEYCHAIN_AUTOSAVE_PAUSED',title:'Keychain временно приостановлен',message:'После отказа macOS VYRON больше не вызывает системный пароль при каждом autosave. Проекты и очередь продолжают сохраняться. Для восстановления защищённых OAuth/API-секретов запустите Настройки → Диагностика → macOS Keychain.',detail,retryable:true,action:'open-settings'};
 if(s.includes('keychain_error')||s.includes('keychain read')||s.includes('keychain write')||s.includes('keychain delete'))return{code:'KEYCHAIN',title:'Проблема с macOS Keychain',message:'Локальное состояние VYRON сохранено, но защищённые OAuth/API-секреты требуют проверки. Откройте Настройки → Диагностика → macOS Keychain.',detail,retryable:true,action:'open-settings'};
 if(s.includes('upload_interrupted')||s.includes('можно продолжить позже'))return{code:'UPLOAD_INTERRUPTED',title:'Загрузка прервана',message:'Прогресс сохранён. Подключение можно восстановить и продолжить видео без повторной загрузки с нуля.',detail,retryable:true,action:'resume-upload'};
 if(s.includes('upload_session_expired')||s.includes('resumable session истек'))return{code:'UPLOAD_SESSION_EXPIRED',title:'Сессия YouTube истекла',message:'Старая resumable-сессия больше недействительна. Проверьте канал перед новым запуском, чтобы исключить дубль.',detail,retryable:false,action:'check-file'};
 if(s.includes('upload_file_changed'))return{code:'UPLOAD_FILE_CHANGED',title:'Видео изменилось после начала загрузки',message:'Размер исходного файла изменился. Продолжение старой сессии заблокировано для защиты от повреждения.',detail,retryable:false,action:'check-file'};
 if(s.includes('upload_file_missing')||s.includes('видео не найден')||s.includes('файл недоступен'))return{code:'FILE_MISSING',title:'Файл недоступен',message:'Подключите внешний диск или верните видео в исходный путь.',detail,retryable:true,action:'check-file'};
 if(s.includes('daily upload limit')||s.includes('uploadlimitexceeded')||s.includes('too many uploads')||s.includes('достигнут лимит загрузок'))return{code:'DAILY_UPLOAD_LIMIT',title:'YouTube остановил загрузки этого канала',message:'Достигнут текущий лимит загрузок канала. Партия сохранена; дождитесь восстановления лимита перед продолжением.',detail,retryable:true,action:'retry'};
 if(s.includes('quota')||s.includes('dailylimit')||s.includes('rate limit exceeded'))return{code:'YOUTUBE_QUOTA',title:'YouTube API quota временно недоступна',message:'Операция остановлена до следующего сброса квоты. Локальные Production/ENDLUME функции продолжают работать.',detail,retryable:true,action:'wait-reset'};
 if(s.includes('oauth_refresh_token_required'))return{code:'OAUTH_REFRESH_TOKEN_REQUIRED',title:'Google не вернул refresh token',message:'Google не вернул refresh token. Повторите подключение.',detail,retryable:true,action:'reconnect'};
 if(s.includes('refresh_token_missing')||s.includes('refresh_token отсутствует')||s.includes('refresh token отсутствует'))return{code:'REFRESH_TOKEN_MISSING',title:'Требуется повторное подключение YouTube',message:'Данные канала сохранены. Нужно только снова войти в Google.',detail,retryable:true,action:'reconnect'};
 if(s.includes('invalid_grant')||s.includes('token')&&s.includes('expired')||s.includes('oauth')&&(s.includes('401')||s.includes('unauthor')))return{code:'OAUTH_EXPIRED',title:'Нужно переподключить YouTube',message:'Авторизация Google больше не действует для этого канала. Переподключите OAuth один раз.',detail,retryable:true,action:'reconnect'};
 if(s.includes('403')||s.includes('forbidden')||s.includes('insufficient permission')||s.includes('insufficientpermissions'))return{code:'PERMISSION',title:'YouTube не разрешил эту операцию',message:'Проверьте OAuth-права канала и доступность функции для этого аккаунта.',detail,retryable:false,action:'reconnect'};
 if(s.includes('schedule_in_past')||s.includes('дата публикации уже в прошлом')||s.includes('scheduled publishing time')&&s.includes('future')||s.includes('must be in the future'))return{code:'SCHEDULE_IN_PAST',title:'Дата публикации уже прошла',message:'Дата должна быть позже текущего времени. Обновите расписание с YouTube и повторите.',detail,retryable:true,action:'retry'};
 if(s.includes('publishat')||s.includes('schedule')&&s.includes('invalid')||s.includes('расписание')&&s.includes('не принят'))return{code:'SCHEDULE_REJECTED',title:'YouTube не принял расписание',message:youtubeRootMessage(detail),detail,retryable:true,action:'retry'};
 if(context==='thumbnail'||s.includes('thumbnail')||s.includes('обложк'))return{code:'THUMBNAIL',title:'Обложка не применена',message:'Видео не потеряно. Проверьте файл изображения и повторите только установку обложки.',detail,retryable:true,action:'retry'};
 if(s.includes('timeout')||s.includes('timed out')||s.includes('network')||s.includes('connection')||s.includes('dns')||s.includes('reqwest'))return{code:'NETWORK',title:'Нет стабильного соединения',message:'Проверьте интернет. Если это загрузка видео, VYRON сохранит resumable-сессию когда это возможно.',detail,retryable:true,action:'retry'};
 if(s.includes('endlume'))return{code:'ENDLUME',title:'ENDLUME требует внимания',message:'Проверьте путь к ENDLUME Studio и локальный статус рендера.',detail,retryable:true,action:'open-settings'};
 if(context==='update')return{code:'UPDATE',title:'Обновление не установлено',message:'Текущая версия приложения сохранена. Можно повторить проверку обновлений позже.',detail,retryable:true,action:'retry'};
 if(context==='upload'||context==='youtube'||s.includes('youtube upload')||s.includes('youtube session'))return{code:'YOUTUBE_RUNTIME',title:'YouTube отклонил операцию',message:youtubeRootMessage(detail),detail,retryable:true,action:'retry'};
 return{code:'UNKNOWN',title:'Операция не выполнена',message:'VYRON сохранил текущее состояние. Откройте технические детали только если нужно разобраться глубже.',detail,retryable:true,action:'retry'};
}
export const humanMessage=(error:unknown,context:ErrorContext='generic')=>humanizeError(error,context).message;
export function technicalDetail(error:unknown){return String(error??'')}
