import {describe,it,expect} from 'vitest';
import {humanizeError} from './errorCenter';
import {isOAuthMissingErrorText,resolveOAuthMissingRows,type ErrorHistoryItem} from './errorHistory';
import {buildFinalRecoveryRows,nextReconnectProfileId,reconnectFailure,reconnectQueue} from './authRecoveryFinalCore';

describe('final real-Mac reconnect recovery',()=>{
 it('classifies a genuinely missing refresh token separately from Keychain denial and offers targeted reconnect',()=>{const h=humanizeError('REFRESH_TOKEN_MISSING: refresh_token отсутствует','oauth');expect(h.code).toBe('OAUTH_TOKEN_MISSING');expect(h.title).toBe('OAuth-токен канала отсутствует');expect(h.message).toContain('Переподключение Google');expect(h.action).toBe('reconnect')});
 it('Google callback without refresh_token is explicit failure',()=>{const h=humanizeError('OAUTH_REFRESH_TOKEN_REQUIRED','oauth');expect(h.title).toContain('Google не вернул refresh token');expect(reconnectFailure('OAUTH_REFRESH_TOKEN_REQUIRED').status).toBe('FAILED')});
 it('31 channels can map to 17 unique profiles and queue only missing profiles',()=>{const profiles=Array.from({length:17},(_,i)=>({id:`p${i}`,channelId:`UC${i}`}));const channels=Array.from({length:31},(_,i)=>({id:`c${i}`,name:`Channel ${i}`,youtubeProfileId:`p${i%17}`,youtubeChannelId:`UC${i%17}`}));const states=profiles.map((p,i)=>({profileUuid:p.id,credentialState:(i===0?'CONNECTED':'MISSING') as 'CONNECTED'|'MISSING',canonicalRefreshPresent:i===0,legacyRefreshPresent:false,migrationState:i===0?'MIGRATED':'NOT_STARTED',lastValidationResult:i===0?'PASS':'NOT_RUN'}));const rows=buildFinalRecoveryRows(channels,profiles,states);expect(rows).toHaveLength(17);expect(reconnectQueue(rows)).toHaveLength(16);expect(rows[0].status).toBe('CONNECTED');expect(rows.some(r=>r.channels.length>1)).toBe(true)});
 it('queue moves to next unique missing profile only',()=>{const channels=[{id:'c1',name:'A',youtubeProfileId:'p1',youtubeChannelId:'UC1'},{id:'c2',name:'B',youtubeProfileId:'p2',youtubeChannelId:'UC2'}],profiles=[{id:'p1',channelId:'UC1'},{id:'p2',channelId:'UC2'}],states:any[]=[];const rows=buildFinalRecoveryRows(channels,profiles,states);expect(nextReconnectProfileId(rows,'p1')).toBe('p2')});
 it('stable 2.1.9 screenshot case never maps legacy PRESENT plus NOT_RUN to CONNECTED',()=>{const channels=[{id:'c1',name:'A',youtubeProfileId:'p1',youtubeChannelId:'UC1'}],profiles=[{id:'p1',channelId:'UC1'}],states=[{profileUuid:'p1',canonicalRefreshPresent:false,legacyRefreshPresent:true,migrationState:'RECONNECT_REQUIRED',credentialState:'RECONNECT_REQUIRED' as const,lastValidationResult:'RECONNECT_REQUIRED'}];const rows=buildFinalRecoveryRows(channels,profiles,states);expect(rows[0].status).toBe('RECONNECT REQUIRED');expect(rows[0].status).not.toBe('CONNECTED')});
 it('canonical metadata without real validation is ready-to-validate, never CONNECTED',()=>{const channels=[{id:'c1',name:'A',youtubeProfileId:'p1',youtubeChannelId:'UC1'}],profiles=[{id:'p1',channelId:'UC1'}],states=[{profileUuid:'p1',canonicalRefreshPresent:true,legacyRefreshPresent:false,migrationState:'MIGRATED',credentialState:'CANONICAL_PRESENT_UNVERIFIED' as const,lastValidationResult:'NOT_RUN'}];const rows=buildFinalRecoveryRows(channels,profiles,states);expect(rows[0].status).toBe('CANONICAL_PRESENT_UNVERIFIED');expect(reconnectQueue(rows)).toHaveLength(0)});
 it('wrong channel stays rejected',()=>{expect(reconnectFailure('WRONG_CHANNEL: Expected UC1; Authorized UC2').status).toBe('WRONG CHANNEL')});
 it('successful reconnect resolves old active REFRESH_TOKEN_MISSING errors without deleting history row',()=>{const rows:ErrorHistoryItem[]=[{id:'1',title:'YouTube error',message:'REFRESH_TOKEN_MISSING',technicalDetail:'profile p1',createdAt:1},{id:'2',title:'Other',message:'network',createdAt:2}];const out=resolveOAuthMissingRows(rows,'p1',['UC1'],100);expect(out).toHaveLength(2);expect(out[0].resolvedAt).toBe(100);expect(out[0].resolvedBy).toContain('p1');expect(out[1].resolvedAt).toBeUndefined();expect(isOAuthMissingErrorText(out[0].message)).toBe(true)});
});
