import {beforeEach,describe,expect,it} from 'vitest';
import {readFileSync} from 'node:fs';
import {channelsSharingQuotaProject,googleCloudConsoleUrl,localGoogleProjectDiagnosticPass,maskOAuthClientId,oauthProjectNumber,secretFieldNames} from './googleProjectDiagnostics';
import {registerYoutubeUploadProject,setYoutubeUploadQuotaLimit,youtubeQuotaProjectIdentity,youtubeUploadQuotaState} from './youtubeQuota';
import type {Channel,YoutubeProfile} from './types';
class M{m=new Map<string,string>();getItem(k:string){return this.m.get(k)??null}setItem(k:string,v:string){this.m.set(k,v)}removeItem(k:string){this.m.delete(k)}clear(){this.m.clear()}}
Object.defineProperty(globalThis,'localStorage',{value:new M(),configurable:true});
const ch=(id:string,p:string):Channel=>({id,name:id,slug:id,cadenceDays:4,targetBufferDays:60,publishHour:18,publishMinute:0,language:'EN',genre:'Music',country:'US',minTracks:10,targetDurationMin:120,enabled:true,youtubeProfileId:p,seo:{titlePatterns:[],descriptionTemplate:'',tags:[],banned:[]}});
const pr=(id:string,masked:string):YoutubeProfile=>({id,clientIdMasked:masked,channelTitle:id});
describe('Google Cloud project diagnostics',()=>{
 beforeEach(()=>localStorage.clear());
 it('retrieves/parses only a standard OAuth project-number candidate, never a fake Project ID',()=>{expect(oauthProjectNumber('123456789012-abcdef.apps.googleusercontent.com')).toBe('123456789012');expect(oauthProjectNumber('my-project-123456')).toBeUndefined()});
 it('masks client id while preserving only the numeric project-number candidate',()=>expect(maskOAuthClientId('123456789012-abcdefghijkl.apps.googleusercontent.com')).toBe('123456789012-••••••••••.apps.googleusercontent.com'));
 it('reuses existing projectKey for same-project channel sharing',()=>{const cfg={configured:true,oauthReady:true,projectId:'real-project-id',clientIdMasked:'12345678…abc123',hasSecret:true,hasApiKey:false},profiles=[pr('p1','12345678…abc123'),pr('p2','12345678…abc123'),pr('p3','99999999…zzz999')],channels=[ch('A','p1'),ch('B','p2'),ch('C','p3')],key=youtubeQuotaProjectIdentity(profiles[0],cfg).projectKey;expect(key).toBe('gcp:real-project-id');expect(channelsSharingQuotaProject(channels,profiles,cfg,key).map(x=>x.id)).toEqual(['A','B'])});
 it('keeps different project ledgers isolated and reads configured limit from existing quota storage',()=>{registerYoutubeUploadProject('gcp:a');setYoutubeUploadQuotaLimit('gcp:a',500);registerYoutubeUploadProject('gcp:b');expect(youtubeUploadQuotaState('gcp:a').limit).toBe(500);expect(youtubeUploadQuotaState('gcp:a').limitSource).toBe('user-configured');expect(youtubeUploadQuotaState('gcp:b').limitSource).toBe('default')});
 it('uses official Cloud Console only and safe selector when Project ID is unknown',()=>{expect(googleCloudConsoleUrl()).toBe('https://console.cloud.google.com/projectselector2/apis/dashboard');const u=googleCloudConsoleUrl('real-project-id');expect(new URL(u).hostname).toBe('console.cloud.google.com');expect(u).toContain('project=real-project-id')});
 it('local diagnostics are explicitly zero-API and reject secret-shaped DTOs',()=>{const safe={oauthProfileId:'p1',clientId:'123456789012-abc.apps.googleusercontent.com',projectId:null,projectIdSource:'not-locally-known' as const,youtubeApiRequests:0 as const,keychainSecretsRead:false as const};expect(secretFieldNames(safe)).toEqual([]);expect(localGoogleProjectDiagnosticPass(safe,'oauth-client:x',{resetAt:'2030-01-01T00:00:00Z',limitSource:'default'})).toBe(true);expect(secretFieldNames({...safe,refresh_token:'NO'})).toEqual(['refresh_token'])});
 it('Settings copies exact client_id and opens only URL produced by safe Cloud helper',()=>{const source=readFileSync('src/SettingsOS.tsx','utf8');expect(source).toContain('navigator.clipboard.writeText(googleProjectDiag.clientId)');expect(source).toContain('api.openWeb(googleCloudConsoleUrl(projectId))')});
 it('api command is a direct local invoke, never ytInvoke/Youtube request ledger',()=>{const source=readFileSync('src/api.ts','utf8');expect(source).toContain("youtubeGoogleProjectDiagnostic:(profileId:string)=>invoke<GoogleProjectDiagnosticSafe>('youtube_google_project_diagnostic',{profileId})");expect(source).not.toContain("ytInvoke<GoogleProjectDiagnosticSafe>('youtube_google_project_diagnostic'")});
});
