import React,{useMemo,useState} from 'react';
import {api,type OAuthLocalInventory} from './api';
import {notifyError,notifySuccess} from './notificationCenter';

const windowsUi=()=>typeof navigator!=='undefined'&&/Windows/i.test(navigator.userAgent);
const secureStorageLabel=()=>windowsUi()?'WINDOWS CREDENTIAL MANAGER':'MACOS KEYCHAIN';

function safeReport(r:OAuthLocalInventory){
 const out:string[]=[];
 out.push('VYRON LOCAL OAUTH CREDENTIAL INVENTORY');
 out.push(`APP VERSION: ${r.app_version}`);out.push(`BUNDLE ID: ${r.bundle_id}`);out.push(`${secureStorageLabel()} SERVICE: ${r.service}`);out.push('');
 out.push(`${secureStorageLabel()} ENUMERATION: ${r.enumeration_status}`);out.push(`OSSTATUS: ${r.osstatus??'N/A'}`);out.push(`TOTAL SERVICE ACCOUNTS: ${r.total_service_accounts}`);
 out.push(`REFRESH TOKEN ACCOUNTS: ${r.refresh_token_accounts}`);out.push(`ACCESS TOKEN ACCOUNTS: ${r.access_token_accounts}`);out.push(`CLIENT SECRET ACCOUNTS: ${r.client_secret_accounts}`);out.push(`UNIQUE OAUTH PROFILE UUIDs: ${r.unique_oauth_profile_uuids}`);out.push('');
 out.push(`CURRENT CHANNEL PROFILES: ${r.current_channel_profiles}`);out.push(`CURRENT UUID WITH REFRESH TOKEN: ${r.current_uuid_with_refresh_token}`);out.push(`CURRENT UUID WITHOUT REFRESH TOKEN: ${r.current_uuid_without_refresh_token}`);out.push(`SECURE STORAGE UUID NOT PRESENT IN CURRENT DATABASE: ${r.keychain_uuid_not_present_in_current_database}`);out.push('');
 out.push(`ORPHAN PROFILE UUID COUNT: ${r.orphan_profile_uuid_count}`);out.push(`READABLE ORPHAN REFRESH TOKENS: ${r.readable_orphan_refresh_tokens}`);out.push(`DENIED ORPHAN REFRESH TOKENS: ${r.denied_orphan_refresh_tokens}`);out.push(`FAILED ORPHAN REFRESH TOKENS: ${r.failed_orphan_refresh_tokens}`);out.push('');
 out.push(`V2.0.8 JSON EXACT PATH: ${r.historical_json.exact_path}`);out.push(`V2.0.8 JSON FILE: ${r.historical_json.file}`);out.push(`JSON PROFILES: ${r.historical_json.profiles_in_json}`);out.push(`JSON REFRESH TOKENS: ${r.historical_json.profiles_with_refresh_token}`);if(r.historical_json.error)out.push(`JSON ERROR: ${r.historical_json.error}`);if(r.enumeration_error)out.push(`ENUMERATION ERROR: ${r.enumeration_error}`);out.push('');
 for(const p of r.profiles){out.push(`PROFILE UUID: ${p.profile_uuid}`);out.push(`  CURRENT: ${p.is_current?'YES':'NO'} | ORPHAN: ${p.is_orphan?'YES':'NO'}`);out.push(`  REFRESH TOKEN ACCOUNT: ${p.refresh_token_account}`);out.push(`  ACCESS TOKEN ACCOUNT: ${p.access_token_account}`);out.push(`  CLIENT SECRET ACCOUNT: ${p.client_secret_account}`);out.push(`  REFRESH TOKEN READ: ${p.refresh_token_read}${p.refresh_read_osstatus!=null?` | OSSTATUS ${p.refresh_read_osstatus}`:''}`);if(p.refresh_read_error)out.push(`  READ ERROR: ${p.refresh_read_error}`);}
 out.push('');out.push('SECRET VALUES ARE NOT INCLUDED. NO YOUTUBE/GOOGLE API CALLS WERE PERFORMED.');return out.join('\n');
}
async function copyText(text:string){try{await navigator.clipboard.writeText(text);return}catch{}const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}
export function OAuthInventoryPanel(){const [busy,setBusy]=useState(false),[r,setR]=useState<OAuthLocalInventory|undefined>();const report=useMemo(()=>r?safeReport(r):'',[r]);async function scan(){setBusy(true);try{const next=await api.securityOauthInventory();setR(next);if(next.enumeration_status==='PASS')notifySuccess('Локальные OAuth credentials просканированы',`${next.refresh_token_accounts} refresh-token account(s), ${next.orphan_profile_uuid_count} orphan UUID.`);else notifyError('Secure storage enumeration failed',next.enumeration_error||`OSStatus ${next.osstatus??'unknown'}`)}catch(e){notifyError('OAuth inventory failed',String(e))}finally{setBusy(false)}}async function copy(){if(!report)return;await copyText(report);notifySuccess('Безопасный отчёт скопирован','Token/client_secret values в отчёт не включаются.')}
 return <div className="settingsStack"><section className="settingsCard"><div className="panelHead"><div><small>LOCAL SECURE STORAGE • NO YOUTUBE API</small><h3>OAuth Diagnostics</h3><p>{windowsUi()?'Локальный inventory Windows Credential Manager для OAuth service VYRON.':'Native Security.framework inventory для OAuth service VYRON.'} Google refresh и channel identity не вызываются.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="primary" disabled={busy} onClick={scan}>{busy?'Сканирую…':'Сканировать локальные credentials'}</button><button className="settingsAction" disabled={!r} onClick={copy}>Скопировать безопасный отчёт</button></div></div>{r&&<><div className="settingsInfoGrid"><span><small>Enumeration</small><b>{r.enumeration_status} • OSStatus {r.osstatus??'—'}</b></span><span><small>Service accounts</small><b>{r.total_service_accounts}</b></span><span><small>Refresh token accounts</small><b>{r.refresh_token_accounts}</b></span><span><small>Current profiles</small><b>{r.current_channel_profiles}</b></span><span><small>Current with token</small><b>{r.current_uuid_with_refresh_token}</b></span><span><small>Orphan UUID</small><b>{r.orphan_profile_uuid_count}</b></span><span><small>Readable orphan</small><b>{r.readable_orphan_refresh_tokens}</b></span><span><small>Denied orphan</small><b>{r.denied_orphan_refresh_tokens}</b></span><span><small>JSON profiles / tokens</small><b>{r.historical_json.profiles_in_json} / {r.historical_json.profiles_with_refresh_token}</b></span></div><details open><summary>Безопасный inventory report</summary><pre style={{whiteSpace:'pre-wrap',wordBreak:'break-word',maxHeight:520,overflow:'auto',userSelect:'text'}}>{report}</pre></details></>}</section></div>}
