import React,{useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {runAutopilotCycle} from './autopilotRuntime';
import {createJobsCount,createMissingJobs} from './autopilotCore';
import {useApp} from './store';
import type {Channel,JobStatus,VideoJob} from './types';
import {ProductionWorkspace} from './ProductionWorkspace';
import {ProductionManager} from './ProductionManager';
import {MaterialsManager} from './MaterialsManager';
import {productionManagerApi,type ProductionStorageStatus,type GlobalProjectCleanupPreview} from './productionManagerApi';
import {scanFactualRenderRuntime} from './renderRuntimeEvidence';
import {replaceFactualActiveRenders} from './activeOperationFacts';
import {applyStaleOperationPatches,buildStaleOperationPatches} from './staleOperationReconciliation';
import {seedActiveUploadFacts} from './uploadTelemetry';
import {notifyError,notifySuccess} from './notificationCenter';
import {patchChannelProductionPrefs,resolveProductionRootFromPrefs,useProductionPrefs} from './productionPrefs';
import {sortChannelsAlphabetically} from './channelSort';
import {hasChannelNameConflict} from './channelIdentity';
import {useLiveInventory} from './renderInventoryRuntime';
import {ProductionPipelinePanel} from './ProductionPipelinePanel';
import {ProductionQueueDetails} from './ProductionQueueDetails';

type Tab='queue'|'materials'|'manager';
export function ProductionOS(){
 const channels=useApp(s=>s.channels),addChannel=useApp(s=>s.addChannel),setJobs=useApp(s=>s.setJobs),patchJob=useApp(s=>s.patchJob),patchJobsBatch=useApp(s=>s.patchJobsBatch),settings=useApp(s=>s.settings),toast=useApp(s=>s.toast),liveSnapshots=useLiveInventory(s=>s.snapshots);
 const [prefs,patchPrefs]=useProductionPrefs();
 const tab=(prefs.tab||'queue') as Tab;
 const channelId=(prefs.selectedChannelId&&channels.some(c=>c.id===prefs.selectedChannelId)?prefs.selectedChannelId:channels[0]?.id)||'';
 const setTab=(v:Tab)=>patchPrefs({tab:v});
 const setChannelId=(id:string)=>patchPrefs({selectedChannelId:id});
 const [futureOpen,setFutureOpen]=useState(false),[futureName,setFutureName]=useState(''),[busy,setBusy]=useState(false),[inbox,setInbox]=useState<any>(),[planOpen,setPlanOpen]=useState(false),[planCount,setPlanCount]=useState(30),[planScope,setPlanScope]=useState<'one'|'all'>('one');
 const [section,setSection]=useState<'overview'|'materials'|'builder'>(()=>tab==='materials'?'materials':tab==='manager'?'builder':'overview');
 const c=channels.find(x=>x.id===channelId),liveInventory=c?liveSnapshots[c.id]:undefined;
 const projectRoot=resolveProductionRootFromPrefs(prefs,channelId,settings.workspace);
 const [projectStorage,setProjectStorage]=useState<ProductionStorageStatus|null>(null);
 const [cleanupPreview,setCleanupPreview]=useState<GlobalProjectCleanupPreview|null>(null),[cleanupPhase,setCleanupPhase]=useState<0|1|2>(0),[cleanupConfirmed,setCleanupConfirmed]=useState(false),[cleanupBusy,setCleanupBusy]=useState(false);
 useEffect(()=>{if(!prefs.selectedChannelId&&channels[0])patchPrefs({selectedChannelId:channels[0].id})},[channels.length,prefs.selectedChannelId]);
 useEffect(()=>{let live=true;if(!projectRoot){setProjectStorage(null);return}productionManagerApi.storageStatus(projectRoot).then(x=>{if(live)setProjectStorage(x)}).catch(e=>{if(live)setProjectStorage({path:projectRoot,exists:false,writable:false,external:projectRoot.startsWith('/Volumes/'),freeBytes:null,error:String(e)})});return()=>{live=false}},[projectRoot]);
 function createFutureChannel(){
  const name=futureName.trim().replace(/\s+/g,' ');if(!name)return;
  if(hasChannelNameConflict(channels,name)){toast('Канал с таким названием уже есть в VYRON');return}
  const created=addChannel({name});
  setChannelId(created.id);setInbox(undefined);setFutureName('');setFutureOpen(false);
  toast(`Будущий канал ${name} создан — можно сразу собирать материалы и проекты`)
 }
 async function chooseProjectRoot(scope:'global'|'channel'){const initial=scope==='channel'?(c?prefs.byChannel[c.id]?.productionRoot:undefined)||projectRoot:(prefs.productionRoot||settings.workspace||projectRoot);const requested=await productionManagerApi.chooseProductionRoot(initial||undefined);if(!requested)return;const st=await productionManagerApi.storageStatus(requested);if(!st.exists||!st.writable){toast(st.error||'Выбранная папка проектов недоступна для записи');return}const path=st.path||requested;if(scope==='channel'&&c){patchChannelProductionPrefs(c.id,{productionRoot:path});toast(`Отдельная папка для ${c.name} сохранена`)}else{patchPrefs({productionRoot:path});toast('Основная папка проектов сохранена')}setProjectStorage(st)}
 async function refreshAll(){setBusy(true);try{const jobPatches:Array<{id:string;patch:Partial<VideoJob>}>=[];for(const j of useApp.getState().jobs){const ch=channels.find(x=>x.id===j.channelId);if(!ch||!j.folder||j.status==='SCHEDULED')continue;try{jobPatches.push({id:j.id,patch:await api.refreshJob(j.folder,ch.minTracks)})}catch(e){jobPatches.push({id:j.id,patch:{status:'ERROR',error:String(e)}})}}if(jobPatches.length)patchJobsBatch(jobPatches);const [uploads,sessions,render]=await Promise.all([api.youtubeActiveUploads(),api.youtubeUploadSessions(),scanFactualRenderRuntime(settings.workspace,channels)]);seedActiveUploadFacts(uploads);if(render.reliable)replaceFactualActiveRenders(render.activeJobIds,render.observedAtMs);const patches=buildStaleOperationPatches(useApp.getState().jobs,{uploadsKnown:true,rendersKnown:render.reliable,activeUploadIds:new Set(uploads.map(x=>x.jobId)),activeRenderIds:render.activeJobIds,uploadSessionIds:new Set(sessions.map(x=>x.jobId)),now:new Date().toISOString()});if(patches.length)patchJobsBatch(patches.map(x=>({id:x.jobId,patch:x.patch})));toast(`Статусы производства обновлены • Uploads: ${uploads.length} • Render: ${render.reliable?render.activeJobIds.size:'?'}`)}finally{setBusy(false)}}
 async function maintainBuffer(){if(!settings.workspace){const ws=await api.defaultWorkspace();useApp.getState().patchSettings({workspace:ws})}let added=0;let next=[...useApp.getState().jobs];for(const ch of channels.filter(x=>x.enabled)){const created=createMissingJobs(ch,next);next=[...next,...created];added+=created.length}setJobs(next);await runAutopilotCycle(true);toast(added?`Буфер пополнен: +${added} проектов`:'Буфер уже заполнен')}
 function planTargets(){return planScope==='all'?channels.filter(x=>x.enabled):(c?[c]:[])}
 const preview=useMemo(()=>{const maxByChannel=useApp.getState().jobSummary.maxNumberByChannel;return planTargets().map(ch=>{const max=maxByChannel[ch.id]||0;return {ch,from:max+1,to:max+planCount,count:planCount}})},[planScope,channelId,planCount,channels.length]);
 async function createExact(){const targets=planTargets();if(!targets.length){toast('Выбери канал');return}const n=Math.max(1,Math.min(1000,Math.floor(planCount)));let next=[...useApp.getState().jobs],created=0;for(const ch of targets){const rows=createJobsCount(ch,next,n);next=[...next,...rows];created+=rows.length}setJobs(next);setPlanOpen(false);toast(`Создано ${created} проектов${targets.length>1?` • ${n} на канал`:''}`)}
 async function ensure(){if(!c)return;const r=await api.ensureChannelInbox(settings.workspace,c.name);setInbox(r);return r}
 async function importImages(){if(!c)return;let root=projectRoot;if(!root){root=await api.defaultWorkspace();useApp.getState().patchSettings({workspace:root})}const storage=await productionManagerApi.storageStatus(root);if(!storage.exists||!storage.writable){toast(storage.error||`Папка проектов недоступна: ${root}`);return}const files=await api.chooseImages();if(!files.length)return;const pending=useApp.getState().jobs.filter(j=>j.channelId===c.id&&j.status==='NEED_IMAGE').sort((a,b)=>a.number-b.number);const nums=pending.slice(0,files.length).map(j=>j.number);if(!nums.length){toast('Нет проектов, ожидающих изображение');return}const imported=await api.importImages(root,c.id,c.name,files,c.minTracks,nums);for(const x of imported){const old=useApp.getState().jobs.find(j=>j.channelId===c.id&&j.number===x.number);if(old)useApp.getState().patchJob(old.id,x);else useApp.getState().addJobs([x])}toast(`${files.length} изображений распределено по VIDEO_${String(nums[0]).padStart(3,'0')}…`)}

 const globalCleanupRoots=()=>[settings.workspace,prefs.productionRoot,...Object.values(prefs.byChannel||{}).map(x=>x.productionRoot)].map(x=>(x||'').trim()).filter((x,i,a)=>Boolean(x)&&a.indexOf(x)===i);
 async function beginGlobalProjectCleanup(){const roots=globalCleanupRoots();if(!roots.length){toast('Нет настроенных Production workspace для очистки');return}setCleanupBusy(true);try{const preview=await productionManagerApi.previewGlobalProjectCleanup(roots);setCleanupPreview(preview);setCleanupConfirmed(false);setCleanupPhase(1)}catch(e){notifyError('Не удалось проверить PROJECT-папки',String(e),{operationId:`global-project-cleanup-preview:${Date.now()}`})}finally{setCleanupBusy(false)}}
 async function executeGlobalProjectCleanup(){if(!cleanupPreview||!cleanupConfirmed)return;const roots=globalCleanupRoots();setCleanupBusy(true);try{const r=await productionManagerApi.executeGlobalProjectCleanup(roots,true);setCleanupPhase(0);setCleanupPreview(null);setCleanupConfirmed(false);notifySuccess('PROJECT-папки очищены',`Все каналы • удалено ${r.deletedProjects} • освобождено ${(r.bytesFreed/1024/1024/1024).toFixed(2)} GB • готовые рендеры защищены: ${r.protectedRenders}.`,{operationId:`global-project-cleanup:${Date.now()}`});if(r.errors.length)notifyError('Не все PROJECT-папки удалены',`${r.failedProjects} ошибок. ${r.errors.slice(0,12).join(' | ')}`,{operationId:`global-project-cleanup-errors:${Date.now()}`})}catch(e){notifyError('Глобальная очистка PROJECT-папок не выполнена',String(e),{operationId:`global-project-cleanup-failed:${Date.now()}`})}finally{setCleanupBusy(false)}}
 return <>
  <div className="pageHeader"><div><small>PRODUCTION PIPELINE</small><h1>Производство</h1><p>Материалы → проекты → ENDLUME. YouTube-публикация вынесена в YouTube Center и не дублируется внутри Production.</p></div><div className="headerActions"><button disabled={busy} onClick={refreshAll}>{busy?'Проверяю…':'↻ Обновить статусы'}</button><button onClick={maintainBuffer}>Поддержать буфер</button><button className="danger" disabled={cleanupBusy} onClick={()=>void beginGlobalProjectCleanup()}>{cleanupBusy?'ПРОВЕРЯЮ…':'ОЧИСТИТЬ PROJECT-ПАПКИ ВСЕХ КАНАЛОВ'}</button><button className="primary compactAction" onClick={()=>setPlanOpen(true)}>+ Создать проекты</button></div></div>
  <section className="panel pmStorageUnified"><div className="pmStorageUnifiedMain"><small>ХРАНИЛИЩЕ ПРОЕКТОВ</small><h3>{projectRoot||'Папка не выбрана'}</h3><p>{projectStorage?.external?'Внешний диск':'Внутренний диск'} • {projectStorage?.writable?'запись доступна':'нужно проверить доступ'}{typeof projectStorage?.freeBytes==='number'?` • свободно ${(projectStorage.freeBytes/1024/1024/1024).toFixed(1)} GB`:''}{liveInventory?` • Live ready: ${liveInventory.readyVideos} • ${liveInventory.folderState}`:''}</p></div><div className="pmActions"><button className="primary" onClick={()=>void chooseProjectRoot('global')}>ИЗМЕНИТЬ ПАПКУ</button>{c&&<button onClick={()=>void chooseProjectRoot('channel')}>ОТДЕЛЬНАЯ ПАПКА ДЛЯ КАНАЛА</button>}{projectRoot&&<button onClick={()=>void productionManagerApi.openFolder(projectRoot)}>ОТКРЫТЬ В FINDER</button>}</div>{projectStorage?.error&&<div className="pmStorageError">{projectStorage.error}</div>}</section>
  {section==='overview'&&<ProductionPipelinePanel/>}
  <div className="youtubeTabs productionTabs productionNavThree"><button className={section==='overview'?'active':''} onClick={()=>{setSection('overview');setTab('queue')}}>Обзор</button><button className={section==='materials'?'active':''} onClick={()=>{setSection('materials');setTab('materials')}}>Материалы</button><button className={section==='builder'?'active':''} onClick={()=>{setSection('builder');setTab('manager')}}>Сборка проектов</button></div>
  {tab==='queue'&&<><ProductionWorkspace/><ProductionQueueDetails onCreateProjects={()=>setPlanOpen(true)}/></>}
  {tab==='materials'&&<MaterialsManager/>}
  {tab==='manager'&&<ProductionManager view="builder"/>}
  
   {cleanupPreview&&cleanupPhase===1&&<div className="modalBackdrop" onMouseDown={()=>setCleanupPhase(0)}><section className="confirmModal" onMouseDown={e=>e.stopPropagation()}><small>GLOBAL PROJECT CLEANUP • PREVIEW</small><h2>Очистить PROJECT-папки всех каналов?</h2><p>Eligibility определяется готовым валидным render, а не YouTube upload. Render может находиться в отдельном настроенном Render root, но обязательно вне удаляемой PROJECT-папки.</p><div className="pmChecklist"><span>Каналов<b>{cleanupPreview.scannedChannels}</b></span><span>Найдено проектов<b>{cleanupPreview.foundProjects}</b></span><span>Готовы к удалению<b>{cleanupPreview.eligibleProjects}</b></span><span>Ещё рендерятся<b>{cleanupPreview.skipReasons?.NOT_COMPLETED||0}</b></span><span>Нет render<b>{cleanupPreview.skipReasons?.OUTPUT_MISSING||0}</b></span><span>Render invalid<b>{cleanupPreview.skipReasons?.OUTPUT_INVALID||0}</b></span><span>Небезопасный путь<b>{(cleanupPreview.skipReasons?.UNSAFE_PROJECT_PATH||0)+(cleanupPreview.skipReasons?.OUTPUT_INSIDE_PROJECT||0)}</b></span><span>Уже удалены<b>{cleanupPreview.skipReasons?.ALREADY_REMOVED||0}</b></span></div><div className="cacheNotice"><b>БУДЕТ ПЕРЕМЕЩЕНО В КОРЗИНУ</b><span>{cleanupPreview.eligibleProjects} PROJECT-папок • ~{(cleanupPreview.estimatedBytes/1024/1024/1024).toFixed(2)} GB</span></div><div className="cacheNotice"><b>ГОТОВЫЕ RENDER-ВИДЕО ЗАЩИЩЕНЫ</b><span>{cleanupPreview.protectedRenders} render-файлов останутся на месте. Не удаляются batch/status manifests, upload history, schedule, metadata и настройки.</span></div><footer><button onClick={()=>{setCleanupPhase(0);setCleanupPreview(null)}}>ОТМЕНА</button><button className="primary" disabled={!cleanupPreview.eligibleProjects} onClick={()=>{setCleanupConfirmed(false);setCleanupPhase(2)}}>{cleanupPreview.eligibleProjects?'ПРОДОЛЖИТЬ':'НЕТ БЕЗОПАСНЫХ PROJECT-ПАПОК'}</button></footer></section></div>}
   {cleanupPreview&&cleanupPhase===2&&<div className="modalBackdrop" onMouseDown={()=>setCleanupPhase(1)}><section className="confirmModal" onMouseDown={e=>e.stopPropagation()}><small>FINAL CONFIRMATION</small><h2>Подтвердить удаление PROJECT-папок?</h2><p>Будет перемещено в Корзину: <b>{cleanupPreview.eligibleProjects}</b> проектных папок. Готовые рендеры сохраняются.</p><label className="pmJobCheck"><input type="checkbox" checked={cleanupConfirmed} onChange={e=>setCleanupConfirmed(e.target.checked)}/><span>Я понимаю, что проектные папки будут удалены.</span></label><footer><button disabled={cleanupBusy} onClick={()=>setCleanupPhase(1)}>НАЗАД</button><button className="danger" disabled={!cleanupConfirmed||cleanupBusy} onClick={()=>void executeGlobalProjectCleanup()}>{cleanupBusy?'УДАЛЯЮ…':'УДАЛИТЬ PROJECT-ПАПКИ'}</button></footer></section></div>}
{futureOpen&&<div className="modalBackdrop" onMouseDown={()=>setFutureOpen(false)}><section className="confirmModal" onMouseDown={e=>e.stopPropagation()}><small>FUTURE CHANNEL</small><h2>Будущий канал</h2><p>Напиши название канала, который создашь позже на YouTube. Его можно использовать в Production и ENDLUME уже сейчас.</p><label>Название будущего канала<input autoFocus value={futureName} placeholder="Например: Deep House France 2026" onChange={e=>setFutureName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')createFutureChannel()}}/></label><div className="cacheNotice"><b>БЕЗ YOUTUBE</b><span>После создания канал сразу станет текущим здесь. Когда позже подключишь одноимённый YouTube-канал, VYRON привяжет его к этой же локальной сущности.</span></div><footer><button onClick={()=>setFutureOpen(false)}>Отмена</button><button className="primary" disabled={!futureName.trim()} onClick={createFutureChannel}>Создать будущий канал</button></footer></section></div>}
  {planOpen&&<div className="modalBackdrop" onMouseDown={()=>setPlanOpen(false)}><section className="confirmModal planModal" onMouseDown={e=>e.stopPropagation()}><small>AUTOPILOT PLANNER</small><h2>Сколько проектов создать?</h2><div className="presetRow">{[10,30,50,100].map(n=><button className={planCount===n?'active':''} key={n} onClick={()=>setPlanCount(n)}>{n}</button>)}<label>Своё число<input type="number" min="1" max="1000" value={planCount} onChange={e=>setPlanCount(Math.max(1,Math.min(1000,+e.target.value||1)))}/></label></div><div className="metadataTargetSwitch"><button className={planScope==='one'?'active':''} onClick={()=>setPlanScope('one')}><b>Один канал</b><small>{c?.name||'выбери канал'}</small></button><button className={planScope==='all'?'active':''} onClick={()=>setPlanScope('all')}><b>Все активные</b><small>{planCount} на каждый канал</small></button></div>{planScope==='one'&&<label>Канал<select value={channelId} onChange={e=>setChannelId(e.target.value)}>{sortChannelsAlphabetically(channels).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<div className="planPreview">{preview.map(x=><div key={x.ch.id}><b>{x.ch.name}</b><span>{x.count} проектов • VIDEO_{String(x.from).padStart(3,'0')} → VIDEO_{String(x.to).padStart(3,'0')}</span><small>по {x.ch.cadenceDays} дн. • {x.ch.minTracks} треков/проект</small></div>)}</div><footer><button onClick={()=>setPlanOpen(false)}>Отмена</button><button className="primary" onClick={createExact}>Создать {preview.reduce((n,x)=>n+x.count,0)} проектов</button></footer></section></div>}
 </>
}
