import type {ImportedMetadata} from './metadata';
export type PublishScheduleMode='file'|'daily'|'2/2'|'3/1';
export type PublishWorkspaceDraft={channelId:string;selectedIds:string[];rows:ImportedMetadata[];docx:boolean;thumbs:string[];allowMissingThumbs:boolean;allowDuplicate:boolean;scheduleMode:PublishScheduleMode;scheduleStartDate:string;scheduleTime:string;updatedAt:string};
const KEY='vyron:youtube-publish-workspaces:v2',ACTIVE='vyron:youtube-publish-active-channel:v2',RECENT='vyron:youtube-recent-channels:v1',ACTIVE_EVENT='vyron:youtube-active-channel';
const empty=(channelId:string):PublishWorkspaceDraft=>({channelId,selectedIds:[],rows:[],docx:false,thumbs:[],allowMissingThumbs:false,allowDuplicate:false,scheduleMode:'file',scheduleStartDate:'',scheduleTime:'',updatedAt:new Date(0).toISOString()});
function all():Record<string,PublishWorkspaceDraft>{try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return x&&typeof x==='object'?x:{}}catch{return{}}}
function cleanRow(x:any):ImportedMetadata{return{number:Number.isFinite(+x?.number)?+x.number:undefined,channel:x?.channel||undefined,title:x?.title||undefined,description:x?.description||undefined,tags:Array.isArray(x?.tags)?x.tags.map(String):undefined,publishAt:x?.publishAt||undefined,publishTime:x?.publishTime||undefined,publishTimezone:x?.publishTimezone||undefined,publishUtcOffsetMinutes:Number.isFinite(+x?.publishUtcOffsetMinutes)?+x.publishUtcOffsetMinutes:undefined,source:String(x?.source||'saved-draft')}}
export function loadPublishWorkspace(channelId:string):PublishWorkspaceDraft{if(!channelId)return empty('');const x=all()[channelId];if(!x)return empty(channelId);return{channelId,selectedIds:Array.isArray(x.selectedIds)?x.selectedIds.map(String):[],rows:Array.isArray(x.rows)?x.rows.map(cleanRow):[],docx:Boolean(x.docx),thumbs:Array.isArray(x.thumbs)?x.thumbs.map(String):[],allowMissingThumbs:Boolean(x.allowMissingThumbs),allowDuplicate:Boolean(x.allowDuplicate),scheduleMode:(['daily','2/2','3/1'].includes(String(x.scheduleMode))?String(x.scheduleMode):'file') as PublishScheduleMode,scheduleStartDate:String(x.scheduleStartDate||''),scheduleTime:String(x.scheduleTime||''),updatedAt:x.updatedAt||new Date(0).toISOString()}}
export function savePublishWorkspace(channelId:string,draft:Partial<PublishWorkspaceDraft>){if(!channelId)return loadPublishWorkspace('');const rows=all(),prev=loadPublishWorkspace(channelId),next:PublishWorkspaceDraft={...prev,...draft,channelId,updatedAt:new Date().toISOString()};rows[channelId]=next;try{localStorage.setItem(KEY,JSON.stringify(rows))}catch{}return next}
export function clearPublishWorkspace(channelId:string){const rows=all();delete rows[channelId];try{localStorage.setItem(KEY,JSON.stringify(rows))}catch{}return empty(channelId)}
export function loadActivePublishChannel(){try{return localStorage.getItem(ACTIVE)||''}catch{return''}}
export function loadRecentPublishChannels(){try{const x=JSON.parse(localStorage.getItem(RECENT)||'[]');return Array.isArray(x)?x.map(String).filter(Boolean).slice(0,5):[]}catch{return[]}}
export function saveActivePublishChannel(channelId:string){if(!channelId)return;try{localStorage.setItem(ACTIVE,channelId);const recent=[channelId,...loadRecentPublishChannels().filter(id=>id!==channelId)].slice(0,5);localStorage.setItem(RECENT,JSON.stringify(recent))}catch{}if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent(ACTIVE_EVENT,{detail:{channelId}}))}
export function subscribeActivePublishChannel(listener:(channelId:string)=>void){if(typeof window==='undefined')return()=>{};const onActive=(event:Event)=>{const id=(event as CustomEvent<{channelId?:string}>).detail?.channelId||loadActivePublishChannel();listener(id)};const onStorage=(event:StorageEvent)=>{if(event.key===ACTIVE)listener(event.newValue||'')};window.addEventListener(ACTIVE_EVENT,onActive);window.addEventListener('storage',onStorage);return()=>{window.removeEventListener(ACTIVE_EVENT,onActive);window.removeEventListener('storage',onStorage)}}
