import React,{useEffect,useMemo,useState} from 'react';
import {buildYoutubeQuotaPlan,clearYoutubeQuotaGuard,loadYoutubeQuotaPlan,saveYoutubeQuotaPlan,setYoutubeQuotaLimit,subscribeYoutubeQuota,subscribeYoutubeQuotaClock,youtubeQuotaBucketUsage,youtubeQuotaClockSnapshot,youtubeQuotaState,youtubeQuotaUsage} from './youtubeQuota';
import {readShortsState,shortUploadsToday,subscribeShortsState} from './shortsCore';

export function QuotaMeter({compact=false,defaultChannels=100}:{compact?:boolean;defaultChannels?:number}){
 const [usage,setUsage]=useState(()=>youtubeQuotaUsage()),[guard,setGuard]=useState(()=>youtubeQuotaState()),[clock,setClock]=useState(()=>youtubeQuotaClockSnapshot()),[shortRev,setShortRev]=useState(0);
 const initial=loadYoutubeQuotaPlan();const [channels,setChannels]=useState(initial.channels||Math.max(1,defaultChannels)),[videos,setVideos]=useState(initial.videosPerChannel||30);
 useEffect(()=>{const refresh=()=>{setUsage(youtubeQuotaUsage());setGuard(youtubeQuotaState())};const off=subscribeYoutubeQuota(refresh),offClock=subscribeYoutubeQuotaClock(setClock),offShort=subscribeShortsState(()=>setShortRev(x=>x+1));return()=>{off();offClock();offShort()}},[]);
 const plan=useMemo(()=>buildYoutubeQuotaPlan(channels,videos,usage),[channels,videos,usage.ptDate,usage.limit,usage.used]);const pct=Math.min(100,usage.limit?usage.used/usage.limit*100:0),remaining=Math.max(0,usage.limit-usage.used);const uploadUsage=youtubeQuotaBucketUsage('videoUploads'),shortUploads=shortUploadsToday(readShortsState()),longUploads=Math.max(0,uploadUsage.used-shortUploads);void shortRev;
 const savePlan=()=>{saveYoutubeQuotaPlan({channels,videosPerChannel:videos});setUsage(youtubeQuotaUsage())};
 return <section className={`quotaMeter ${guard.blocked?'blocked':''} ${compact?'compact':''}`}>
  <div className="quotaMeterHead"><div><small>YOUTUBE API QUOTA</small><h3>{guard.blocked?'YouTube API отклонил запрос':'Локальный ledger'}</h3><p>{guard.blocked?'Сервер YouTube вернул quotaExceeded. Число «Осталось» ниже — локальный ledger, а не чтение реального баланса Google. Ручная синхронизация делает один контрольный запрос.':'Расход считается по фактически предпринятым API method calls. Countdown локальный и не обращается к YouTube.'}</p></div><span className={guard.blocked?'bad':'good'}>{guard.blocked?'PROVIDER QUOTA':'TRACKING'}</span></div>
  <div className="quotaMeterStats"><div><small>Использовано</small><b>{usage.used.toLocaleString('ru-RU')}</b><em>из {usage.limit.toLocaleString('ru-RU')}</em></div><div><small>Осталось</small><b>{remaining.toLocaleString('ru-RU')}</b><em>units</em></div><div><small>Сброс</small><b>{clock.localTime}</b><em>00:00 America/Los_Angeles</em></div><div><small>До сброса</small><b>{clock.countdown}</b><em>{clock.localDate}</em></div></div>
  <div className="quotaMeterBar"><i style={{width:`${pct}%`}}/><span>{pct.toFixed(0)}%</span></div>
  <div className="videoUploadsSplit"><span><small>Long Videos</small><b>{longUploads}</b></span><span><small>Shorts</small><b>{shortUploads}</b></span><span><small>Total Video Uploads</small><b>{uploadUsage.used}</b></span></div>
  {!compact&&<><div className="quotaPlannerControls"><label>Дневной лимит<input type="number" min="1000" step="1000" value={usage.limit} onChange={e=>setUsage(setYoutubeQuotaLimit(Math.max(1000,+e.target.value||10000)))}/></label><label>Каналов в плане<input type="number" min="1" max="1000" value={channels} onChange={e=>setChannels(Math.max(1,+e.target.value||1))}/></label><label>Видео / канал<input type="number" min="1" max="1000" value={videos} onChange={e=>setVideos(Math.max(1,+e.target.value||1))}/></label><button onClick={savePlan}>Сохранить план</button>{guard.blocked&&<button onClick={()=>{clearYoutubeQuotaGuard();setGuard(youtubeQuotaState());setUsage(youtubeQuotaUsage())}}>Проверить снова</button>}</div><div className="quotaPlannerSummary"><span><small>≈ на канал</small><b>{plan.perChannel.toLocaleString('ru-RU')} units</b></span><span><small>Нужно всего</small><b>{plan.totalUnits.toLocaleString('ru-RU')}</b></span><span><small>Сегодня</small><b>{plan.todayChannels} каналов</b></span><span><small>Оценка</small><b>≈ {plan.days} дн.</b></span></div><p className="quotaFinePrint">Планировщик — предварительная модель. Перед реальной Metadata/Publish операцией VYRON YT PEISOV показывает отдельный request plan и резервирует рассчитанную квоту. Фактический ledger заполняется только реальными API attempts.</p></>}
 </section>
}
