import {describe,expect,it} from 'vitest';
import type {Channel,ProjectLifecycleRecord,UploadHistoryRecord,VideoJob} from './types';
import {buildReadyVideoInventory,filterReadyVideoInventory,isReadyAvailable} from './readyVideoInventory';

const channel=(id:string,name=id):Channel=>({id,name,slug:id,cadenceDays:1,targetBufferDays:60,publishHour:18,publishMinute:0,language:'RU',genre:'Music',country:'RU',minTracks:10,targetDurationMin:120,enabled:true,seo:{titlePatterns:[],descriptionTemplate:'',tags:[],banned:[]}});
const job=(id:string,channelId:string,status:VideoJob['status']='READY_UPLOAD'):VideoJob=>({id,channelId,number:Number(id.replace(/\D/g,''))||1,folder:`/projects/${id}`,status,createdAt:'2026-09-14T00:00:00Z',tracksCount:10,minTracks:10,finalPath:`/renders/${id}.mp4`,title:id,description:'',tags:[],storageLifecycle:'NEW'});
const lifecycle=(j:VideoJob):Record<string,ProjectLifecycleRecord>=>({[`project-${j.id}`]:{projectId:`project-${j.id}`,jobId:j.id,projectPath:j.folder,renderPath:j.finalPath,status:'RENDERED',renderExists:true,updatedAt:'2026-09-14T00:00:00Z'}});
const uploaded=(j:VideoJob,publishAt='2026-09-13T18:00:00Z'):UploadHistoryRecord=>({id:`h-${j.id}`,jobId:j.id,channelId:j.channelId,youtubeVideoId:`yt-${j.id}`,localFilePath:j.finalPath!,originalFilename:`${j.id}.mp4`,uploadedAt:'2026-09-12T00:00:00Z',fileSize:100,sha256:`sha-${j.id}`,publishAt,status:'UPLOADED'});

describe('VYRON 2.1.6 Ready Video Inventory',()=>{
  it('TEST 1 — groups projects by channelId',()=>{const a=job('1','a'),b=job('2','b'),s=buildReadyVideoInventory([channel('a'),channel('b')],[a,b],[],{...lifecycle(a),...lifecycle(b)},{},[]);expect(s.byChannel.a.free).toBe(1);expect(s.byChannel.b.free).toBe(1);expect(s.items.find(x=>x.jobId==='1')?.channelId).toBe('a')});
  it('TEST 2 — READY final video with authoritative render and no upload/schedule/error is READY_AVAILABLE',()=>{const j=job('1','a');expect(isReadyAvailable(j,[],lifecycle(j),[])).toBe(true);expect(buildReadyVideoInventory([channel('a')],[j],[],lifecycle(j),{},[]).items[0].status).toBe('READY')});
  it('TEST 3 — scheduled is not READY_AVAILABLE',()=>{const j=job('1','a','SCHEDULED');j.publishAt='2026-09-20T18:00:00Z';expect(isReadyAvailable(j,[],lifecycle(j),[])).toBe(false);expect(buildReadyVideoInventory([channel('a')],[j],[],lifecycle(j),{},[],new Date('2026-09-14T00:00:00Z')).byChannel.a.scheduled).toBe(1)});
  it('TEST 4 — factual active upload is not READY_AVAILABLE',()=>{const j=job('1','a');const active=[{jobId:j.id,channelId:'a',status:'UPLOADING' as const,progressPercent:13}];expect(isReadyAvailable(j,[],lifecycle(j),active)).toBe(false);const s=buildReadyVideoInventory([channel('a')],[j],[],lifecycle(j),{},active);expect(s.byChannel.a.uploading).toBe(1);expect(s.items[0].progressPercent).toBe(13)});
  it('TEST 5 — uploaded proof is not READY_AVAILABLE and is published when publishAt passed',()=>{const j=job('1','a');const h=uploaded(j);expect(isReadyAvailable(j,[h],lifecycle(j),[])).toBe(false);expect(buildReadyVideoInventory([channel('a')],[j],[h],lifecycle(j),{},[],new Date('2026-09-14T00:00:00Z')).byChannel.a.published).toBe(1)});
  it('TEST 6 — selected channel counter is independent from global count',()=>{const a1=job('1','a'),a2=job('2','a'),b1=job('3','b');const s=buildReadyVideoInventory([channel('a'),channel('b')],[a1,a2,b1],[],{...lifecycle(a1),...lifecycle(a2),...lifecycle(b1)},{},[]);expect(s.globalFreeCount).toBe(3);expect(s.byChannel.a.free).toBe(2);expect(s.byChannel.b.free).toBe(1);expect(s.globalFinalVideoCount).toBe(3)});
  it('exposes concrete project/video fields and filters by channel status and VIDEO_xxx',()=>{const a=job('7','a'),b=job('8','b');const s=buildReadyVideoInventory([channel('a','ELARA'),channel('b','Lost Highway FM')],[a,b],[],{...lifecycle(a),...lifecycle(b)},{},[]);expect(s.items[0]).toEqual(expect.objectContaining({projectName:'7',filename:'7.mp4'}));expect(filterReadyVideoInventory(s.items,{channelId:'a',status:'READY',query:'VIDEO_007'}).map(x=>x.jobId)).toEqual(['7']);expect(filterReadyVideoInventory(s.items,{channelId:'a',status:'READY',query:'lost'})).toHaveLength(0)});
  it('requires authoritative render existence when lifecycle record exists',()=>{const j=job('1','a'),life=lifecycle(j);life['project-1'].renderExists=false;expect(isReadyAvailable(j,[],life,[])).toBe(false)});
  it('does not double count READY -> active upload -> uploaded transition',()=>{const j=job('1','a'),ch=[channel('a')],life=lifecycle(j);const ready=buildReadyVideoInventory(ch,[j],[],life,{},[]);expect([ready.byChannel.a.free,ready.byChannel.a.uploading,ready.byChannel.a.published]).toEqual([1,0,0]);const active=buildReadyVideoInventory(ch,[j],[],life,{},[{jobId:'1',channelId:'a',status:'UPLOADING'}]);expect([active.byChannel.a.free,active.byChannel.a.uploading,active.byChannel.a.published]).toEqual([0,1,0]);const done=buildReadyVideoInventory(ch,[j],[uploaded(j)],life,{},[],new Date('2026-09-14T00:00:00Z'));expect([done.byChannel.a.free,done.byChannel.a.uploading,done.byChannel.a.published]).toEqual([0,0,1])});
});
