import React,{useMemo,useState} from 'react';
import {useApp} from './store';
import {buildReadyVideoInventory,filterReadyVideoInventory,type InventoryUploadFact,type ReadyVideoInventoryStatus} from './readyVideoInventory';

const statusLabel:Record<ReadyVideoInventoryStatus,string>={READY:'СВОБОДНО',QUEUED:'В ОЧЕРЕДИ',UPLOADING:'ЗАГРУЖАЕТСЯ',SCHEDULED:'ЗАПЛАНИРОВАНО',PUBLISHED:'ОПУБЛИКОВАНО',ERROR:'ОШИБКА'};
const time=(iso?:string)=>iso?new Date(iso).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const eta=(seconds?:number|null)=>seconds==null?'—':seconds<60?`≈ ${Math.max(0,Math.round(seconds))} сек`:`≈ ${Math.max(1,Math.round(seconds/60))} мин`;

export function ReadyVideoInventory({uploadFacts=[]}:{uploadFacts?:InventoryUploadFact[]}){
  const channels=useApp(s=>s.channels),jobs=useApp(s=>s.jobs),history=useApp(s=>s.uploadHistory),lifecycle=useApp(s=>s.projectLifecycle),fingerprints=useApp(s=>s.fingerprintCache);
  const [channelId,setChannelId]=useState(''),[status,setStatus]=useState<'ALL'|ReadyVideoInventoryStatus|'ACTIVE'>('READY'),[query,setQuery]=useState('');
  const snapshot=useMemo(()=>buildReadyVideoInventory(channels.filter(c=>c.enabled),jobs,history,lifecycle,fingerprints,uploadFacts),[channels,jobs,history,lifecycle,fingerprints,uploadFacts]);
  const rows=useMemo(()=>filterReadyVideoInventory(snapshot.items,{channelId,status,query}),[snapshot.items,channelId,status,query]);
  return <section className="panel readyVideoInventory">
    <div className="panelHead"><div><small>READY VIDEO INVENTORY • ZERO API</small><h3>Запас готовых видео</h3><p>Глобальный production count отделён от реального свободного запаса каждого канала.</p></div><div className="inventoryGlobal"><small>ВСЕ КАНАЛЫ</small><b>{snapshot.globalFinalVideoCount} готовых MP4</b><span>{snapshot.globalFreeCount} свободных</span></div></div>
    <div className="inventoryChannelTable"><div className="inventoryChannelRow head"><span>Канал</span><span>Свободно</span><span>Запланировано</span><span>Загружается</span><span>Опубликовано</span><span>Ошибки</span><span>Запас дней</span></div>{snapshot.channels.map(x=><button key={x.channelId} className={`inventoryChannelRow ${channelId===x.channelId?'selected':''}`} onClick={()=>setChannelId(channelId===x.channelId?'':x.channelId)}><span><b>{x.channelName}</b></span><span>{x.free}</span><span>{x.scheduled}</span><span>{x.uploading}</span><span>{x.published}</span><span>{x.errors}</span><span>{x.stockDays} дн.</span></button>)}</div>
    <div className="inventoryFilters"><label>Канал<select value={channelId} onChange={e=>setChannelId(e.target.value)}><option value="">Все каналы</option>{snapshot.channels.map(x=><option key={x.channelId} value={x.channelId}>{x.channelName}</option>)}</select></label><label>Статус<select value={status} onChange={e=>setStatus(e.target.value as any)}><option value="ALL">Все</option><option value="READY">Свободные</option><option value="SCHEDULED">Запланированные</option><option value="ACTIVE">Загружаются</option><option value="PUBLISHED">Опубликованные</option><option value="ERROR">Ошибки</option></select></label><label className="inventorySearch">Поиск<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название / VIDEO_xxx"/></label></div>
    <div className="inventoryVideoList">{rows.length?rows.map(x=><article key={x.jobId} className={`inventoryVideoRow status-${x.status.toLowerCase()}`}><span className="inventoryStatus"><i/>{statusLabel[x.status]}</span><span><b>{x.projectName}</b><small>{x.videoCode} • {x.filename||'production video'}</small></span><span><small>Канал</small><b>{x.channelName}</b></span><span><small>Metadata</small><b>{x.metadataState}</b></span><span><small>PublishAt</small><b>{time(x.publishAt)}</b></span>{(x.status==='UPLOADING'||x.status==='QUEUED')&&<span><small>Upload</small><b>{x.status==='QUEUED'?'Очередь':`${Math.max(0,Math.min(100,x.progressPercent||0)).toFixed(0)}%`}</b><em>{x.status==='UPLOADING'?eta(x.estimatedRemainingSeconds):'ожидает слот'}</em></span>}{x.status==='ERROR'&&<span className="inventoryError"><small>Ошибка</small><b>{x.error||'Активная backend upload job не найдена'}</b></span>}</article>):<div className="empty inventoryEmpty"><b>Нет видео по выбранным фильтрам</b><p>Inventory использует локальный authoritative lifecycle и не делает YouTube API запросов.</p></div>}</div>
  </section>;
}
