export type ReleaseHistoryEntry={date:string;version:string;title:string;items:string[]};
export const VYRON_RELEASE_HISTORY:ReleaseHistoryEntry[]=[
 {date:'10.09.2026',version:'2.1.0',title:'Shorts Factory, Content Buffer & Safe Storage',items:['Publisher продолжает расписание от последнего реального YouTube publishAt и блокирует даты в прошлом.','Error Center показывает техническую ошибку YouTube, позволяет убрать отдельную ошибку и очистить весь счётчик.','Shorts Factory создаёт вертикальные 1080×1920 Shorts из готовых Long Video с отдельными metadata/schedule/recovery.','Content Buffer использует существующий runway канала; Storage Manager получил безопасный архив готовых MP4 без удаления исходного видео.']},
 {date:'09.09.2026',version:'2.0.13',title:'Keychain Recovery & Storage Resilience',items:['Ошибки macOS Keychain больше не превращаются в безликое «VYRON сохранил текущее состояние»: показывается конкретно отказ пароля, отмена или необходимость разблокировки.','Autosave локальных проектов/очереди больше не блокируется из-за недоступного Keychain; секреты по-прежнему не записываются в state.json.','Настройки → Диагностика получили отдельную проверку macOS Keychain через временную тестовую запись.','Добавлены regression-тесты Keychain error mapping, Tauri registration и безопасного state persistence.']},
 {date:'09.09.2026',version:'2.0.12',title:'Hotfix очистки project assets',items:['Исправлена регистрация Tauri-команды cleanup_completed_production_assets: кнопка очистки project assets теперь вызывает реальный backend вместо ошибки «Command not found».','Добавлен regression-тест цепочки UI invoke → Rust command → tauri::generate_handler registration.','Безопасная очистка сохранена: удаляются только image/music завершённых проектов с существующим готовым MP4; Rendered/*.mp4 не удаляются.']},
 {date:'09.09.2026',version:'2.0.11',title:'Production, Publisher и YouTube controls',items:['Publisher: явные режимы «Из файла / Каждый день / 2/2 / 3/1» и время публикации с preview дат.','Publisher: metadata-файл является источником title, description, tags и publishAt непосредственно перед videos.insert.','Publisher: ускорен resumable upload без лишнего стартового probe; увеличен безопасный размер chunk.','Production: двойное подтверждение очистки всех завершённых project assets; готовые MP4 не удаляются.','Topbar: кликабельный центр ошибок с историей.','YouTube quota: стоимость партии, plan/fact/delta и сколько uploads доступно сегодня.','Existing Videos: category, playlist, authoritative backup и verified Undo без скрытого sync.']},
 {date:'09.09.2026',version:'2.0.10',title:'Verified YouTube Apply',items:['После каждого videos.update выполняется обязательный owner-authorized videos.list.','Успех только после проверки title, description, tags, publishAt и privacyStatus.','Quota preflight учитывает обязательную verification read; скрытый fallback update удалён.']},
 {date:'06.09.2026',version:'2.0.9',title:'Security Hardening',items:['OAuth tokens, client secrets и API keys перенесены в macOS Keychain.','Усилена защита локальных state/config/backup файлов и redaction секретов.','Publisher, Production, ENDLUME, Analytics и updater сохранены через regression gate.']}
];
