import React,{useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {useApp} from './store';
import type {YoutubeExistingVideo} from './types';
import {readExistingCache,replaceExistingCacheFromSync,mergeExistingCacheVideos,krasDateKey} from './channelSchedule';
import {beginManualYoutubeQuotaProbe,isYoutubeQuotaError,markYoutubeQuotaExceeded,planYoutubeQuota,releaseYoutubeQuotaReservation,reserveYoutubeQuota,youtubeOperationActualCost,youtubeQuotaMessage,youtubeQuotaState} from './youtubeQuota';
import {markYoutubeCache} from './youtubeCache';
import {sortChannelsAlphabetically} from './channelSort';
import {loadActivePublishChannel,saveActivePublishChannel} from './publishWorkspaceState';
import {buildScheduleOnlyPlan,clearScheduleRecovery,futureScheduledVideos,inferScheduleSummary,kratTime,loadScheduleRecovery,privateNoScheduleVideos,recoveryCounts,recoveryFromPlan,saveScheduleRecovery,type ScheduleOnlyMode,type ScheduleOnlyRecovery,type ScheduleOnlyStartMode} from './scheduleOnly';
import './scheduleOnly.css';

const CACHE_FRESH_MS=6*60*60*1000;
const fmt=(iso?:string)=>iso?new Intl.DateTimeFormat('ru-RU',{timeZone:'Asia/Krasnoyarsk',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(iso))+' KRAT':'—';
export const scheduleChannelSwitchReset=(channelId:string)=>({channelId,videos:[] as YoutubeExistingVideo[],cacheUpdatedAt:'',selectedIds:[] as string[],mode:'daily' as ScheduleOnlyMode,startMode:'preserveFirst' as ScheduleOnlyStartMode,manualStartDate:'',time:'04:00',intervalDays:2,publishDays:3,pauseDays:1,selectFrom:'',confirm:false,recovery:undefined as ScheduleOnlyRecovery|undefined,lastActualCost:null as number|null,selectedOnly:false});
export function ScheduleOS(){
 const channels=useApp(s=>s.channels),toast=useApp(s=>s.toast);
 const [channelId,setChannelId]=useState(()=>{const saved=loadActivePublishChannel();return channels.length?(channels.some(c=>c.id===saved)?saved:channels[0].id):saved}),[videos,setVideos]=useState<YoutubeExistingVideo[]>([]),[cacheUpdatedAt,setCacheUpdatedAt]=useState(''),[busy,setBusy]=useState(false),[selectedIds,setSelectedIds]=useState<string[]>([]),[mode,setMode]=useState<ScheduleOnlyMode>('daily'),[startMode,setStartMode]=useState<ScheduleOnlyStartMode>('preserveFirst'),[manualStartDate,setManualStartDate]=useState(''),[time,setTime]=useState('04:00'),[intervalDays,setIntervalDays]=useState(2),[publishDays,setPublishDays]=useState(3),[pauseDays,setPauseDays]=useState(1),[selectFrom,setSelectFrom]=useState(''),[confirm,setConfirm]=useState(false),[recovery,setRecovery]=useState<ScheduleOnlyRecovery|undefined>(),[lastActualCost,setLastActualCost]=useState<number|null>(null),[selectedOnly,setSelectedOnly]=useState(false);
 const channel=channels.find(c=>c.id===channelId),profileId=channel?.youtubeProfileId||'';
 function loadLocal(id:string){if(!id){setVideos([]);setCacheUpdatedAt('');setSelectedIds([]);setRecovery(undefined);return}const cache=readExistingCache(id);const rows=(cache?.videos||[]).map(v=>({...v,tags:[...(v.tags||[])]}));setVideos(rows);setCacheUpdatedAt(cache?.updatedAt||'');setSelectedIds([]);const summary=inferScheduleSummary(rows);if(summary.time!=='—'&&summary.time!=='разное')setTime(summary.time);setRecovery(loadScheduleRecovery(id));}
 function switchChannel(nextId:string){if(nextId===channelId)return;if(nextId&&!channels.some(c=>c.id===nextId))return;const reset=scheduleChannelSwitchReset(nextId);setVideos(reset.videos);setCacheUpdatedAt(reset.cacheUpdatedAt);setSelectedIds(reset.selectedIds);setMode(reset.mode);setStartMode(reset.startMode);setManualStartDate(reset.manualStartDate);setTime(reset.time);setIntervalDays(reset.intervalDays);setPublishDays(reset.publishDays);setPauseDays(reset.pauseDays);setSelectFrom(reset.selectFrom);setConfirm(reset.confirm);setRecovery(reset.recovery);setLastActualCost(reset.lastActualCost);setSelectedOnly(reset.selectedOnly);if(reset.channelId)saveActivePublishChannel(reset.channelId);setChannelId(reset.channelId)}
 const channelIdsKey=channels.map(c=>c.id).join('\u0000');
 useEffect(()=>{if(!channels.length){loadLocal('');return}if(!channels.some(c=>c.id===channelId)){switchChannel(channels[0].id);return}if(loadActivePublishChannel()!==channelId)saveActivePublishChannel(channelId);loadLocal(channelId)},[channelId,channelIdsKey]);
 const future=useMemo(()=>futureScheduledVideos(videos),[videos]),noSchedule=useMemo(()=>privateNoScheduleVideos(videos),[videos]),summary=useMemo(()=>inferScheduleSummary(videos),[videos]);
 const cacheAge=cacheUpdatedAt?Date.now()-Date.parse(cacheUpdatedAt):Number.POSITIVE_INFINITY,cacheStale=videos.length>0&&(!Number.isFinite(cacheAge)||cacheAge>CACHE_FRESH_MS);
 const plan=useMemo(()=>buildScheduleOnlyPlan({channelId,videos,selectedIds,mode,startMode,manualStartDate,time,intervalDays,publishDays,pauseDays}),[channelId,videos,selectedIds,mode,startMode,manualStartDate,time,intervalDays,publishDays,pauseDays]);
 const quotaPlan=useMemo(()=>planYoutubeQuota([{method:'videos.list',count:plan.writeCount,label:'Schedule pre-read'},{method:'videos.update',count:plan.writeCount,label:'Schedule status write'},{method:'videos.list',count:plan.writeCount,label:'Schedule verify'}],recovery?.operationId),[plan.writeCount,recovery?.operationId]);
 const recoveryStat=recoveryCounts(recovery),selectedSet=new Set(selectedIds),visibleFuture=selectedOnly?future.filter(v=>selectedSet.has(v.id)):future,visibleNoSchedule=selectedOnly?noSchedule.filter(v=>selectedSet.has(v.id)):noSchedule;
 async function sync(){if(!profileId){toast('Сначала привяжи YouTube OAuth к каналу');return}if(!beginManualYoutubeQuotaProbe()){toast(youtubeQuotaMessage());return}setBusy(true);try{const r=await api.youtubeListExisting(profileId,5000);const rows=(r.videos||[]).map(v=>({...v,selected:false}));replaceExistingCacheFromSync(channelId,rows,r);markYoutubeCache('existing',channelId);setVideos(rows);setCacheUpdatedAt(new Date().toISOString());setSelectedIds([]);const x=inferScheduleSummary(rows);if(x.time!=='—'&&x.time!=='разное')setTime(x.time);toast(`Расписание синхронизировано: future scheduled ${x.futureCount}`)}catch(e){if(isYoutubeQuotaError(e)){markYoutubeQuotaExceeded(e);toast(youtubeQuotaMessage())}else toast(String(e))}finally{setBusy(false)}}
 const toggle=(id:string)=>setSelectedIds(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const selectAllFuture=()=>setSelectedIds(future.map(v=>v.id));
 const selectFromDate=()=>{if(!selectFrom)return;setSelectedIds(future.filter(v=>(krasDateKey(v.publishAt)||'')>=selectFrom).map(v=>v.id))};
 function compress(){setMode('daily');setStartMode('preserveFirst')}
 function stretch(){setMode('everyOther');setStartMode('preserveFirst')}
 async function runRecovery(next:ScheduleOnlyRecovery,onlyStatuses:Array<'PENDING'|'FAILED'>){
  if(!profileId||busy)return;const rows=next.rows.filter(r=>r.status!=='APPLIED'&&onlyStatuses.includes(r.status));if(!rows.length){toast('Нет строк для применения');return}
  const q=planYoutubeQuota([{method:'videos.list',count:rows.length,label:'Schedule pre-read'},{method:'videos.update',count:rows.length,label:'Schedule status write'},{method:'videos.list',count:rows.length,label:'Schedule verify'}],next.operationId);if(!q.affordable){toast(`Недостаточно YouTube API quota: нужно ${q.buckets.general.required}, доступно ${q.buckets.general.available}`);return}if(!reserveYoutubeQuota(next.operationId,q)){toast('Quota reservation не создана');return}
  setBusy(true);let current={...next,rows:next.rows.map(r=>({...r}))};saveScheduleRecovery(current);setRecovery({...current});
  try{for(const row of rows){const target=current.rows.find(x=>x.videoId===row.videoId)!;if(target.status==='FAILED')target.status='PENDING';target.error=undefined;saveScheduleRecovery(current);setRecovery({...current,rows:current.rows.map(r=>({...r}))});try{const result=await api.youtubeUpdateExistingSchedule(profileId,row.videoId,row.desiredPublishAt,next.operationId);if(!result.verified){target.status='FAILED';target.error=`YouTube не подтвердил schedule-only: ${(result.mismatches||[]).join(', ')||'verification failed'}`}else{target.status='APPLIED';target.error=undefined;const old=videos.find(v=>v.id===row.videoId);if(old){const updated={...old,publishAt:result.actual?.publishAt||row.desiredPublishAt,privacyStatus:result.actual?.privacyStatus||old.privacyStatus,selected:false};setVideos(prev=>prev.map(v=>v.id===updated.id?updated:v));mergeExistingCacheVideos(channelId,[updated])}}}catch(e){target.status='FAILED';target.error=String(e);if(isYoutubeQuotaError(e)){markYoutubeQuotaExceeded(e);saveScheduleRecovery(current);setRecovery({...current,rows:current.rows.map(r=>({...r}))});break}}saveScheduleRecovery(current);setRecovery({...current,rows:current.rows.map(r=>({...r}))})}
   setLastActualCost(youtubeOperationActualCost(next.operationId).buckets.general);const c=recoveryCounts(current);toast(`Schedule-only: applied ${c.applied}, failed ${c.failed}, pending ${c.pending}`)
  }finally{releaseYoutubeQuotaReservation(next.operationId);setBusy(false)}
 }
 async function apply(){setConfirm(false);if(cacheStale){toast('Cached schedule устарел. Нажми «СИНХРОНИЗИРОВАТЬ С YOUTUBE» перед write.');return}if(plan.blocked||!plan.writeCount){toast(plan.writeCount?'Исправь conflict/past rows перед Apply':'Нет новых дат для записи');return}const rec=recoveryFromPlan(plan);setRecovery(rec);saveScheduleRecovery(rec);await runRecovery(rec,['PENDING'])}
 async function continueRecovery(kind:'pending'|'failed'){if(!recovery)return;if(kind==='failed'){const next={...recovery,rows:recovery.rows.map(r=>r.status==='FAILED'?{...r,status:'PENDING' as const}:r)};saveScheduleRecovery(next);setRecovery(next);await runRecovery(next,['PENDING'])}else await runRecovery(recovery,['PENDING'])}
 const canApply=Boolean(profileId&&plan.writeCount&&!plan.blocked&&!cacheStale&&!busy&&quotaPlan.affordable);
 return <div className="scheduleOnlyPage">
  <div className="pageHeader"><div><small>SCHEDULE-ONLY • ZERO DOCX</small><h1>Расписание канала</h1><p>Меняет только YouTube status.publishAt. Title, description, tags, thumbnail, playlist и upload ledger не участвуют.</p></div><div className="headerActions"><button disabled={busy||!profileId} onClick={sync}>{busy?'Работаю…':'↻ СИНХРОНИЗИРОВАТЬ С YOUTUBE'}</button></div></div>
  <section className="panel scheduleSummary"><div className="scheduleChannelField"><small>Канал</small>{channels.length?<select aria-label="Канал" value={channelId} disabled={busy} onChange={e=>switchChannel(e.target.value)}>{sortChannelsAlphabetically(channels).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>:<b>Нет подключённых каналов</b>}</div><div><small>Видео в cache</small><b>{videos.length}</b></div><div><small>Будущие scheduled/private</small><b>{future.length}</b></div><div><small>Текущий график</small><b>{summary.cadence}</b></div><div><small>Текущее время</small><b>{summary.time==='—'?'—':`${summary.time} KRAT`}</b></div><div><small>Диапазон</small><b>{summary.firstPublishAt&&summary.lastPublishAt?`${fmt(summary.firstPublishAt)} → ${fmt(summary.lastPublishAt)}`:'—'}</b></div><div><small>Cache</small><b className={cacheStale?'bad':'ok'}>{!cacheUpdatedAt?'не синхронизирован':cacheStale?'устарел':new Date(cacheUpdatedAt).toLocaleString('ru-RU')}</b></div></section>
  {recovery&&(recoveryStat.pending||recoveryStat.failed)&&<section className="publisherNotice scheduleRecovery"><b>Расписание изменено частично</b><span>Applied: {recoveryStat.applied} • Failed: {recoveryStat.failed} • Pending: {recoveryStat.pending}</span><div className="headerActions">{recoveryStat.pending>0&&<button disabled={busy} onClick={()=>void continueRecovery('pending')}>ПРОДОЛЖИТЬ</button>}{recoveryStat.failed>0&&<button disabled={busy} onClick={()=>void continueRecovery('failed')}>ПОВТОРИТЬ НЕУДАВШИЕСЯ</button>}<button disabled={busy} onClick={()=>{clearScheduleRecovery(channelId);setRecovery(undefined)}}>СКРЫТЬ RECOVERY</button></div></section>}
  <section className="panel"><div className="panelHead"><div><small>1. VIDEO SELECTION</small><h3>Какие даты менять</h3></div><span>{selectedIds.length} selected</span></div><div className="scheduleActions"><button onClick={selectAllFuture}>Выбрать все будущие</button><button onClick={()=>setSelectedIds([])}>Снять выбор</button><button onClick={()=>setSelectedOnly(x=>!x)}>{selectedOnly?'Показать все':'Только выбранные'}</button><label>Только начиная с<input type="date" value={selectFrom} onChange={e=>setSelectFrom(e.target.value)}/></label><button disabled={!selectFrom} onClick={selectFromDate}>Выбрать от даты</button></div>
   <div className="scheduleVideoList">{visibleFuture.map(v=><label key={v.id}><input type="checkbox" checked={selectedSet.has(v.id)} onChange={()=>toggle(v.id)}/><span><b>{v.title}</b><small>{fmt(v.publishAt)} • SCHEDULED</small></span></label>)}</div>
   {visibleNoSchedule.length>0&&<details><summary>PRIVATE — NO SCHEDULE ({visibleNoSchedule.length}) • включаются только вручную</summary><div className="scheduleVideoList">{visibleNoSchedule.map(v=><label key={v.id}><input type="checkbox" checked={selectedSet.has(v.id)} onChange={()=>toggle(v.id)}/><span><b>{v.title}</b><small>PRIVATE — NO SCHEDULE</small></span></label>)}</div></details>}
  </section>
  <section className="panel"><div className="panelHead"><div><small>2. NEW SCHEDULE</small><h3>Перестроить выбранные даты</h3></div><span>Asia/Krasnoyarsk</span></div><div className="youtubeTabs scheduleModeTabs"><button className={mode==='daily'?'active':''} onClick={()=>setMode('daily')}>Каждый день</button><button className={mode==='everyOther'?'active':''} onClick={()=>setMode('everyOther')}>Через день</button><button className={mode==='interval'?'active':''} onClick={()=>setMode('interval')}>Каждые N дней</button><button className={mode==='pattern'?'active':''} onClick={()=>setMode('pattern')}>3 дня / 1 пауза</button></div><div className="scheduleActions"><button onClick={compress}>СЖАТЬ РАСПИСАНИЕ</button><button onClick={stretch}>РАСТЯНУТЬ РАСПИСАНИЕ</button>{mode==='interval'&&<label>N дней<input type="number" min="1" max="30" value={intervalDays} onChange={e=>setIntervalDays(Math.max(1,+e.target.value||1))}/></label>}{mode==='pattern'&&<><label>Дней публикаций<input type="number" min="1" max="30" value={publishDays} onChange={e=>setPublishDays(Math.max(1,+e.target.value||1))}/></label><label>Пауза<input type="number" min="1" max="30" value={pauseDays} onChange={e=>setPauseDays(Math.max(1,+e.target.value||1))}/></label></>}<label>Время KRAT<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><div className="scheduleStartChoice"><label><input type="radio" checked={startMode==='preserveFirst'} onChange={()=>setStartMode('preserveFirst')}/> Сохранить первую текущую дату {plan.startDate&&<b>{plan.startDate}</b>}</label><label><input type="radio" checked={startMode==='manual'} onChange={()=>setStartMode('manual')}/> Указать первую дату вручную</label>{startMode==='manual'&&<input type="date" value={manualStartDate} onChange={e=>setManualStartDate(e.target.value)}/>}</div></section>
  <section className="panel"><div className="panelHead"><div><small>3. OLD → NEW PREVIEW</small><h3>До API write requests = 0</h3></div><span>{plan.writeCount} changes</span></div><div className="scheduleRequestPlan"><span>Операция <b>Schedule update</b></span><span>Videos <b>{plan.selectedCount}</b></span><span>Metadata writes <b>0</b></span><span>Thumbnail writes <b>0</b></span><span>Playlist writes <b>0</b></span><span>Schedule/status writes <b>{plan.writeCount}</b></span><span>videos.insert <b>0</b></span><span>General quota estimate <b>{quotaPlan.buckets.general.required}</b></span></div><div className="scheduleTableWrap"><table className="scheduleOnlyTable"><thead><tr><th>VIDEO / TITLE</th><th>CURRENT DATE</th><th>NEW DATE</th><th>STATUS</th></tr></thead><tbody>{plan.rows.map(r=><tr key={r.videoId} className={r.state==='READY'||r.state==='ALREADY_CORRECT'?'':'warn'}><td><b>{r.title}</b><small>{r.videoId}</small></td><td>{fmt(r.currentPublishAt)}</td><td>{fmt(r.desiredPublishAt)}</td><td>{r.state}{r.reason&&r.reason!==r.state?<small>{r.reason}</small>:null}</td></tr>)}</tbody></table></div>{cacheStale&&<div className="errorBox">Cached schedule старше 6 часов. Preview локальный, но Apply заблокирован до явной синхронизации.</div>}{plan.conflictCount>0&&<div className="errorBox">Найдены внешние занятые слоты: {plan.conflictCount}. Selected-set old slots конфликтами не считаются.</div>}{plan.pastCount>0&&<div className="errorBox">Есть даты в прошлом/без допустимого старта: {plan.pastCount}. Silent auto-shift отключён.</div>}{lastActualCost!==null&&<div className="successBox">Последняя операция: фактический general API cost {lastActualCost}; videos.insert = 0.</div>}<div className="scheduleApplyBar"><span>Title 0 • Description 0 • Tags 0 • Thumbnail 0 • Publish date/time {plan.writeCount} changes</span><button className="primary" disabled={!canApply} onClick={()=>setConfirm(true)}>ПРИМЕНИТЬ {plan.writeCount} НОВЫЕ ДАТЫ</button></div></section>
  {confirm&&<div className="modalBackdrop" onMouseDown={()=>setConfirm(false)}><section className="confirmModal" onMouseDown={e=>e.stopPropagation()}><small>SCHEDULE-ONLY WRITE CONFIRMATION</small><h2>Будет изменено {plan.writeCount} видео</h2><p>Не изменится: {Math.max(0,videos.length-plan.writeCount)} видео.</p><div className="confirmCounts"><span>Publish date/time <b>{plan.writeCount}</b></span><span>Title <b>0</b></span><span>Description <b>0</b></span><span>Tags <b>0</b></span><span>Thumbnail <b>0</b></span><span>Playlist <b>0</b></span><span>videos.insert <b>0</b></span></div><p>Каждая строка: owner pre-read → videos.update(part=status) → verify read. Snippet не отправляется. Privacy и остальные writable status fields сохраняются.</p><p><b>General quota plan:</b> {quotaPlan.buckets.general.required} units • API calls {quotaPlan.operations.reduce((n,x)=>n+x.count,0)}.</p><footer><button onClick={()=>setConfirm(false)}>ОТМЕНА</button><button className="primary" disabled={!canApply} onClick={()=>void apply()}>ИЗМЕНИТЬ РАСПИСАНИЕ ДЛЯ {plan.writeCount} ВИДЕО</button></footer></section></div>}
 </div>
}
