import {beforeEach,describe,expect,it} from 'vitest';
import type {YoutubeExistingVideo} from './types';
import {buildScheduleOnlyPlan,inferScheduleSummary,isPrivateNoSchedule,loadScheduleRecovery,recoveryCounts,recoveryFromPlan,saveScheduleRecovery} from './scheduleOnly';
import {recordYoutubeApiRequest,registerYoutubeUploadProject,youtubeUploadQuotaState} from './youtubeQuota';
class MemoryStorage{private m=new Map<string,string>();getItem(k:string){return this.m.get(k)??null}setItem(k:string,v:string){this.m.set(k,String(v))}removeItem(k:string){this.m.delete(k)}clear(){this.m.clear()}key(i:number){return [...this.m.keys()][i]??null}get length(){return this.m.size}}
const storage=new MemoryStorage();Object.defineProperty(globalThis,'localStorage',{value:storage,configurable:true});
const now=new Date('2026-09-13T00:00:00.000Z');
const iso=(day:number)=>`2026-09-${String(day).padStart(2,'0')}T21:00:00.000Z`; // 04:00 KRAT next calendar date
const v=(id:string,day?:number,extra:Partial<YoutubeExistingVideo>={}):YoutubeExistingVideo=>({id,position:Number(id.replace(/\D/g,''))||0,title:`Title ${id}`,description:`Desc ${id}`,tags:[`tag-${id}`],categoryId:'10',privacyStatus:'private',publishAt:day?iso(day):undefined,selected:false,...extra});
const base=[v('v1',13),v('v2',15),v('v3',17),v('v4',19)]; // KRAT 14/16/18/20
function plan(videos=base,selectedIds=base.map(x=>x.id),extra:any={}){return buildScheduleOnlyPlan({channelId:'midnight',videos,selectedIds,mode:'daily',startMode:'preserveFirst',time:'04:00',now,...extra})}
describe('VYRON schedule-only S1-S20 planner contracts',()=>{
 beforeEach(()=>storage.clear());
 it('S1 no DOCX/metadata state is required for daily preview',()=>{const p=plan();expect(p.writeCount).toBe(3);expect(p.blocked).toBe(false)});
 it('S2 compresses 14/16/18/20 to 14/15/16/17 KRAT preserving first date',()=>{const p=plan();expect(p.rows.map(x=>x.desiredPublishAt)).toEqual([iso(13),iso(14),iso(15),iso(16)]);expect(p.rows.map(x=>x.state)).toEqual(['ALREADY_CORRECT','READY','READY','READY'])});
 it('S3 stretches daily to every other day',()=>{const daily=[v('v1',13),v('v2',14),v('v3',15),v('v4',16)];const p=plan(daily,daily.map(x=>x.id),{mode:'everyOther'});expect(p.rows.map(x=>x.desiredPublishAt)).toEqual([iso(13),iso(15),iso(17),iso(19)])});
 it('S4 public video is read-only ALREADY_PUBLISHED',()=>{const publicV=v('pub',12,{privacyStatus:'public'});const p=plan([...base,publicV],[...base.map(x=>x.id),'pub']);expect(p.rows.find(x=>x.videoId==='pub')?.state).toBe('ALREADY_PUBLISHED');expect(p.writeCount).toBe(3)});
 it('S5 private no-schedule is never auto-included but can be explicitly scheduled',()=>{const draft=v('draft',undefined);expect(isPrivateNoSchedule(draft)).toBe(true);expect(plan([...base,draft],base.map(x=>x.id)).rows.some(x=>x.videoId==='draft')).toBe(false);const p=plan([...base,draft],[...base.map(x=>x.id),'draft']);expect(p.rows.find(x=>x.videoId==='draft')?.state).toBe('READY')});
 it('S6-S9 planner does not mutate title description tags thumbnail',()=>{const original={...base[1],tags:[...base[1].tags],thumbnail:'thumb'};const p=plan([original],[original.id]);expect(p.rows[0].title).toBe(original.title);expect(original.description).toBe('Desc v2');expect(original.tags).toEqual(['tag-v2']);expect(original.thumbnail).toBe('thumb')});
 it('S10 videos.insert ledger remains unchanged after schedule API methods',()=>{const project='gcp:midnight',ptDate=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).replaceAll('/','-');localStorage.setItem('vyron:youtube-quota-ledger:v3',JSON.stringify({version:3,ptDate,buckets:{general:{limit:10000,used:0,calls:0},videoUploads:{limit:100,used:89,calls:89},search:{limit:100,used:0,calls:0}}}));registerYoutubeUploadProject(project);expect(youtubeUploadQuotaState(project).used).toBe(89);recordYoutubeApiRequest({method:'videos.list',operationId:'schedule-only'});recordYoutubeApiRequest({method:'videos.update',operationId:'schedule-only'});recordYoutubeApiRequest({method:'videos.list',operationId:'schedule-only'});expect(youtubeUploadQuotaState(project).used).toBe(89)});
 it('S11 KRAT converter produces correct UTC instants and inferred time',()=>{const p=plan();expect(p.rows[1].desiredPublishAt).toBe('2026-09-14T21:00:00.000Z');expect(inferScheduleSummary(base,now).time).toBe('04:00')});
 it('S12 past manual start is blocked, never silently shifted',()=>{const p=plan(base,base.map(x=>x.id),{startMode:'manual',manualStartDate:'2026-09-12'});expect(p.blocked).toBe(true);expect(p.pastCount).toBeGreaterThan(0)});
 it('S13 external occupied slot is a conflict',()=>{const external=v('external',14);const p=plan([...base,external],base.map(x=>x.id));expect(p.rows.find(x=>x.videoId==='v2')?.state).toBe('CONFLICT');expect(p.blocked).toBe(true)});
 it('S14 selected-set old slots do not create false conflicts',()=>{const p=plan();expect(p.conflictCount).toBe(0);expect(p.rows.find(x=>x.videoId==='v3')?.desiredPublishAt).toBe(iso(15))});
 it('S15 partial failure recovery preserves applied/failed/pending rows',()=>{const p=plan();const r=recoveryFromPlan(p);r.rows[0].status='APPLIED';r.rows[1].status='FAILED';r.rows[1].error='quota';saveScheduleRecovery(r,storage as any);const loaded=loadScheduleRecovery('midnight',storage as any)!;expect(recoveryCounts(loaded)).toEqual({applied:1,failed:1,pending:1,total:3});expect(loaded.rows[1].desiredPublishAt).toBe(r.rows[1].desiredPublishAt)});
 it('S16 plan hash / operation id is deterministic for restart idempotency',()=>{const a=plan(),b=plan();expect(a.planHash).toBe(b.planHash);expect(a.operationId).toBe(b.operationId);expect(a.operationId.startsWith('schedule-only:midnight:')).toBe(true)});
 it('S17-S19 request model contains only schedule rows and zero metadata concepts',()=>{const p=plan();expect(p.rows.filter(x=>x.state==='READY')).toHaveLength(3);expect(JSON.stringify(p)).not.toContain('description');expect(JSON.stringify(p)).not.toContain('tags');expect(JSON.stringify(p)).not.toContain('thumbnail')});
 it('S20 scheduled private remains private in source model',()=>{const p=plan();expect(p.rows.filter(x=>x.desiredPublishAt).every(x=>x.privacyStatus==='private')).toBe(true)});
 it('supports custom N-day interval and 3/1 pattern without a second timezone converter',()=>{const n=plan(base,base.map(x=>x.id),{mode:'interval',intervalDays:3});expect(n.rows.map(x=>x.desiredPublishAt)).toEqual([iso(13),iso(16),iso(19),iso(22)]);const pat=plan(base,base.map(x=>x.id),{mode:'pattern',publishDays:3,pauseDays:1});expect(pat.rows.map(x=>x.desiredPublishAt)).toEqual([iso(13),iso(14),iso(15),iso(17)])});
});
