import {fileURLToPath} from 'node:url';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {ScheduleOS,scheduleChannelSwitchReset} from './ScheduleOS';
import {buildScheduleOnlyPlan,recoveryFromPlan} from './scheduleOnly';
import type {Channel,YoutubeExistingVideo} from './types';
import {readFileSync} from 'node:fs';

const storeFixture=vi.hoisted(()=>({channels:[] as Channel[],toast:(_message:string)=>{}}));
const activeChannelFixture=vi.hoisted(()=>({id:'',saved:[] as string[]}));
vi.mock('./store',()=>({useApp:(selector:(state:typeof storeFixture)=>unknown)=>selector(storeFixture)}));
vi.mock('./publishWorkspaceState',()=>({loadActivePublishChannel:()=>activeChannelFixture.id,saveActivePublishChannel:(channelId:string)=>{activeChannelFixture.id=channelId;activeChannelFixture.saved.push(channelId)}}));

const ui=readFileSync(fileURLToPath(new URL('./ScheduleOS.tsx',import.meta.url)),'utf8');
const channel=(id:string,name=`Channel ${id}`,profile=`profile-${id}`):Channel=>({id,name,slug:id,cadenceDays:2,targetBufferDays:60,publishHour:4,publishMinute:0,language:'EN',genre:'Music',country:'US',minTracks:10,targetDurationMin:120,enabled:true,youtubeProfileId:profile,seo:{titlePatterns:[],descriptionTemplate:'',tags:[],banned:[]}});
const video=(id:string,publishAt:string):YoutubeExistingVideo=>({id,position:1,title:id,description:'',tags:[],categoryId:'10',privacyStatus:'private',publishAt,selected:false});
function render(channels:Channel[]){storeFixture.channels=channels;return renderToStaticMarkup(React.createElement(ScheduleOS))}

describe('Schedule channel selector isolation',()=>{
 beforeEach(()=>{vi.restoreAllMocks();storeFixture.channels=[];activeChannelFixture.id='';activeChannelFixture.saved=[]});
 it('TEST 1 — renders an explicit channel selector when multiple channels exist',()=>{const html=render([channel('a','Channel A'),channel('b','Channel B')]);expect(html).toContain('aria-label="Канал"');expect(html).toContain('<select');});
 it('TEST 2 — exposes all 31 channels as options',()=>{const channels=Array.from({length:31},(_,i)=>channel(`c${i+1}`,`Channel ${String(i+1).padStart(2,'0')}`));const html=render(channels);expect((html.match(/<option/g)||[])).toHaveLength(31);for(const c of channels)expect(html).toContain(`value="${c.id}"`)});
 it('TEST 3 — switching A → B resets transient A data and changes the plan context to B',()=>{const reset=scheduleChannelSwitchReset('b');expect(reset.channelId).toBe('b');expect(reset.videos).toEqual([]);const b=[video('b1','2026-09-20T21:00:00.000Z')];const plan=buildScheduleOnlyPlan({channelId:reset.channelId,videos:b,selectedIds:['b1'],mode:'daily',startMode:'preserveFirst',time:'04:00',intervalDays:2,publishDays:3,pauseDays:1,now:new Date('2026-09-13T00:00:00Z')});expect(plan.channelId).toBe('b');expect(plan.rows.every(r=>r.videoId.startsWith('b'))).toBe(true)});
 it('TEST 4 — selectedIds are always cleared on channel change',()=>{expect(scheduleChannelSwitchReset('b').selectedIds).toEqual([]);expect(ui).toContain('setSelectedIds(reset.selectedIds)')});
 it('TEST 5 — apply/recovery target is derived from the selected channel, never the previous one',()=>{const b=[video('b1','2026-09-20T21:00:00.000Z'),video('b2','2026-09-22T21:00:00.000Z')];const p=buildScheduleOnlyPlan({channelId:'b',videos:b,selectedIds:['b1','b2'],mode:'daily',startMode:'preserveFirst',time:'04:00',intervalDays:2,publishDays:3,pauseDays:1,now:new Date('2026-09-13T00:00:00Z')});expect(recoveryFromPlan(p).channelId).toBe('b');expect(ui).toContain('saveScheduleRecovery(rec)');expect(ui).toContain('mergeExistingCacheVideos(channelId,[updated])')});
 it('TEST 6 — cache loading is keyed only by current channelId and stale UI cache is cleared before load',()=>{expect(ui).toContain('readExistingCache(id)');expect(ui).toContain("setCacheUpdatedAt(reset.cacheUpdatedAt)");expect(ui).toContain('loadLocal(channelId)')});
 it('TEST 7 — sync resolves OAuth profile from selected channel and writes cache under selected channelId',()=>{expect(ui).toContain("profileId=channel?.youtubeProfileId||''");expect(ui).toContain('api.youtubeListExisting(profileId,5000)');expect(ui).toContain('replaceExistingCacheFromSync(channelId,rows,r)');expect(ui).toContain("onChange={e=>switchChannel(e.target.value)}")});
 it('TEST 8 — A → B → A starts each context with an empty selection and no leaked draft/confirmation state',()=>{for(const id of ['b','a']){const x=scheduleChannelSwitchReset(id);expect(x.channelId).toBe(id);expect(x.selectedIds).toEqual([]);expect(x.confirm).toBe(false);expect(x.recovery).toBeUndefined();expect(x.selectedOnly).toBe(false);expect(x.manualStartDate).toBe('')}});
 it('TEST 9 — persisted Channel B is restored when it exists',()=>{activeChannelFixture.id='b';const html=render([channel('a','Channel A'),channel('b','Channel B')]);expect(html).toContain('<option value="b" selected="">Channel B</option>');expect(ui).toContain('loadActivePublishChannel()')});
 it('TEST 10 — switch persistence only accepts a resolved channel and records A → B → A',()=>{expect(ui).toContain('if(nextId&&!channels.some(c=>c.id===nextId))return');expect(ui).toContain('saveActivePublishChannel(reset.channelId)');for(const id of ['b','a']){const x=scheduleChannelSwitchReset(id);expect(x.channelId).toBe(id)}expect(ui).toContain("onChange={e=>switchChannel(e.target.value)}")});
 it('TEST 11 — remount persistence restores B from the existing application context',()=>{activeChannelFixture.id='b';const channels=[channel('a','Channel A'),channel('b','Channel B')];expect(render(channels)).toContain('<option value="b" selected="">Channel B</option>');expect(render(channels)).toContain('<option value="b" selected="">Channel B</option>')});
 it('TEST 12 — invalid persisted channel falls back safely to the first connected channel',()=>{activeChannelFixture.id='missing';const html=render([channel('a','Channel A'),channel('b','Channel B')]);expect(html).toContain('<option value="a" selected="">Channel A</option>');expect(html).not.toContain('value="missing"')});
 it('TEST 13 — zero channels renders a safe empty state',()=>{activeChannelFixture.id='b';const html=render([]);expect(html).toContain('Нет подключённых каналов');expect(html).not.toContain('<option')});
 it('TEST 14 — one channel remains selectable and normal',()=>{activeChannelFixture.id='missing';const html=render([channel('only','Only Channel')]);expect((html.match(/<option/g)||[])).toHaveLength(1);expect(html).toContain('Only Channel');expect(html).toContain('СИНХРОНИЗИРОВАТЬ С YOUTUBE')});
 it('TEST 15 — restored B keeps selection, cache, sync and apply isolated to B',()=>{activeChannelFixture.id='b';const html=render([channel('a','Channel A'),channel('b','Channel B','profile-b')]);expect(html).toContain('<option value="b" selected="">Channel B</option>');expect(scheduleChannelSwitchReset('b').selectedIds).toEqual([]);expect(ui).toContain('readExistingCache(id)');expect(ui).toContain("profileId=channel?.youtubeProfileId||''");expect(ui).toContain('api.youtubeListExisting(profileId,5000)');expect(ui).toContain('replaceExistingCacheFromSync(channelId,rows,r)');expect(ui).toContain('const rec=recoveryFromPlan(plan)');expect(ui).toContain('mergeExistingCacheVideos(channelId,[updated])')});
 it('TEST 16 — preserves ZERO DOCX / schedule-only write contract',()=>{expect(ui).toContain('SCHEDULE-ONLY • ZERO DOCX');expect(ui).toContain('youtubeUpdateExistingSchedule');expect(ui).toContain('Metadata writes <b>0</b>');expect(ui).toContain('Thumbnail writes <b>0</b>');expect(ui).toContain('Playlist writes <b>0</b>');expect(ui).toContain('videos.insert <b>0</b>')});
});
