import React,{useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {useApp} from './store';
import type {Channel,ChannelAnalytics,ChannelStatisticsSnapshot,YoutubeProfile} from './types';
import {channelStatsStatusLabel,compactChannelStat,exactChannelStat,formatStatsUpdatedAt,subscriberStatLabel} from './youtubeChannelStats';
import {channelStatisticsRefreshRunning,ensureStatisticsBaselines,refreshYoutubeChannelStatistics,refreshYoutubeProfileStatistics,type ChannelStatisticsRefreshProgress,type ChannelStatisticsRefreshSummary} from './youtubeChannelStatsRuntime';
import {classifyYoutubeChannels,latestStatisticsSnapshot,makeStatisticsSnapshot,monthlyStatisticsSummary,snapshotsInPeriod,statisticsDelta,statisticsPeriodRange,type LinkedYoutubeChannel,type StatisticsPeriod} from './youtubeStatisticsCenter';
import {subscribeYoutubeQuota,youtubeQuotaUsage} from './youtubeQuota';

type SortKey='name'|'subscribers'|'views'|'videos'|'sub24'|'sub7'|'views7'|'updated'|'error';
type Group='points'|'day'|'week'|'month';
const DAY=86400000;
const signed=(v?:number)=>v==null?'Недостаточно данных':`${v>0?'+':''}${new Intl.NumberFormat('ru-RU').format(v)}`;
const num=(v?:number)=>v==null?'—':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(v);
const duration=(sec?:number)=>sec==null?'—':`${Math.floor(sec/60)}:${String(Math.round(sec)%60).padStart(2,'0')}`;
const localDate=(iso?:string)=>iso?new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso)):'—';

function currentSnapshot(row:LinkedYoutubeChannel):ChannelStatisticsSnapshot|undefined{
 const s=row.channel.stats,at=s?.statisticsUpdatedAt||s?.updatedAt;if(!s||!at)return;
 return makeStatisticsSnapshot(row.channel,row.profile,s,'LIVE_REFRESH',at);
}
function analyticsArgs(period:StatisticsPeriod,custom:{from:string;to:string}){
 const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate());
 if(period==='today')return{days:1,offset:0,allTime:false};
 if(period==='yesterday')return{days:1,offset:1,allTime:false};
 if(period==='7d')return{days:7,offset:0,allTime:false};
 if(period==='30d')return{days:30,offset:0,allTime:false};
 if(period==='90d')return{days:90,offset:0,allTime:false};
 if(period==='all')return{days:7300,offset:0,allTime:true};
 if(period==='month')return{days:Math.max(1,now.getDate()),offset:0,allTime:false};
 if(period==='prevMonth'){const prevEnd=new Date(now.getFullYear(),now.getMonth(),0),days=prevEnd.getDate(),offset=Math.round((today.getTime()-new Date(prevEnd.getFullYear(),prevEnd.getMonth(),prevEnd.getDate()).getTime())/DAY);return{days,offset,allTime:false}}
 const from=custom.from?new Date(custom.from+'T00:00:00'):today,to=custom.to?new Date(custom.to+'T00:00:00'):today;
 const safeTo=to.getTime()>today.getTime()?today:to,days=Math.max(1,Math.min(7300,Math.floor((safeTo.getTime()-from.getTime())/DAY)+1)),offset=Math.max(0,Math.floor((today.getTime()-safeTo.getTime())/DAY));
 return{days,offset,allTime:false};
}
function groupSnapshots(rows:ChannelStatisticsSnapshot[],group:Group){
 if(group==='points')return rows;
 const map=new Map<string,ChannelStatisticsSnapshot>();
 for(const row of rows){const d=new Date(row.capturedAt);let key='';if(group==='day')key=row.capturedAt.slice(0,10);else if(group==='month')key=row.capturedAt.slice(0,7);else{const x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())),day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));const week=Math.ceil((((x.getTime()-y.getTime())/DAY)+1)/7);key=x.getUTCFullYear()+'-W'+String(week).padStart(2,'0')}map.set(key,row)}
 return [...map.values()].sort((a,b)=>a.capturedAt.localeCompare(b.capturedAt));
}

export function StatisticsCenter(){
 const channels=useApp(s=>s.channels),history=useApp(s=>s.statisticsHistory),activity=useApp(s=>s.activityJournal),updateChannel=useApp(s=>s.updateChannel),toast=useApp(s=>s.toast);
 const [profiles,setProfiles]=useState<YoutubeProfile[]>([]),[loadingProfiles,setLoadingProfiles]=useState(true),[showUnlinked,setShowUnlinked]=useState(false),[refreshing,setRefreshing]=useState(channelStatisticsRefreshRunning()),[progress,setProgress]=useState<ChannelStatisticsRefreshProgress>({done:0,total:0}),[summary,setSummary]=useState<ChannelStatisticsRefreshSummary|null>(null),[oneBusy,setOneBusy]=useState(''),[period,setPeriod]=useState<StatisticsPeriod>('30d'),[custom,setCustom]=useState({from:'',to:''}),[sort,setSort]=useState<SortKey>('name'),[desc,setDesc]=useState(false),[selected,setSelected]=useState(()=>sessionStorage.getItem('vyron:statistics:selected-channel')||''),[group,setGroup]=useState<Group>('day'),[analyticsBusy,setAnalyticsBusy]=useState(false),[,setQuotaTick]=useState(0);
 useEffect(()=>subscribeYoutubeQuota(()=>setQuotaTick(x=>x+1)),[]);
 useEffect(()=>{let live=true;void api.youtubeProfiles().then(async p=>{if(!live)return;setProfiles(p);await ensureStatisticsBaselines(p)}).catch(e=>toast('Не удалось прочитать OAuth profiles: '+String(e))).finally(()=>live&&setLoadingProfiles(false));return()=>{live=false}},[]);
 const classification=useMemo(()=>classifyYoutubeChannels(channels,profiles),[channels,profiles]);
 const eligible=classification.eligible,eligibleIds=new Set(eligible.map(x=>x.channel.id));
 const nonEligible=channels.filter(c=>!eligibleIds.has(c.id));
 const latestBatch=useMemo(()=>activity.filter(x=>x.eventType==='STATS_REFRESH_BATCH'&&x.status!=='STARTED').sort((a,b)=>b.timestamp.localeCompare(a.timestamp))[0],[activity]);
 const quota=youtubeQuotaUsage(),lastUpdated=eligible.map(x=>x.channel.stats?.statisticsUpdatedAt||x.channel.stats?.updatedAt).filter(Boolean).sort().at(-1);

 function metrics(row:LinkedYoutubeChannel){
  const rows=history[row.channel.id]||[],current=currentSnapshot(row);
  return{current,d24:current?statisticsDelta(rows,current,DAY):{insufficient:true},d7:current?statisticsDelta(rows,current,7*DAY):{insufficient:true},d30:current?statisticsDelta(rows,current,30*DAY):{insufficient:true}};
 }
 const sorted=useMemo(()=>eligible.slice().sort((a,b)=>{const am=metrics(a),bm=metrics(b);const val=(row:LinkedYoutubeChannel,m:ReturnType<typeof metrics>)=>sort==='name'?row.channel.name.toLocaleLowerCase('ru-RU'):sort==='subscribers'?(row.channel.stats?.hiddenSubscriberCount?-Infinity:Number(row.channel.stats?.subscriberCount??row.channel.stats?.subscribers??-Infinity)):sort==='views'?Number(row.channel.stats?.viewCount??row.channel.stats?.views??-Infinity):sort==='videos'?Number(row.channel.stats?.videoCount??row.channel.stats?.videos??-Infinity):sort==='sub24'?Number(m.d24.subscriberDelta??-Infinity):sort==='sub7'?Number(m.d7.subscriberDelta??-Infinity):sort==='views7'?Number(m.d7.viewDelta??-Infinity):sort==='updated'?Date.parse(row.channel.stats?.statisticsUpdatedAt||row.channel.stats?.updatedAt||'')||0:row.channel.stats?.syncWarning?1:0;const av=val(a,am),bv=val(b,bm),cmp=typeof av==='string'&&typeof bv==='string'?av.localeCompare(bv,'ru-RU'):Number(av)-Number(bv);return desc?-cmp:cmp}),[eligible,history,sort,desc,channels]);

 async function reloadProfiles(){const p=await api.youtubeProfiles();setProfiles(p);await ensureStatisticsBaselines(p);return p}
 async function refreshAll(){if(refreshing)return;setRefreshing(true);setProgress({done:0,total:eligible.length});try{const result=await refreshYoutubeChannelStatistics(true,setProgress);setSummary(result);await reloadProfiles();toast(result.failed?`Статистика: обновлено ${result.updated}, ошибок ${result.failed}`:`✓ Статистика обновлена: ${result.updated} каналов • API ${result.apiRequests} • quota ${result.quotaUnits}`)}catch(e){toast('Обновление статистики: '+String(e))}finally{setRefreshing(false)}}
 async function refreshOne(row:LinkedYoutubeChannel){if(oneBusy)return;setOneBusy(row.channel.id);try{const result=await refreshYoutubeProfileStatistics(row.profile,`stats-manual:${row.channel.id}:${Date.now()}`);toast(result?`✓ ${row.channel.name}: статистика обновлена`:`⚠ ${row.channel.name}: не удалось обновить, сохранён последний cache`)}finally{setOneBusy('')}}
 function connectChannel(channel:Channel){sessionStorage.setItem('vyron:accounts:focus-channel',channel.id);window.dispatchEvent(new Event('vyron:youtube-accounts'))}
 function openDetail(channelId:string){sessionStorage.setItem('vyron:statistics:selected-channel',channelId);setSelected(channelId)}
 const detail=eligible.find(x=>x.channel.id===selected),detailRows=detail?snapshotsInPeriod(history[detail.channel.id]||[],statisticsPeriodRange(period,new Date(),custom)):[],grouped=groupSnapshots(detailRows,group);
 const now=new Date(),monthly=detail?monthlyStatisticsSummary(history[detail.channel.id]||[],period==='prevMonth'?(now.getMonth()===0?now.getFullYear()-1:now.getFullYear()):now.getFullYear(),period==='prevMonth'?(now.getMonth()+11)%12:now.getMonth()):undefined;
 async function refreshAnalytics(){if(!detail||!detail.profile.analyticsAuthorized||analyticsBusy)return;setAnalyticsBusy(true);try{const args=analyticsArgs(period,custom),a=await api.youtubeAnalytics(detail.profile.id,args.days,args.offset,args.allTime);updateChannel(detail.channel.id,{analytics:a});toast(`✓ Analytics ${detail.channel.name}: обновлено`)}catch(e){toast('Analytics: '+String(e))}finally{setAnalyticsBusy(false)}}

 const knownSubscribers=eligible.filter(x=>!x.channel.stats?.hiddenSubscriberCount&&Number.isFinite(Number(x.channel.stats?.subscriberCount??x.channel.stats?.subscribers))).reduce((n,x)=>n+Number(x.channel.stats?.subscriberCount??x.channel.stats?.subscribers||0),0),hiddenSubscribers=eligible.filter(x=>x.channel.stats?.hiddenSubscriberCount).length,totalViews=eligible.reduce((n,x)=>n+Number(x.channel.stats?.viewCount??x.channel.stats?.views||0),0),totalVideos=eligible.reduce((n,x)=>n+Number(x.channel.stats?.videoCount??x.channel.stats?.videos||0),0);

 return <div className="statisticsCenter">
  <div className="pageHeader"><div><small>MULTI-CHANNEL STATISTICS CENTER</small><h1>Статистика каналов</h1><p>Только реально связанные YouTube Channel ID + OAuth Profile участвуют в API refresh. Local/future/orphan проекты не расходуют quota.</p></div><div className="headerActions"><button disabled={refreshing||loadingProfiles||!eligible.length} className="primary" onClick={()=>void refreshAll()}>{refreshing?`↻ ${progress.done} / ${progress.total}`:'↻ Обновить все подключённые'}</button><button onClick={()=>setShowUnlinked(x=>!x)}>{showUnlinked?'Скрыть непривязанные':'Показать непривязанные'}</button></div></div>
  <div className="metrics six"><div className="metric green"><small>YOUTUBE ПОДКЛЮЧЕНО</small><strong>{eligible.length}</strong><span>unique Channel ID</span></div><div className="metric orange"><small>НЕ ПОДКЛЮЧЕНО</small><strong>{channels.length-eligible.length}</strong><span>0 stats API calls</span></div><div className="metric blue"><small>ОБНОВЛЕНО</small><strong>{summary?`${summary.updated} / ${summary.requested}`:latestBatch?`${latestBatch.details?.updatedChannels||0} / ${latestBatch.details?.requestedChannels||0}`:'—'}</strong><span>последний batch</span></div><div className="metric red"><small>ОШИБКИ</small><strong>{summary?.failed??latestBatch?.details?.failedChannels??0}</strong><span>cache не стирается</span></div><div className="metric purple"><small>ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ</small><strong>{lastUpdated?new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(lastUpdated)):'—'}</strong><span>{lastUpdated?new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit'}).format(new Date(lastUpdated)):'нет данных'}</span></div><div className="metric cyan"><small>QUOTA GENERAL</small><strong>{quota.used.toLocaleString('ru-RU')} / {quota.limit.toLocaleString('ru-RU')}</strong><span>method-level ledger</span></div></div>
  <section className="panel"><div className="panelHead"><div><small>NETWORK TOTALS</small><h3>Только подключённые каналы</h3></div></div><div className="syncAudit"><span>Known subscribers <b>{knownSubscribers.toLocaleString('ru-RU')}</b></span><span>Hidden subscribers <b>{hiddenSubscribers} каналов</b></span><span>Total views <b>{totalViews.toLocaleString('ru-RU')}</b></span><span>Public videos <b>{totalVideos.toLocaleString('ru-RU')}</b></span><span>Orphans <b>{classification.orphans.length}</b></span><span>Duplicate IDs <b>{classification.duplicates.length}</b></span></div></section>
  <section className="panel"><div className="panelHead"><div><small>CHANNEL STATISTICS</small><h3>{eligible.length} подключённых</h3></div><div className="headerActions"><select value={sort} onChange={e=>setSort(e.target.value as SortKey)}><option value="name">Канал</option><option value="subscribers">Подписчики</option><option value="views">Просмотры</option><option value="videos">Видео</option><option value="sub24">Подписчики 24ч</option><option value="sub7">Подписчики 7д</option><option value="views7">Просмотры 7д</option><option value="updated">Последнее обновление</option><option value="error">Ошибка</option></select><button onClick={()=>setDesc(x=>!x)}>{desc?'↓':'↑'}</button></div></div>
   <div className="runwayTable"><div className="runwayRow runwayTh" style={{gridTemplateColumns:'2fr repeat(8,minmax(90px,1fr)) 120px'}}><span>Канал</span><span>Подписчики</span><span>24ч</span><span>7д</span><span>30д</span><span>Всего просмотров</span><span>Views 24ч / 7д / 30д</span><span>Видео</span><span>Обновлено</span><span>Действие</span></div>
   {sorted.map(row=>{const m=metrics(row),s=row.channel.stats,busy=oneBusy===row.channel.id;return <div className="runwayRow" style={{gridTemplateColumns:'2fr repeat(8,minmax(90px,1fr)) 120px'}} key={row.channel.id}><span className="runwayChannel"><b>{row.channel.name}</b><small>{s?.handle||row.youtubeChannelId}</small><em className="good">BASIC DATA ✓</em></span><span><b>{subscriberStatLabel(s)}</b></span><span>{m.d24.insufficient?'Недостаточно данных':signed(m.d24.subscriberDelta)}</span><span>{m.d7.insufficient?'Недостаточно данных':signed(m.d7.subscriberDelta)}</span><span>{m.d30.insufficient?'Недостаточно данных':signed(m.d30.subscriberDelta)}</span><span><b>{exactChannelStat(s?.viewCount??s?.views)}</b></span><span><small>{m.d24.insufficient?'—':signed(m.d24.viewDelta)} / {m.d7.insufficient?'—':signed(m.d7.viewDelta)} / {m.d30.insufficient?'—':signed(m.d30.viewDelta)}</small></span><span>{exactChannelStat(s?.videoCount??s?.videos)}</span><span><small>{formatStatsUpdatedAt(s?.statisticsUpdatedAt||s?.updatedAt)}</small><em className={s?.syncWarning?'warn':'good'}>{channelStatsStatusLabel(s,busy)}</em></span><span><button disabled={busy||refreshing} onClick={()=>void refreshOne(row)}>{busy?'↻':'↻'}</button><button onClick={()=>openDetail(row.channel.id)}>Подробнее</button></span></div>})}
   {!eligible.length&&!loadingProfiles&&<div className="empty"><b>Подключённых YouTube-каналов нет</b><p>Local/future projects не считаются YouTube-каналами и не расходуют API quota.</p></div>}</div>
  </section>
  {showUnlinked&&<section className="panel"><div className="panelHead"><div><small>LOCAL / UNLINKED</small><h3>Не участвуют в Refresh All</h3></div></div>{nonEligible.map(c=>{const reason=classification.orphans.some(x=>x.id===c.id)?'ORPHAN_MAPPING':classification.mismatched.some(x=>x.id===c.id)?'CHANNEL_MISMATCH':classification.duplicates.some(x=>x.channelIds.includes(c.id))?'DUPLICATE_CHANNEL_ID':'YOUTUBE_NOT_LINKED';return <div className="actionRow" key={c.id}><span>○</span><div><b>{c.name}</b><small>YouTube: НЕ ПОДКЛЮЧЁН • {reason} • API calls: 0</small></div><button onClick={()=>connectChannel(c)}>Подключить YouTube</button></div>})}</section>}
  {detail&&<section className="panel"><div className="panelHead"><div><small>CHANNEL DETAIL</small><h3>{detail.channel.name}</h3><p>{detail.youtubeChannelId}</p></div><button onClick={()=>{setSelected('');sessionStorage.removeItem('vyron:statistics:selected-channel')}}>Закрыть</button></div>
   <div className="publishToolbar"><select value={period} onChange={e=>setPeriod(e.target.value as StatisticsPeriod)}><option value="today">Сегодня</option><option value="yesterday">Вчера</option><option value="7d">7 дней</option><option value="30d">30 дней</option><option value="month">Этот месяц</option><option value="prevMonth">Прошлый месяц</option><option value="90d">90 дней</option><option value="all">Всё время VYRON</option><option value="custom">Произвольный период</option></select>{period==='custom'&&<><input type="date" value={custom.from} onChange={e=>setCustom(x=>({...x,from:e.target.value}))}/><input type="date" value={custom.to} onChange={e=>setCustom(x=>({...x,to:e.target.value}))}/></>}<select value={group} onChange={e=>setGroup(e.target.value as Group)}><option value="points">Все точки</option><option value="day">По дням</option><option value="week">По неделям</option><option value="month">По месяцам</option></select></div>
   <div className="metrics six"><div className="metric green"><small>SUBSCRIBERS</small><strong>{subscriberStatLabel(detail.channel.stats)}</strong></div><div className="metric blue"><small>TOTAL VIEWS</small><strong>{compactChannelStat(detail.channel.stats?.viewCount??detail.channel.stats?.views)}</strong></div><div className="metric purple"><small>PUBLIC VIDEOS</small><strong>{compactChannelStat(detail.channel.stats?.videoCount??detail.channel.stats?.videos)}</strong></div><div className="metric cyan"><small>BASIC DATA</small><strong>✓</strong></div><div className="metric orange"><small>ANALYTICS</small><strong>{detail.profile.analyticsAuthorized?'✓':'NO SCOPE'}</strong></div><div className="metric"><small>MONETARY</small><strong>{detail.profile.monetaryAuthorized?'✓':'OPTIONAL'}</strong></div></div>
   {monthly&&(period==='month'||period==='prevMonth')&&<div className="syncAudit"><span>Данные с <b>{new Date(monthly.coverageFrom).toLocaleDateString('ru-RU')}</b></span><span>до <b>{new Date(monthly.coverageTo).toLocaleDateString('ru-RU')}</b></span><span>Subscribers Δ <b>{signed(monthly.subscriberChange)}</b></span><span>Views recorded Δ <b>{signed(monthly.viewChange)}</b></span><span>Videos Δ <b>{signed(monthly.videoChange)}</b></span><span>Coverage <b>{monthly.completeMonth?'полный месяц':'частичный'}</b></span></div>}
   <div className="todayGrid"><section><div className="panelHead"><div><small>STATISTICS HISTORY</small><h3>{grouped.length} точек</h3></div></div>{grouped.slice().reverse().slice(0,200).map(x=><div className="actionRow" key={x.snapshotId}><span>◷</span><div><b>{localDate(x.capturedAt)}</b><small>Subscribers: {x.hiddenSubscriberCount?'Скрыто':exactChannelStat(x.subscriberCount)} • Views: {exactChannelStat(x.viewCount)} • Videos: {exactChannelStat(x.videoCount)}</small></div><em>{x.source}</em></div>)}{!grouped.length&&<p>Для выбранного периода данных пока недостаточно.</p>}</section>
   <section><div className="panelHead"><div><small>PERIOD ANALYTICS</small><h3>YouTube Analytics API</h3></div>{detail.profile.analyticsAuthorized&&<button disabled={analyticsBusy} onClick={()=>void refreshAnalytics()}>{analyticsBusy?'↻ Обновление…':'↻ Обновить Analytics'}</button>}</div>{!detail.profile.analyticsAuthorized?<div className="publisherNotice"><b>Нет разрешения Analytics</b><p>Basic statistics продолжают работать. VYRON не запускает OAuth reconnect автоматически.</p></div>:<AnalyticsFacts analytics={detail.channel.analytics}/>}</section></div>
  </section>}
 </div>;
}

function AnalyticsFacts({analytics:a}:{analytics?:ChannelAnalytics}){
 if(!a)return <p>Analytics ещё не синхронизирована для выбранного канала.</p>;
 return <><div className="channelMetricsGrid analyticsKpis"><span><small>Views period</small><b>{a.views.toLocaleString('ru-RU')}</b></span><span><small>Watch time</small><b>{num(a.watchMinutes/60,1)} ч</b></span><span><small>Avg duration</small><b>{duration(a.averageViewDuration)}</b></span><span><small>Avg %</small><b>{num(a.averageViewPercentage,1)}%</b></span><span><small>Subscribers gained</small><b>+{a.subscribersGained.toLocaleString('ru-RU')}</b></span><span><small>Subscribers lost</small><b>-{a.subscribersLost.toLocaleString('ru-RU')}</b></span><span><small>Likes</small><b>{a.likes.toLocaleString('ru-RU')}</b></span><span><small>Comments</small><b>{a.comments.toLocaleString('ru-RU')}</b></span><span><small>Shares</small><b>{a.shares.toLocaleString('ru-RU')}</b></span>{a.engagedViews!=null&&<span><small>Engaged views</small><b>{a.engagedViews.toLocaleString('ru-RU')}</b></span>}</div><small>Analytics updated: {localDate(a.updatedAt)} • period {a.periodDays} days</small></>;
}
