import type {FingerprintCacheEntry,ProjectLifecycleRecord,UploadHistoryRecord,VideoJob} from './types';

export const STORAGE_STATE_VERSION=9;
export function successfulUploadForHash(history:UploadHistoryRecord[],sha256:string){const h=sha256.trim().toLowerCase();return history.slice().reverse().find(x=>x.status==='UPLOADED'&&Boolean(x.youtubeVideoId)&&x.sha256.toLowerCase()===h)}
export function duplicateUploadIds(jobs:VideoJob[],fingerprints:Record<string,{sha256:string}>,history:UploadHistoryRecord[],allowOverrideIds:Set<string>=new Set()){return jobs.filter(j=>{if(allowOverrideIds.has(j.id))return false;const fp=fingerprints[j.id];return Boolean(fp&&successfulUploadForHash(history,fp.sha256))}).map(j=>j.id)}
export function recordVerifiedUpload(history:UploadHistoryRecord[],record:Omit<UploadHistoryRecord,'id'|'status'>){if(!record.youtubeVideoId?.trim())throw new Error('VERIFIED_VIDEO_ID_REQUIRED');if(!record.sha256?.trim())throw new Error('SHA256_REQUIRED');return[...history,{...record,processingState:record.processingState||'UPLOAD_ACCEPTED',id:crypto.randomUUID(),status:'UPLOADED' as const}]}
export function updateUploadProcessing(history:UploadHistoryRecord[],jobId:string,patch:Partial<Pick<UploadHistoryRecord,'processingState'|'processingCheckedAt'|'processingStatus'|'processingError'|'readyAt'|'identityVerifiedAt'>>){return history.map(x=>x.jobId===jobId&&x.status==='UPLOADED'?{...x,...patch}:x)}
export function cleanupEligibleUpload(x:UploadHistoryRecord,job?:VideoJob){if(x.status!=='UPLOADED'||x.processingState!=='READY'||x.remoteExists===false||!x.youtubeVideoId?.trim()||!x.profileId?.trim()||!x.localFilePath?.trim()||!x.sha256?.trim()||Boolean(x.trashedAt)||x.sourceLifecycle!=='PRESENT')return false;if(job){if(job.id!==x.jobId||job.finalPath!==x.localFilePath)return false;if(job.uploadFingerprint&&job.uploadFingerprint.toLowerCase()!==x.sha256.toLowerCase())return false}return true}
export function cacheHit(entry:FingerprintCacheEntry|undefined,size:number,mtimeMs:number){return Boolean(entry&&entry.size===size&&entry.mtimeMs===mtimeMs&&/^[a-f0-9]{64}$/i.test(entry.sha256))}
export function nextProjectLifecycle(base:ProjectLifecycleRecord,history:UploadHistoryRecord[]){const proof=base.jobId?history.slice().reverse().find(x=>x.jobId===base.jobId&&x.status==='UPLOADED'&&x.processingState==='READY'&&Boolean(x.youtubeVideoId)):undefined;return{...base,status:(base.renderExists&&base.renderPath&&proof?'SAFE_TO_CLEAN':'RENDERED') as ProjectLifecycleRecord['status'],youtubeVideoId:proof?.youtubeVideoId,uploadedAt:proof?.uploadedAt,updatedAt:new Date().toISOString()}}
export function canSafelyCleanProject(x:ProjectLifecycleRecord){return x.status==='SAFE_TO_CLEAN'&&Boolean(x.renderExists&&x.renderPath&&x.youtubeVideoId&&x.jobId)}
export function uploadedJobs(history:UploadHistoryRecord[]){return new Set(history.filter(x=>x.status==='UPLOADED'&&Boolean(x.youtubeVideoId)).map(x=>x.jobId))}
export function markHistoryTrashed(history:UploadHistoryRecord[],jobId:string,at=new Date().toISOString(),trashOperationId?:string){return history.map(x=>x.jobId===jobId&&x.status==='UPLOADED'&&x.processingState==='READY'&&!x.trashedAt?{...x,trashedAt:at,trashOperationId,sourceLifecycle:'TRASHED_BY_VYRON',sourceCheckedAt:at}:x)}
export function markHistorySourceState(history:UploadHistoryRecord[],id:string,sourceLifecycle:UploadHistoryRecord['sourceLifecycle'],at=new Date().toISOString()){return history.map(x=>x.id===id?{...x,sourceLifecycle,sourceCheckedAt:at}:x)}
