import {describe,it,expect} from 'vitest';
import {MultiChannelUploadQueue,type ImmutableUploadJob} from './uploadQueue';

const wait=()=>new Promise<void>(r=>setTimeout(r,0));
function spec(n:number,channelId:string,profileId=`profile-${channelId}`):ImmutableUploadJob{return{jobId:`j${n}`,projectId:`p${n}`,localVideoIdentity:`video-${n}`,videoNumber:n,channelId,channelName:channelId,profileId,filePath:`/${n}.mp4`,fingerprint:`${n}`.padStart(64,'a'),fileSize:100,modifiedAt:1,publishAt:'2030-01-01T00:00:00Z',title:`Video ${n}`,description:'d',tags:['x'],categoryId:'10',quotaOperations:[{method:'videos.insert',count:1},{method:'videos.list',count:1}],allowDuplicate:false,submittedAt:'2026-09-14T00:00:00Z'}}

describe('multi-channel upload queue',()=>{
 it('uses bounded concurrency and at most one active upload per channel',async()=>{const resolvers:Record<string,()=>void>={},started:string[]=[];const q=new MultiChannelUploadQueue(s=>new Promise<void>(r=>{started.push(s.jobId);resolvers[s.jobId]=r}),2);q.enqueue(spec(1,'A'));q.enqueue(spec(2,'A'));q.enqueue(spec(3,'B'));await wait();expect(started).toEqual(['j1','j3']);expect(q.snapshot().running.map(x=>x.spec.channelId).sort()).toEqual(['A','B']);resolvers.j1();await wait();expect(started).toEqual(['j1','j3','j2'])});
 it('keeps FIFO order while allowing another channel past a busy channel',async()=>{const done:Record<string,()=>void>={},started:string[]=[];const q=new MultiChannelUploadQueue(s=>new Promise<void>(r=>{started.push(s.jobId);done[s.jobId]=r}),2);q.enqueue(spec(1,'A'));q.enqueue(spec(2,'A'));q.enqueue(spec(3,'B'));q.enqueue(spec(4,'C'));await wait();expect(started).toEqual(['j1','j3']);done.j3();await wait();expect(started).toEqual(['j1','j3','j4']);done.j1();await wait();expect(started).toEqual(['j1','j3','j4','j2'])});
 it('freezes channel/profile/file identity at submission',async()=>{let captured:ImmutableUploadJob|undefined;let release!:()=>void;const q=new MultiChannelUploadQueue(s=>new Promise<void>(r=>{captured=s;release=r}),1);const mutable:any=spec(1,'ELARA','profile-elara');q.enqueue(mutable);mutable.channelId='Lost Highway FM';mutable.profileId='profile-lost';mutable.filePath='/evil.mp4';mutable.tags.push('changed');await wait();expect(captured?.channelId).toBe('ELARA');expect(captured?.profileId).toBe('profile-elara');expect(captured?.filePath).toBe('/1.mp4');expect(captured?.tags).toEqual(['x']);release()});
 it('prevents queue-wide project/fingerprint duplicates while queued or running',async()=>{let release!:()=>void;const q=new MultiChannelUploadQueue(()=>new Promise<void>(r=>release=r),1);const a=spec(1,'A');q.enqueue(a);expect(()=>q.enqueue({...spec(2,'B'),fingerprint:a.fingerprint})).toThrow(/DUPLICATE/);expect(()=>q.enqueue({...spec(3,'C'),projectId:a.projectId})).toThrow(/DUPLICATE/);release();await wait()});
 it('keeps credentials isolated across simultaneous channels and UI-like switching',async()=>{const seen:Array<[string,string,string]>=[];const q=new MultiChannelUploadQueue(async s=>{seen.push([s.jobId,s.channelId,s.profileId])},2);q.enqueue(spec(1,'ELARA','profile-elara'));q.enqueue(spec(2,'Lost Highway FM','profile-lost'));await wait();await wait();expect(seen).toContainEqual(['j1','ELARA','profile-elara']);expect(seen).toContainEqual(['j2','Lost Highway FM','profile-lost'])});
 it('allows safe removal only while queued',async()=>{let release!:()=>void;const q=new MultiChannelUploadQueue(()=>new Promise<void>(r=>release=r),1);q.enqueue(spec(1,'A'));q.enqueue(spec(2,'B'));await wait();expect(q.removeQueued('j1')).toBe(false);expect(q.removeQueued('j2')).toBe(true);expect(q.snapshot().queued).toHaveLength(0);release()});
 it('waits for the exact submitted batch and returns every terminal failure beyond recent UI limits',async()=>{const q=new MultiChannelUploadQueue(async s=>{throw new Error(`boom-${s.jobId}`)},4);const ids:string[]=[];for(let i=1;i<=25;i++)ids.push(q.enqueue(spec(i,`C${i}`)).queueId);const rows=await q.waitForEntries(ids);expect(rows).toHaveLength(25);expect(rows.every(x=>x.state==='FAILED')).toBe(true);expect(rows.map(x=>x.spec.jobId)).toContain('j25')});
});
