import {beforeEach,describe,expect,it,vi} from 'vitest';import type {YoutubeExistingVideo} from './types';
class S{m=new Map<string,string>();getItem(k:string){return this.m.get(k)??null}setItem(k:string,v:string){this.m.set(k,String(v))}removeItem(k:string){this.m.delete(k)}clear(){this.m.clear()}key(i:number){return[...this.m.keys()][i]??null}get length(){return this.m.size}}
const storage=new S();Object.defineProperty(globalThis,'localStorage',{value:storage,configurable:true});if(typeof (globalThis as any).window==='undefined')Object.defineProperty(globalThis,'window',{value:{dispatchEvent:vi.fn()},configurable:true});
const fx=vi.hoisted(()=>({files:new Map<string,any>()}));
vi.mock('./api',()=>({api:{youtubeInventoryRead:vi.fn(async(channelId:string)=>fx.files.has(channelId)?{found:true,schemaVersion:2,channelId,path:'x',payload:fx.files.get(channelId)}:{found:false,schemaVersion:2,channelId,path:'x'}),youtubeInventoryWrite:vi.fn(async(channelId:string,payload:any)=>{fx.files.set(channelId,structuredClone(payload));return{ok:true,verified:true,schemaVersion:2,channelId,path:'x',bytes:JSON.stringify(payload).length}}),youtubeInventoryDelete:vi.fn(async()=>({ok:true,deleted:true}))}}));
import {loadExistingInventory,resetExistingInventoryMemoryForTests,writeExistingInventory} from './existingInventoryNative';import type {ExistingInventoryCache} from './existingInventoryCodec';
const video=(id:string,i:number,privacyStatus='public',publishAt?:string):YoutubeExistingVideo=>({id,position:i,title:id,description:'Description '+id,tags:['deep','house'],categoryId:'10',privacyStatus,publishAt,selected:false});
describe('6.1.2 native inventory truth',()=>{beforeEach(()=>{storage.clear();fx.files.clear();resetExistingInventoryMemoryForTests()});
it('preserves Lumière 20 total / 15 Scheduled / until 2026-10-18',async()=>{const videos:YoutubeExistingVideo[]=[];for(let i=0;i<5;i++)videos.push(video('p'+i,i));for(let d=4;d<=18;d++)videos.push(video('s'+d,videos.length,'private','2026-10-'+String(d).padStart(2,'0')+'T18:00:00+07:00'));const c:ExistingInventoryCache={version:1,updatedAt:'2026-10-03T00:00:00Z',lastCompleteAt:'2026-10-03T00:00:00Z',videos,baseline:Object.fromEntries(videos.map(v=>[v.id,v])),lastUndo:[],syncInfo:{syncComplete:true,scheduleComplete:true},lastCompleteSyncInfo:{syncComplete:true,scheduleComplete:true}};expect((await writeExistingInventory('lumiere',c)).ok).toBe(true);const got=await loadExistingInventory('lumiere');expect(got?.videos).toHaveLength(20);const scheduled=got!.videos.filter(v=>v.privacyStatus==='private'&&v.publishAt);expect(scheduled).toHaveLength(15);expect(scheduled.sort((a,b)=>Date.parse(a.publishAt!)-Date.parse(b.publishAt!)).at(-1)?.publishAt).toContain('2026-10-18')});
it('returns INVENTORY_STORAGE_CORRUPT instead of zeroing data',async()=>{fx.files.set('bad',{schemaVersion:2,channelId:'bad',updatedAt:'x',videos:'broken',baselineDelta:{}});await expect(loadExistingInventory('bad')).rejects.toThrow('INVENTORY_STORAGE_CORRUPT')})});
