import {beforeEach,describe,expect,it,vi} from 'vitest';
import type {YoutubeExistingVideo} from './types';
class S{m=new Map<string,string>();getItem(k:string){return this.m.get(k)??null}setItem(k:string,v:string){this.m.set(k,String(v))}removeItem(k:string){this.m.delete(k)}clear(){this.m.clear()}key(i:number){return[...this.m.keys()][i]??null}get length(){return this.m.size}}
const storage=new S();Object.defineProperty(globalThis,'localStorage',{value:storage,configurable:true});if(typeof (globalThis as any).window==='undefined')Object.defineProperty(globalThis,'window',{value:{dispatchEvent:vi.fn()},configurable:true});
const fx=vi.hoisted(()=>({files:new Map<string,any>(),fail:new Set<string>()}));
vi.mock('./api',()=>({api:{youtubeInventoryRead:vi.fn(async(channelId:string)=>fx.files.has(channelId)?{found:true,schemaVersion:2,channelId,path:'x',payload:fx.files.get(channelId)}:{found:false,schemaVersion:2,channelId,path:'x'}),youtubeInventoryWrite:vi.fn(async(channelId:string,payload:any)=>{if(fx.fail.has(channelId))throw new Error('INVENTORY_STORAGE_WRITE_FAILED');fx.files.set(channelId,structuredClone(payload));return{ok:true,verified:true,schemaVersion:2,channelId,path:'x',bytes:JSON.stringify(payload).length}}),youtubeInventoryDelete:vi.fn(async()=>({ok:true,deleted:true}))}}));
import {migrateLegacyExistingInventories} from './existingInventoryMigration';import {loadExistingInventory,resetExistingInventoryMemoryForTests,writeExistingInventory} from './existingInventoryNative';import type {ExistingInventoryCache} from './existingInventoryCodec';
const v=(id:string,i:number):YoutubeExistingVideo=>({id,position:i,title:id,description:'D'.repeat(4000),tags:Array.from({length:20},(_,x)=>'tag-'+x+'-'+('x'.repeat(30))),categoryId:'10',privacyStatus:'public',thumbnail:'https://i.ytimg.com/'+id,views:1,likes:1,comments:1,selected:false});
const c=(id:string,n:number):ExistingInventoryCache=>{const videos=Array.from({length:n},(_,i)=>v(id+'-'+i,i));return{version:1,updatedAt:'2026-10-03T00:00:00.000Z',videos,baseline:Object.fromEntries(videos.map(x=>[x.id,x])),lastUndo:[],syncInfo:{syncComplete:true,scheduleComplete:true},lastCompleteAt:'2026-10-03T00:00:00.000Z',lastCompleteSyncInfo:{syncComplete:true,scheduleComplete:true}}};
describe('6.1.2 native inventory stress',()=>{beforeEach(()=>{storage.clear();fx.files.clear();fx.fail.clear();resetExistingInventoryMemoryForTests()});
it('migrates 31x100 and reclaims heavy localStorage',async()=>{storage.setItem('settings','KEEP');for(let i=0;i<31;i++){const id='c'+i;storage.setItem('vyron:existing-cache:v1:'+id,JSON.stringify(c(id,100)))}const r=await migrateLegacyExistingInventories();expect(r).toMatchObject({migrated:31,failed:0,removedLegacy:31,apiRequests:0});expect(storage.getItem('settings')).toBe('KEEP');for(let i=0;i<31;i++)expect((await loadExistingInventory('c'+i))?.videos).toHaveLength(100);expect([...storage.m.keys()].filter(k=>k.startsWith('vyron:existing-cache:v1:'))).toHaveLength(0)});
it('stores 1000 videos without legacy payload',async()=>{expect((await writeExistingInventory('big',c('big',1000))).ok).toBe(true);expect((await loadExistingInventory('big'))?.videos).toHaveLength(1000);expect(storage.getItem('vyron:existing-cache:v1:big')).toBeNull()});
it('keeps legacy data if native write fails',async()=>{storage.setItem('vyron:existing-cache:v1:fail',JSON.stringify(c('fail',20)));fx.fail.add('fail');const r=await migrateLegacyExistingInventories();expect(r.failed).toBe(1);expect(storage.getItem('vyron:existing-cache:v1:fail')).not.toBeNull()})});
