import React,{useEffect,useMemo,useRef,useState} from 'react';
import {useApp} from './store';
import {api} from './api';
import {sortChannelsAlphabetically} from './channelSort';
import {loadActivePublishChannel,saveActivePublishChannel,subscribeActivePublishChannel} from './publishWorkspaceState';
import type {Channel,YoutubeProfile} from './types';
import {channelCountrySource,channelLanguageSource,channelStatsStatusLabel,compactChannelStat,exactChannelStat,subscriberStatLabel,youtubeCountryLabel} from './youtubeChannelStats';
import {refreshYoutubeProfileStatistics} from './youtubeChannelStatsRuntime';
import {ChannelAvatar} from './ChannelAvatar';
import {EMPTY_SCHEDULE,useJobDerived} from './jobDerivedRuntime';
import {recordYoutubeRouteEvent} from './youtubeRouteDiagnostics';

export function filterYoutubeChannels(channels:Channel[],query:string){const q=query.trim().toLocaleLowerCase('ru-RU');const ordered=sortChannelsAlphabetically(channels);if(!q)return ordered;return ordered.filter(c=>[c.name,c.slug,c.youtubeChannelId,c.stats?.handle].filter(Boolean).some(v=>String(v).toLocaleLowerCase('ru-RU').includes(q)))}
export function resolveYoutubeActiveChannel(channels:Channel[],saved:string){return channels.some(c=>c.id===saved)?saved:(sortChannelsAlphabetically(channels)[0]?.id||'')}
const fmtDate=(iso?:string)=>iso?new Date(iso).toLocaleDateString('ru-RU'):'—';
const fmtDateTime=(iso?:string)=>iso?new Date(iso).toLocaleString('ru-RU'):'—';
let youtubeProfileRuntimeCache:YoutubeProfile[]=[];
async function loadYoutubeProfileRuntimeCache(){const rows=await api.youtubeProfiles();youtubeProfileRuntimeCache=rows;return rows}

export function YouTubeChannelBar({active:routeActive=true}:{active?:boolean}={}){
 const channels=useApp(s=>s.channels)||[],channelKey=channels.map(c=>c.id).join('|');
 const [activeId,setActiveId]=useState(()=>resolveYoutubeActiveChannel(channels,loadActivePublishChannel())),[query,setQuery]=useState(''),[feedback,setFeedback]=useState(''),[refreshing,setRefreshing]=useState(false),[detailsOpen,setDetailsOpen]=useState(false),[profiles,setProfiles]=useState<YoutubeProfile[]>(()=>youtubeProfileRuntimeCache);
 const activeIdRef=useRef(activeId);activeIdRef.current=activeId;
 useEffect(()=>{if(!routeActive)return;return subscribeActivePublishChannel(id=>{recordYoutubeRouteEvent('YouTubeChannelBar','active-channel-event');const next=resolveYoutubeActiveChannel(channels,id);if(next===activeIdRef.current)return;activeIdRef.current=next;recordYoutubeRouteEvent('YouTubeChannelBar','state-write:activeId');setActiveId(next);const c=channels.find(x=>x.id===next);if(c){recordYoutubeRouteEvent('YouTubeChannelBar','state-write:feedback');setFeedback('Активный канал: '+c.name)}})},[routeActive,channelKey]);
 useEffect(()=>{if(!routeActive||!detailsOpen)return;let live=true;const refresh=()=>void loadYoutubeProfileRuntimeCache().then(p=>{if(live)setProfiles(p)}).catch(()=>{});refresh();const invalidate=()=>{youtubeProfileRuntimeCache=[];if(live)refresh()};window.addEventListener('vyron:oauth-state-changed',invalidate);return()=>{live=false;window.removeEventListener('vyron:oauth-state-changed',invalidate)}},[routeActive,detailsOpen]);
 useEffect(()=>{if(!routeActive)return;const saved=loadActivePublishChannel(),resolved=resolveYoutubeActiveChannel(channels,saved);if(resolved&&resolved!==saved){recordYoutubeRouteEvent('YouTubeChannelBar','persist-fallback-active-channel');saveActivePublishChannel(resolved)}if(resolved!==activeIdRef.current){activeIdRef.current=resolved;recordYoutubeRouteEvent('YouTubeChannelBar','state-write:sync-activeId');setActiveId(resolved)}},[routeActive,channelKey]);
 const visible=useMemo(()=>filterYoutubeChannels(channels,query),[channels,query]),active=channels.find(c=>c.id===activeId),activeLinked=Boolean(active?.youtubeProfileId&&active?.youtubeChannelId),profile=profiles.find(p=>p.id===active?.youtubeProfileId);
 const stats=active?.stats,{nextScheduled,scheduledCount}=useJobDerived(s=>s.scheduleByChannel[activeId]||EMPTY_SCHEDULE),lastSync=stats?.statisticsUpdatedAt||stats?.updatedAt||active?.analytics?.updatedAt;
 async function refreshActive(){const current=useApp.getState().channels.find(c=>c.id===activeId);if(!current?.youtubeProfileId||!current.youtubeChannelId)return;setRefreshing(true);try{const cached=profiles.find(x=>x.id===current.youtubeProfileId&&x.channelId===current.youtubeChannelId),p=cached||((await loadYoutubeProfileRuntimeCache()).find(x=>x.id===current.youtubeProfileId&&x.channelId===current.youtubeChannelId));if(!p){setFeedback('⚠ '+current.name+': профиль YouTube не связан точно');return}setProfiles(youtubeProfileRuntimeCache);const fresh=await refreshYoutubeProfileStatistics(p,'channel-bar:'+current.id+':'+Date.now());setFeedback(fresh?'✓ Данные канала обновлены':'⚠ Не удалось обновить; показан локальный кэш')}finally{setRefreshing(false)}}
 function choose(nextId:string){if(!channels.some(c=>c.id===nextId))return;saveActivePublishChannel(nextId);if(nextId!==activeIdRef.current){activeIdRef.current=nextId;setActiveId(nextId)}setQuery('');setFeedback('Активный канал: '+(channels.find(c=>c.id===nextId)?.name||nextId))}
 return <section className="youtubeChannelBar channelContextBar" aria-label="Активный YouTube канал"><div className="channelContextIdentity">{active?<ChannelAvatar channel={active} size="lg"/>:<span className="channelAvatar channelAvatar-lg channelAvatarFallback">Y</span>}<div><small>АКТИВНЫЙ КАНАЛ</small><b>{active?.name||'Канал не выбран'}</b><span>{stats?.handle||active?.youtubeChannelId||active?.id||'—'}</span></div></div>
  <div className="channelContextMetrics channelContextMetricsPrimary"><span><small>Подписчики</small><b title={stats?.hiddenSubscriberCount?'Скрыты каналом':exactChannelStat(stats?.subscriberCount??stats?.subscribers)}>{subscriberStatLabel(stats)}</b></span><span><small>Просмотры</small><b title={exactChannelStat(stats?.viewCount??stats?.views)}>{compactChannelStat(stats?.viewCount??stats?.views)}</b></span><span><small>Видео</small><b title={exactChannelStat(stats?.videoCount??stats?.videos)}>{compactChannelStat(stats?.videoCount??stats?.videos)}</b></span></div>{detailsOpen&&<div className="channelContextMetrics channelContextMetricsDetails"><span><small>Создан</small><b>{fmtDate(stats?.publishedAt||active?.analytics?.channelPublishedAt)}</b></span><span><small>Страна канала</small><b>{youtubeCountryLabel(channelCountrySource(stats,active?.analytics?.channelCountry,active?.country))}</b></span><span><small>Язык YouTube</small><b>{channelLanguageSource(stats,active?.analytics?.channelLanguage)}</b></span><span><small>OAuth</small><b className={activeLinked?'ok':'warn'}>{activeLinked?'Подключён':'Нужно внимание'}</b></span><span><small>Google</small><b>{profile?.googleEmail||'—'}</b></span><span><small>OAuth Client</small><b title={profile?.clientIdMasked||''}>{profile?.clientIdMasked||'—'}</b></span><span><small>Последнее обновление</small><b>{fmtDateTime(lastSync)}</b></span><span><small>Следующая публикация</small><b>{nextScheduled?fmtDateTime(nextScheduled):'—'}</b><em>{scheduledCount?'Ещё '+scheduledCount:'Очереди нет'}</em></span></div>}
  <div className="channelContextControls"><label className="youtubeChannelSearch">🔎<input aria-label="Найти канал" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти канал…"/></label><select aria-label="Активный YouTube-канал" value={visible.some(c=>c.id===activeId)?activeId:''} onChange={e=>choose(e.target.value)}><option value="" disabled>{visible.length?'Выберите канал':'Нет совпадений'}</option>{visible.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="compact" onClick={()=>setDetailsOpen(x=>!x)}>{detailsOpen?'Скрыть':'Подробнее'}</button>{detailsOpen&&<button className="compact" disabled={refreshing||!activeLinked} onClick={()=>void refreshActive()}>{refreshing?'Обновляю…':'↻ Обновить'}</button>}</div>
  <div className="youtubeChannelFeedback" aria-live="polite">{feedback||channelStatsStatusLabel(stats,refreshing)}</div></section>;
}
