import React,{useEffect,useMemo,useState} from 'react';
import {useApp} from './store';
import {api} from './api';
import {sortChannelsAlphabetically} from './channelSort';
import {loadActivePublishChannel,saveActivePublishChannel,subscribeActivePublishChannel} from './publishWorkspaceState';
import type {Channel,YoutubeProfile} from './types';
import {channelStatsStatusLabel,compactChannelStat,exactChannelStat,subscriberStatLabel} from './youtubeChannelStats';
import {refreshYoutubeProfileStatistics} from './youtubeChannelStatsRuntime';
import {classifyYoutubeChannels} from './youtubeStatisticsCenter';

export function filterYoutubeChannels(channels:Channel[],query:string){const q=query.trim().toLocaleLowerCase('ru-RU');const ordered=sortChannelsAlphabetically(channels);if(!q)return ordered;return ordered.filter(c=>[c.name,c.slug,c.youtubeChannelId,c.stats?.handle].filter(Boolean).some(v=>String(v).toLocaleLowerCase('ru-RU').includes(q)))}
export function resolveYoutubeActiveChannel(channels:Channel[],saved:string){return channels.some(c=>c.id===saved)?saved:(sortChannelsAlphabetically(channels)[0]?.id||'')}
const fmtDate=(iso?:string)=>iso?new Date(iso).toLocaleDateString('ru-RU'):'—';
const fmtDateTime=(iso?:string)=>iso?new Date(iso).toLocaleString('ru-RU'):'—';

export function YouTubeChannelBar(){
 const channels=useApp(s=>s.channels)||[],jobs=useApp(s=>s.jobs)||[],channelKey=channels.map(c=>c.id).join('|');
 const [activeId,setActiveId]=useState(()=>resolveYoutubeActiveChannel(channels,loadActivePublishChannel())),[query,setQuery]=useState(''),[feedback,setFeedback]=useState(''),[refreshing,setRefreshing]=useState(false),[profiles,setProfiles]=useState<YoutubeProfile[]>([]);
 useEffect(()=>subscribeActivePublishChannel(id=>{setActiveId(resolveYoutubeActiveChannel(channels,id));const c=channels.find(x=>x.id===id);if(c)setFeedback('Активный канал: '+c.name)}),[channelKey]);
 useEffect(()=>{let live=true;const refresh=()=>void api.youtubeProfiles().then(p=>{if(live)setProfiles(p)}).catch(()=>{});refresh();window.addEventListener('vyron:oauth-state-changed',refresh);return()=>{live=false;window.removeEventListener('vyron:oauth-state-changed',refresh)}},[]);
 useEffect(()=>{const resolved=resolveYoutubeActiveChannel(channels,loadActivePublishChannel());if(resolved&&resolved!==loadActivePublishChannel())saveActivePublishChannel(resolved);setActiveId(resolved)},[channelKey]);
 const visible=useMemo(()=>filterYoutubeChannels(channels,query),[channels,query]),active=channels.find(c=>c.id===activeId),activeLinked=classifyYoutubeChannels(active?[active]:[],profiles).linked[0],profile=profiles.find(p=>p.id===active?.youtubeProfileId);
 const stats=active?.stats,scheduled=jobs.filter(j=>j.channelId===activeId&&Boolean(j.publishAt)&&new Date(j.publishAt!).getTime()>Date.now()).sort((a,b)=>String(a.publishAt).localeCompare(String(b.publishAt))),nextScheduled=scheduled[0]?.publishAt,lastSync=stats?.statisticsUpdatedAt||stats?.updatedAt||active?.analytics?.updatedAt;
 async function refreshActive(){const current=useApp.getState().channels.find(c=>c.id===activeId);if(!current?.youtubeProfileId||!current.youtubeChannelId)return;const p=profiles.find(x=>x.id===current.youtubeProfileId&&x.channelId===current.youtubeChannelId);if(!p){setFeedback('⚠ '+current.name+': профиль YouTube не связан точно');return}setRefreshing(true);try{const fresh=await refreshYoutubeProfileStatistics(p,'channel-bar:'+current.id+':'+Date.now());setFeedback(fresh?'✓ Данные канала обновлены':'⚠ Не удалось обновить; показан локальный кэш')}finally{setRefreshing(false)}}
 function choose(nextId:string){if(!channels.some(c=>c.id===nextId))return;saveActivePublishChannel(nextId);setActiveId(nextId);setQuery('');setFeedback('Активный канал: '+(channels.find(c=>c.id===nextId)?.name||nextId))}
 return <section className="youtubeChannelBar channelContextBar" aria-label="Активный YouTube канал"><div className="channelContextIdentity">{active?.analytics?.channelThumbnail||stats?.thumbnail?<img src={active?.analytics?.channelThumbnail||stats?.thumbnail}/>:<i>{active?.name?.slice(0,2).toUpperCase()||'YT'}</i>}<div><small>АКТИВНЫЙ КАНАЛ</small><b>{active?.name||'Канал не выбран'}</b><span>{stats?.handle||active?.youtubeChannelId||active?.id||'—'}</span></div></div>
  <div className="channelContextMetrics"><span><small>Подписчики</small><b title={stats?.hiddenSubscriberCount?'Скрыты каналом':exactChannelStat(stats?.subscriberCount??stats?.subscribers)}>{subscriberStatLabel(stats)}</b></span><span><small>Просмотры</small><b title={exactChannelStat(stats?.viewCount??stats?.views)}>{compactChannelStat(stats?.viewCount??stats?.views)}</b></span><span><small>Видео</small><b title={exactChannelStat(stats?.videoCount??stats?.videos)}>{compactChannelStat(stats?.videoCount??stats?.videos)}</b></span><span><small>Создан</small><b>{fmtDate(active?.analytics?.channelPublishedAt)}</b></span><span><small>Страна / язык</small><b>{active?.analytics?.channelCountry||active?.country||'—'} · {active?.analytics?.channelLanguage||active?.language||'—'}</b></span><span><small>OAuth</small><b className={activeLinked?'ok':'warn'}>{activeLinked?'Подключён':'Нужно внимание'}</b></span><span><small>Google</small><b>{profile?.googleEmail||'—'}</b></span><span><small>OAuth Client</small><b title={profile?.clientIdMasked||''}>{profile?.clientIdMasked||'—'}</b></span><span><small>Последнее обновление</small><b>{fmtDateTime(lastSync)}</b></span><span><small>Следующая публикация</small><b>{nextScheduled?fmtDateTime(nextScheduled):'—'}</b><em>{scheduled.length?'Ещё '+scheduled.length:'Очереди нет'}</em></span></div>
  <div className="channelContextControls"><label className="youtubeChannelSearch">🔎<input aria-label="Найти канал" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти канал…"/></label><select aria-label="Активный YouTube-канал" value={visible.some(c=>c.id===activeId)?activeId:''} onChange={e=>choose(e.target.value)}><option value="" disabled>{visible.length?'Выберите канал':'Нет совпадений'}</option>{visible.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="compact" disabled={refreshing||!activeLinked} onClick={()=>void refreshActive()}>{refreshing?'Обновляю…':'↻ Обновить'}</button></div>
  <div className="youtubeChannelFeedback" aria-live="polite">{feedback||channelStatsStatusLabel(stats,refreshing)}</div></section>;
}
