#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT=Path(sys.argv[1] if len(sys.argv)>1 else '.')
def r(p): return (ROOT/p).read_text()
def w(p,s): (ROOT/p).write_text(s)
def rep(p,a,b,count=1):
    s=r(p)
    if a not in s: raise SystemExit(f'v207 future-channel semantics missing anchor {p}: {a[:220]!r}')
    w(p,s.replace(a,b,count))

# -----------------------------------------------------------------------------
# Local production identity must stay stable after YouTube binding.
# A YouTube title is used to discover the future channel, but it must not rename
# the already-created local channel afterwards (folders / batches use that name).
# -----------------------------------------------------------------------------
rep('src/AccountsPage.tsx',
"if(exact){state.updateChannel(exact.id,{youtubeProfileId:p.id,youtubeChannelId:p.channelId,name:p.channelTitle||exact.name});return{channel:exact,mode:'existing' as const}}",
"if(exact){state.updateChannel(exact.id,{youtubeProfileId:p.id,youtubeChannelId:p.channelId});return{channel:exact,mode:'existing' as const}}")

rep('src/youtubeIntelligence.ts',
"s.updateChannel(channel.id,{name:ps.title||channel.name,youtubeChannelId:ps.channelId||channel.youtubeChannelId,stats:{subscribers:ps.subscribers??channel.stats?.subscribers,views:ps.views??channel.stats?.views,videos:ps.videos??channel.stats?.videos,updatedAt:r.updatedAt},analytics:r});",
"s.updateChannel(channel.id,{youtubeChannelId:ps.channelId||channel.youtubeChannelId,stats:{subscribers:ps.subscribers??channel.stats?.subscribers,views:ps.views??channel.stats?.views,videos:ps.videos??channel.stats?.videos,updatedAt:r.updatedAt},analytics:r});")

# -----------------------------------------------------------------------------
# A deliberately unbound future channel is a valid production state, not a
# broken OAuth state. Health still reports real render/job errors and low buffer.
# Previously-linked channels are not classified as future because at least one
# YouTube binding field remains present.
# -----------------------------------------------------------------------------
rep('src/ChannelsOS.tsx',
"function health(c:Channel,jobs:VideoJob[]){let n=100;if(!c.youtubeProfileId)n-=25;if(!c.analytics)n-=15;if(jobs.some(j=>j.channelId===c.id&&j.status==='ERROR'))n-=20;const b=bufferDays(c,jobs);if(b<7)n-=25;else if(b<14)n-=12;return Math.max(0,n)}",
"function health(c:Channel,jobs:VideoJob[]){let n=100;if(!isFutureChannel(c)){if(!c.youtubeProfileId)n-=25;if(!c.analytics)n-=15}if(jobs.some(j=>j.channelId===c.id&&j.status==='ERROR'))n-=20;const b=bufferDays(c,jobs);if(b<7)n-=25;else if(b<14)n-=12;return Math.max(0,n)}")

# DashboardOS is generated by the 2.0.0 operational-attention patch. Future
# channels should remain visible in production priority, but must not create
# OAuth / auto-upload-limit warnings until a YouTube binding actually exists.
p='src/DashboardOS.tsx';s=r(p)
anchor="import {humanizeError} from './errorCenter';"
if anchor not in s: raise SystemExit('v207 Dashboard import anchor missing')
if "from './channelIdentity'" not in s:s=s.replace(anchor,anchor+"import {isFutureChannel} from './channelIdentity';",1)
old="...enabled.filter(c=>!c.youtubeProfileId).slice(0,3).map(c=>({label:'YouTube',text:`${c.name}: OAuth не подключён`,page:'youtube' as const}))"
if old not in s: raise SystemExit('v207 Dashboard OAuth issue anchor missing')
s=s.replace(old,"...enabled.filter(c=>!isFutureChannel(c)&&!c.youtubeProfileId).slice(0,3).map(c=>({label:'YouTube',text:`${c.name}: OAuth не подключён`,page:'youtube' as const}))",1)
old="...enabled.filter(c=>settings.autoUploadYoutube&&!c.safeDailyUploadLimit).slice(0,3).map(c=>({label:'Autopilot',text:`${c.name}: для авто-Youtube не задан безопасный 24h-limit`,page:'youtube' as const}))"
if old not in s: raise SystemExit('v207 Dashboard autoupload issue anchor missing')
s=s.replace(old,"...enabled.filter(c=>!isFutureChannel(c)&&settings.autoUploadYoutube&&!c.safeDailyUploadLimit).slice(0,3).map(c=>({label:'Autopilot',text:`${c.name}: для авто-Youtube не задан безопасный 24h-limit`,page:'youtube' as const}))",1)
w(p,s)

# Settings' global Autopilot opt-in validation should also ignore future channels:
# they cannot upload until OAuth exists and should not prevent connected channels
# from using the explicitly-enabled guarded YouTube Autopilot.
p='src/SettingsOS.tsx';s=r(p)
old="const missing=channels.filter(c=>c.enabled&&(!c.youtubeProfileId||!c.safeDailyUploadLimit));"
if old in s:
    if "from './channelIdentity'" not in s:
        import_anchor="import {notifyInfo,notifyWarning} from './notificationCenter';"
        if import_anchor in s:s=s.replace(import_anchor,import_anchor+"\nimport {isFutureChannel} from './channelIdentity';",1)
        else:
            first=s.find('\n');s=s[:first+1]+"import {isFutureChannel} from './channelIdentity';\n"+s[first+1:]
    s=s.replace(old,"const missing=channels.filter(c=>c.enabled&&!isFutureChannel(c)&&(!c.youtubeProfileId||!c.safeDailyUploadLimit));",1)
    w(p,s)

w('src/futureChannelSemantics.test.ts',r'''import {describe,expect,it} from 'vitest';import {readFileSync} from 'node:fs';
describe('future channel semantics',()=>{
 it('does not rename local production identity after YouTube bind or analytics sync',()=>{const a=readFileSync('src/AccountsPage.tsx','utf8'),y=readFileSync('src/youtubeIntelligence.ts','utf8');expect(a).not.toContain('name:p.channelTitle||exact.name');expect(y).not.toContain('name:ps.title||channel.name')});
 it('does not report intentionally future channels as OAuth failures',()=>{const d=readFileSync('src/DashboardOS.tsx','utf8'),c=readFileSync('src/ChannelsOS.tsx','utf8');expect(d).toContain('!isFutureChannel(c)&&!c.youtubeProfileId');expect(d).toContain('!isFutureChannel(c)&&settings.autoUploadYoutube');expect(c).toContain('if(!isFutureChannel(c)){if(!c.youtubeProfileId)n-=25;if(!c.analytics)n-=15}')});
 it('keeps YouTube Autopilot hard-gated by OAuth',()=>{const a=readFileSync('src/youtubeAutopilot.ts','utf8');expect(a).toContain('!channel.youtubeProfileId');expect(a).toContain('if(!s.autoUploadYoutube||!s.youtubePublishSafeMode||!channel.youtubeProfileId||!channel.safeDailyUploadLimit)return')});
});
''')
print('VYRON 2.0.7 future-channel semantics applied')
