import React,{useRef,useState} from 'react';
import * as mammoth from 'mammoth';
import {api} from './api';
import {useApp} from './store';
import {parseMetadataFile,type ImportedMetadata} from './metadata';
import type {JobStatus,VideoJob} from './types';

const statusLabel:Record<JobStatus,string>={NEED_IMAGE:'Нужна картинка',WAITING_MUSIC:'Ждёт музыку',READY_RENDER:'Готов к рендеру',RENDERING:'Рендерится',READY_UPLOAD:'Готов к YouTube',UPLOADING:'Загружается',SCHEDULED:'Запланирован',ERROR:'Ошибка'};

export function PublisherOS(){
 const channels=useApp(s=>s.channels),jobs=useApp(s=>s.jobs),patchJob=useApp(s=>s.patchJob),settings=useApp(s=>s.settings),toast=useApp(s=>s.toast);
 const [rows,setRows]=useState<ImportedMetadata[]>([]),[files,setFiles]=useState<string[]>([]),[metaChannel,setMetaChannel]=useState(channels[0]?.id||''),[busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
 const ready=jobs.filter(j=>['READY_UPLOAD','UPLOADING','SCHEDULED','ERROR'].includes(j.status));
 async function read(fl:FileList|null){if(!fl?.length)return;const out:ImportedMetadata[]=[],names:string[]=[];for(const f of Array.from(fl)){const docx=f.name.toLowerCase().endsWith('.docx');const text=docx?(await mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()})).value:await f.text();out.push(...parseMetadataFile(f.name,text));names.push(f.name)}setRows(out);setFiles(names);toast(`Метаданные: ${out.length} записей`)}
 async function apply(){const used=new Set<string>();let ok=0,miss=0;for(let i=0;i<rows.length;i++){const r=rows[i],named=r.channel?channels.find(c=>c.name.toLowerCase()===r.channel?.toLowerCase()||c.id===r.channel):undefined,channelId=named?.id||metaChannel;const pool=useApp.getState().jobs.filter(j=>(!channelId||j.channelId===channelId)&&!used.has(j.id)).sort((a,b)=>a.number-b.number);const j=r.number?pool.find(x=>x.number===r.number):pool[0];if(!j){miss++;continue}used.add(j.id);const p:Partial<VideoJob>={metadataSource:'import',metadataLocked:true};if(r.title)p.title=r.title;if(r.description)p.description=r.description;if(r.tags?.length)p.tags=r.tags;if(r.publishAt)p.publishAt=r.publishAt;patchJob(j.id,p);const after={...j,...p};if(j.folder)await api.writeJobMetadata(j.folder,after.title,after.description,after.tags,after.publishAt,'import');ok++}toast(`Применено: ${ok}${miss?` • не найдено ${miss}`:''}`)}
 async function upload(job:VideoJob){const c=channels.find(x=>x.id===job.channelId);if(!c?.youtubeProfileId){toast(`У ${c?.name||'канала'} не привязан YouTube OAuth`);return false}if(!job.finalPath){toast('final.mp4 не найден');return false}patchJob(job.id,{status:'UPLOADING',uploadProgress:0,error:undefined});try{const r=await api.youtubeUpload(c.youtubeProfileId,job.id,job.finalPath,job.title,job.description,job.tags,job.publishAt,settings.youtubeCategoryId);if(!r.videoId)throw new Error('YouTube не вернул video ID');patchJob(job.id,{status:'SCHEDULED',youtubeVideoId:r.videoId,uploadProgress:100,uploadedAt:new Date().toISOString()});return true}catch(e){patchJob(job.id,{status:'ERROR',error:String(e)});toast(String(e));return false}}
 async function uploadAll(){setBusy(true);let n=0;try{for(const j of useApp.getState().jobs.filter(j=>j.status==='READY_UPLOAD'&&j.finalPath).sort((a,b)=>(a.publishAt||'').localeCompare(b.publishAt||''))){if(await upload(j))n++}toast(`YouTube: загружено ${n}`)}finally{setBusy(false)}}
 return <>
  <input ref={input} hidden type="file" multiple accept=".docx,.json,.txt,.csv,application/json,text/plain,text/csv" onChange={e=>{void read(e.target.files);e.currentTarget.value=''}}/>
  <div className="queueHeader"><div><small>UPLOAD QUEUE</small><h2>Очередь YouTube</h2><p>Новые final.mp4, загрузка, обработка, расписание и ошибки.</p></div><div className="headerActions"><button onClick={()=>input.current?.click()}>✦ Метаданные</button><button className="primary" disabled={busy||!jobs.some(j=>j.status==='READY_UPLOAD')} onClick={uploadAll}>{busy?'Загружаю…':'Загрузить все готовые'}</button></div></div>
  <div className="queueKpis"><span>Готовы <b>{jobs.filter(j=>j.status==='READY_UPLOAD').length}</b></span><span>Uploading <b>{jobs.filter(j=>j.status==='UPLOADING').length}</b></span><span>Scheduled <b>{jobs.filter(j=>j.status==='SCHEDULED').length}</b></span><span className={jobs.some(j=>j.status==='ERROR')?'warn':''}>Ошибки <b>{jobs.filter(j=>j.status==='ERROR').length}</b></span></div>
  {files.length>0&&<section className="panel metadataInline"><div><b>Metadata Inbox</b><p>{files.length} файлов • {rows.length} записей</p></div><select value={metaChannel} onChange={e=>setMetaChannel(e.target.value)}><option value="">Все каналы</option>{channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="primary" disabled={!rows.length} onClick={apply}>Применить</button><button onClick={()=>{setRows([]);setFiles([])}}>Очистить</button></section>}
  {ready.length===0?<div className="empty"><b>Нет готовых MP4</b><p>После появления final.mp4 ролик автоматически попадёт сюда.</p></div>:<div className="publishList compactPublish">{ready.map(j=>{const c=channels.find(x=>x.id===j.channelId);return <article className="publishCard compact" key={j.id}><div className="thumb"><span>▶</span><small>VIDEO_{String(j.number).padStart(3,'0')}</small></div><div className="publishMeta"><small>{c?.name} • {j.metadataSource||'template'}</small><input value={j.title} maxLength={100} onChange={e=>patchJob(j.id,{title:e.target.value,metadataLocked:true})}/><details><summary>Описание и теги</summary><textarea value={j.description} maxLength={5000} onChange={e=>patchJob(j.id,{description:e.target.value,metadataLocked:true})}/><input value={j.tags.join(', ')} onChange={e=>patchJob(j.id,{tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean),metadataLocked:true})}/></details>{j.status==='UPLOADING'&&<div className="progress"><i style={{width:`${j.uploadProgress||0}%`}}/><span>{Math.round(j.uploadProgress||0)}%</span></div>}{j.error&&<div className="errorBox">{j.error}</div>}</div><div className="publishSide"><label>Дата<input type="datetime-local" value={j.publishAt?new Date(new Date(j.publishAt).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={e=>patchJob(j.id,{publishAt:e.target.value?new Date(e.target.value).toISOString():undefined,metadataLocked:true})}/></label><span className={`publishState ${j.status.toLowerCase()}`}>{statusLabel[j.status]}</span>{j.status==='READY_UPLOAD'&&<button className="primary" onClick={()=>upload(j)}>Загрузить</button>}{j.status==='ERROR'&&<button onClick={()=>patchJob(j.id,{status:j.finalPath?'READY_UPLOAD':'ERROR',error:undefined})}>Повторить</button>}{j.youtubeVideoId&&<small>YT: {j.youtubeVideoId}</small>}</div></article>})}</div>}
 </>;
}
