import React,{useMemo,useState} from 'react';
import {api} from './api';
import {useApp} from './store';
import {refreshChannelAnalytics,refreshCompetitor} from './youtubeIntelligence';
import {isYoutubeQuotaError,markYoutubeQuotaExceeded,youtubeQuotaMessage,youtubeQuotaState} from './youtubeQuota';

export function YouTubeDataTools(){
 const channels=useApp(s=>s.channels),competitors=useApp(s=>s.competitors),add=useApp(s=>s.addCompetitor),update=useApp(s=>s.updateChannel),toast=useApp(s=>s.toast);
 const [channelId,setChannelId]=useState(channels.find(c=>c.youtubeProfileId)?.id||channels[0]?.id||''),[busy,setBusy]=useState(''),[note,setNote]=useState('');
 const channel=channels.find(c=>c.id===channelId),list=useMemo(()=>competitors.filter(c=>c.channelId===channelId),[competitors,channelId]);
 const guard=()=>{if(youtubeQuotaState().blocked){setNote(youtubeQuotaMessage());toast(youtubeQuotaMessage());return false}return true};
 async function analytics(){if(!channel?.youtubeProfileId){toast('Сначала подключи YouTube OAuth');return}if(!guard())return;setBusy('analytics');try{const r=await refreshChannelAnalytics(channel.id,90,true);update(channel.id,{analytics:r});setNote(`✓ Аналитика обновлена: ${new Date(r.updatedAt).toLocaleString('ru-RU')}`);toast(`${channel.name}: аналитика обновлена`)}catch(e){if(isYoutubeQuotaError(e)){markYoutubeQuotaExceeded(e);setNote(youtubeQuotaMessage())}else setNote(String(e));toast(isYoutubeQuotaError(e)?youtubeQuotaMessage():String(e))}finally{setBusy('')}}
 async function discover(){if(!channel?.youtubeProfileId){toast('Сначала подключи YouTube OAuth');return}if(!guard())return;setBusy('discover');try{const found=await api.youtubeDiscoverCompetitors(channel.youtubeProfileId,Math.max(10,Math.min(50,useApp.getState().settings.competitorPoolSize||30)));const existing=new Set(list.map(c=>c.youtubeChannelId).filter(Boolean));let added=0;for(const x of found){if(existing.has(x.channelId)||x.channelId===channel.youtubeChannelId)continue;add({id:crypto.randomUUID(),channelId,name:x.name,url:x.url,youtubeChannelId:x.channelId,thumbnail:x.thumbnail,subscribers:x.subscribers,views:x.views,videos:x.videos,history:[],similarity:x.similarity,source:'auto'});existing.add(x.channelId);added++}setNote(`✓ Найдено ${found.length}, добавлено новых ${added}`);toast(`Конкуренты: +${added}`)}catch(e){if(isYoutubeQuotaError(e)){markYoutubeQuotaExceeded(e);setNote(youtubeQuotaMessage())}else setNote(String(e));toast(isYoutubeQuotaError(e)?youtubeQuotaMessage():String(e))}finally{setBusy('')}}
 async function refreshCompetitors(){if(!guard())return;setBusy('competitors');let ok=0;try{for(const c of list){try{await refreshCompetitor(c.id,true);ok++}catch(e){if(isYoutubeQuotaError(e)){markYoutubeQuotaExceeded(e);setNote(youtubeQuotaMessage());break}useApp.getState().log(`${c.name}: ${String(e)}`,'warn')}}if(!youtubeQuotaState().blocked){setNote(`✓ Обновлено конкурентов: ${ok}/${list.length}`);toast(`Конкуренты: ${ok}/${list.length}`)}}finally{setBusy('')}}
 return <section className="panel youtubeDataTools"><div className="panelHead"><div><small>EXPLICIT API ACTIONS</small><h3>Данные YouTube</h3><p>API вызывается только после нажатия кнопки на этом экране. Другие разделы используют сохранённый локальный кэш.</p></div><span className="localOnlyBadge">YOUTUBE ZONE</span></div><div className="youtubeDataToolbar"><label>Канал<select value={channelId} onChange={e=>setChannelId(e.target.value)}>{channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="youtubeActionGrid"><button disabled={!!busy||!channel?.youtubeProfileId} onClick={analytics}><b>{busy==='analytics'?'Обновляю…':'Обновить аналитику'}</b><small>90 дней → локальный cache</small></button><button disabled={!!busy||!channel?.youtubeProfileId} onClick={discover}><b>{busy==='discover'?'Ищу…':'Найти конкурентов'}</b><small>Только по явному действию</small></button><button disabled={!!busy||!list.length} onClick={refreshCompetitors}><b>{busy==='competitors'?'Обновляю…':'Обновить конкурентов'}</b><small>{list.length} сохранено локально</small></button></div>{note&&<div className="youtubeActionNote">{note}</div>}</section>
}
